import { defineStrings } from "@evi/api";

import type { WordKey, Words } from "./track";

export const t = defineStrings({
    en: {
        "settings.showOnProfiles": "On profiles",
        "settings.showOnProfiles.description": "A clock next to the badges on someone's profile; hover it for the times.",
        "settings.showInMemberList": "In the member list",
        "settings.showInMemberList.description": "Under the name of offline members.",
        "settings.showInFriends": "In the friends list",
        "settings.showInFriends.description": "Under the name of offline friends.",
        "settings.showInDms": "In direct messages",
        "settings.showInDms.description": "Under the name of offline people in the DM list.",
        "settings.ignoreBots": "Ignore bots",
        "settings.ignoreBots.description": "Don't track bots and apps.",
        "unit.y": "{n}y",
        "unit.mo": "{n}mo",
        "unit.w": "{n}w",
        "unit.d": "{n}d",
        "unit.h": "{n}h",
        "unit.m": "{n}m",
        "ago": "{span} ago",
        "justNow": "just now",
        "seen": "Last seen {when}",
        "seenIn": "Last seen in the last {span}",
        "active": "Active {when}",
        "online": "Online now",
        "message": "Last message {when}",
        "messageIn": "Last message {when} in {where}",
        "where.channel": "#{name}",
        "where.dms": "your DMs",
        "where.group": "the group {name}",
        "where.groupUnnamed": "a group DM",
        "people": { one: "{n} person", other: "{n} people" },
        "remembered.title": "Remembered",
        "remembered.cleared": "Cleared {people}.",
        "remembered.status": "{people} of {cap}. Kept on this device only; friends and DMs are kept longest.",
        "remembered.meter": "Space used",
        "remembered.undo": "Undo",
        "remembered.cancel": "Cancel",
        "remembered.confirmClear": "Clear {people}?",
        "remembered.export": "Export",
        "remembered.import": "Import",
        "remembered.clear": "Clear data",
        "toast.restored": "Restored {people}",
        "toast.imported": "Imported {people}",
        "toast.nothingToImport": "Nothing to import in that file",
        "toast.badFile": "That file isn't a Last Seen export",
        "people.title": "People",
        "people.searchPlaceholder": "Search by name or ID",
        "people.searchLabel": "Search remembered people",
        "people.nothingRecent": "Nothing recent",
        "people.noMatch": "No one matches that.",
        "people.empty": "No one yet. People show up here as Discord tells your client about them.",
        "people.showing": "Showing {shown} of {total}. Search to find someone else.",
    },
    de: {
        "settings.showOnProfiles": "In Profilen",
        "settings.showOnProfiles.description": "Eine Uhr neben den Abzeichen im Profil einer Person; fahre darüber, um die Zeiten zu sehen.",
        "settings.showInMemberList": "In der Mitgliederliste",
        "settings.showInMemberList.description": "Unter dem Namen von Offline-Mitgliedern.",
        "settings.showInFriends": "In der Freundesliste",
        "settings.showInFriends.description": "Unter dem Namen von Offline-Freunden.",
        "settings.showInDms": "In Direktnachrichten",
        "settings.showInDms.description": "Unter dem Namen von Offline-Personen in der DM-Liste.",
        "settings.ignoreBots": "Bots ignorieren",
        "settings.ignoreBots.description": "Bots und Apps nicht erfassen.",
        "unit.y": "{n} J.",
        "unit.mo": "{n} Mon.",
        "unit.w": "{n} Wo.",
        "unit.d": "{n} T.",
        "unit.h": "{n} Std.",
        "unit.m": "{n} Min.",
        "ago": "vor {span}",
        "justNow": "gerade eben",
        "seen": "Zuletzt online {when}",
        "seenIn": "Zuletzt online in den letzten {span}",
        "active": "Aktiv {when}",
        "online": "Jetzt online",
        "message": "Letzte Nachricht {when}",
        "messageIn": "Letzte Nachricht {when} in {where}",
        "where.channel": "#{name}",
        "where.dms": "deinen DMs",
        "where.group": "der Gruppe {name}",
        "where.groupUnnamed": "einer Gruppen-DM",
        "people": { one: "{n} Person", other: "{n} Personen" },
        "remembered.title": "Gespeichert",
        "remembered.cleared": "{people} gelöscht.",
        "remembered.status": "{people} von {cap}. Nur auf diesem Gerät gespeichert; Freunde und DMs bleiben am längsten erhalten.",
        "remembered.meter": "Belegter Speicher",
        "remembered.undo": "Rückgängig",
        "remembered.cancel": "Abbrechen",
        "remembered.confirmClear": "{people} löschen?",
        "remembered.export": "Exportieren",
        "remembered.import": "Importieren",
        "remembered.clear": "Daten löschen",
        "toast.restored": "{people} wiederhergestellt",
        "toast.imported": "{people} importiert",
        "toast.nothingToImport": "In dieser Datei gibt es nichts zu importieren",
        "toast.badFile": "Diese Datei ist kein Last-Seen-Export",
        "people.title": "Personen",
        "people.searchPlaceholder": "Nach Name oder ID suchen",
        "people.searchLabel": "Gespeicherte Personen durchsuchen",
        "people.nothingRecent": "Nichts Aktuelles",
        "people.noMatch": "Dazu passt niemand.",
        "people.empty": "Noch niemand. Personen erscheinen hier, sobald Discord deinem Client von ihnen berichtet.",
        "people.showing": "{shown} von {total} werden angezeigt. Suche, um jemand anderen zu finden.",
    },
    es: {
        "settings.showOnProfiles": "En los perfiles",
        "settings.showOnProfiles.description": "Un reloj junto a las insignias del perfil de alguien; pasa el cursor por encima para ver las horas.",
        "settings.showInMemberList": "En la lista de miembros",
        "settings.showInMemberList.description": "Debajo del nombre de los miembros desconectados.",
        "settings.showInFriends": "En la lista de amigos",
        "settings.showInFriends.description": "Debajo del nombre de los amigos desconectados.",
        "settings.showInDms": "En mensajes directos",
        "settings.showInDms.description": "Debajo del nombre de las personas desconectadas en la lista de MD.",
        "settings.ignoreBots": "Ignorar bots",
        "settings.ignoreBots.description": "No registrar bots ni aplicaciones.",
        "unit.y": "{n} a",
        "unit.mo": "{n} mes",
        "unit.w": "{n} sem",
        "unit.d": "{n} d",
        "unit.h": "{n} h",
        "unit.m": "{n} min",
        "ago": "hace {span}",
        "justNow": "ahora mismo",
        "seen": "Última conexión {when}",
        "seenIn": "Última conexión en las últimas {span}",
        "active": "Activo {when}",
        "online": "En línea ahora",
        "message": "Último mensaje {when}",
        "messageIn": "Último mensaje {when} en {where}",
        "where.channel": "#{name}",
        "where.dms": "tus MD",
        "where.group": "el grupo {name}",
        "where.groupUnnamed": "un MD de grupo",
        "people": { one: "{n} persona", other: "{n} personas" },
        "remembered.title": "Guardadas",
        "remembered.cleared": "Borrado: {people}.",
        "remembered.status": "{people} de {cap}. Se guardan solo en este dispositivo; los amigos y los MD se conservan más tiempo.",
        "remembered.meter": "Espacio usado",
        "remembered.undo": "Deshacer",
        "remembered.cancel": "Cancelar",
        "remembered.confirmClear": "¿Borrar {people}?",
        "remembered.export": "Exportar",
        "remembered.import": "Importar",
        "remembered.clear": "Borrar datos",
        "toast.restored": "Restaurado: {people}",
        "toast.imported": "Importado: {people}",
        "toast.nothingToImport": "No hay nada que importar en ese archivo",
        "toast.badFile": "Ese archivo no es una exportación de Last Seen",
        "people.title": "Personas",
        "people.searchPlaceholder": "Buscar por nombre o ID",
        "people.searchLabel": "Buscar entre las personas guardadas",
        "people.nothingRecent": "Nada reciente",
        "people.noMatch": "No hay nadie que coincida.",
        "people.empty": "Todavía nadie. Las personas aparecen aquí a medida que Discord informa de ellas a tu cliente.",
        "people.showing": "Mostrando {shown} de {total}. Busca para encontrar a otra persona.",
    },
    fr: {
        "settings.showOnProfiles": "Sur les profils",
        "settings.showOnProfiles.description": "Une horloge à côté des badges du profil d'une personne ; survole-la pour voir les heures.",
        "settings.showInMemberList": "Dans la liste des membres",
        "settings.showInMemberList.description": "Sous le nom des membres hors ligne.",
        "settings.showInFriends": "Dans la liste d'amis",
        "settings.showInFriends.description": "Sous le nom des amis hors ligne.",
        "settings.showInDms": "Dans les messages privés",
        "settings.showInDms.description": "Sous le nom des personnes hors ligne dans la liste des MP.",
        "settings.ignoreBots": "Ignorer les bots",
        "settings.ignoreBots.description": "Ne pas suivre les bots et les applications.",
        "unit.y": "{n} a",
        "unit.mo": "{n} mois",
        "unit.w": "{n} sem.",
        "unit.d": "{n} j",
        "unit.h": "{n} h",
        "unit.m": "{n} min",
        "ago": "il y a {span}",
        "justNow": "à l'instant",
        "seen": "Dernière connexion {when}",
        "seenIn": "Dernière connexion il y a moins de {span}",
        "active": "Actif {when}",
        "online": "En ligne",
        "message": "Dernier message {when}",
        "messageIn": "Dernier message {when} dans {where}",
        "where.channel": "#{name}",
        "where.dms": "tes MP",
        "where.group": "le groupe {name}",
        "where.groupUnnamed": "un MP de groupe",
        "people": { one: "{n} personne", other: "{n} personnes" },
        "remembered.title": "Enregistrées",
        "remembered.cleared": "Effacé : {people}.",
        "remembered.status": "{people} sur {cap}. Conservées uniquement sur cet appareil ; les amis et les MP sont gardés le plus longtemps.",
        "remembered.meter": "Espace utilisé",
        "remembered.undo": "Annuler",
        "remembered.cancel": "Annuler",
        "remembered.confirmClear": "Effacer {people} ?",
        "remembered.export": "Exporter",
        "remembered.import": "Importer",
        "remembered.clear": "Effacer les données",
        "toast.restored": "Restauré : {people}",
        "toast.imported": "Importé : {people}",
        "toast.nothingToImport": "Rien à importer dans ce fichier",
        "toast.badFile": "Ce fichier n'est pas un export de Last Seen",
        "people.title": "Personnes",
        "people.searchPlaceholder": "Rechercher par nom ou ID",
        "people.searchLabel": "Rechercher parmi les personnes enregistrées",
        "people.nothingRecent": "Rien de récent",
        "people.noMatch": "Personne ne correspond.",
        "people.empty": "Personne pour l'instant. Les personnes apparaissent ici quand Discord les signale à ton client.",
        "people.showing": "{shown} affichées sur {total}. Utilise la recherche pour trouver quelqu'un d'autre.",
    },
    ja: {
        "settings.showOnProfiles": "プロフィールに表示",
        "settings.showOnProfiles.description": "ユーザーのプロフィールのバッジの横に時計を表示します。ホバーすると時刻が見られます。",
        "settings.showInMemberList": "メンバーリストに表示",
        "settings.showInMemberList.description": "オフラインのメンバーの名前の下に表示します。",
        "settings.showInFriends": "フレンドリストに表示",
        "settings.showInFriends.description": "オフラインのフレンドの名前の下に表示します。",
        "settings.showInDms": "ダイレクトメッセージに表示",
        "settings.showInDms.description": "DMリストのオフラインのユーザーの名前の下に表示します。",
        "settings.ignoreBots": "Botを無視",
        "settings.ignoreBots.description": "Botやアプリは記録しません。",
        "unit.y": "{n}年",
        "unit.mo": "{n}か月",
        "unit.w": "{n}週間",
        "unit.d": "{n}日",
        "unit.h": "{n}時間",
        "unit.m": "{n}分",
        "ago": "{span}前",
        "justNow": "たった今",
        "seen": "最終オンライン: {when}",
        "seenIn": "最終オンライン: 過去{span}以内",
        "active": "アクティブ: {when}",
        "online": "オンライン中",
        "message": "最後のメッセージ: {when}",
        "messageIn": "最後のメッセージ: {when}({where})",
        "where.channel": "#{name}",
        "where.dms": "あなたのDM",
        "where.group": "グループ「{name}」",
        "where.groupUnnamed": "グループDM",
        "people": { other: "{n}人" },
        "remembered.title": "記憶している人数",
        "remembered.cleared": "{people}分を消去しました。",
        "remembered.status": "{cap}人中{people}。このデバイスにのみ保存され、フレンドとDMの相手は最も長く保持されます。",
        "remembered.meter": "使用中の容量",
        "remembered.undo": "元に戻す",
        "remembered.cancel": "キャンセル",
        "remembered.confirmClear": "{people}分を消去しますか?",
        "remembered.export": "エクスポート",
        "remembered.import": "インポート",
        "remembered.clear": "データを消去",
        "toast.restored": "{people}分を復元しました",
        "toast.imported": "{people}分をインポートしました",
        "toast.nothingToImport": "このファイルにはインポートできるデータがありません",
        "toast.badFile": "このファイルはLast Seenのエクスポートではありません",
        "people.title": "ユーザー",
        "people.searchPlaceholder": "名前またはIDで検索",
        "people.searchLabel": "記憶しているユーザーを検索",
        "people.nothingRecent": "最近の記録なし",
        "people.noMatch": "一致するユーザーはいません。",
        "people.empty": "まだ誰もいません。Discordがクライアントにユーザーの情報を伝えると、ここに表示されます。",
        "people.showing": "{total}人中{shown}人を表示中。ほかのユーザーは検索で探してください。",
    },
    pl: {
        "settings.showOnProfiles": "Na profilach",
        "settings.showOnProfiles.description": "Zegar obok odznak na profilu użytkownika; najedź na niego, aby zobaczyć godziny.",
        "settings.showInMemberList": "Na liście członków",
        "settings.showInMemberList.description": "Pod nazwą członków offline.",
        "settings.showInFriends": "Na liście znajomych",
        "settings.showInFriends.description": "Pod nazwą znajomych offline.",
        "settings.showInDms": "W wiadomościach prywatnych",
        "settings.showInDms.description": "Pod nazwą osób offline na liście wiadomości prywatnych.",
        "settings.ignoreBots": "Ignoruj boty",
        "settings.ignoreBots.description": "Nie śledź botów i aplikacji.",
        "unit.y": "{n} r.",
        "unit.mo": "{n} mies.",
        "unit.w": "{n} tyg.",
        "unit.d": "{n} d.",
        "unit.h": "{n} godz.",
        "unit.m": "{n} min",
        "ago": "{span} temu",
        "justNow": "przed chwilą",
        "seen": "Ostatnio online {when}",
        "seenIn": "Ostatnio online w ciągu ostatnich {span}",
        "active": "Aktywny {when}",
        "online": "Teraz online",
        "message": "Ostatnia wiadomość {when}",
        "messageIn": "Ostatnia wiadomość {when} w {where}",
        "where.channel": "#{name}",
        "where.dms": "Twoich wiadomościach prywatnych",
        "where.group": "grupie {name}",
        "where.groupUnnamed": "grupowej wiadomości prywatnej",
        "people": { one: "{n} osoba", few: "{n} osoby", many: "{n} osób", other: "{n} osoby" },
        "remembered.title": "Zapamiętane",
        "remembered.cleared": "Wyczyszczono: {people}.",
        "remembered.status": "{people} z {cap}. Przechowywane tylko na tym urządzeniu; znajomi i wiadomości prywatne są trzymane najdłużej.",
        "remembered.meter": "Zajęte miejsce",
        "remembered.undo": "Cofnij",
        "remembered.cancel": "Anuluj",
        "remembered.confirmClear": "Wyczyścić: {people}?",
        "remembered.export": "Eksportuj",
        "remembered.import": "Importuj",
        "remembered.clear": "Wyczyść dane",
        "toast.restored": "Przywrócono: {people}",
        "toast.imported": "Zaimportowano: {people}",
        "toast.nothingToImport": "W tym pliku nie ma nic do zaimportowania",
        "toast.badFile": "Ten plik nie jest eksportem Last Seen",
        "people.title": "Osoby",
        "people.searchPlaceholder": "Szukaj po nazwie lub ID",
        "people.searchLabel": "Szukaj wśród zapamiętanych osób",
        "people.nothingRecent": "Nic nowego",
        "people.noMatch": "Nikt nie pasuje.",
        "people.empty": "Na razie nikogo. Osoby pojawiają się tutaj, gdy Discord przekaże Twojemu klientowi informacje o nich.",
        "people.showing": "Wyświetlono {shown} z {total}. Użyj wyszukiwania, aby znaleźć kogoś innego.",
    },
    "pt-BR": {
        "settings.showOnProfiles": "Nos perfis",
        "settings.showOnProfiles.description": "Um relógio ao lado das insígnias no perfil de alguém; passe o mouse para ver os horários.",
        "settings.showInMemberList": "Na lista de membros",
        "settings.showInMemberList.description": "Abaixo do nome dos membros offline.",
        "settings.showInFriends": "Na lista de amigos",
        "settings.showInFriends.description": "Abaixo do nome dos amigos offline.",
        "settings.showInDms": "Nas mensagens diretas",
        "settings.showInDms.description": "Abaixo do nome das pessoas offline na lista de DMs.",
        "settings.ignoreBots": "Ignorar bots",
        "settings.ignoreBots.description": "Não rastrear bots e apps.",
        "unit.y": "{n} a",
        "unit.mo": "{n} mes.",
        "unit.w": "{n} sem",
        "unit.d": "{n} d",
        "unit.h": "{n} h",
        "unit.m": "{n} min",
        "ago": "há {span}",
        "justNow": "agora mesmo",
        "seen": "Visto por último {when}",
        "seenIn": "Visto por último nas últimas {span}",
        "active": "Ativo {when}",
        "online": "Online agora",
        "message": "Última mensagem {when}",
        "messageIn": "Última mensagem {when} {where}",
        "where.channel": "em #{name}",
        "where.dms": "nas suas DMs",
        "where.group": "no grupo {name}",
        "where.groupUnnamed": "em uma DM em grupo",
        "people": { one: "{n} pessoa", other: "{n} pessoas" },
        "remembered.title": "Lembradas",
        "remembered.cleared": "Apagado: {people}.",
        "remembered.status": "{people} de {cap}. Guardadas só neste dispositivo; amigos e DMs são mantidos por mais tempo.",
        "remembered.meter": "Espaço usado",
        "remembered.undo": "Desfazer",
        "remembered.cancel": "Cancelar",
        "remembered.confirmClear": "Apagar {people}?",
        "remembered.export": "Exportar",
        "remembered.import": "Importar",
        "remembered.clear": "Apagar dados",
        "toast.restored": "Restaurado: {people}",
        "toast.imported": "Importado: {people}",
        "toast.nothingToImport": "Não há nada para importar nesse arquivo",
        "toast.badFile": "Esse arquivo não é uma exportação do Last Seen",
        "people.title": "Pessoas",
        "people.searchPlaceholder": "Buscar por nome ou ID",
        "people.searchLabel": "Buscar entre as pessoas lembradas",
        "people.nothingRecent": "Nada recente",
        "people.noMatch": "Ninguém corresponde.",
        "people.empty": "Ninguém ainda. As pessoas aparecem aqui conforme o Discord informa sobre elas ao seu cliente.",
        "people.showing": "Mostrando {shown} de {total}. Use a busca para encontrar outra pessoa.",
    },
    ru: {
        "settings.showOnProfiles": "В профилях",
        "settings.showOnProfiles.description": "Часы рядом со значками в профиле пользователя; наведите на них курсор, чтобы увидеть время.",
        "settings.showInMemberList": "В списке участников",
        "settings.showInMemberList.description": "Под именем участников, которые не в сети.",
        "settings.showInFriends": "В списке друзей",
        "settings.showInFriends.description": "Под именем друзей, которые не в сети.",
        "settings.showInDms": "В личных сообщениях",
        "settings.showInDms.description": "Под именем пользователей, которые не в сети, в списке ЛС.",
        "settings.ignoreBots": "Игнорировать ботов",
        "settings.ignoreBots.description": "Не отслеживать ботов и приложения.",
        "unit.y": "{n} г.",
        "unit.mo": "{n} мес.",
        "unit.w": "{n} нед.",
        "unit.d": "{n} дн.",
        "unit.h": "{n} ч",
        "unit.m": "{n} мин",
        "ago": "{span} назад",
        "justNow": "только что",
        "seen": "Последний раз в сети: {when}",
        "seenIn": "Последний раз в сети: за последние {span}",
        "active": "Активность: {when}",
        "online": "Сейчас в сети",
        "message": "Последнее сообщение: {when}",
        "messageIn": "Последнее сообщение: {when}, {where}",
        "where.channel": "в #{name}",
        "where.dms": "в личных сообщениях",
        "where.group": "в группе {name}",
        "where.groupUnnamed": "в групповом чате",
        "people": { one: "{n} человек", few: "{n} человека", many: "{n} человек", other: "{n} человека" },
        "remembered.title": "Запомнено",
        "remembered.cleared": "Удалено: {people}.",
        "remembered.status": "{people} из {cap}. Хранится только на этом устройстве; друзья и собеседники из ЛС хранятся дольше всего.",
        "remembered.meter": "Занятое место",
        "remembered.undo": "Отменить",
        "remembered.cancel": "Отмена",
        "remembered.confirmClear": "Удалить: {people}?",
        "remembered.export": "Экспорт",
        "remembered.import": "Импорт",
        "remembered.clear": "Удалить данные",
        "toast.restored": "Восстановлено: {people}",
        "toast.imported": "Импортировано: {people}",
        "toast.nothingToImport": "В этом файле нечего импортировать",
        "toast.badFile": "Этот файл не является экспортом Last Seen",
        "people.title": "Люди",
        "people.searchPlaceholder": "Поиск по имени или ID",
        "people.searchLabel": "Поиск среди запомненных людей",
        "people.nothingRecent": "Ничего свежего",
        "people.noMatch": "Никто не подходит.",
        "people.empty": "Пока никого. Люди появляются здесь, когда Discord сообщает о них клиенту.",
        "people.showing": "Показано {shown} из {total}. Воспользуйтесь поиском, чтобы найти кого-то ещё.",
    },
    tr: {
        "settings.showOnProfiles": "Profillerde",
        "settings.showOnProfiles.description": "Birinin profilinde rozetlerin yanında bir saat; zamanları görmek için üzerine gel.",
        "settings.showInMemberList": "Üye listesinde",
        "settings.showInMemberList.description": "Çevrimdışı üyelerin adının altında.",
        "settings.showInFriends": "Arkadaş listesinde",
        "settings.showInFriends.description": "Çevrimdışı arkadaşların adının altında.",
        "settings.showInDms": "Doğrudan mesajlarda",
        "settings.showInDms.description": "DM listesindeki çevrimdışı kişilerin adının altında.",
        "settings.ignoreBots": "Botları yok say",
        "settings.ignoreBots.description": "Botları ve uygulamaları takip etme.",
        "unit.y": "{n} yıl",
        "unit.mo": "{n} ay",
        "unit.w": "{n} hf",
        "unit.d": "{n} gn",
        "unit.h": "{n} sa",
        "unit.m": "{n} dk",
        "ago": "{span} önce",
        "justNow": "az önce",
        "seen": "Son görülme: {when}",
        "seenIn": "Son görülme: son {span} içinde",
        "active": "Aktif: {when}",
        "online": "Şu an çevrimiçi",
        "message": "Son mesaj: {when}",
        "messageIn": "Son mesaj: {when}, {where}",
        "where.channel": "#{name} kanalında",
        "where.dms": "DM'lerinde",
        "where.group": "{name} grubunda",
        "where.groupUnnamed": "bir grup DM'sinde",
        "people": { one: "{n} kişi", other: "{n} kişi" },
        "remembered.title": "Hatırlananlar",
        "remembered.cleared": "{people} silindi.",
        "remembered.status": "{cap} kişiden {people}. Yalnızca bu cihazda tutulur; arkadaşlar ve DM'ler en uzun süre saklanır.",
        "remembered.meter": "Kullanılan alan",
        "remembered.undo": "Geri al",
        "remembered.cancel": "İptal",
        "remembered.confirmClear": "{people} silinsin mi?",
        "remembered.export": "Dışa aktar",
        "remembered.import": "İçe aktar",
        "remembered.clear": "Verileri temizle",
        "toast.restored": "{people} geri yüklendi",
        "toast.imported": "{people} içe aktarıldı",
        "toast.nothingToImport": "Bu dosyada içe aktarılacak bir şey yok",
        "toast.badFile": "Bu dosya bir Last Seen dışa aktarımı değil",
        "people.title": "Kişiler",
        "people.searchPlaceholder": "Ada veya kimliğe göre ara",
        "people.searchLabel": "Hatırlanan kişilerde ara",
        "people.nothingRecent": "Yakın zamanda bir şey yok",
        "people.noMatch": "Eşleşen kimse yok.",
        "people.empty": "Henüz kimse yok. Discord istemcine kişileri bildirdikçe burada görünürler.",
        "people.showing": "{total} kişiden {shown} tanesi gösteriliyor. Başka birini bulmak için ara.",
    },
});

/** The words for track.ts's summaries, in Discord's language */
export const words: Words = (key: WordKey, vars) => t(key, vars);

/** "{n} people" with the count as Discord writes numbers */
export const people = (n: number) => t("people", { count: n, n: n.toLocaleString() });

