import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "download": "Download",
        "viewBanner": "View Banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Server Avatar",
        "kind.banner": "Banner",
        "kind.server-banner": "Server Banner",
        "kind.icon": "Icon",
        "kind.splash": "Invite Background",
        "kind.discovery-splash": "Discovery Background",
        "toast.downloadFailed": "Couldn't download the picture, opening it in your browser",
        "details.open": "Profile details",
        "details.title": "Profile details",
        "details.close": "Close",
        "details.theme": "Profile theme",
        "details.primary": "Top",
        "details.accent": "Bottom",
        "details.bannerColor": "Banner colour",
        "details.nameStyle": "Display name style",
        "details.effect": "Effect",
        "details.font": "Font",
        "details.color": "Colour {n}",
        "details.nameplate": "Nameplate",
        "details.none": "Nothing custom on this profile: no theme, banner colour, name style or nameplate.",
        "details.copy": "Copy {value}",
        "details.copied": "Copied {value}",
        "details.useTop": "Use as my profile's top colour",
        "details.useBottom": "Use as my profile's bottom colour",
        "details.useTheme": "Use this whole theme on my profile",
        "details.useBanner": "Use as my banner colour",
        "details.useNameStyle": "Use this name style on my profile",
        "details.applied": "Saved to your profile",
        "details.applyFailed": "Couldn't save that to your profile",
        "details.needsNitro": "Discord only allows that with Nitro",
        "details.inShop": "View in Shop",
    },
    de: {
        "download": "Herunterladen",
        "viewBanner": "Banner ansehen",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Server-Avatar",
        "kind.banner": "Banner",
        "kind.server-banner": "Server-Banner",
        "kind.icon": "Symbol",
        "kind.splash": "Einladungshintergrund",
        "kind.discovery-splash": "Entdecken-Hintergrund",
        "toast.downloadFailed": "Das Bild konnte nicht heruntergeladen werden, es wird in deinem Browser geöffnet",
        "details.open": "Profildetails",
        "details.title": "Profildetails",
        "details.close": "Schließen",
        "details.theme": "Profildesign",
        "details.primary": "Oben",
        "details.accent": "Unten",
        "details.bannerColor": "Bannerfarbe",
        "details.nameStyle": "Stil des Anzeigenamens",
        "details.effect": "Effekt",
        "details.font": "Schriftart",
        "details.color": "Farbe {n}",
        "details.nameplate": "Namensschild",
        "details.none": "Nichts Eigenes an diesem Profil: kein Design, keine Bannerfarbe, kein Namensstil und kein Namensschild.",
        "details.copy": "{value} kopieren",
        "details.copied": "{value} kopiert",
        "details.useTop": "Als obere Farbe meines Profils verwenden",
        "details.useBottom": "Als untere Farbe meines Profils verwenden",
        "details.useTheme": "Dieses ganze Design für mein Profil verwenden",
        "details.useBanner": "Als meine Bannerfarbe verwenden",
        "details.useNameStyle": "Diesen Namensstil für mein Profil verwenden",
        "details.applied": "In deinem Profil gespeichert",
        "details.applyFailed": "Konnte das nicht in deinem Profil speichern",
        "details.needsNitro": "Discord erlaubt das nur mit Nitro",
        "details.inShop": "Im Shop ansehen",
    },
    es: {
        "download": "Descargar",
        "viewBanner": "Ver banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar del servidor",
        "kind.banner": "Banner",
        "kind.server-banner": "Banner del servidor",
        "kind.icon": "Icono",
        "kind.splash": "Fondo de invitación",
        "kind.discovery-splash": "Fondo de Descubrimiento",
        "toast.downloadFailed": "No se pudo descargar la imagen, se abrirá en tu navegador",
        "details.open": "Detalles del perfil",
        "details.title": "Detalles del perfil",
        "details.close": "Cerrar",
        "details.theme": "Tema del perfil",
        "details.primary": "Arriba",
        "details.accent": "Abajo",
        "details.bannerColor": "Color del banner",
        "details.nameStyle": "Estilo del nombre",
        "details.effect": "Efecto",
        "details.font": "Fuente",
        "details.color": "Color {n}",
        "details.nameplate": "Placa de nombre",
        "details.none": "Este perfil no tiene nada personalizado: ni tema, ni color de banner, ni estilo de nombre, ni placa.",
        "details.copy": "Copiar {value}",
        "details.copied": "{value} copiado",
        "details.useTop": "Usar como color superior de mi perfil",
        "details.useBottom": "Usar como color inferior de mi perfil",
        "details.useTheme": "Usar todo este tema en mi perfil",
        "details.useBanner": "Usar como color de mi banner",
        "details.useNameStyle": "Usar este estilo de nombre en mi perfil",
        "details.applied": "Guardado en tu perfil",
        "details.applyFailed": "No se pudo guardar en tu perfil",
        "details.needsNitro": "Discord solo lo permite con Nitro",
        "details.inShop": "Ver en la tienda",
    },
    fr: {
        "download": "Télécharger",
        "viewBanner": "Voir la bannière",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar du serveur",
        "kind.banner": "Bannière",
        "kind.server-banner": "Bannière du serveur",
        "kind.icon": "Icône",
        "kind.splash": "Arrière-plan d'invitation",
        "kind.discovery-splash": "Arrière-plan de Découverte",
        "toast.downloadFailed": "Impossible de télécharger l'image, ouverture dans ton navigateur",
        "details.open": "Détails du profil",
        "details.title": "Détails du profil",
        "details.close": "Fermer",
        "details.theme": "Thème du profil",
        "details.primary": "Haut",
        "details.accent": "Bas",
        "details.bannerColor": "Couleur de la bannière",
        "details.nameStyle": "Style du pseudo",
        "details.effect": "Effet",
        "details.font": "Police",
        "details.color": "Couleur {n}",
        "details.nameplate": "Plaque de nom",
        "details.none": "Rien de personnalisé sur ce profil : ni thème, ni couleur de bannière, ni style de pseudo, ni plaque.",
        "details.copy": "Copier {value}",
        "details.copied": "{value} copié",
        "details.useTop": "Utiliser comme couleur du haut de mon profil",
        "details.useBottom": "Utiliser comme couleur du bas de mon profil",
        "details.useTheme": "Utiliser tout ce thème sur mon profil",
        "details.useBanner": "Utiliser comme couleur de ma bannière",
        "details.useNameStyle": "Utiliser ce style de pseudo sur mon profil",
        "details.applied": "Enregistré sur votre profil",
        "details.applyFailed": "Impossible d'enregistrer cela sur votre profil",
        "details.needsNitro": "Discord ne le permet qu'avec Nitro",
        "details.inShop": "Voir dans la boutique",
    },
    ja: {
        "download": "ダウンロード",
        "viewBanner": "バナーを表示",
        "kind.avatar": "アバター",
        "kind.server-avatar": "サーバーアバター",
        "kind.banner": "バナー",
        "kind.server-banner": "サーバーバナー",
        "kind.icon": "アイコン",
        "kind.splash": "招待の背景",
        "kind.discovery-splash": "ディスカバリーの背景",
        "toast.downloadFailed": "画像をダウンロードできなかったため、ブラウザーで開きます",
        "details.open": "プロフィールの詳細",
        "details.title": "プロフィールの詳細",
        "details.close": "閉じる",
        "details.theme": "プロフィールテーマ",
        "details.primary": "上",
        "details.accent": "下",
        "details.bannerColor": "バナーの色",
        "details.nameStyle": "表示名のスタイル",
        "details.effect": "エフェクト",
        "details.font": "フォント",
        "details.color": "色 {n}",
        "details.nameplate": "ネームプレート",
        "details.none": "このプロフィールにはカスタマイズがありません(テーマ、バナーの色、名前のスタイル、ネームプレートなし)。",
        "details.copy": "{value}をコピー",
        "details.copied": "{value}をコピーしました",
        "details.useTop": "自分のプロフィールの上の色にする",
        "details.useBottom": "自分のプロフィールの下の色にする",
        "details.useTheme": "このテーマを自分のプロフィールに使う",
        "details.useBanner": "自分のバナーの色にする",
        "details.useNameStyle": "この名前のスタイルを自分のプロフィールに使う",
        "details.applied": "プロフィールに保存しました",
        "details.applyFailed": "プロフィールに保存できませんでした",
        "details.needsNitro": "DiscordではNitroが必要です",
        "details.inShop": "ショップで見る",
    },
    pl: {
        "download": "Pobierz",
        "viewBanner": "Zobacz baner",
        "kind.avatar": "Awatar",
        "kind.server-avatar": "Awatar serwera",
        "kind.banner": "Baner",
        "kind.server-banner": "Baner serwera",
        "kind.icon": "Ikona",
        "kind.splash": "Tło zaproszenia",
        "kind.discovery-splash": "Tło odkrywania",
        "toast.downloadFailed": "Nie udało się pobrać obrazu, otwieram go w przeglądarce",
        "details.open": "Szczegóły profilu",
        "details.title": "Szczegóły profilu",
        "details.close": "Zamknij",
        "details.theme": "Motyw profilu",
        "details.primary": "Góra",
        "details.accent": "Dół",
        "details.bannerColor": "Kolor banera",
        "details.nameStyle": "Styl nazwy",
        "details.effect": "Efekt",
        "details.font": "Czcionka",
        "details.color": "Kolor {n}",
        "details.nameplate": "Tabliczka",
        "details.none": "Ten profil nie ma nic własnego: bez motywu, koloru banera, stylu nazwy i tabliczki.",
        "details.copy": "Kopiuj {value}",
        "details.copied": "Skopiowano {value}",
        "details.useTop": "Użyj jako górnego koloru mojego profilu",
        "details.useBottom": "Użyj jako dolnego koloru mojego profilu",
        "details.useTheme": "Użyj całego tego motywu w moim profilu",
        "details.useBanner": "Użyj jako koloru mojego banera",
        "details.useNameStyle": "Użyj tego stylu nazwy w moim profilu",
        "details.applied": "Zapisano w twoim profilu",
        "details.applyFailed": "Nie udało się zapisać tego w profilu",
        "details.needsNitro": "Discord pozwala na to tylko z Nitro",
        "details.inShop": "Zobacz w sklepie",
    },
    "pt-BR": {
        "download": "Baixar",
        "viewBanner": "Ver banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar do servidor",
        "kind.banner": "Banner",
        "kind.server-banner": "Banner do servidor",
        "kind.icon": "Ícone",
        "kind.splash": "Plano de fundo do convite",
        "kind.discovery-splash": "Plano de fundo do Descobrir",
        "toast.downloadFailed": "Não foi possível baixar a imagem, abrindo no seu navegador",
        "details.open": "Detalhes do perfil",
        "details.title": "Detalhes do perfil",
        "details.close": "Fechar",
        "details.theme": "Tema do perfil",
        "details.primary": "Topo",
        "details.accent": "Base",
        "details.bannerColor": "Cor do banner",
        "details.nameStyle": "Estilo do nome",
        "details.effect": "Efeito",
        "details.font": "Fonte",
        "details.color": "Cor {n}",
        "details.nameplate": "Placa de nome",
        "details.none": "Nada personalizado neste perfil: sem tema, cor de banner, estilo de nome ou placa.",
        "details.copy": "Copiar {value}",
        "details.copied": "{value} copiado",
        "details.useTop": "Usar como cor de cima do meu perfil",
        "details.useBottom": "Usar como cor de baixo do meu perfil",
        "details.useTheme": "Usar este tema inteiro no meu perfil",
        "details.useBanner": "Usar como cor do meu banner",
        "details.useNameStyle": "Usar este estilo de nome no meu perfil",
        "details.applied": "Salvo no seu perfil",
        "details.applyFailed": "Não foi possível salvar no seu perfil",
        "details.needsNitro": "O Discord só permite isso com Nitro",
        "details.inShop": "Ver na loja",
    },
    ru: {
        "download": "Скачать",
        "viewBanner": "Посмотреть баннер",
        "kind.avatar": "Аватар",
        "kind.server-avatar": "Аватар сервера",
        "kind.banner": "Баннер",
        "kind.server-banner": "Баннер сервера",
        "kind.icon": "Значок",
        "kind.splash": "Фон приглашения",
        "kind.discovery-splash": "Фон в «Обзоре»",
        "toast.downloadFailed": "Не удалось скачать изображение, открываем его в браузере",
        "details.open": "Детали профиля",
        "details.title": "Детали профиля",
        "details.close": "Закрыть",
        "details.theme": "Тема профиля",
        "details.primary": "Верх",
        "details.accent": "Низ",
        "details.bannerColor": "Цвет баннера",
        "details.nameStyle": "Стиль имени",
        "details.effect": "Эффект",
        "details.font": "Шрифт",
        "details.color": "Цвет {n}",
        "details.nameplate": "Табличка",
        "details.none": "В этом профиле нет ничего своего: ни темы, ни цвета баннера, ни стиля имени, ни таблички.",
        "details.copy": "Копировать {value}",
        "details.copied": "Скопировано: {value}",
        "details.useTop": "Сделать верхним цветом моего профиля",
        "details.useBottom": "Сделать нижним цветом моего профиля",
        "details.useTheme": "Использовать эту тему в моём профиле",
        "details.useBanner": "Сделать цветом моего баннера",
        "details.useNameStyle": "Использовать этот стиль имени в моём профиле",
        "details.applied": "Сохранено в вашем профиле",
        "details.applyFailed": "Не удалось сохранить в профиле",
        "details.needsNitro": "Discord разрешает это только с Nitro",
        "details.inShop": "Открыть в магазине",
    },
    tr: {
        "download": "İndir",
        "viewBanner": "Banner'ı Görüntüle",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Sunucu Avatarı",
        "kind.banner": "Banner",
        "kind.server-banner": "Sunucu Banner'ı",
        "kind.icon": "Simge",
        "kind.splash": "Davet Arka Planı",
        "kind.discovery-splash": "Keşfet Arka Planı",
        "toast.downloadFailed": "Resim indirilemedi, tarayıcında açılıyor",
        "details.open": "Profil ayrıntıları",
        "details.title": "Profil ayrıntıları",
        "details.close": "Kapat",
        "details.theme": "Profil teması",
        "details.primary": "Üst",
        "details.accent": "Alt",
        "details.bannerColor": "Afiş rengi",
        "details.nameStyle": "Görünen ad stili",
        "details.effect": "Efekt",
        "details.font": "Yazı tipi",
        "details.color": "Renk {n}",
        "details.nameplate": "İsim plakası",
        "details.none": "Bu profilde özel bir şey yok: tema, afiş rengi, ad stili ya da isim plakası yok.",
        "details.copy": "{value} kopyala",
        "details.copied": "{value} kopyalandı",
        "details.useTop": "Profilimin üst rengi yap",
        "details.useBottom": "Profilimin alt rengi yap",
        "details.useTheme": "Bu temanın tamamını profilimde kullan",
        "details.useBanner": "Afiş rengim yap",
        "details.useNameStyle": "Bu ad stilini profilimde kullan",
        "details.applied": "Profiline kaydedildi",
        "details.applyFailed": "Bu profiline kaydedilemedi",
        "details.needsNitro": "Discord buna yalnızca Nitro ile izin veriyor",
        "details.inShop": "Mağazada gör",
    },
});
