import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "download": "Download",
        "viewBanner": "View Banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Server Avatar",
        "kind.banner": "Banner",
        "kind.server-banner": "Server Banner",
        "kind.icon": "Icon",
        "kind.splash": "Invite Background",
        "kind.discovery-splash": "Discovery Background",
        "toast.downloadFailed": "Couldn't download the picture, opening it in your browser",
    },
    de: {
        "download": "Herunterladen",
        "viewBanner": "Banner ansehen",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Server-Avatar",
        "kind.banner": "Banner",
        "kind.server-banner": "Server-Banner",
        "kind.icon": "Symbol",
        "kind.splash": "Einladungshintergrund",
        "kind.discovery-splash": "Entdecken-Hintergrund",
        "toast.downloadFailed": "Das Bild konnte nicht heruntergeladen werden, es wird in deinem Browser geöffnet",
    },
    es: {
        "download": "Descargar",
        "viewBanner": "Ver banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar del servidor",
        "kind.banner": "Banner",
        "kind.server-banner": "Banner del servidor",
        "kind.icon": "Icono",
        "kind.splash": "Fondo de invitación",
        "kind.discovery-splash": "Fondo de Descubrimiento",
        "toast.downloadFailed": "No se pudo descargar la imagen, se abrirá en tu navegador",
    },
    fr: {
        "download": "Télécharger",
        "viewBanner": "Voir la bannière",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar du serveur",
        "kind.banner": "Bannière",
        "kind.server-banner": "Bannière du serveur",
        "kind.icon": "Icône",
        "kind.splash": "Arrière-plan d'invitation",
        "kind.discovery-splash": "Arrière-plan de Découverte",
        "toast.downloadFailed": "Impossible de télécharger l'image, ouverture dans ton navigateur",
    },
    ja: {
        "download": "ダウンロード",
        "viewBanner": "バナーを表示",
        "kind.avatar": "アバター",
        "kind.server-avatar": "サーバーアバター",
        "kind.banner": "バナー",
        "kind.server-banner": "サーバーバナー",
        "kind.icon": "アイコン",
        "kind.splash": "招待の背景",
        "kind.discovery-splash": "ディスカバリーの背景",
        "toast.downloadFailed": "画像をダウンロードできなかったため、ブラウザーで開きます",
    },
    pl: {
        "download": "Pobierz",
        "viewBanner": "Zobacz baner",
        "kind.avatar": "Awatar",
        "kind.server-avatar": "Awatar serwera",
        "kind.banner": "Baner",
        "kind.server-banner": "Baner serwera",
        "kind.icon": "Ikona",
        "kind.splash": "Tło zaproszenia",
        "kind.discovery-splash": "Tło odkrywania",
        "toast.downloadFailed": "Nie udało się pobrać obrazu, otwieram go w przeglądarce",
    },
    "pt-BR": {
        "download": "Baixar",
        "viewBanner": "Ver banner",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Avatar do servidor",
        "kind.banner": "Banner",
        "kind.server-banner": "Banner do servidor",
        "kind.icon": "Ícone",
        "kind.splash": "Plano de fundo do convite",
        "kind.discovery-splash": "Plano de fundo do Descobrir",
        "toast.downloadFailed": "Não foi possível baixar a imagem, abrindo no seu navegador",
    },
    ru: {
        "download": "Скачать",
        "viewBanner": "Посмотреть баннер",
        "kind.avatar": "Аватар",
        "kind.server-avatar": "Аватар сервера",
        "kind.banner": "Баннер",
        "kind.server-banner": "Баннер сервера",
        "kind.icon": "Значок",
        "kind.splash": "Фон приглашения",
        "kind.discovery-splash": "Фон в «Обзоре»",
        "toast.downloadFailed": "Не удалось скачать изображение, открываем его в браузере",
    },
    tr: {
        "download": "İndir",
        "viewBanner": "Banner'ı Görüntüle",
        "kind.avatar": "Avatar",
        "kind.server-avatar": "Sunucu Avatarı",
        "kind.banner": "Banner",
        "kind.server-banner": "Sunucu Banner'ı",
        "kind.icon": "Simge",
        "kind.splash": "Davet Arka Planı",
        "kind.discovery-splash": "Keşfet Arka Planı",
        "toast.downloadFailed": "Resim indirilemedi, tarayıcında açılıyor",
    },
});
