import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "copy": "Copy",
        "copied": "Copied",
        "copiedPart": "Copied the first {size}",
        "copyFailed": "Couldn't copy it",
        "download": "Download",
        "downloadFailed": "Couldn't save the file",
        "pretty": "Pretty print",
        "original": "Show as sent",
        "preview.show": "Preview",
        "preview.hide": "Hide preview",
        "preview.loading": "Loading…",
        "preview.error": "Couldn't load this file",
        "preview.partial": "Showing the first {size}",
        "settings.lineNumbers": "Line numbers",
        "settings.lineNumbers.description": "Numbers beside the lines of code blocks and text files. Text files start without word wrap, since wrapped lines can't be numbered.",
        "settings.filePreview": "Preview other text files",
        "settings.filePreview.description": "Text files Discord shows only as a download (like .log, .cfg or .ini) get a Preview button.",
    },
    de: {
        "copy": "Kopieren",
        "copied": "Kopiert",
        "copiedPart": "Die ersten {size} kopiert",
        "copyFailed": "Konnte nicht kopiert werden",
        "download": "Herunterladen",
        "downloadFailed": "Die Datei konnte nicht gespeichert werden",
        "pretty": "Formatieren",
        "original": "Wie gesendet anzeigen",
        "preview.show": "Vorschau",
        "preview.hide": "Vorschau ausblenden",
        "preview.loading": "Wird geladen…",
        "preview.error": "Diese Datei konnte nicht geladen werden",
        "preview.partial": "Die ersten {size} werden angezeigt",
        "settings.lineNumbers": "Zeilennummern",
        "settings.lineNumbers.description": "Nummern neben den Zeilen von Codeblöcken und Textdateien. Textdateien starten ohne Zeilenumbruch, da umbrochene Zeilen nicht nummeriert werden können.",
        "settings.filePreview": "Vorschau für weitere Textdateien",
        "settings.filePreview.description": "Textdateien, die Discord nur zum Herunterladen zeigt (etwa .log, .cfg oder .ini), bekommen eine Vorschau-Schaltfläche.",
    },
    es: {
        "copy": "Copiar",
        "copied": "Copiado",
        "copiedPart": "Se copiaron los primeros {size}",
        "copyFailed": "No se pudo copiar",
        "download": "Descargar",
        "downloadFailed": "No se pudo guardar el archivo",
        "pretty": "Formatear",
        "original": "Mostrar como se envió",
        "preview.show": "Vista previa",
        "preview.hide": "Ocultar vista previa",
        "preview.loading": "Cargando…",
        "preview.error": "No se pudo cargar este archivo",
        "preview.partial": "Se muestran los primeros {size}",
        "settings.lineNumbers": "Números de línea",
        "settings.lineNumbers.description": "Números junto a las líneas de los bloques de código y archivos de texto. Los archivos de texto empiezan sin ajuste de línea, porque las líneas ajustadas no se pueden numerar.",
        "settings.filePreview": "Vista previa de otros archivos de texto",
        "settings.filePreview.description": "Los archivos de texto que Discord solo muestra para descargar (como .log, .cfg o .ini) tienen un botón de vista previa.",
    },
    fr: {
        "copy": "Copier",
        "copied": "Copié",
        "copiedPart": "Les premiers {size} ont été copiés",
        "copyFailed": "Impossible de copier",
        "download": "Télécharger",
        "downloadFailed": "Impossible d'enregistrer le fichier",
        "pretty": "Mettre en forme",
        "original": "Afficher tel qu'envoyé",
        "preview.show": "Aperçu",
        "preview.hide": "Masquer l'aperçu",
        "preview.loading": "Chargement…",
        "preview.error": "Impossible de charger ce fichier",
        "preview.partial": "Affichage des premiers {size}",
        "settings.lineNumbers": "Numéros de ligne",
        "settings.lineNumbers.description": "Des numéros à côté des lignes des blocs de code et des fichiers texte. Les fichiers texte s'ouvrent sans retour à la ligne, car les lignes renvoyées ne peuvent pas être numérotées.",
        "settings.filePreview": "Aperçu des autres fichiers texte",
        "settings.filePreview.description": "Les fichiers texte que Discord ne propose qu'au téléchargement (comme .log, .cfg ou .ini) ont un bouton Aperçu.",
    },
    ja: {
        "copy": "コピー",
        "copied": "コピーしました",
        "copiedPart": "先頭の{size}をコピーしました",
        "copyFailed": "コピーできませんでした",
        "download": "ダウンロード",
        "downloadFailed": "ファイルを保存できませんでした",
        "pretty": "整形して表示",
        "original": "送信時のまま表示",
        "preview.show": "プレビュー",
        "preview.hide": "プレビューを閉じる",
        "preview.loading": "読み込み中…",
        "preview.error": "このファイルを読み込めませんでした",
        "preview.partial": "先頭の{size}を表示しています",
        "settings.lineNumbers": "行番号",
        "settings.lineNumbers.description": "コードブロックとテキストファイルの各行の横に番号を表示します。折り返した行には番号を付けられないため、テキストファイルは折り返しなしで表示されます。",
        "settings.filePreview": "その他のテキストファイルをプレビュー",
        "settings.filePreview.description": "Discordがダウンロードとしてのみ表示するテキストファイル(.log、.cfg、.iniなど)にプレビューボタンを追加します。",
    },
    pl: {
        "copy": "Kopiuj",
        "copied": "Skopiowano",
        "copiedPart": "Skopiowano pierwsze {size}",
        "copyFailed": "Nie udało się skopiować",
        "download": "Pobierz",
        "downloadFailed": "Nie udało się zapisać pliku",
        "pretty": "Sformatuj",
        "original": "Pokaż tak, jak wysłano",
        "preview.show": "Podgląd",
        "preview.hide": "Ukryj podgląd",
        "preview.loading": "Wczytywanie…",
        "preview.error": "Nie udało się wczytać tego pliku",
        "preview.partial": "Pokazano pierwsze {size}",
        "settings.lineNumbers": "Numery wierszy",
        "settings.lineNumbers.description": "Numery obok wierszy bloków kodu i plików tekstowych. Pliki tekstowe otwierają się bez zawijania wierszy, bo zawiniętych wierszy nie da się ponumerować.",
        "settings.filePreview": "Podgląd innych plików tekstowych",
        "settings.filePreview.description": "Pliki tekstowe, które Discord pokazuje tylko do pobrania (np. .log, .cfg lub .ini), dostają przycisk podglądu.",
    },
    "pt-BR": {
        "copy": "Copiar",
        "copied": "Copiado",
        "copiedPart": "Os primeiros {size} foram copiados",
        "copyFailed": "Não foi possível copiar",
        "download": "Baixar",
        "downloadFailed": "Não foi possível salvar o arquivo",
        "pretty": "Formatar",
        "original": "Mostrar como foi enviado",
        "preview.show": "Pré-visualizar",
        "preview.hide": "Ocultar pré-visualização",
        "preview.loading": "Carregando…",
        "preview.error": "Não foi possível carregar este arquivo",
        "preview.partial": "Mostrando os primeiros {size}",
        "settings.lineNumbers": "Números de linha",
        "settings.lineNumbers.description": "Números ao lado das linhas de blocos de código e arquivos de texto. Arquivos de texto abrem sem quebra de linha, porque linhas quebradas não podem ser numeradas.",
        "settings.filePreview": "Pré-visualizar outros arquivos de texto",
        "settings.filePreview.description": "Arquivos de texto que o Discord só mostra para baixar (como .log, .cfg ou .ini) ganham um botão de pré-visualização.",
    },
    ru: {
        "copy": "Копировать",
        "copied": "Скопировано",
        "copiedPart": "Скопированы первые {size}",
        "copyFailed": "Не удалось скопировать",
        "download": "Скачать",
        "downloadFailed": "Не удалось сохранить файл",
        "pretty": "Форматировать",
        "original": "Показать как отправлено",
        "preview.show": "Просмотр",
        "preview.hide": "Скрыть просмотр",
        "preview.loading": "Загрузка…",
        "preview.error": "Не удалось загрузить этот файл",
        "preview.partial": "Показаны первые {size}",
        "settings.lineNumbers": "Номера строк",
        "settings.lineNumbers.description": "Номера рядом со строками блоков кода и текстовых файлов. Текстовые файлы открываются без переноса строк, потому что перенесённые строки нельзя пронумеровать.",
        "settings.filePreview": "Просмотр других текстовых файлов",
        "settings.filePreview.description": "Текстовые файлы, которые Discord показывает только для скачивания (например, .log, .cfg или .ini), получают кнопку просмотра.",
    },
    tr: {
        "copy": "Kopyala",
        "copied": "Kopyalandı",
        "copiedPart": "İlk {size} kopyalandı",
        "copyFailed": "Kopyalanamadı",
        "download": "İndir",
        "downloadFailed": "Dosya kaydedilemedi",
        "pretty": "Biçimlendir",
        "original": "Gönderildiği gibi göster",
        "preview.show": "Önizle",
        "preview.hide": "Önizlemeyi gizle",
        "preview.loading": "Yükleniyor…",
        "preview.error": "Bu dosya yüklenemedi",
        "preview.partial": "İlk {size} gösteriliyor",
        "settings.lineNumbers": "Satır numaraları",
        "settings.lineNumbers.description": "Kod bloklarının ve metin dosyalarının satırlarının yanında numaralar. Kaydırılan satırlar numaralandırılamadığı için metin dosyaları satır kaydırma olmadan açılır.",
        "settings.filePreview": "Diğer metin dosyalarını önizle",
        "settings.filePreview.description": "Discord'un yalnızca indirme olarak gösterdiği metin dosyaları (.log, .cfg veya .ini gibi) bir Önizle düğmesi alır.",
    },
});
