import { defineStrings } from "@evi/api";

/**
 * Each entry reads "<who> <action> <target>": actions are verb phrases the target follows, and a
 * create/update/delete is "op.*" with the kind of thing in it (its article inside, where the
 * language needs one).
 */
export const t = defineStrings({
    en: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Audit log",
        "dialog.close": "Close",
        "filter.search": "Search names, actions, reasons and changes",
        "filter.actor": "Done by",
        "filter.anyone": "Anyone",
        "filter.from": "From",
        "filter.to": "To",
        "filter.groups": "Kinds of action",
        "filter.clear": "Clear filters",
        "group.server": "Server",
        "group.channels": "Channels",
        "group.members": "Members",
        "group.roles": "Roles",
        "group.messages": "Messages",
        "group.invites": "Invites",
        "group.apps": "Apps & webhooks",
        "group.expressions": "Emoji, stickers & sounds",
        "group.events": "Events & stages",
        "group.threads": "Threads",
        "group.automod": "AutoMod",
        "group.onboarding": "Onboarding",
        "group.other": "Other",
        "op.create": "created the {kind}",
        "op.update": "updated the {kind}",
        "op.delete": "deleted the {kind}",
        "kind.channel": "channel",
        "kind.overwrite": "channel permissions",
        "kind.role": "role",
        "kind.invite": "invite",
        "kind.webhook": "webhook",
        "kind.emoji": "emoji",
        "kind.integration": "integration",
        "kind.stage": "stage",
        "kind.sticker": "sticker",
        "kind.event": "event",
        "kind.thread": "thread",
        "kind.sound": "sound",
        "kind.automodRule": "AutoMod rule",
        "kind.prompt": "onboarding question",
        "kind.onboarding": "onboarding",
        "kind.homeSettings": "home settings",
        "kind.eventException": "event exception",
        "kind.voiceStatus": "voice channel status",
        "action.guildUpdate": "updated the server",
        "action.channelPositions": "reordered channels",
        "action.kick": "kicked",
        "action.prune": "pruned inactive members",
        "action.ban": "banned",
        "action.unban": "unbanned",
        "action.memberUpdate": "updated the member",
        "action.memberRoles": "changed the roles of",
        "action.move": "moved members in voice",
        "action.disconnect": "disconnected members from voice",
        "action.botAdd": "added the app",
        "action.rolePositions": "reordered roles",
        "action.messageDelete": "deleted a message by",
        "action.bulkDelete": "bulk deleted messages in",
        "action.pin": "pinned a message by",
        "action.unpin": "unpinned a message by",
        "action.commandPermissions": "changed command permissions for",
        "action.automodBlock": "had a message blocked by AutoMod:",
        "action.automodFlag": "had a message flagged by AutoMod:",
        "action.automodTimeout": "was timed out by AutoMod:",
        "action.automodQuarantine": "was quarantined by AutoMod:",
        "action.monetizationRequest": "requested server monetization",
        "action.monetizationTerms": "accepted the monetization terms",
        "action.homeFeature": "featured an item in the Server Guide",
        "action.homeRemove": "removed an item from the Server Guide",
        "action.harmfulLink": "had a harmful link blocked:",
        "action.voiceStatusSet": "set the voice status of",
        "action.voiceStatusClear": "cleared the voice status of",
        "action.verificationUpdate": "changed member verification",
        "action.profileUpdate": "updated the server profile",
        "action.migratePins": "moved pinning to the Pin Messages permission",
        "action.migrateSlowmode": "moved slowmode bypass to its own permission",
        "action.unknown": "did action #{type}",
        "key.name": "Name",
        "key.topic": "Topic",
        "key.nsfw": "Age-restricted",
        "key.rate_limit_per_user": "Slowmode",
        "key.permissions": "Permissions",
        "key.allow": "Allowed",
        "key.deny": "Denied",
        "key.color": "Colour",
        "key.colors": "Colours",
        "key.hoist": "Shown separately",
        "key.mentionable": "Mentionable",
        "key.nick": "Nickname",
        "key.deaf": "Server deafened",
        "key.mute": "Server muted",
        "key.communication_disabled_until": "Timed out until",
        "key.max_uses": "Max uses",
        "key.max_age": "Expires after",
        "key.temporary": "Temporary membership",
        "key.code": "Code",
        "key.bitrate": "Bitrate",
        "key.user_limit": "User limit",
        "key.position": "Position",
        "key.type": "Type",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Icon",
        "key.description": "Description",
        "key.add": "Roles given",
        "key.remove": "Roles taken",
        "key.archived": "Archived",
        "key.locked": "Locked",
        "key.auto_archive_duration": "Hide after inactivity",
        "key.status": "Status",
        "key.channel_id": "Channel",
        "key.reason": "Reason",
        "value.none": "none",
        "value.yes": "Yes",
        "value.no": "No",
        "value.never": "Never",
        "value.off": "Off",
        "change.to": "changed to",
        "change.rolesAdded": "Roles given",
        "change.rolesRemoved": "Roles taken",
        "detail.prune": "{count} removed, inactive for {days} days",
        "detail.messages": { one: "{count} message", other: "{count} messages" },
        "detail.members": { one: "{count} member", other: "{count} members" },
        "detail.channel": "in {channel}",
        "detail.overwrite": "for {name}",
        "detail.rule": "Rule: {rule}",
        "detail.status": "Status: {status}",
        "actor.system": "Discord",
        "tag.app": "App",
        "tag.webhook": "Webhook",
        "target.copyId": "Copy ID",
        "target.openChannel": "Go to channel",
        "target.openProfile": "Open profile",
        "row.times": "×{count}",
        "row.reason": "Reason:",
        "row.noChanges": "No details",
        "row.show": "Show changes",
        "row.hide": "Hide changes",
        "row.changes": { one: "{count} change", other: "{count} changes" },
        "state.error": "Couldn't load the audit log: {error}",
        "state.retry": "Try again",
        "state.waiting": "Discord asked to slow down. Continuing in {seconds} s…",
        "state.loading": "Loading…",
        "state.stalled": "Nothing older matches yet.",
        "state.more": "Keep looking",
        "state.noMatch": "Nothing matches these filters.",
        "state.empty": "This server's audit log is empty.",
        "state.end": "That's the whole audit log.",
        "foot.shown": "{shown} shown of {loaded} loaded",
        "foot.group": "Group repeats",
        "toast.copied": "Copied",
        "toast.exported": { one: "Saved {count} entry", other: "Saved {count} entries" },
        "error.client": "Discord's request client wasn't found",
    },
    de: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Audit-Log",
        "dialog.close": "Schließen",
        "filter.search": "Namen, Aktionen, Gründe und Änderungen durchsuchen",
        "filter.actor": "Ausgeführt von",
        "filter.anyone": "Alle",
        "filter.from": "Von",
        "filter.to": "Bis",
        "filter.groups": "Arten von Aktionen",
        "filter.clear": "Filter zurücksetzen",
        "group.server": "Server",
        "group.channels": "Kanäle",
        "group.members": "Mitglieder",
        "group.roles": "Rollen",
        "group.messages": "Nachrichten",
        "group.invites": "Einladungen",
        "group.apps": "Apps & Webhooks",
        "group.expressions": "Emojis, Sticker & Sounds",
        "group.events": "Events & Stages",
        "group.threads": "Threads",
        "group.automod": "AutoMod",
        "group.onboarding": "Onboarding",
        "group.other": "Sonstiges",
        "op.create": "erstellte {kind}",
        "op.update": "änderte {kind}",
        "op.delete": "löschte {kind}",
        "kind.channel": "den Kanal",
        "kind.overwrite": "die Kanalberechtigungen",
        "kind.role": "die Rolle",
        "kind.invite": "die Einladung",
        "kind.webhook": "den Webhook",
        "kind.emoji": "das Emoji",
        "kind.integration": "die Integration",
        "kind.stage": "die Stage",
        "kind.sticker": "den Sticker",
        "kind.event": "das Event",
        "kind.thread": "den Thread",
        "kind.sound": "den Sound",
        "kind.automodRule": "die AutoMod-Regel",
        "kind.prompt": "die Onboarding-Frage",
        "kind.onboarding": "das Onboarding",
        "kind.homeSettings": "die Startseiten-Einstellungen",
        "kind.eventException": "die Event-Ausnahme",
        "kind.voiceStatus": "den Sprachkanal-Status",
        "action.guildUpdate": "änderte den Server",
        "action.channelPositions": "ordnete Kanäle neu",
        "action.kick": "kickte",
        "action.prune": "entfernte inaktive Mitglieder",
        "action.ban": "bannte",
        "action.unban": "entbannte",
        "action.memberUpdate": "änderte das Mitglied",
        "action.memberRoles": "änderte die Rollen von",
        "action.move": "verschob Mitglieder im Sprachkanal",
        "action.disconnect": "trennte Mitglieder vom Sprachkanal",
        "action.botAdd": "fügte die App hinzu",
        "action.rolePositions": "ordnete Rollen neu",
        "action.messageDelete": "löschte eine Nachricht von",
        "action.bulkDelete": "löschte mehrere Nachrichten in",
        "action.pin": "pinnte eine Nachricht von",
        "action.unpin": "entfernte eine angepinnte Nachricht von",
        "action.commandPermissions": "änderte Befehlsberechtigungen für",
        "action.automodBlock": "– Nachricht von AutoMod blockiert:",
        "action.automodFlag": "– Nachricht von AutoMod markiert:",
        "action.automodTimeout": "– von AutoMod getimeoutet:",
        "action.automodQuarantine": "– von AutoMod unter Quarantäne gestellt:",
        "action.monetizationRequest": "beantragte die Server-Monetarisierung",
        "action.monetizationTerms": "akzeptierte die Monetarisierungsbedingungen",
        "action.homeFeature": "hob einen Eintrag im Server-Guide hervor",
        "action.homeRemove": "entfernte einen Eintrag aus dem Server-Guide",
        "action.harmfulLink": "– schädlicher Link blockiert:",
        "action.voiceStatusSet": "setzte den Sprachstatus von",
        "action.voiceStatusClear": "entfernte den Sprachstatus von",
        "action.verificationUpdate": "änderte die Mitgliederverifizierung",
        "action.profileUpdate": "änderte das Serverprofil",
        "action.migratePins": "verschob das Anpinnen in die Berechtigung „Nachrichten anpinnen“",
        "action.migrateSlowmode": "verschob das Umgehen des Slowmodes in eine eigene Berechtigung",
        "action.unknown": "führte Aktion #{type} aus",
        "key.name": "Name",
        "key.topic": "Thema",
        "key.nsfw": "Altersbeschränkt",
        "key.rate_limit_per_user": "Slowmode",
        "key.permissions": "Berechtigungen",
        "key.allow": "Erlaubt",
        "key.deny": "Verweigert",
        "key.color": "Farbe",
        "key.colors": "Farben",
        "key.hoist": "Getrennt angezeigt",
        "key.mentionable": "Erwähnbar",
        "key.nick": "Spitzname",
        "key.deaf": "Server-taub",
        "key.mute": "Server-stumm",
        "key.communication_disabled_until": "Timeout bis",
        "key.max_uses": "Max. Nutzungen",
        "key.max_age": "Läuft ab nach",
        "key.temporary": "Temporäre Mitgliedschaft",
        "key.code": "Code",
        "key.bitrate": "Bitrate",
        "key.user_limit": "Nutzerlimit",
        "key.position": "Position",
        "key.type": "Typ",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Symbol",
        "key.description": "Beschreibung",
        "key.add": "Rollen vergeben",
        "key.remove": "Rollen entzogen",
        "key.archived": "Archiviert",
        "key.locked": "Gesperrt",
        "key.auto_archive_duration": "Nach Inaktivität ausblenden",
        "key.status": "Status",
        "key.channel_id": "Kanal",
        "key.reason": "Grund",
        "value.none": "keine",
        "value.yes": "Ja",
        "value.no": "Nein",
        "value.never": "Nie",
        "value.off": "Aus",
        "change.to": "geändert zu",
        "change.rolesAdded": "Rollen vergeben",
        "change.rolesRemoved": "Rollen entzogen",
        "detail.prune": "{count} entfernt, {days} Tage inaktiv",
        "detail.messages": { one: "{count} Nachricht", other: "{count} Nachrichten" },
        "detail.members": { one: "{count} Mitglied", other: "{count} Mitglieder" },
        "detail.channel": "in {channel}",
        "detail.overwrite": "für {name}",
        "detail.rule": "Regel: {rule}",
        "detail.status": "Status: {status}",
        "actor.system": "Discord",
        "tag.app": "App",
        "tag.webhook": "Webhook",
        "target.copyId": "ID kopieren",
        "target.openChannel": "Zum Kanal",
        "target.openProfile": "Profil öffnen",
        "row.times": "×{count}",
        "row.reason": "Grund:",
        "row.noChanges": "Keine Details",
        "row.show": "Änderungen anzeigen",
        "row.hide": "Änderungen ausblenden",
        "row.changes": { one: "{count} Änderung", other: "{count} Änderungen" },
        "state.error": "Das Audit-Log konnte nicht geladen werden: {error}",
        "state.retry": "Erneut versuchen",
        "state.waiting": "Discord bittet um eine Pause. Weiter in {seconds} s …",
        "state.loading": "Wird geladen …",
        "state.stalled": "Noch nichts Älteres passt.",
        "state.more": "Weitersuchen",
        "state.noMatch": "Nichts passt zu diesen Filtern.",
        "state.empty": "Das Audit-Log dieses Servers ist leer.",
        "state.end": "Das ist das ganze Audit-Log.",
        "foot.shown": "{shown} von {loaded} geladenen angezeigt",
        "foot.group": "Wiederholungen bündeln",
        "toast.copied": "Kopiert",
        "toast.exported": { one: "{count} Eintrag gespeichert", other: "{count} Einträge gespeichert" },
        "error.client": "Discords Anfrage-Client wurde nicht gefunden",
    },
    es: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Registro de auditoría",
        "dialog.close": "Cerrar",
        "filter.search": "Buscar nombres, acciones, motivos y cambios",
        "filter.actor": "Hecho por",
        "filter.anyone": "Cualquiera",
        "filter.from": "Desde",
        "filter.to": "Hasta",
        "filter.groups": "Tipos de acción",
        "filter.clear": "Quitar filtros",
        "group.server": "Servidor",
        "group.channels": "Canales",
        "group.members": "Miembros",
        "group.roles": "Roles",
        "group.messages": "Mensajes",
        "group.invites": "Invitaciones",
        "group.apps": "Apps y webhooks",
        "group.expressions": "Emojis, stickers y sonidos",
        "group.events": "Eventos y escenarios",
        "group.threads": "Hilos",
        "group.automod": "AutoMod",
        "group.onboarding": "Incorporación",
        "group.other": "Otros",
        "op.create": "creó {kind}",
        "op.update": "cambió {kind}",
        "op.delete": "eliminó {kind}",
        "kind.channel": "el canal",
        "kind.overwrite": "los permisos del canal",
        "kind.role": "el rol",
        "kind.invite": "la invitación",
        "kind.webhook": "el webhook",
        "kind.emoji": "el emoji",
        "kind.integration": "la integración",
        "kind.stage": "el escenario",
        "kind.sticker": "el sticker",
        "kind.event": "el evento",
        "kind.thread": "el hilo",
        "kind.sound": "el sonido",
        "kind.automodRule": "la regla de AutoMod",
        "kind.prompt": "la pregunta de incorporación",
        "kind.onboarding": "la incorporación",
        "kind.homeSettings": "los ajustes de inicio",
        "kind.eventException": "la excepción del evento",
        "kind.voiceStatus": "el estado del canal de voz",
        "action.guildUpdate": "cambió el servidor",
        "action.channelPositions": "reordenó los canales",
        "action.kick": "expulsó a",
        "action.prune": "eliminó a los miembros inactivos",
        "action.ban": "baneó a",
        "action.unban": "desbaneó a",
        "action.memberUpdate": "cambió al miembro",
        "action.memberRoles": "cambió los roles de",
        "action.move": "movió miembros en voz",
        "action.disconnect": "desconectó miembros de voz",
        "action.botAdd": "añadió la app",
        "action.rolePositions": "reordenó los roles",
        "action.messageDelete": "eliminó un mensaje de",
        "action.bulkDelete": "eliminó varios mensajes en",
        "action.pin": "fijó un mensaje de",
        "action.unpin": "desfijó un mensaje de",
        "action.commandPermissions": "cambió los permisos de comandos de",
        "action.automodBlock": "— AutoMod bloqueó un mensaje:",
        "action.automodFlag": "— AutoMod marcó un mensaje:",
        "action.automodTimeout": "— AutoMod aplicó un aislamiento:",
        "action.automodQuarantine": "— AutoMod puso en cuarentena:",
        "action.monetizationRequest": "solicitó la monetización del servidor",
        "action.monetizationTerms": "aceptó los términos de monetización",
        "action.homeFeature": "destacó un elemento en la Guía del servidor",
        "action.homeRemove": "quitó un elemento de la Guía del servidor",
        "action.harmfulLink": "— se bloqueó un enlace peligroso:",
        "action.voiceStatusSet": "puso el estado de voz de",
        "action.voiceStatusClear": "quitó el estado de voz de",
        "action.verificationUpdate": "cambió la verificación de miembros",
        "action.profileUpdate": "cambió el perfil del servidor",
        "action.migratePins": "pasó fijar mensajes al permiso Fijar mensajes",
        "action.migrateSlowmode": "pasó saltarse el modo lento a su propio permiso",
        "action.unknown": "hizo la acción #{type}",
        "key.name": "Nombre",
        "key.topic": "Tema",
        "key.nsfw": "Con restricción de edad",
        "key.rate_limit_per_user": "Modo lento",
        "key.permissions": "Permisos",
        "key.allow": "Permitido",
        "key.deny": "Denegado",
        "key.color": "Color",
        "key.colors": "Colores",
        "key.hoist": "Se muestra por separado",
        "key.mentionable": "Mencionable",
        "key.nick": "Apodo",
        "key.deaf": "Ensordecido en el servidor",
        "key.mute": "Silenciado en el servidor",
        "key.communication_disabled_until": "Aislado hasta",
        "key.max_uses": "Usos máximos",
        "key.max_age": "Caduca tras",
        "key.temporary": "Membresía temporal",
        "key.code": "Código",
        "key.bitrate": "Tasa de bits",
        "key.user_limit": "Límite de usuarios",
        "key.position": "Posición",
        "key.type": "Tipo",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Icono",
        "key.description": "Descripción",
        "key.add": "Roles dados",
        "key.remove": "Roles quitados",
        "key.archived": "Archivado",
        "key.locked": "Bloqueado",
        "key.auto_archive_duration": "Ocultar tras inactividad",
        "key.status": "Estado",
        "key.channel_id": "Canal",
        "key.reason": "Motivo",
        "value.none": "nada",
        "value.yes": "Sí",
        "value.no": "No",
        "value.never": "Nunca",
        "value.off": "Desactivado",
        "change.to": "cambiado a",
        "change.rolesAdded": "Roles dados",
        "change.rolesRemoved": "Roles quitados",
        "detail.prune": "{count} eliminados, inactivos durante {days} días",
        "detail.messages": { one: "{count} mensaje", other: "{count} mensajes" },
        "detail.members": { one: "{count} miembro", other: "{count} miembros" },
        "detail.channel": "en {channel}",
        "detail.overwrite": "para {name}",
        "detail.rule": "Regla: {rule}",
        "detail.status": "Estado: {status}",
        "actor.system": "Discord",
        "tag.app": "App",
        "tag.webhook": "Webhook",
        "target.copyId": "Copiar ID",
        "target.openChannel": "Ir al canal",
        "target.openProfile": "Abrir perfil",
        "row.times": "×{count}",
        "row.reason": "Motivo:",
        "row.noChanges": "Sin detalles",
        "row.show": "Mostrar cambios",
        "row.hide": "Ocultar cambios",
        "row.changes": { one: "{count} cambio", other: "{count} cambios" },
        "state.error": "No se pudo cargar el registro de auditoría: {error}",
        "state.retry": "Reintentar",
        "state.waiting": "Discord pidió ir más despacio. Seguimos en {seconds} s…",
        "state.loading": "Cargando…",
        "state.stalled": "Aún no coincide nada más antiguo.",
        "state.more": "Seguir buscando",
        "state.noMatch": "Nada coincide con estos filtros.",
        "state.empty": "El registro de auditoría de este servidor está vacío.",
        "state.end": "Ese es todo el registro de auditoría.",
        "foot.shown": "{shown} mostradas de {loaded} cargadas",
        "foot.group": "Agrupar repeticiones",
        "toast.copied": "Copiado",
        "toast.exported": { one: "Se guardó {count} entrada", other: "Se guardaron {count} entradas" },
        "error.client": "No se encontró el cliente de peticiones de Discord",
    },
    fr: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Logs du serveur",
        "dialog.close": "Fermer",
        "filter.search": "Rechercher des noms, actions, raisons et modifications",
        "filter.actor": "Fait par",
        "filter.anyone": "Tout le monde",
        "filter.from": "Du",
        "filter.to": "Au",
        "filter.groups": "Types d'action",
        "filter.clear": "Effacer les filtres",
        "group.server": "Serveur",
        "group.channels": "Salons",
        "group.members": "Membres",
        "group.roles": "Rôles",
        "group.messages": "Messages",
        "group.invites": "Invitations",
        "group.apps": "Applis et webhooks",
        "group.expressions": "Émojis, autocollants et sons",
        "group.events": "Événements et conférences",
        "group.threads": "Fils",
        "group.automod": "AutoMod",
        "group.onboarding": "Accueil",
        "group.other": "Autre",
        "op.create": "a créé {kind}",
        "op.update": "a modifié {kind}",
        "op.delete": "a supprimé {kind}",
        "kind.channel": "le salon",
        "kind.overwrite": "les permissions du salon",
        "kind.role": "le rôle",
        "kind.invite": "l'invitation",
        "kind.webhook": "le webhook",
        "kind.emoji": "l'émoji",
        "kind.integration": "l'intégration",
        "kind.stage": "la conférence",
        "kind.sticker": "l'autocollant",
        "kind.event": "l'événement",
        "kind.thread": "le fil",
        "kind.sound": "le son",
        "kind.automodRule": "la règle AutoMod",
        "kind.prompt": "la question d'accueil",
        "kind.onboarding": "l'accueil",
        "kind.homeSettings": "les paramètres d'accueil",
        "kind.eventException": "l'exception d'événement",
        "kind.voiceStatus": "le statut du salon vocal",
        "action.guildUpdate": "a modifié le serveur",
        "action.channelPositions": "a réorganisé les salons",
        "action.kick": "a expulsé",
        "action.prune": "a retiré les membres inactifs",
        "action.ban": "a banni",
        "action.unban": "a débanni",
        "action.memberUpdate": "a modifié le membre",
        "action.memberRoles": "a changé les rôles de",
        "action.move": "a déplacé des membres en vocal",
        "action.disconnect": "a déconnecté des membres du vocal",
        "action.botAdd": "a ajouté l'appli",
        "action.rolePositions": "a réorganisé les rôles",
        "action.messageDelete": "a supprimé un message de",
        "action.bulkDelete": "a supprimé des messages en masse dans",
        "action.pin": "a épinglé un message de",
        "action.unpin": "a désépinglé un message de",
        "action.commandPermissions": "a changé les permissions des commandes de",
        "action.automodBlock": "— message bloqué par AutoMod :",
        "action.automodFlag": "— message signalé par AutoMod :",
        "action.automodTimeout": "— exclu temporairement par AutoMod :",
        "action.automodQuarantine": "— mis en quarantaine par AutoMod :",
        "action.monetizationRequest": "a demandé la monétisation du serveur",
        "action.monetizationTerms": "a accepté les conditions de monétisation",
        "action.homeFeature": "a mis en avant un élément du Guide du serveur",
        "action.homeRemove": "a retiré un élément du Guide du serveur",
        "action.harmfulLink": "— lien dangereux bloqué :",
        "action.voiceStatusSet": "a défini le statut vocal de",
        "action.voiceStatusClear": "a effacé le statut vocal de",
        "action.verificationUpdate": "a modifié la vérification des membres",
        "action.profileUpdate": "a modifié le profil du serveur",
        "action.migratePins": "a déplacé l'épinglage vers la permission Épingler des messages",
        "action.migrateSlowmode": "a donné sa propre permission au contournement du mode lent",
        "action.unknown": "a fait l'action n° {type}",
        "key.name": "Nom",
        "key.topic": "Sujet",
        "key.nsfw": "Soumis à une limite d'âge",
        "key.rate_limit_per_user": "Mode lent",
        "key.permissions": "Permissions",
        "key.allow": "Autorisé",
        "key.deny": "Refusé",
        "key.color": "Couleur",
        "key.colors": "Couleurs",
        "key.hoist": "Affiché séparément",
        "key.mentionable": "Mentionnable",
        "key.nick": "Pseudo",
        "key.deaf": "Mis en sourdine par le serveur",
        "key.mute": "Rendu muet par le serveur",
        "key.communication_disabled_until": "Exclu jusqu'au",
        "key.max_uses": "Utilisations max.",
        "key.max_age": "Expire après",
        "key.temporary": "Adhésion temporaire",
        "key.code": "Code",
        "key.bitrate": "Débit",
        "key.user_limit": "Limite d'utilisateurs",
        "key.position": "Position",
        "key.type": "Type",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Icône",
        "key.description": "Description",
        "key.add": "Rôles donnés",
        "key.remove": "Rôles retirés",
        "key.archived": "Archivé",
        "key.locked": "Verrouillé",
        "key.auto_archive_duration": "Masquer après inactivité",
        "key.status": "Statut",
        "key.channel_id": "Salon",
        "key.reason": "Raison",
        "value.none": "aucun",
        "value.yes": "Oui",
        "value.no": "Non",
        "value.never": "Jamais",
        "value.off": "Désactivé",
        "change.to": "changé en",
        "change.rolesAdded": "Rôles donnés",
        "change.rolesRemoved": "Rôles retirés",
        "detail.prune": "{count} retirés, inactifs depuis {days} jours",
        "detail.messages": { one: "{count} message", other: "{count} messages" },
        "detail.members": { one: "{count} membre", other: "{count} membres" },
        "detail.channel": "dans {channel}",
        "detail.overwrite": "pour {name}",
        "detail.rule": "Règle : {rule}",
        "detail.status": "Statut : {status}",
        "actor.system": "Discord",
        "tag.app": "Appli",
        "tag.webhook": "Webhook",
        "target.copyId": "Copier l'identifiant",
        "target.openChannel": "Aller au salon",
        "target.openProfile": "Ouvrir le profil",
        "row.times": "×{count}",
        "row.reason": "Raison :",
        "row.noChanges": "Aucun détail",
        "row.show": "Afficher les modifications",
        "row.hide": "Masquer les modifications",
        "row.changes": { one: "{count} modification", other: "{count} modifications" },
        "state.error": "Impossible de charger les logs : {error}",
        "state.retry": "Réessayer",
        "state.waiting": "Discord demande de ralentir. Reprise dans {seconds} s…",
        "state.loading": "Chargement…",
        "state.stalled": "Rien de plus ancien ne correspond pour l'instant.",
        "state.more": "Continuer à chercher",
        "state.noMatch": "Rien ne correspond à ces filtres.",
        "state.empty": "Les logs de ce serveur sont vides.",
        "state.end": "Ce sont tous les logs.",
        "foot.shown": "{shown} affichées sur {loaded} chargées",
        "foot.group": "Regrouper les répétitions",
        "toast.copied": "Copié",
        "toast.exported": { one: "{count} entrée enregistrée", other: "{count} entrées enregistrées" },
        "error.client": "Le client de requêtes de Discord est introuvable",
    },
    ja: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "監査ログ",
        "dialog.close": "閉じる",
        "filter.search": "名前・操作・理由・変更内容を検索",
        "filter.actor": "実行者",
        "filter.anyone": "全員",
        "filter.from": "開始",
        "filter.to": "終了",
        "filter.groups": "操作の種類",
        "filter.clear": "フィルターをクリア",
        "group.server": "サーバー",
        "group.channels": "チャンネル",
        "group.members": "メンバー",
        "group.roles": "ロール",
        "group.messages": "メッセージ",
        "group.invites": "招待",
        "group.apps": "アプリとウェブフック",
        "group.expressions": "絵文字・スタンプ・サウンド",
        "group.events": "イベントとステージ",
        "group.threads": "スレッド",
        "group.automod": "AutoMod",
        "group.onboarding": "オンボーディング",
        "group.other": "その他",
        "op.create": "が{kind}を作成:",
        "op.update": "が{kind}を更新:",
        "op.delete": "が{kind}を削除:",
        "kind.channel": "チャンネル",
        "kind.overwrite": "チャンネル権限",
        "kind.role": "ロール",
        "kind.invite": "招待",
        "kind.webhook": "ウェブフック",
        "kind.emoji": "絵文字",
        "kind.integration": "連携サービス",
        "kind.stage": "ステージ",
        "kind.sticker": "スタンプ",
        "kind.event": "イベント",
        "kind.thread": "スレッド",
        "kind.sound": "サウンド",
        "kind.automodRule": "AutoModルール",
        "kind.prompt": "オンボーディングの質問",
        "kind.onboarding": "オンボーディング",
        "kind.homeSettings": "ホーム設定",
        "kind.eventException": "イベントの例外",
        "kind.voiceStatus": "ボイスチャンネルのステータス",
        "action.guildUpdate": "がサーバーを更新",
        "action.channelPositions": "がチャンネルを並べ替え",
        "action.kick": "がキック:",
        "action.prune": "が非アクティブなメンバーを削除",
        "action.ban": "がBAN:",
        "action.unban": "がBANを解除:",
        "action.memberUpdate": "がメンバーを更新:",
        "action.memberRoles": "がロールを変更:",
        "action.move": "がボイスのメンバーを移動",
        "action.disconnect": "がボイスからメンバーを切断",
        "action.botAdd": "がアプリを追加:",
        "action.rolePositions": "がロールを並べ替え",
        "action.messageDelete": "がメッセージを削除。送信者:",
        "action.bulkDelete": "がメッセージを一括削除:",
        "action.pin": "がメッセージをピン留め。送信者:",
        "action.unpin": "がピン留めを解除。送信者:",
        "action.commandPermissions": "がコマンド権限を変更:",
        "action.automodBlock": "のメッセージをAutoModがブロック:",
        "action.automodFlag": "のメッセージをAutoModが報告:",
        "action.automodTimeout": "— AutoModがタイムアウト:",
        "action.automodQuarantine": "— AutoModが隔離:",
        "action.monetizationRequest": "がサーバーの収益化を申請",
        "action.monetizationTerms": "が収益化の規約に同意",
        "action.homeFeature": "がサーバーガイドに項目を掲載",
        "action.homeRemove": "がサーバーガイドから項目を削除",
        "action.harmfulLink": "— 危険なリンクをブロック:",
        "action.voiceStatusSet": "がボイスステータスを設定:",
        "action.voiceStatusClear": "がボイスステータスを解除:",
        "action.verificationUpdate": "がメンバー認証を変更",
        "action.profileUpdate": "がサーバープロフィールを更新",
        "action.migratePins": "がピン留めを「メッセージをピン留め」権限に移行",
        "action.migrateSlowmode": "が低速モードの回避を専用の権限に移行",
        "action.unknown": "が操作 #{type} を実行",
        "key.name": "名前",
        "key.topic": "トピック",
        "key.nsfw": "年齢制限",
        "key.rate_limit_per_user": "低速モード",
        "key.permissions": "権限",
        "key.allow": "許可",
        "key.deny": "拒否",
        "key.color": "色",
        "key.colors": "色",
        "key.hoist": "別に表示",
        "key.mentionable": "メンション可能",
        "key.nick": "ニックネーム",
        "key.deaf": "サーバースピーカーミュート",
        "key.mute": "サーバーミュート",
        "key.communication_disabled_until": "タイムアウト期限",
        "key.max_uses": "最大使用回数",
        "key.max_age": "有効期限",
        "key.temporary": "一時的なメンバー",
        "key.code": "コード",
        "key.bitrate": "ビットレート",
        "key.user_limit": "ユーザー数制限",
        "key.position": "位置",
        "key.type": "種類",
        "key.avatar_hash": "アバター",
        "key.icon_hash": "アイコン",
        "key.description": "説明",
        "key.add": "付与したロール",
        "key.remove": "外したロール",
        "key.archived": "アーカイブ済み",
        "key.locked": "ロック",
        "key.auto_archive_duration": "非アクティブ後に非表示",
        "key.status": "ステータス",
        "key.channel_id": "チャンネル",
        "key.reason": "理由",
        "value.none": "なし",
        "value.yes": "はい",
        "value.no": "いいえ",
        "value.never": "無期限",
        "value.off": "オフ",
        "change.to": "変更後",
        "change.rolesAdded": "付与したロール",
        "change.rolesRemoved": "外したロール",
        "detail.prune": "{count}人を削除（{days}日間非アクティブ）",
        "detail.messages": { other: "{count}件のメッセージ" },
        "detail.members": { other: "{count}人のメンバー" },
        "detail.channel": "{channel}で",
        "detail.overwrite": "{name}に対して",
        "detail.rule": "ルール: {rule}",
        "detail.status": "ステータス: {status}",
        "actor.system": "Discord",
        "tag.app": "アプリ",
        "tag.webhook": "ウェブフック",
        "target.copyId": "IDをコピー",
        "target.openChannel": "チャンネルへ移動",
        "target.openProfile": "プロフィールを開く",
        "row.times": "×{count}",
        "row.reason": "理由:",
        "row.noChanges": "詳細なし",
        "row.show": "変更内容を表示",
        "row.hide": "変更内容を隠す",
        "row.changes": { other: "{count}件の変更" },
        "state.error": "監査ログを読み込めませんでした: {error}",
        "state.retry": "再試行",
        "state.waiting": "Discordから速度を落とすよう求められました。{seconds}秒後に再開します…",
        "state.loading": "読み込み中…",
        "state.stalled": "これより古い一致はまだありません。",
        "state.more": "さらに探す",
        "state.noMatch": "このフィルターに一致するものはありません。",
        "state.empty": "このサーバーの監査ログは空です。",
        "state.end": "監査ログはこれで全部です。",
        "foot.shown": "読み込み済み{loaded}件中{shown}件を表示",
        "foot.group": "繰り返しをまとめる",
        "toast.copied": "コピーしました",
        "toast.exported": { other: "{count}件を保存しました" },
        "error.client": "Discordのリクエストクライアントが見つかりません",
    },
    pl: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Dziennik zdarzeń",
        "dialog.close": "Zamknij",
        "filter.search": "Szukaj nazw, działań, powodów i zmian",
        "filter.actor": "Wykonane przez",
        "filter.anyone": "Każdy",
        "filter.from": "Od",
        "filter.to": "Do",
        "filter.groups": "Rodzaje działań",
        "filter.clear": "Wyczyść filtry",
        "group.server": "Serwer",
        "group.channels": "Kanały",
        "group.members": "Członkowie",
        "group.roles": "Role",
        "group.messages": "Wiadomości",
        "group.invites": "Zaproszenia",
        "group.apps": "Aplikacje i webhooki",
        "group.expressions": "Emoji, naklejki i dźwięki",
        "group.events": "Wydarzenia i sceny",
        "group.threads": "Wątki",
        "group.automod": "AutoMod",
        "group.onboarding": "Wprowadzenie",
        "group.other": "Inne",
        "op.create": "utworzył(a) {kind}",
        "op.update": "zmienił(a) {kind}",
        "op.delete": "usunął(-ęła) {kind}",
        "kind.channel": "kanał",
        "kind.overwrite": "uprawnienia kanału",
        "kind.role": "rolę",
        "kind.invite": "zaproszenie",
        "kind.webhook": "webhook",
        "kind.emoji": "emoji",
        "kind.integration": "integrację",
        "kind.stage": "scenę",
        "kind.sticker": "naklejkę",
        "kind.event": "wydarzenie",
        "kind.thread": "wątek",
        "kind.sound": "dźwięk",
        "kind.automodRule": "regułę AutoMod",
        "kind.prompt": "pytanie wprowadzające",
        "kind.onboarding": "wprowadzenie",
        "kind.homeSettings": "ustawienia strony głównej",
        "kind.eventException": "wyjątek wydarzenia",
        "kind.voiceStatus": "status kanału głosowego",
        "action.guildUpdate": "zmienił(a) serwer",
        "action.channelPositions": "zmienił(a) kolejność kanałów",
        "action.kick": "wyrzucił(a)",
        "action.prune": "usunął(-ęła) nieaktywnych członków",
        "action.ban": "zbanował(a)",
        "action.unban": "odbanował(a)",
        "action.memberUpdate": "zmienił(a) członka",
        "action.memberRoles": "zmienił(a) role użytkownika",
        "action.move": "przeniósł(-osła) członków na kanale głosowym",
        "action.disconnect": "rozłączył(a) członków z kanału głosowego",
        "action.botAdd": "dodał(a) aplikację",
        "action.rolePositions": "zmienił(a) kolejność ról",
        "action.messageDelete": "usunął(-ęła) wiadomość od",
        "action.bulkDelete": "masowo usunął(-ęła) wiadomości w",
        "action.pin": "przypiął(-ęła) wiadomość od",
        "action.unpin": "odpiął(-ęła) wiadomość od",
        "action.commandPermissions": "zmienił(a) uprawnienia poleceń dla",
        "action.automodBlock": "— AutoMod zablokował wiadomość:",
        "action.automodFlag": "— AutoMod oflagował wiadomość:",
        "action.automodTimeout": "— AutoMod nałożył przerwę:",
        "action.automodQuarantine": "— AutoMod objął kwarantanną:",
        "action.monetizationRequest": "złożył(a) wniosek o monetyzację serwera",
        "action.monetizationTerms": "zaakceptował(a) warunki monetyzacji",
        "action.homeFeature": "wyróżnił(a) element w Przewodniku serwera",
        "action.homeRemove": "usunął(-ęła) element z Przewodnika serwera",
        "action.harmfulLink": "— zablokowano szkodliwy link:",
        "action.voiceStatusSet": "ustawił(a) status głosowy kanału",
        "action.voiceStatusClear": "usunął(-ęła) status głosowy kanału",
        "action.verificationUpdate": "zmienił(a) weryfikację członków",
        "action.profileUpdate": "zmienił(a) profil serwera",
        "action.migratePins": "przeniósł(-osła) przypinanie do uprawnienia Przypinanie wiadomości",
        "action.migrateSlowmode": "przeniósł(-osła) omijanie trybu powolnego do osobnego uprawnienia",
        "action.unknown": "wykonał(a) działanie nr {type}",
        "key.name": "Nazwa",
        "key.topic": "Temat",
        "key.nsfw": "Z ograniczeniem wiekowym",
        "key.rate_limit_per_user": "Tryb powolny",
        "key.permissions": "Uprawnienia",
        "key.allow": "Dozwolone",
        "key.deny": "Zabronione",
        "key.color": "Kolor",
        "key.colors": "Kolory",
        "key.hoist": "Wyświetlana osobno",
        "key.mentionable": "Można wspomnieć",
        "key.nick": "Pseudonim",
        "key.deaf": "Wyciszony dźwięk na serwerze",
        "key.mute": "Wyciszony na serwerze",
        "key.communication_disabled_until": "Przerwa do",
        "key.max_uses": "Maks. użyć",
        "key.max_age": "Wygasa po",
        "key.temporary": "Członkostwo tymczasowe",
        "key.code": "Kod",
        "key.bitrate": "Przepływność",
        "key.user_limit": "Limit użytkowników",
        "key.position": "Pozycja",
        "key.type": "Typ",
        "key.avatar_hash": "Awatar",
        "key.icon_hash": "Ikona",
        "key.description": "Opis",
        "key.add": "Nadane role",
        "key.remove": "Odebrane role",
        "key.archived": "Zarchiwizowany",
        "key.locked": "Zablokowany",
        "key.auto_archive_duration": "Ukryj po bezczynności",
        "key.status": "Status",
        "key.channel_id": "Kanał",
        "key.reason": "Powód",
        "value.none": "brak",
        "value.yes": "Tak",
        "value.no": "Nie",
        "value.never": "Nigdy",
        "value.off": "Wyłączone",
        "change.to": "zmieniono na",
        "change.rolesAdded": "Nadane role",
        "change.rolesRemoved": "Odebrane role",
        "detail.prune": "usunięto {count}, nieaktywni przez {days} dni",
        "detail.messages": { one: "{count} wiadomość", few: "{count} wiadomości", many: "{count} wiadomości", other: "{count} wiadomości" },
        "detail.members": { one: "{count} członek", few: "{count} członków", many: "{count} członków", other: "{count} członków" },
        "detail.channel": "na {channel}",
        "detail.overwrite": "dla {name}",
        "detail.rule": "Reguła: {rule}",
        "detail.status": "Status: {status}",
        "actor.system": "Discord",
        "tag.app": "Aplikacja",
        "tag.webhook": "Webhook",
        "target.copyId": "Kopiuj ID",
        "target.openChannel": "Przejdź do kanału",
        "target.openProfile": "Otwórz profil",
        "row.times": "×{count}",
        "row.reason": "Powód:",
        "row.noChanges": "Brak szczegółów",
        "row.show": "Pokaż zmiany",
        "row.hide": "Ukryj zmiany",
        "row.changes": { one: "{count} zmiana", few: "{count} zmiany", many: "{count} zmian", other: "{count} zmiany" },
        "state.error": "Nie udało się wczytać dziennika zdarzeń: {error}",
        "state.retry": "Spróbuj ponownie",
        "state.waiting": "Discord prosi o zwolnienie. Kontynuacja za {seconds} s…",
        "state.loading": "Wczytywanie…",
        "state.stalled": "Na razie nic starszego nie pasuje.",
        "state.more": "Szukaj dalej",
        "state.noMatch": "Nic nie pasuje do tych filtrów.",
        "state.empty": "Dziennik zdarzeń tego serwera jest pusty.",
        "state.end": "To cały dziennik zdarzeń.",
        "foot.shown": "Pokazano {shown} z {loaded} wczytanych",
        "foot.group": "Grupuj powtórzenia",
        "toast.copied": "Skopiowano",
        "toast.exported": { one: "Zapisano {count} wpis", few: "Zapisano {count} wpisy", many: "Zapisano {count} wpisów", other: "Zapisano {count} wpisu" },
        "error.client": "Nie znaleziono klienta zapytań Discorda",
    },
    "pt-BR": {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Registro de auditoria",
        "dialog.close": "Fechar",
        "filter.search": "Pesquisar nomes, ações, motivos e alterações",
        "filter.actor": "Feito por",
        "filter.anyone": "Qualquer pessoa",
        "filter.from": "De",
        "filter.to": "Até",
        "filter.groups": "Tipos de ação",
        "filter.clear": "Limpar filtros",
        "group.server": "Servidor",
        "group.channels": "Canais",
        "group.members": "Membros",
        "group.roles": "Cargos",
        "group.messages": "Mensagens",
        "group.invites": "Convites",
        "group.apps": "Apps e webhooks",
        "group.expressions": "Emojis, figurinhas e sons",
        "group.events": "Eventos e palcos",
        "group.threads": "Tópicos",
        "group.automod": "AutoMod",
        "group.onboarding": "Integração",
        "group.other": "Outros",
        "op.create": "criou {kind}",
        "op.update": "alterou {kind}",
        "op.delete": "excluiu {kind}",
        "kind.channel": "o canal",
        "kind.overwrite": "as permissões do canal",
        "kind.role": "o cargo",
        "kind.invite": "o convite",
        "kind.webhook": "o webhook",
        "kind.emoji": "o emoji",
        "kind.integration": "a integração",
        "kind.stage": "o palco",
        "kind.sticker": "a figurinha",
        "kind.event": "o evento",
        "kind.thread": "o tópico",
        "kind.sound": "o som",
        "kind.automodRule": "a regra do AutoMod",
        "kind.prompt": "a pergunta de integração",
        "kind.onboarding": "a integração de membros",
        "kind.homeSettings": "as configurações da página inicial",
        "kind.eventException": "a exceção do evento",
        "kind.voiceStatus": "o status do canal de voz",
        "action.guildUpdate": "alterou o servidor",
        "action.channelPositions": "reordenou os canais",
        "action.kick": "expulsou",
        "action.prune": "removeu membros inativos",
        "action.ban": "baniu",
        "action.unban": "desbaniu",
        "action.memberUpdate": "alterou o membro",
        "action.memberRoles": "alterou os cargos de",
        "action.move": "moveu membros na voz",
        "action.disconnect": "desconectou membros da voz",
        "action.botAdd": "adicionou o app",
        "action.rolePositions": "reordenou os cargos",
        "action.messageDelete": "excluiu uma mensagem de",
        "action.bulkDelete": "excluiu mensagens em massa em",
        "action.pin": "fixou uma mensagem de",
        "action.unpin": "desafixou uma mensagem de",
        "action.commandPermissions": "alterou as permissões de comandos de",
        "action.automodBlock": "— o AutoMod bloqueou uma mensagem:",
        "action.automodFlag": "— o AutoMod sinalizou uma mensagem:",
        "action.automodTimeout": "— o AutoMod aplicou castigo:",
        "action.automodQuarantine": "— o AutoMod colocou em quarentena:",
        "action.monetizationRequest": "pediu a monetização do servidor",
        "action.monetizationTerms": "aceitou os termos de monetização",
        "action.homeFeature": "destacou um item no Guia do servidor",
        "action.homeRemove": "removeu um item do Guia do servidor",
        "action.harmfulLink": "— link perigoso bloqueado:",
        "action.voiceStatusSet": "definiu o status de voz de",
        "action.voiceStatusClear": "limpou o status de voz de",
        "action.verificationUpdate": "alterou a verificação de membros",
        "action.profileUpdate": "alterou o perfil do servidor",
        "action.migratePins": "passou fixar mensagens para a permissão Fixar mensagens",
        "action.migrateSlowmode": "passou ignorar o modo lento para uma permissão própria",
        "action.unknown": "fez a ação nº {type}",
        "key.name": "Nome",
        "key.topic": "Tópico",
        "key.nsfw": "Restrição de idade",
        "key.rate_limit_per_user": "Modo lento",
        "key.permissions": "Permissões",
        "key.allow": "Permitido",
        "key.deny": "Negado",
        "key.color": "Cor",
        "key.colors": "Cores",
        "key.hoist": "Exibido separadamente",
        "key.mentionable": "Mencionável",
        "key.nick": "Apelido",
        "key.deaf": "Ensurdecido no servidor",
        "key.mute": "Silenciado no servidor",
        "key.communication_disabled_until": "De castigo até",
        "key.max_uses": "Usos máximos",
        "key.max_age": "Expira após",
        "key.temporary": "Associação temporária",
        "key.code": "Código",
        "key.bitrate": "Taxa de bits",
        "key.user_limit": "Limite de usuários",
        "key.position": "Posição",
        "key.type": "Tipo",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Ícone",
        "key.description": "Descrição",
        "key.add": "Cargos dados",
        "key.remove": "Cargos removidos",
        "key.archived": "Arquivado",
        "key.locked": "Trancado",
        "key.auto_archive_duration": "Ocultar após inatividade",
        "key.status": "Status",
        "key.channel_id": "Canal",
        "key.reason": "Motivo",
        "value.none": "nenhum",
        "value.yes": "Sim",
        "value.no": "Não",
        "value.never": "Nunca",
        "value.off": "Desativado",
        "change.to": "alterado para",
        "change.rolesAdded": "Cargos dados",
        "change.rolesRemoved": "Cargos removidos",
        "detail.prune": "{count} removidos, inativos há {days} dias",
        "detail.messages": { one: "{count} mensagem", other: "{count} mensagens" },
        "detail.members": { one: "{count} membro", other: "{count} membros" },
        "detail.channel": "em {channel}",
        "detail.overwrite": "para {name}",
        "detail.rule": "Regra: {rule}",
        "detail.status": "Status: {status}",
        "actor.system": "Discord",
        "tag.app": "App",
        "tag.webhook": "Webhook",
        "target.copyId": "Copiar ID",
        "target.openChannel": "Ir para o canal",
        "target.openProfile": "Abrir perfil",
        "row.times": "×{count}",
        "row.reason": "Motivo:",
        "row.noChanges": "Sem detalhes",
        "row.show": "Mostrar alterações",
        "row.hide": "Ocultar alterações",
        "row.changes": { one: "{count} alteração", other: "{count} alterações" },
        "state.error": "Não foi possível carregar o registro de auditoria: {error}",
        "state.retry": "Tentar novamente",
        "state.waiting": "O Discord pediu para ir mais devagar. Continuando em {seconds} s…",
        "state.loading": "Carregando…",
        "state.stalled": "Nada mais antigo corresponde por enquanto.",
        "state.more": "Continuar procurando",
        "state.noMatch": "Nada corresponde a estes filtros.",
        "state.empty": "O registro de auditoria deste servidor está vazio.",
        "state.end": "Esse é o registro de auditoria inteiro.",
        "foot.shown": "{shown} exibidas de {loaded} carregadas",
        "foot.group": "Agrupar repetições",
        "toast.copied": "Copiado",
        "toast.exported": { one: "{count} entrada salva", other: "{count} entradas salvas" },
        "error.client": "O cliente de requisições do Discord não foi encontrado",
    },
    ru: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Журнал аудита",
        "dialog.close": "Закрыть",
        "filter.search": "Искать имена, действия, причины и изменения",
        "filter.actor": "Кто сделал",
        "filter.anyone": "Все",
        "filter.from": "С",
        "filter.to": "По",
        "filter.groups": "Типы действий",
        "filter.clear": "Сбросить фильтры",
        "group.server": "Сервер",
        "group.channels": "Каналы",
        "group.members": "Участники",
        "group.roles": "Роли",
        "group.messages": "Сообщения",
        "group.invites": "Приглашения",
        "group.apps": "Приложения и вебхуки",
        "group.expressions": "Эмодзи, стикеры и звуки",
        "group.events": "События и трибуны",
        "group.threads": "Ветки",
        "group.automod": "AutoMod",
        "group.onboarding": "Приветствие",
        "group.other": "Другое",
        "op.create": "создал(а) {kind}",
        "op.update": "изменил(а) {kind}",
        "op.delete": "удалил(а) {kind}",
        "kind.channel": "канал",
        "kind.overwrite": "права канала",
        "kind.role": "роль",
        "kind.invite": "приглашение",
        "kind.webhook": "вебхук",
        "kind.emoji": "эмодзи",
        "kind.integration": "интеграцию",
        "kind.stage": "трибуну",
        "kind.sticker": "стикер",
        "kind.event": "событие",
        "kind.thread": "ветку",
        "kind.sound": "звук",
        "kind.automodRule": "правило AutoMod",
        "kind.prompt": "вопрос приветствия",
        "kind.onboarding": "приветствие",
        "kind.homeSettings": "настройки главной",
        "kind.eventException": "исключение события",
        "kind.voiceStatus": "статус голосового канала",
        "action.guildUpdate": "изменил(а) сервер",
        "action.channelPositions": "изменил(а) порядок каналов",
        "action.kick": "выгнал(а)",
        "action.prune": "удалил(а) неактивных участников",
        "action.ban": "забанил(а)",
        "action.unban": "разбанил(а)",
        "action.memberUpdate": "изменил(а) участника",
        "action.memberRoles": "изменил(а) роли участника",
        "action.move": "переместил(а) участников в голосовом",
        "action.disconnect": "отключил(а) участников от голосового",
        "action.botAdd": "добавил(а) приложение",
        "action.rolePositions": "изменил(а) порядок ролей",
        "action.messageDelete": "удалил(а) сообщение от",
        "action.bulkDelete": "массово удалил(а) сообщения в",
        "action.pin": "закрепил(а) сообщение от",
        "action.unpin": "открепил(а) сообщение от",
        "action.commandPermissions": "изменил(а) права команд для",
        "action.automodBlock": "— AutoMod заблокировал сообщение:",
        "action.automodFlag": "— AutoMod пометил сообщение:",
        "action.automodTimeout": "— AutoMod выдал тайм-аут:",
        "action.automodQuarantine": "— AutoMod отправил в карантин:",
        "action.monetizationRequest": "подал(а) заявку на монетизацию сервера",
        "action.monetizationTerms": "принял(а) условия монетизации",
        "action.homeFeature": "выделил(а) элемент в Путеводителе по серверу",
        "action.homeRemove": "убрал(а) элемент из Путеводителя по серверу",
        "action.harmfulLink": "— заблокирована опасная ссылка:",
        "action.voiceStatusSet": "задал(а) голосовой статус для",
        "action.voiceStatusClear": "убрал(а) голосовой статус у",
        "action.verificationUpdate": "изменил(а) проверку участников",
        "action.profileUpdate": "изменил(а) профиль сервера",
        "action.migratePins": "перенёс(ла) закрепление в право «Закреплять сообщения»",
        "action.migrateSlowmode": "вынес(ла) обход медленного режима в отдельное право",
        "action.unknown": "выполнил(а) действие №{type}",
        "key.name": "Название",
        "key.topic": "Тема",
        "key.nsfw": "С возрастным ограничением",
        "key.rate_limit_per_user": "Медленный режим",
        "key.permissions": "Права",
        "key.allow": "Разрешено",
        "key.deny": "Запрещено",
        "key.color": "Цвет",
        "key.colors": "Цвета",
        "key.hoist": "Показывать отдельно",
        "key.mentionable": "Можно упоминать",
        "key.nick": "Ник",
        "key.deaf": "Звук отключён на сервере",
        "key.mute": "Микрофон отключён на сервере",
        "key.communication_disabled_until": "Тайм-аут до",
        "key.max_uses": "Макс. использований",
        "key.max_age": "Истекает через",
        "key.temporary": "Временное участие",
        "key.code": "Код",
        "key.bitrate": "Битрейт",
        "key.user_limit": "Лимит пользователей",
        "key.position": "Позиция",
        "key.type": "Тип",
        "key.avatar_hash": "Аватар",
        "key.icon_hash": "Значок",
        "key.description": "Описание",
        "key.add": "Выданы роли",
        "key.remove": "Сняты роли",
        "key.archived": "В архиве",
        "key.locked": "Закрыта",
        "key.auto_archive_duration": "Скрывать после неактивности",
        "key.status": "Статус",
        "key.channel_id": "Канал",
        "key.reason": "Причина",
        "value.none": "нет",
        "value.yes": "Да",
        "value.no": "Нет",
        "value.never": "Никогда",
        "value.off": "Выкл.",
        "change.to": "изменено на",
        "change.rolesAdded": "Выданы роли",
        "change.rolesRemoved": "Сняты роли",
        "detail.prune": "удалено {count}, неактивны {days} дн.",
        "detail.messages": { one: "{count} сообщение", few: "{count} сообщения", many: "{count} сообщений", other: "{count} сообщения" },
        "detail.members": { one: "{count} участник", few: "{count} участника", many: "{count} участников", other: "{count} участника" },
        "detail.channel": "в {channel}",
        "detail.overwrite": "для {name}",
        "detail.rule": "Правило: {rule}",
        "detail.status": "Статус: {status}",
        "actor.system": "Discord",
        "tag.app": "Приложение",
        "tag.webhook": "Вебхук",
        "target.copyId": "Копировать ID",
        "target.openChannel": "Перейти в канал",
        "target.openProfile": "Открыть профиль",
        "row.times": "×{count}",
        "row.reason": "Причина:",
        "row.noChanges": "Нет подробностей",
        "row.show": "Показать изменения",
        "row.hide": "Скрыть изменения",
        "row.changes": { one: "{count} изменение", few: "{count} изменения", many: "{count} изменений", other: "{count} изменения" },
        "state.error": "Не удалось загрузить журнал аудита: {error}",
        "state.retry": "Повторить",
        "state.waiting": "Discord просит притормозить. Продолжим через {seconds} с…",
        "state.loading": "Загрузка…",
        "state.stalled": "Более старых совпадений пока нет.",
        "state.more": "Искать дальше",
        "state.noMatch": "Ничего не подходит под эти фильтры.",
        "state.empty": "Журнал аудита этого сервера пуст.",
        "state.end": "Это весь журнал аудита.",
        "foot.shown": "Показано {shown} из {loaded} загруженных",
        "foot.group": "Объединять повторы",
        "toast.copied": "Скопировано",
        "toast.exported": { one: "Сохранена {count} запись", few: "Сохранено {count} записи", many: "Сохранено {count} записей", other: "Сохранено {count} записи" },
        "error.client": "Клиент запросов Discord не найден",
    },
    tr: {
        "menu.open": "Audit Log Plus",
        "dialog.title": "Denetim kaydı",
        "dialog.close": "Kapat",
        "filter.search": "İsim, eylem, sebep ve değişiklik ara",
        "filter.actor": "Yapan",
        "filter.anyone": "Herkes",
        "filter.from": "Başlangıç",
        "filter.to": "Bitiş",
        "filter.groups": "Eylem türleri",
        "filter.clear": "Filtreleri temizle",
        "group.server": "Sunucu",
        "group.channels": "Kanallar",
        "group.members": "Üyeler",
        "group.roles": "Roller",
        "group.messages": "Mesajlar",
        "group.invites": "Davetler",
        "group.apps": "Uygulamalar ve webhook'lar",
        "group.expressions": "Emojiler, çıkartmalar ve sesler",
        "group.events": "Etkinlikler ve sahneler",
        "group.threads": "Alt başlıklar",
        "group.automod": "AutoMod",
        "group.onboarding": "Karşılama",
        "group.other": "Diğer",
        "op.create": "{kind} oluşturdu:",
        "op.update": "{kind} güncelledi:",
        "op.delete": "{kind} sildi:",
        "kind.channel": "kanal",
        "kind.overwrite": "kanal izinlerini",
        "kind.role": "rol",
        "kind.invite": "davet",
        "kind.webhook": "webhook",
        "kind.emoji": "emoji",
        "kind.integration": "entegrasyon",
        "kind.stage": "sahne",
        "kind.sticker": "çıkartma",
        "kind.event": "etkinlik",
        "kind.thread": "alt başlık",
        "kind.sound": "ses",
        "kind.automodRule": "AutoMod kuralı",
        "kind.prompt": "karşılama sorusu",
        "kind.onboarding": "karşılama",
        "kind.homeSettings": "ana sayfa ayarlarını",
        "kind.eventException": "etkinlik istisnası",
        "kind.voiceStatus": "ses kanalı durumunu",
        "action.guildUpdate": "sunucuyu güncelledi",
        "action.channelPositions": "kanalları yeniden sıraladı",
        "action.kick": "sunucudan attı:",
        "action.prune": "etkin olmayan üyeleri temizledi",
        "action.ban": "yasakladı:",
        "action.unban": "yasağı kaldırdı:",
        "action.memberUpdate": "üyeyi güncelledi:",
        "action.memberRoles": "rollerini değiştirdi:",
        "action.move": "sesteki üyeleri taşıdı",
        "action.disconnect": "üyelerin ses bağlantısını kesti",
        "action.botAdd": "uygulamayı ekledi:",
        "action.rolePositions": "rolleri yeniden sıraladı",
        "action.messageDelete": "bir mesajı sildi, gönderen:",
        "action.bulkDelete": "toplu mesaj sildi:",
        "action.pin": "bir mesajı sabitledi, gönderen:",
        "action.unpin": "bir mesajın sabitlemesini kaldırdı, gönderen:",
        "action.commandPermissions": "komut izinlerini değiştirdi:",
        "action.automodBlock": "— AutoMod bir mesajı engelledi:",
        "action.automodFlag": "— AutoMod bir mesajı işaretledi:",
        "action.automodTimeout": "— AutoMod zaman aşımı verdi:",
        "action.automodQuarantine": "— AutoMod karantinaya aldı:",
        "action.monetizationRequest": "sunucu para kazanma başvurusu yaptı",
        "action.monetizationTerms": "para kazanma şartlarını kabul etti",
        "action.homeFeature": "Sunucu Rehberi'nde bir öğeyi öne çıkardı",
        "action.homeRemove": "Sunucu Rehberi'nden bir öğeyi kaldırdı",
        "action.harmfulLink": "— zararlı bağlantı engellendi:",
        "action.voiceStatusSet": "ses durumunu ayarladı:",
        "action.voiceStatusClear": "ses durumunu temizledi:",
        "action.verificationUpdate": "üye doğrulamasını değiştirdi",
        "action.profileUpdate": "sunucu profilini güncelledi",
        "action.migratePins": "sabitlemeyi Mesajları Sabitle iznine taşıdı",
        "action.migrateSlowmode": "yavaş modu atlamayı ayrı bir izne taşıdı",
        "action.unknown": "#{type} eylemini yaptı",
        "key.name": "İsim",
        "key.topic": "Konu",
        "key.nsfw": "Yaş sınırlı",
        "key.rate_limit_per_user": "Yavaş mod",
        "key.permissions": "İzinler",
        "key.allow": "İzin verildi",
        "key.deny": "Reddedildi",
        "key.color": "Renk",
        "key.colors": "Renkler",
        "key.hoist": "Ayrı gösterilir",
        "key.mentionable": "Bahsedilebilir",
        "key.nick": "Takma ad",
        "key.deaf": "Sunucuda sağırlaştırıldı",
        "key.mute": "Sunucuda susturuldu",
        "key.communication_disabled_until": "Zaman aşımı bitişi",
        "key.max_uses": "En fazla kullanım",
        "key.max_age": "Süresi dolar",
        "key.temporary": "Geçici üyelik",
        "key.code": "Kod",
        "key.bitrate": "Bit hızı",
        "key.user_limit": "Kullanıcı sınırı",
        "key.position": "Sıra",
        "key.type": "Tür",
        "key.avatar_hash": "Avatar",
        "key.icon_hash": "Simge",
        "key.description": "Açıklama",
        "key.add": "Verilen roller",
        "key.remove": "Alınan roller",
        "key.archived": "Arşivlendi",
        "key.locked": "Kilitli",
        "key.auto_archive_duration": "Hareketsizlikten sonra gizle",
        "key.status": "Durum",
        "key.channel_id": "Kanal",
        "key.reason": "Sebep",
        "value.none": "yok",
        "value.yes": "Evet",
        "value.no": "Hayır",
        "value.never": "Asla",
        "value.off": "Kapalı",
        "change.to": "şuna değişti",
        "change.rolesAdded": "Verilen roller",
        "change.rolesRemoved": "Alınan roller",
        "detail.prune": "{count} kişi çıkarıldı, {days} gündür etkin değillerdi",
        "detail.messages": { other: "{count} mesaj" },
        "detail.members": { other: "{count} üye" },
        "detail.channel": "{channel} kanalında",
        "detail.overwrite": "{name} için",
        "detail.rule": "Kural: {rule}",
        "detail.status": "Durum: {status}",
        "actor.system": "Discord",
        "tag.app": "Uygulama",
        "tag.webhook": "Webhook",
        "target.copyId": "ID'yi kopyala",
        "target.openChannel": "Kanala git",
        "target.openProfile": "Profili aç",
        "row.times": "×{count}",
        "row.reason": "Sebep:",
        "row.noChanges": "Ayrıntı yok",
        "row.show": "Değişiklikleri göster",
        "row.hide": "Değişiklikleri gizle",
        "row.changes": { other: "{count} değişiklik" },
        "state.error": "Denetim kaydı yüklenemedi: {error}",
        "state.retry": "Tekrar dene",
        "state.waiting": "Discord yavaşlamamızı istedi. {seconds} sn içinde devam ediliyor…",
        "state.loading": "Yükleniyor…",
        "state.stalled": "Şimdilik daha eski bir eşleşme yok.",
        "state.more": "Aramaya devam et",
        "state.noMatch": "Bu filtrelere uyan bir şey yok.",
        "state.empty": "Bu sunucunun denetim kaydı boş.",
        "state.end": "Denetim kaydının tamamı bu.",
        "foot.shown": "Yüklenen {loaded} kayıttan {shown} tanesi gösteriliyor",
        "foot.group": "Tekrarları grupla",
        "toast.copied": "Kopyalandı",
        "toast.exported": { other: "{count} kayıt kaydedildi" },
        "error.client": "Discord'un istek istemcisi bulunamadı",
    },
});
