import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "perm.CREATE_INSTANT_INVITE": "Create Invite",
        "perm.KICK_MEMBERS": "Kick Members",
        "perm.BAN_MEMBERS": "Ban Members",
        "perm.ADMINISTRATOR": "Administrator",
        "perm.MANAGE_CHANNELS": "Manage Channels",
        "perm.MANAGE_GUILD": "Manage Server",
        "perm.ADD_REACTIONS": "Add Reactions",
        "perm.VIEW_AUDIT_LOG": "View Audit Log",
        "perm.PRIORITY_SPEAKER": "Priority Speaker",
        "perm.STREAM": "Video",
        "perm.VIEW_CHANNEL": "View Channels",
        "perm.SEND_MESSAGES": "Send Messages",
        "perm.SEND_TTS_MESSAGES": "Send Text-to-Speech Messages",
        "perm.MANAGE_MESSAGES": "Manage Messages",
        "perm.EMBED_LINKS": "Embed Links",
        "perm.ATTACH_FILES": "Attach Files",
        "perm.READ_MESSAGE_HISTORY": "Read Message History",
        "perm.MENTION_EVERYONE": "Mention @everyone, @here and All Roles",
        "perm.USE_EXTERNAL_EMOJIS": "Use External Emoji",
        "perm.VIEW_GUILD_INSIGHTS": "View Server Insights",
        "perm.CONNECT": "Connect",
        "perm.SPEAK": "Speak",
        "perm.MUTE_MEMBERS": "Mute Members",
        "perm.DEAFEN_MEMBERS": "Deafen Members",
        "perm.MOVE_MEMBERS": "Move Members",
        "perm.USE_VAD": "Use Voice Activity",
        "perm.CHANGE_NICKNAME": "Change Nickname",
        "perm.MANAGE_NICKNAMES": "Manage Nicknames",
        "perm.MANAGE_ROLES": "Manage Roles",
        "perm.MANAGE_WEBHOOKS": "Manage Webhooks",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Manage Expressions",
        "perm.USE_APPLICATION_COMMANDS": "Use Application Commands",
        "perm.REQUEST_TO_SPEAK": "Request to Speak",
        "perm.MANAGE_EVENTS": "Manage Events",
        "perm.MANAGE_THREADS": "Manage Threads",
        "perm.CREATE_PUBLIC_THREADS": "Create Public Threads",
        "perm.CREATE_PRIVATE_THREADS": "Create Private Threads",
        "perm.USE_EXTERNAL_STICKERS": "Use External Stickers",
        "perm.SEND_MESSAGES_IN_THREADS": "Send Messages in Threads",
        "perm.USE_EMBEDDED_ACTIVITIES": "Use Activities",
        "perm.MODERATE_MEMBERS": "Timeout Members",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "View Server Subscription Insights",
        "perm.USE_SOUNDBOARD": "Use Soundboard",
        "perm.CREATE_GUILD_EXPRESSIONS": "Create Expressions",
        "perm.CREATE_EVENTS": "Create Events",
        "perm.USE_EXTERNAL_SOUNDS": "Use External Sounds",
        "perm.SEND_VOICE_MESSAGES": "Send Voice Messages",
        "perm.SEND_POLLS": "Create Polls",
        "perm.USE_EXTERNAL_APPS": "Use External Apps",
        "perm.PIN_MESSAGES": "Pin Messages",
        "perm.BYPASS_SLOWMODE": "Bypass Slowmode",
        "perm.unknown": "Unknown (bit {bit})",
        "category.General": "General",
        "category.Membership": "Membership",
        "category.Text": "Text",
        "category.Voice": "Voice",
        "category.Apps": "Apps",
        "category.Events": "Events",
        "category.Advanced": "Advanced",
        "category.Other": "Other",
        "ui.close": "Close",
        "ui.sections": "Sections",
        "ui.show": "Show",
        "ui.searchLabel": "Search permissions",
        "ui.search": "Search",
        "ui.showAll": "Show all permissions",
        "ui.nothing": "Nothing to show.",
        "filter.all": "All",
        "filter.granted": "Granted",
        "filter.notGranted": "Not granted",
        "filter.allowed": "Allowed",
        "filter.denied": "Denied",
        "empty.match.all": "No permissions match “{query}”.",
        "empty.match.granted": "No granted permissions match “{query}”.",
        "empty.match.notGranted": "No permissions that aren't granted match “{query}”.",
        "empty.match.allowed": "No allowed permissions match “{query}”.",
        "empty.match.denied": "No denied permissions match “{query}”.",
        "empty.none.granted": "No permissions are granted here.",
        "empty.none.notGranted": "Every permission is granted here.",
        "empty.none.allowed": "No permissions are allowed here.",
        "empty.none.denied": "No permissions are denied here.",
        "count.of": "{granted} of {total}",
        "count.granted": "{count} granted",
        "count.allowedDenied": "{allowed} allowed, {denied} denied",
        "chip.overwrite": "overwrite",
        "chip.owner": "Server owner",
        "chip.member": "Member",
        "chip.deletedRole": "Deleted role",
        "chip.admin": "Administrator through the {role} role",
        "chip.everyone": "Granted to @everyone",
        "chip.role": "Granted by the {role} role",
        "chip.everyone.allowed": "Allowed by this channel's @everyone overwrite",
        "chip.everyone.denied": "Denied by this channel's @everyone overwrite",
        "chip.roleOverwrite.allowed": "Allowed by this channel's {role} overwrite",
        "chip.roleOverwrite.denied": "Denied by this channel's {role} overwrite",
        "chip.memberOverwrite.allowed": "Allowed by an overwrite for this member",
        "chip.memberOverwrite.denied": "Denied by an overwrite for this member",
        "notice.owner": "Server owner: has every permission, and channel overwrites don't apply.",
        "notice.admin": "Administrator through the {role} role: has every permission, and channel overwrites don't apply.",
        "notice.adminDeleted": "Administrator through a deleted role: has every permission, and channel overwrites don't apply.",
        "notice.roleAdmin": "Administrator: this role has every permission and bypasses channel overwrites.",
        "notice.overwrite.member": "Member overwrite: anything not listed is inherited from the server.",
        "notice.overwrite.role": "Role overwrite: anything not listed is inherited from the server.",
        "empty.overwrite": "This overwrite doesn't allow or deny anything, so everything is inherited from the server.",
        "empty.noOverwrites": "This channel has no overwrites, so everyone gets their server role permissions here.",
        "section.inChannel": "In {channel}",
        "section.serverWide": "Server-wide",
        "section.you": "You",
        "section.overwrites": "Overwrites",
        "section.roles": "Roles",
        "this.channel": "this channel",
        "this.server": "this server",
        "subtitle.memberChannel": "Permissions in {channel} · {guild}",
        "subtitle.member": "Permissions in {guild}",
        "subtitle.role": "Role permissions · {guild}",
        "subtitle.channel": "Channel permissions · {overwrites} · {guild}",
        "subtitle.guild": "Server permissions · {roles}",
        "overwrites.count": { one: "{count} overwrite", other: "{count} overwrites" },
        "roles.count": { one: "{count} role", other: "{count} roles" },
        "menu.view": "View Permissions",
        "toast.fail": "Couldn't read the permissions",
    },
    de: {
        "perm.CREATE_INSTANT_INVITE": "Einladung erstellen",
        "perm.KICK_MEMBERS": "Mitglieder kicken",
        "perm.BAN_MEMBERS": "Mitglieder bannen",
        "perm.ADMINISTRATOR": "Administrator",
        "perm.MANAGE_CHANNELS": "Kanäle verwalten",
        "perm.MANAGE_GUILD": "Server verwalten",
        "perm.ADD_REACTIONS": "Reaktionen hinzufügen",
        "perm.VIEW_AUDIT_LOG": "Audit-Log anzeigen",
        "perm.PRIORITY_SPEAKER": "Vorrangiger Sprecher",
        "perm.STREAM": "Video",
        "perm.VIEW_CHANNEL": "Kanäle ansehen",
        "perm.SEND_MESSAGES": "Nachrichten senden",
        "perm.SEND_TTS_MESSAGES": "Text-zu-Sprache-Nachrichten senden",
        "perm.MANAGE_MESSAGES": "Nachrichten verwalten",
        "perm.EMBED_LINKS": "Links einbetten",
        "perm.ATTACH_FILES": "Dateien anhängen",
        "perm.READ_MESSAGE_HISTORY": "Nachrichtenverlauf anzeigen",
        "perm.MENTION_EVERYONE": "@everyone, @here und alle Rollen erwähnen",
        "perm.USE_EXTERNAL_EMOJIS": "Externe Emojis verwenden",
        "perm.VIEW_GUILD_INSIGHTS": "Server-Einblicke anzeigen",
        "perm.CONNECT": "Verbinden",
        "perm.SPEAK": "Sprechen",
        "perm.MUTE_MEMBERS": "Mitglieder stummschalten",
        "perm.DEAFEN_MEMBERS": "Mitgliedern den Ton nehmen",
        "perm.MOVE_MEMBERS": "Mitglieder verschieben",
        "perm.USE_VAD": "Sprachaktivierung verwenden",
        "perm.CHANGE_NICKNAME": "Nickname ändern",
        "perm.MANAGE_NICKNAMES": "Nicknames verwalten",
        "perm.MANAGE_ROLES": "Rollen verwalten",
        "perm.MANAGE_WEBHOOKS": "Webhooks verwalten",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Ausdrücke verwalten",
        "perm.USE_APPLICATION_COMMANDS": "Anwendungsbefehle verwenden",
        "perm.REQUEST_TO_SPEAK": "Sprechen anfragen",
        "perm.MANAGE_EVENTS": "Events verwalten",
        "perm.MANAGE_THREADS": "Threads verwalten",
        "perm.CREATE_PUBLIC_THREADS": "Öffentliche Threads erstellen",
        "perm.CREATE_PRIVATE_THREADS": "Private Threads erstellen",
        "perm.USE_EXTERNAL_STICKERS": "Externe Sticker verwenden",
        "perm.SEND_MESSAGES_IN_THREADS": "Nachrichten in Threads senden",
        "perm.USE_EMBEDDED_ACTIVITIES": "Aktivitäten verwenden",
        "perm.MODERATE_MEMBERS": "Mitglieder in Auszeit schicken",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Einblicke in Server-Abos anzeigen",
        "perm.USE_SOUNDBOARD": "Soundboard verwenden",
        "perm.CREATE_GUILD_EXPRESSIONS": "Ausdrücke erstellen",
        "perm.CREATE_EVENTS": "Events erstellen",
        "perm.USE_EXTERNAL_SOUNDS": "Externe Sounds verwenden",
        "perm.SEND_VOICE_MESSAGES": "Sprachnachrichten senden",
        "perm.SEND_POLLS": "Umfragen erstellen",
        "perm.USE_EXTERNAL_APPS": "Externe Apps verwenden",
        "perm.PIN_MESSAGES": "Nachrichten anheften",
        "perm.BYPASS_SLOWMODE": "Slowmode umgehen",
        "perm.unknown": "Unbekannt (Bit {bit})",
        "category.General": "Allgemein",
        "category.Membership": "Mitgliedschaft",
        "category.Text": "Text",
        "category.Voice": "Sprache",
        "category.Apps": "Apps",
        "category.Events": "Events",
        "category.Advanced": "Erweitert",
        "category.Other": "Sonstiges",
        "ui.close": "Schließen",
        "ui.sections": "Bereiche",
        "ui.show": "Anzeigen",
        "ui.searchLabel": "Berechtigungen durchsuchen",
        "ui.search": "Suchen",
        "ui.showAll": "Alle Berechtigungen anzeigen",
        "ui.nothing": "Nichts anzuzeigen.",
        "filter.all": "Alle",
        "filter.granted": "Erteilt",
        "filter.notGranted": "Nicht erteilt",
        "filter.allowed": "Erlaubt",
        "filter.denied": "Verweigert",
        "empty.match.all": "Keine Berechtigungen passen zu „{query}“.",
        "empty.match.granted": "Keine erteilten Berechtigungen passen zu „{query}“.",
        "empty.match.notGranted": "Keine nicht erteilten Berechtigungen passen zu „{query}“.",
        "empty.match.allowed": "Keine erlaubten Berechtigungen passen zu „{query}“.",
        "empty.match.denied": "Keine verweigerten Berechtigungen passen zu „{query}“.",
        "empty.none.granted": "Hier ist keine Berechtigung erteilt.",
        "empty.none.notGranted": "Hier sind alle Berechtigungen erteilt.",
        "empty.none.allowed": "Hier ist keine Berechtigung erlaubt.",
        "empty.none.denied": "Hier ist keine Berechtigung verweigert.",
        "count.of": "{granted} von {total}",
        "count.granted": "{count} erteilt",
        "count.allowedDenied": "{allowed} erlaubt, {denied} verweigert",
        "chip.overwrite": "Überschreibung",
        "chip.owner": "Servereigentümer",
        "chip.member": "Mitglied",
        "chip.deletedRole": "Gelöschte Rolle",
        "chip.admin": "Administrator durch die Rolle {role}",
        "chip.everyone": "An @everyone erteilt",
        "chip.role": "Von der Rolle {role} erteilt",
        "chip.everyone.allowed": "Durch die @everyone-Überschreibung dieses Kanals erlaubt",
        "chip.everyone.denied": "Durch die @everyone-Überschreibung dieses Kanals verweigert",
        "chip.roleOverwrite.allowed": "Durch die Überschreibung der Rolle {role} in diesem Kanal erlaubt",
        "chip.roleOverwrite.denied": "Durch die Überschreibung der Rolle {role} in diesem Kanal verweigert",
        "chip.memberOverwrite.allowed": "Durch eine Überschreibung für dieses Mitglied erlaubt",
        "chip.memberOverwrite.denied": "Durch eine Überschreibung für dieses Mitglied verweigert",
        "notice.owner": "Servereigentümer: hat alle Berechtigungen, Kanalüberschreibungen gelten nicht.",
        "notice.admin": "Administrator durch die Rolle {role}: hat alle Berechtigungen, Kanalüberschreibungen gelten nicht.",
        "notice.adminDeleted": "Administrator durch eine gelöschte Rolle: hat alle Berechtigungen, Kanalüberschreibungen gelten nicht.",
        "notice.roleAdmin": "Administrator: Diese Rolle hat alle Berechtigungen und ignoriert Kanalüberschreibungen.",
        "notice.overwrite.member": "Mitglieder-Überschreibung: Alles, was nicht aufgeführt ist, wird vom Server übernommen.",
        "notice.overwrite.role": "Rollen-Überschreibung: Alles, was nicht aufgeführt ist, wird vom Server übernommen.",
        "empty.overwrite": "Diese Überschreibung erlaubt oder verweigert nichts, daher wird alles vom Server übernommen.",
        "empty.noOverwrites": "Dieser Kanal hat keine Überschreibungen, daher gelten hier für alle die Berechtigungen ihrer Serverrollen.",
        "section.inChannel": "In {channel}",
        "section.serverWide": "Serverweit",
        "section.you": "Du",
        "section.overwrites": "Überschreibungen",
        "section.roles": "Rollen",
        "this.channel": "diesem Kanal",
        "this.server": "diesem Server",
        "subtitle.memberChannel": "Berechtigungen in {channel} · {guild}",
        "subtitle.member": "Berechtigungen auf {guild}",
        "subtitle.role": "Rollenberechtigungen · {guild}",
        "subtitle.channel": "Kanalberechtigungen · {overwrites} · {guild}",
        "subtitle.guild": "Serverberechtigungen · {roles}",
        "overwrites.count": { one: "{count} Überschreibung", other: "{count} Überschreibungen" },
        "roles.count": { one: "{count} Rolle", other: "{count} Rollen" },
        "menu.view": "Berechtigungen anzeigen",
        "toast.fail": "Berechtigungen konnten nicht gelesen werden",
    },
    es: {
        "perm.CREATE_INSTANT_INVITE": "Crear invitación",
        "perm.KICK_MEMBERS": "Expulsar miembros",
        "perm.BAN_MEMBERS": "Banear miembros",
        "perm.ADMINISTRATOR": "Administrador",
        "perm.MANAGE_CHANNELS": "Gestionar canales",
        "perm.MANAGE_GUILD": "Gestionar servidor",
        "perm.ADD_REACTIONS": "Añadir reacciones",
        "perm.VIEW_AUDIT_LOG": "Ver el registro de auditoría",
        "perm.PRIORITY_SPEAKER": "Prioridad de palabra",
        "perm.STREAM": "Vídeo",
        "perm.VIEW_CHANNEL": "Ver canales",
        "perm.SEND_MESSAGES": "Enviar mensajes",
        "perm.SEND_TTS_MESSAGES": "Enviar mensajes de texto a voz",
        "perm.MANAGE_MESSAGES": "Gestionar mensajes",
        "perm.EMBED_LINKS": "Insertar enlaces",
        "perm.ATTACH_FILES": "Adjuntar archivos",
        "perm.READ_MESSAGE_HISTORY": "Ver el historial de mensajes",
        "perm.MENTION_EVERYONE": "Mencionar a @everyone, @here y todos los roles",
        "perm.USE_EXTERNAL_EMOJIS": "Usar emojis externos",
        "perm.VIEW_GUILD_INSIGHTS": "Ver información del servidor",
        "perm.CONNECT": "Conectar",
        "perm.SPEAK": "Hablar",
        "perm.MUTE_MEMBERS": "Silenciar miembros",
        "perm.DEAFEN_MEMBERS": "Ensordecer miembros",
        "perm.MOVE_MEMBERS": "Mover miembros",
        "perm.USE_VAD": "Usar detección de voz",
        "perm.CHANGE_NICKNAME": "Cambiar apodo",
        "perm.MANAGE_NICKNAMES": "Gestionar apodos",
        "perm.MANAGE_ROLES": "Gestionar roles",
        "perm.MANAGE_WEBHOOKS": "Gestionar webhooks",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Gestionar expresiones",
        "perm.USE_APPLICATION_COMMANDS": "Usar comandos de aplicación",
        "perm.REQUEST_TO_SPEAK": "Solicitar hablar",
        "perm.MANAGE_EVENTS": "Gestionar eventos",
        "perm.MANAGE_THREADS": "Gestionar hilos",
        "perm.CREATE_PUBLIC_THREADS": "Crear hilos públicos",
        "perm.CREATE_PRIVATE_THREADS": "Crear hilos privados",
        "perm.USE_EXTERNAL_STICKERS": "Usar stickers externos",
        "perm.SEND_MESSAGES_IN_THREADS": "Enviar mensajes en hilos",
        "perm.USE_EMBEDDED_ACTIVITIES": "Usar actividades",
        "perm.MODERATE_MEMBERS": "Aislar temporalmente a miembros",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Ver información de suscripciones del servidor",
        "perm.USE_SOUNDBOARD": "Usar panel de sonidos",
        "perm.CREATE_GUILD_EXPRESSIONS": "Crear expresiones",
        "perm.CREATE_EVENTS": "Crear eventos",
        "perm.USE_EXTERNAL_SOUNDS": "Usar sonidos externos",
        "perm.SEND_VOICE_MESSAGES": "Enviar mensajes de voz",
        "perm.SEND_POLLS": "Crear encuestas",
        "perm.USE_EXTERNAL_APPS": "Usar aplicaciones externas",
        "perm.PIN_MESSAGES": "Fijar mensajes",
        "perm.BYPASS_SLOWMODE": "Saltarse el modo lento",
        "perm.unknown": "Desconocido (bit {bit})",
        "category.General": "General",
        "category.Membership": "Membresía",
        "category.Text": "Texto",
        "category.Voice": "Voz",
        "category.Apps": "Aplicaciones",
        "category.Events": "Eventos",
        "category.Advanced": "Avanzado",
        "category.Other": "Otros",
        "ui.close": "Cerrar",
        "ui.sections": "Secciones",
        "ui.show": "Mostrar",
        "ui.searchLabel": "Buscar permisos",
        "ui.search": "Buscar",
        "ui.showAll": "Mostrar todos los permisos",
        "ui.nothing": "No hay nada que mostrar.",
        "filter.all": "Todos",
        "filter.granted": "Concedidos",
        "filter.notGranted": "No concedidos",
        "filter.allowed": "Permitidos",
        "filter.denied": "Denegados",
        "empty.match.all": "Ningún permiso coincide con «{query}».",
        "empty.match.granted": "Ningún permiso concedido coincide con «{query}».",
        "empty.match.notGranted": "Ningún permiso no concedido coincide con «{query}».",
        "empty.match.allowed": "Ningún permiso permitido coincide con «{query}».",
        "empty.match.denied": "Ningún permiso denegado coincide con «{query}».",
        "empty.none.granted": "Aquí no hay ningún permiso concedido.",
        "empty.none.notGranted": "Aquí están concedidos todos los permisos.",
        "empty.none.allowed": "Aquí no hay ningún permiso permitido.",
        "empty.none.denied": "Aquí no hay ningún permiso denegado.",
        "count.of": "{granted} de {total}",
        "count.granted": "{count} concedidos",
        "count.allowedDenied": "{allowed} permitidos, {denied} denegados",
        "chip.overwrite": "sobrescritura",
        "chip.owner": "Propietario del servidor",
        "chip.member": "Miembro",
        "chip.deletedRole": "Rol eliminado",
        "chip.admin": "Administrador mediante el rol {role}",
        "chip.everyone": "Concedido a @everyone",
        "chip.role": "Concedido por el rol {role}",
        "chip.everyone.allowed": "Permitido por la sobrescritura de @everyone de este canal",
        "chip.everyone.denied": "Denegado por la sobrescritura de @everyone de este canal",
        "chip.roleOverwrite.allowed": "Permitido por la sobrescritura del rol {role} en este canal",
        "chip.roleOverwrite.denied": "Denegado por la sobrescritura del rol {role} en este canal",
        "chip.memberOverwrite.allowed": "Permitido por una sobrescritura para este miembro",
        "chip.memberOverwrite.denied": "Denegado por una sobrescritura para este miembro",
        "notice.owner": "Propietario del servidor: tiene todos los permisos y las sobrescrituras de canal no se aplican.",
        "notice.admin": "Administrador mediante el rol {role}: tiene todos los permisos y las sobrescrituras de canal no se aplican.",
        "notice.adminDeleted": "Administrador mediante un rol eliminado: tiene todos los permisos y las sobrescrituras de canal no se aplican.",
        "notice.roleAdmin": "Administrador: este rol tiene todos los permisos y se salta las sobrescrituras de canal.",
        "notice.overwrite.member": "Sobrescritura de miembro: lo que no aparece se hereda del servidor.",
        "notice.overwrite.role": "Sobrescritura de rol: lo que no aparece se hereda del servidor.",
        "empty.overwrite": "Esta sobrescritura no permite ni deniega nada, así que todo se hereda del servidor.",
        "empty.noOverwrites": "Este canal no tiene sobrescrituras, así que aquí todos tienen los permisos de sus roles del servidor.",
        "section.inChannel": "En {channel}",
        "section.serverWide": "En todo el servidor",
        "section.you": "Tú",
        "section.overwrites": "Sobrescrituras",
        "section.roles": "Roles",
        "this.channel": "este canal",
        "this.server": "este servidor",
        "subtitle.memberChannel": "Permisos en {channel} · {guild}",
        "subtitle.member": "Permisos en {guild}",
        "subtitle.role": "Permisos del rol · {guild}",
        "subtitle.channel": "Permisos del canal · {overwrites} · {guild}",
        "subtitle.guild": "Permisos del servidor · {roles}",
        "overwrites.count": { one: "{count} sobrescritura", other: "{count} sobrescrituras" },
        "roles.count": { one: "{count} rol", other: "{count} roles" },
        "menu.view": "Ver permisos",
        "toast.fail": "No se pudieron leer los permisos",
    },
    fr: {
        "perm.CREATE_INSTANT_INVITE": "Créer une invitation",
        "perm.KICK_MEMBERS": "Expulser des membres",
        "perm.BAN_MEMBERS": "Bannir des membres",
        "perm.ADMINISTRATOR": "Administrateur",
        "perm.MANAGE_CHANNELS": "Gérer les salons",
        "perm.MANAGE_GUILD": "Gérer le serveur",
        "perm.ADD_REACTIONS": "Ajouter des réactions",
        "perm.VIEW_AUDIT_LOG": "Voir les logs du serveur",
        "perm.PRIORITY_SPEAKER": "Voix prioritaire",
        "perm.STREAM": "Vidéo",
        "perm.VIEW_CHANNEL": "Voir les salons",
        "perm.SEND_MESSAGES": "Envoyer des messages",
        "perm.SEND_TTS_MESSAGES": "Envoyer des messages de synthèse vocale",
        "perm.MANAGE_MESSAGES": "Gérer les messages",
        "perm.EMBED_LINKS": "Intégrer des liens",
        "perm.ATTACH_FILES": "Joindre des fichiers",
        "perm.READ_MESSAGE_HISTORY": "Voir les anciens messages",
        "perm.MENTION_EVERYONE": "Mentionner @everyone, @here et tous les rôles",
        "perm.USE_EXTERNAL_EMOJIS": "Utiliser des émojis externes",
        "perm.VIEW_GUILD_INSIGHTS": "Voir les analyses du serveur",
        "perm.CONNECT": "Se connecter",
        "perm.SPEAK": "Parler",
        "perm.MUTE_MEMBERS": "Rendre des membres muets",
        "perm.DEAFEN_MEMBERS": "Mettre en sourdine des membres",
        "perm.MOVE_MEMBERS": "Déplacer des membres",
        "perm.USE_VAD": "Utiliser la détection de la voix",
        "perm.CHANGE_NICKNAME": "Changer de pseudo",
        "perm.MANAGE_NICKNAMES": "Gérer les pseudos",
        "perm.MANAGE_ROLES": "Gérer les rôles",
        "perm.MANAGE_WEBHOOKS": "Gérer les webhooks",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Gérer les expressions",
        "perm.USE_APPLICATION_COMMANDS": "Utiliser les commandes d'application",
        "perm.REQUEST_TO_SPEAK": "Demander à parler",
        "perm.MANAGE_EVENTS": "Gérer les évènements",
        "perm.MANAGE_THREADS": "Gérer les fils",
        "perm.CREATE_PUBLIC_THREADS": "Créer des fils publics",
        "perm.CREATE_PRIVATE_THREADS": "Créer des fils privés",
        "perm.USE_EXTERNAL_STICKERS": "Utiliser des stickers externes",
        "perm.SEND_MESSAGES_IN_THREADS": "Envoyer des messages dans les fils",
        "perm.USE_EMBEDDED_ACTIVITIES": "Utiliser les activités",
        "perm.MODERATE_MEMBERS": "Exclure temporairement des membres",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Voir les analyses des abonnements du serveur",
        "perm.USE_SOUNDBOARD": "Utiliser la table de mixage",
        "perm.CREATE_GUILD_EXPRESSIONS": "Créer des expressions",
        "perm.CREATE_EVENTS": "Créer des évènements",
        "perm.USE_EXTERNAL_SOUNDS": "Utiliser des sons externes",
        "perm.SEND_VOICE_MESSAGES": "Envoyer des messages vocaux",
        "perm.SEND_POLLS": "Créer des sondages",
        "perm.USE_EXTERNAL_APPS": "Utiliser des applications externes",
        "perm.PIN_MESSAGES": "Épingler des messages",
        "perm.BYPASS_SLOWMODE": "Ignorer le mode lent",
        "perm.unknown": "Inconnue (bit {bit})",
        "category.General": "Général",
        "category.Membership": "Adhésion",
        "category.Text": "Texte",
        "category.Voice": "Vocal",
        "category.Apps": "Applications",
        "category.Events": "Évènements",
        "category.Advanced": "Avancé",
        "category.Other": "Autres",
        "ui.close": "Fermer",
        "ui.sections": "Sections",
        "ui.show": "Afficher",
        "ui.searchLabel": "Rechercher des permissions",
        "ui.search": "Rechercher",
        "ui.showAll": "Afficher toutes les permissions",
        "ui.nothing": "Rien à afficher.",
        "filter.all": "Toutes",
        "filter.granted": "Accordées",
        "filter.notGranted": "Non accordées",
        "filter.allowed": "Autorisées",
        "filter.denied": "Refusées",
        "empty.match.all": "Aucune permission ne correspond à « {query} ».",
        "empty.match.granted": "Aucune permission accordée ne correspond à « {query} ».",
        "empty.match.notGranted": "Aucune permission non accordée ne correspond à « {query} ».",
        "empty.match.allowed": "Aucune permission autorisée ne correspond à « {query} ».",
        "empty.match.denied": "Aucune permission refusée ne correspond à « {query} ».",
        "empty.none.granted": "Aucune permission n'est accordée ici.",
        "empty.none.notGranted": "Toutes les permissions sont accordées ici.",
        "empty.none.allowed": "Aucune permission n'est autorisée ici.",
        "empty.none.denied": "Aucune permission n'est refusée ici.",
        "count.of": "{granted} sur {total}",
        "count.granted": "{count} accordées",
        "count.allowedDenied": "{allowed} autorisées, {denied} refusées",
        "chip.overwrite": "remplacement",
        "chip.owner": "Propriétaire du serveur",
        "chip.member": "Membre",
        "chip.deletedRole": "Rôle supprimé",
        "chip.admin": "Administrateur via le rôle {role}",
        "chip.everyone": "Accordée à @everyone",
        "chip.role": "Accordée par le rôle {role}",
        "chip.everyone.allowed": "Autorisée par le remplacement @everyone de ce salon",
        "chip.everyone.denied": "Refusée par le remplacement @everyone de ce salon",
        "chip.roleOverwrite.allowed": "Autorisée par le remplacement du rôle {role} dans ce salon",
        "chip.roleOverwrite.denied": "Refusée par le remplacement du rôle {role} dans ce salon",
        "chip.memberOverwrite.allowed": "Autorisée par un remplacement pour ce membre",
        "chip.memberOverwrite.denied": "Refusée par un remplacement pour ce membre",
        "notice.owner": "Propriétaire du serveur : a toutes les permissions, et les remplacements de salon ne s'appliquent pas.",
        "notice.admin": "Administrateur via le rôle {role} : a toutes les permissions, et les remplacements de salon ne s'appliquent pas.",
        "notice.adminDeleted": "Administrateur via un rôle supprimé : a toutes les permissions, et les remplacements de salon ne s'appliquent pas.",
        "notice.roleAdmin": "Administrateur : ce rôle a toutes les permissions et ignore les remplacements de salon.",
        "notice.overwrite.member": "Remplacement de membre : ce qui n'est pas listé est hérité du serveur.",
        "notice.overwrite.role": "Remplacement de rôle : ce qui n'est pas listé est hérité du serveur.",
        "empty.overwrite": "Ce remplacement n'autorise ni ne refuse rien, tout est donc hérité du serveur.",
        "empty.noOverwrites": "Ce salon n'a aucun remplacement, donc chacun a ici les permissions de ses rôles du serveur.",
        "section.inChannel": "Dans {channel}",
        "section.serverWide": "Sur tout le serveur",
        "section.you": "Toi",
        "section.overwrites": "Remplacements",
        "section.roles": "Rôles",
        "this.channel": "ce salon",
        "this.server": "ce serveur",
        "subtitle.memberChannel": "Permissions dans {channel} · {guild}",
        "subtitle.member": "Permissions dans {guild}",
        "subtitle.role": "Permissions du rôle · {guild}",
        "subtitle.channel": "Permissions du salon · {overwrites} · {guild}",
        "subtitle.guild": "Permissions du serveur · {roles}",
        "overwrites.count": { one: "{count} remplacement", other: "{count} remplacements" },
        "roles.count": { one: "{count} rôle", other: "{count} rôles" },
        "menu.view": "Voir les permissions",
        "toast.fail": "Impossible de lire les permissions",
    },
    ja: {
        "perm.CREATE_INSTANT_INVITE": "招待を作成",
        "perm.KICK_MEMBERS": "メンバーをキック",
        "perm.BAN_MEMBERS": "メンバーをBAN",
        "perm.ADMINISTRATOR": "管理者",
        "perm.MANAGE_CHANNELS": "チャンネルの管理",
        "perm.MANAGE_GUILD": "サーバー管理",
        "perm.ADD_REACTIONS": "リアクションの追加",
        "perm.VIEW_AUDIT_LOG": "監査ログを表示",
        "perm.PRIORITY_SPEAKER": "優先スピーカー",
        "perm.STREAM": "動画",
        "perm.VIEW_CHANNEL": "チャンネルを見る",
        "perm.SEND_MESSAGES": "メッセージを送信",
        "perm.SEND_TTS_MESSAGES": "テキスト読み上げメッセージを送信する",
        "perm.MANAGE_MESSAGES": "メッセージの管理",
        "perm.EMBED_LINKS": "埋め込みリンク",
        "perm.ATTACH_FILES": "ファイルを添付",
        "perm.READ_MESSAGE_HISTORY": "メッセージ履歴を読む",
        "perm.MENTION_EVERYONE": "@everyone、@here、全てのロールにメンション",
        "perm.USE_EXTERNAL_EMOJIS": "外部の絵文字を使用する",
        "perm.VIEW_GUILD_INSIGHTS": "サーバーインサイトを見る",
        "perm.CONNECT": "接続",
        "perm.SPEAK": "発言",
        "perm.MUTE_MEMBERS": "メンバーをミュート",
        "perm.DEAFEN_MEMBERS": "メンバーのスピーカーをミュート",
        "perm.MOVE_MEMBERS": "メンバーを移動",
        "perm.USE_VAD": "音声検出を使用",
        "perm.CHANGE_NICKNAME": "ニックネームの変更",
        "perm.MANAGE_NICKNAMES": "ニックネームの管理",
        "perm.MANAGE_ROLES": "ロールの管理",
        "perm.MANAGE_WEBHOOKS": "ウェブフックの管理",
        "perm.MANAGE_GUILD_EXPRESSIONS": "表現の管理",
        "perm.USE_APPLICATION_COMMANDS": "アプリコマンドを使う",
        "perm.REQUEST_TO_SPEAK": "スピーカー参加をリクエスト",
        "perm.MANAGE_EVENTS": "イベントの管理",
        "perm.MANAGE_THREADS": "スレッドの管理",
        "perm.CREATE_PUBLIC_THREADS": "公開スレッドの作成",
        "perm.CREATE_PRIVATE_THREADS": "プライベートスレッドの作成",
        "perm.USE_EXTERNAL_STICKERS": "外部のスタンプを使用する",
        "perm.SEND_MESSAGES_IN_THREADS": "スレッドでメッセージを送信",
        "perm.USE_EMBEDDED_ACTIVITIES": "アクティビティを使用",
        "perm.MODERATE_MEMBERS": "メンバーをタイムアウト",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "サーバーサブスクリプションのインサイトを見る",
        "perm.USE_SOUNDBOARD": "サウンドボードを使用",
        "perm.CREATE_GUILD_EXPRESSIONS": "表現の作成",
        "perm.CREATE_EVENTS": "イベントの作成",
        "perm.USE_EXTERNAL_SOUNDS": "外部のサウンドを使用",
        "perm.SEND_VOICE_MESSAGES": "ボイスメッセージを送信",
        "perm.SEND_POLLS": "投票を作成",
        "perm.USE_EXTERNAL_APPS": "外部のアプリを使用",
        "perm.PIN_MESSAGES": "メッセージをピン留め",
        "perm.BYPASS_SLOWMODE": "低速モードの影響を受けない",
        "perm.unknown": "不明（ビット {bit}）",
        "category.General": "一般",
        "category.Membership": "メンバーシップ",
        "category.Text": "テキスト",
        "category.Voice": "ボイス",
        "category.Apps": "アプリ",
        "category.Events": "イベント",
        "category.Advanced": "高度",
        "category.Other": "その他",
        "ui.close": "閉じる",
        "ui.sections": "セクション",
        "ui.show": "表示",
        "ui.searchLabel": "権限を検索",
        "ui.search": "検索",
        "ui.showAll": "すべての権限を表示",
        "ui.nothing": "表示できるものはありません。",
        "filter.all": "すべて",
        "filter.granted": "付与済み",
        "filter.notGranted": "未付与",
        "filter.allowed": "許可",
        "filter.denied": "拒否",
        "empty.match.all": "「{query}」に一致する権限はありません。",
        "empty.match.granted": "「{query}」に一致する付与済みの権限はありません。",
        "empty.match.notGranted": "「{query}」に一致する未付与の権限はありません。",
        "empty.match.allowed": "「{query}」に一致する許可された権限はありません。",
        "empty.match.denied": "「{query}」に一致する拒否された権限はありません。",
        "empty.none.granted": "ここで付与されている権限はありません。",
        "empty.none.notGranted": "ここではすべての権限が付与されています。",
        "empty.none.allowed": "ここで許可されている権限はありません。",
        "empty.none.denied": "ここで拒否されている権限はありません。",
        "count.of": "{total}件中{granted}件",
        "count.granted": "{count}件付与済み",
        "count.allowedDenied": "許可{allowed}件、拒否{denied}件",
        "chip.overwrite": "上書き",
        "chip.owner": "サーバーオーナー",
        "chip.member": "メンバー",
        "chip.deletedRole": "削除されたロール",
        "chip.admin": "{role}ロールによる管理者権限",
        "chip.everyone": "@everyone に付与",
        "chip.role": "{role}ロールが付与",
        "chip.everyone.allowed": "このチャンネルの @everyone の上書きで許可",
        "chip.everyone.denied": "このチャンネルの @everyone の上書きで拒否",
        "chip.roleOverwrite.allowed": "このチャンネルの{role}の上書きで許可",
        "chip.roleOverwrite.denied": "このチャンネルの{role}の上書きで拒否",
        "chip.memberOverwrite.allowed": "このメンバー向けの上書きで許可",
        "chip.memberOverwrite.denied": "このメンバー向けの上書きで拒否",
        "notice.owner": "サーバーオーナー：すべての権限を持ち、チャンネルの上書きは適用されません。",
        "notice.admin": "{role}ロールによる管理者：すべての権限を持ち、チャンネルの上書きは適用されません。",
        "notice.adminDeleted": "削除されたロールによる管理者：すべての権限を持ち、チャンネルの上書きは適用されません。",
        "notice.roleAdmin": "管理者：このロールはすべての権限を持ち、チャンネルの上書きを無視します。",
        "notice.overwrite.member": "メンバーの上書き：記載のないものはサーバーの設定を引き継ぎます。",
        "notice.overwrite.role": "ロールの上書き：記載のないものはサーバーの設定を引き継ぎます。",
        "empty.overwrite": "この上書きでは何も許可・拒否されていないため、すべてサーバーの設定を引き継ぎます。",
        "empty.noOverwrites": "このチャンネルには上書きがないため、ここでは全員がサーバーロールの権限を持ちます。",
        "section.inChannel": "{channel}内",
        "section.serverWide": "サーバー全体",
        "section.you": "あなた",
        "section.overwrites": "上書き",
        "section.roles": "ロール",
        "this.channel": "このチャンネル",
        "this.server": "このサーバー",
        "subtitle.memberChannel": "{channel}での権限 · {guild}",
        "subtitle.member": "{guild}での権限",
        "subtitle.role": "ロールの権限 · {guild}",
        "subtitle.channel": "チャンネルの権限 · {overwrites} · {guild}",
        "subtitle.guild": "サーバーの権限 · {roles}",
        "overwrites.count": { other: "上書き{count}件" },
        "roles.count": { other: "ロール{count}件" },
        "menu.view": "権限を表示",
        "toast.fail": "権限を読み取れませんでした",
    },
    pl: {
        "perm.CREATE_INSTANT_INVITE": "Tworzenie zaproszeń",
        "perm.KICK_MEMBERS": "Wyrzucanie członków",
        "perm.BAN_MEMBERS": "Banowanie członków",
        "perm.ADMINISTRATOR": "Administrator",
        "perm.MANAGE_CHANNELS": "Zarządzanie kanałami",
        "perm.MANAGE_GUILD": "Zarządzanie serwerem",
        "perm.ADD_REACTIONS": "Dodawanie reakcji",
        "perm.VIEW_AUDIT_LOG": "Wyświetlanie dziennika zdarzeń",
        "perm.PRIORITY_SPEAKER": "Priorytetowy rozmówca",
        "perm.STREAM": "Wideo",
        "perm.VIEW_CHANNEL": "Wyświetlanie kanałów",
        "perm.SEND_MESSAGES": "Wysyłanie wiadomości",
        "perm.SEND_TTS_MESSAGES": "Wysyłanie wiadomości zamiany tekstu na mowę",
        "perm.MANAGE_MESSAGES": "Zarządzanie wiadomościami",
        "perm.EMBED_LINKS": "Osadzanie linków",
        "perm.ATTACH_FILES": "Załączanie plików",
        "perm.READ_MESSAGE_HISTORY": "Czytanie historii wiadomości",
        "perm.MENTION_EVERYONE": "Wzmiankowanie @everyone, @here i wszystkich ról",
        "perm.USE_EXTERNAL_EMOJIS": "Używanie zewnętrznych emoji",
        "perm.VIEW_GUILD_INSIGHTS": "Wyświetlanie statystyk serwera",
        "perm.CONNECT": "Łączenie",
        "perm.SPEAK": "Mówienie",
        "perm.MUTE_MEMBERS": "Wyciszanie członków",
        "perm.DEAFEN_MEMBERS": "Ogłuszanie członków",
        "perm.MOVE_MEMBERS": "Przenoszenie członków",
        "perm.USE_VAD": "Używanie aktywacji głosowej",
        "perm.CHANGE_NICKNAME": "Zmiana pseudonimu",
        "perm.MANAGE_NICKNAMES": "Zarządzanie pseudonimami",
        "perm.MANAGE_ROLES": "Zarządzanie rolami",
        "perm.MANAGE_WEBHOOKS": "Zarządzanie webhookami",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Zarządzanie wyrażeniami",
        "perm.USE_APPLICATION_COMMANDS": "Używanie poleceń aplikacji",
        "perm.REQUEST_TO_SPEAK": "Prośba o głos",
        "perm.MANAGE_EVENTS": "Zarządzanie wydarzeniami",
        "perm.MANAGE_THREADS": "Zarządzanie wątkami",
        "perm.CREATE_PUBLIC_THREADS": "Tworzenie publicznych wątków",
        "perm.CREATE_PRIVATE_THREADS": "Tworzenie prywatnych wątków",
        "perm.USE_EXTERNAL_STICKERS": "Używanie zewnętrznych naklejek",
        "perm.SEND_MESSAGES_IN_THREADS": "Wysyłanie wiadomości w wątkach",
        "perm.USE_EMBEDDED_ACTIVITIES": "Używanie aktywności",
        "perm.MODERATE_MEMBERS": "Wyciszanie członków czasowo",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Wyświetlanie statystyk subskrypcji serwera",
        "perm.USE_SOUNDBOARD": "Używanie tablicy dźwięków",
        "perm.CREATE_GUILD_EXPRESSIONS": "Tworzenie wyrażeń",
        "perm.CREATE_EVENTS": "Tworzenie wydarzeń",
        "perm.USE_EXTERNAL_SOUNDS": "Używanie zewnętrznych dźwięków",
        "perm.SEND_VOICE_MESSAGES": "Wysyłanie wiadomości głosowych",
        "perm.SEND_POLLS": "Tworzenie ankiet",
        "perm.USE_EXTERNAL_APPS": "Używanie zewnętrznych aplikacji",
        "perm.PIN_MESSAGES": "Przypinanie wiadomości",
        "perm.BYPASS_SLOWMODE": "Pomijanie trybu powolnego",
        "perm.unknown": "Nieznane (bit {bit})",
        "category.General": "Ogólne",
        "category.Membership": "Członkostwo",
        "category.Text": "Tekst",
        "category.Voice": "Głos",
        "category.Apps": "Aplikacje",
        "category.Events": "Wydarzenia",
        "category.Advanced": "Zaawansowane",
        "category.Other": "Inne",
        "ui.close": "Zamknij",
        "ui.sections": "Sekcje",
        "ui.show": "Pokaż",
        "ui.searchLabel": "Szukaj uprawnień",
        "ui.search": "Szukaj",
        "ui.showAll": "Pokaż wszystkie uprawnienia",
        "ui.nothing": "Nie ma nic do pokazania.",
        "filter.all": "Wszystkie",
        "filter.granted": "Przyznane",
        "filter.notGranted": "Nieprzyznane",
        "filter.allowed": "Dozwolone",
        "filter.denied": "Zabronione",
        "empty.match.all": "Żadne uprawnienia nie pasują do „{query}”.",
        "empty.match.granted": "Żadne przyznane uprawnienia nie pasują do „{query}”.",
        "empty.match.notGranted": "Żadne nieprzyznane uprawnienia nie pasują do „{query}”.",
        "empty.match.allowed": "Żadne dozwolone uprawnienia nie pasują do „{query}”.",
        "empty.match.denied": "Żadne zabronione uprawnienia nie pasują do „{query}”.",
        "empty.none.granted": "Nie przyznano tu żadnych uprawnień.",
        "empty.none.notGranted": "Wszystkie uprawnienia są tu przyznane.",
        "empty.none.allowed": "Nie zezwolono tu na żadne uprawnienia.",
        "empty.none.denied": "Nie zabroniono tu żadnych uprawnień.",
        "count.of": "{granted} z {total}",
        "count.granted": "Przyznane: {count}",
        "count.allowedDenied": "Dozwolone: {allowed}, zabronione: {denied}",
        "chip.overwrite": "nadpisanie",
        "chip.owner": "Właściciel serwera",
        "chip.member": "Członek",
        "chip.deletedRole": "Usunięta rola",
        "chip.admin": "Administrator dzięki roli {role}",
        "chip.everyone": "Przyznane roli @everyone",
        "chip.role": "Przyznane przez rolę {role}",
        "chip.everyone.allowed": "Dozwolone przez nadpisanie @everyone na tym kanale",
        "chip.everyone.denied": "Zabronione przez nadpisanie @everyone na tym kanale",
        "chip.roleOverwrite.allowed": "Dozwolone przez nadpisanie roli {role} na tym kanale",
        "chip.roleOverwrite.denied": "Zabronione przez nadpisanie roli {role} na tym kanale",
        "chip.memberOverwrite.allowed": "Dozwolone przez nadpisanie dla tego członka",
        "chip.memberOverwrite.denied": "Zabronione przez nadpisanie dla tego członka",
        "notice.owner": "Właściciel serwera: ma wszystkie uprawnienia, a nadpisania kanału go nie dotyczą.",
        "notice.admin": "Administrator dzięki roli {role}: ma wszystkie uprawnienia, a nadpisania kanału go nie dotyczą.",
        "notice.adminDeleted": "Administrator dzięki usuniętej roli: ma wszystkie uprawnienia, a nadpisania kanału go nie dotyczą.",
        "notice.roleAdmin": "Administrator: ta rola ma wszystkie uprawnienia i pomija nadpisania kanału.",
        "notice.overwrite.member": "Nadpisanie dla członka: wszystko, czego tu nie ma, jest dziedziczone z serwera.",
        "notice.overwrite.role": "Nadpisanie dla roli: wszystko, czego tu nie ma, jest dziedziczone z serwera.",
        "empty.overwrite": "To nadpisanie niczego nie zezwala ani nie zabrania, więc wszystko jest dziedziczone z serwera.",
        "empty.noOverwrites": "Ten kanał nie ma nadpisań, więc każdy ma tu uprawnienia wynikające ze swoich ról na serwerze.",
        "section.inChannel": "Na kanale {channel}",
        "section.serverWide": "Na całym serwerze",
        "section.you": "Ty",
        "section.overwrites": "Nadpisania",
        "section.roles": "Role",
        "this.channel": "ten kanał",
        "this.server": "ten serwer",
        "subtitle.memberChannel": "Uprawnienia na kanale {channel} · {guild}",
        "subtitle.member": "Uprawnienia na serwerze {guild}",
        "subtitle.role": "Uprawnienia roli · {guild}",
        "subtitle.channel": "Uprawnienia kanału · {overwrites} · {guild}",
        "subtitle.guild": "Uprawnienia serwera · {roles}",
        "overwrites.count": { one: "{count} nadpisanie", few: "{count} nadpisania", many: "{count} nadpisań", other: "{count} nadpisania" },
        "roles.count": { one: "{count} rola", few: "{count} role", many: "{count} ról", other: "{count} roli" },
        "menu.view": "Wyświetl uprawnienia",
        "toast.fail": "Nie udało się odczytać uprawnień",
    },
    "pt-BR": {
        "perm.CREATE_INSTANT_INVITE": "Criar convite",
        "perm.KICK_MEMBERS": "Expulsar membros",
        "perm.BAN_MEMBERS": "Banir membros",
        "perm.ADMINISTRATOR": "Administrador",
        "perm.MANAGE_CHANNELS": "Gerenciar canais",
        "perm.MANAGE_GUILD": "Gerenciar servidor",
        "perm.ADD_REACTIONS": "Adicionar reações",
        "perm.VIEW_AUDIT_LOG": "Ver o registro de auditoria",
        "perm.PRIORITY_SPEAKER": "Voz prioritária",
        "perm.STREAM": "Vídeo",
        "perm.VIEW_CHANNEL": "Ver canais",
        "perm.SEND_MESSAGES": "Enviar mensagens",
        "perm.SEND_TTS_MESSAGES": "Enviar mensagens de texto para voz",
        "perm.MANAGE_MESSAGES": "Gerenciar mensagens",
        "perm.EMBED_LINKS": "Inserir links",
        "perm.ATTACH_FILES": "Anexar arquivos",
        "perm.READ_MESSAGE_HISTORY": "Ver histórico de mensagens",
        "perm.MENTION_EVERYONE": "Mencionar @everyone, @here e todos os cargos",
        "perm.USE_EXTERNAL_EMOJIS": "Usar emojis externos",
        "perm.VIEW_GUILD_INSIGHTS": "Ver informações do servidor",
        "perm.CONNECT": "Conectar",
        "perm.SPEAK": "Falar",
        "perm.MUTE_MEMBERS": "Silenciar membros",
        "perm.DEAFEN_MEMBERS": "Ensurdecer membros",
        "perm.MOVE_MEMBERS": "Mover membros",
        "perm.USE_VAD": "Usar detecção de voz",
        "perm.CHANGE_NICKNAME": "Alterar apelido",
        "perm.MANAGE_NICKNAMES": "Gerenciar apelidos",
        "perm.MANAGE_ROLES": "Gerenciar cargos",
        "perm.MANAGE_WEBHOOKS": "Gerenciar webhooks",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Gerenciar expressões",
        "perm.USE_APPLICATION_COMMANDS": "Usar comandos de aplicativos",
        "perm.REQUEST_TO_SPEAK": "Pedir para falar",
        "perm.MANAGE_EVENTS": "Gerenciar eventos",
        "perm.MANAGE_THREADS": "Gerenciar tópicos",
        "perm.CREATE_PUBLIC_THREADS": "Criar tópicos públicos",
        "perm.CREATE_PRIVATE_THREADS": "Criar tópicos privados",
        "perm.USE_EXTERNAL_STICKERS": "Usar figurinhas externas",
        "perm.SEND_MESSAGES_IN_THREADS": "Enviar mensagens em tópicos",
        "perm.USE_EMBEDDED_ACTIVITIES": "Usar atividades",
        "perm.MODERATE_MEMBERS": "Colocar membros em castigo",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Ver informações de assinaturas do servidor",
        "perm.USE_SOUNDBOARD": "Usar painel de sons",
        "perm.CREATE_GUILD_EXPRESSIONS": "Criar expressões",
        "perm.CREATE_EVENTS": "Criar eventos",
        "perm.USE_EXTERNAL_SOUNDS": "Usar sons externos",
        "perm.SEND_VOICE_MESSAGES": "Enviar mensagens de voz",
        "perm.SEND_POLLS": "Criar enquetes",
        "perm.USE_EXTERNAL_APPS": "Usar aplicativos externos",
        "perm.PIN_MESSAGES": "Fixar mensagens",
        "perm.BYPASS_SLOWMODE": "Ignorar o modo lento",
        "perm.unknown": "Desconhecida (bit {bit})",
        "category.General": "Geral",
        "category.Membership": "Associação",
        "category.Text": "Texto",
        "category.Voice": "Voz",
        "category.Apps": "Aplicativos",
        "category.Events": "Eventos",
        "category.Advanced": "Avançado",
        "category.Other": "Outros",
        "ui.close": "Fechar",
        "ui.sections": "Seções",
        "ui.show": "Mostrar",
        "ui.searchLabel": "Pesquisar permissões",
        "ui.search": "Pesquisar",
        "ui.showAll": "Mostrar todas as permissões",
        "ui.nothing": "Nada para mostrar.",
        "filter.all": "Todas",
        "filter.granted": "Concedidas",
        "filter.notGranted": "Não concedidas",
        "filter.allowed": "Permitidas",
        "filter.denied": "Negadas",
        "empty.match.all": "Nenhuma permissão corresponde a “{query}”.",
        "empty.match.granted": "Nenhuma permissão concedida corresponde a “{query}”.",
        "empty.match.notGranted": "Nenhuma permissão não concedida corresponde a “{query}”.",
        "empty.match.allowed": "Nenhuma permissão permitida corresponde a “{query}”.",
        "empty.match.denied": "Nenhuma permissão negada corresponde a “{query}”.",
        "empty.none.granted": "Nenhuma permissão é concedida aqui.",
        "empty.none.notGranted": "Todas as permissões são concedidas aqui.",
        "empty.none.allowed": "Nenhuma permissão é permitida aqui.",
        "empty.none.denied": "Nenhuma permissão é negada aqui.",
        "count.of": "{granted} de {total}",
        "count.granted": "{count} concedidas",
        "count.allowedDenied": "{allowed} permitidas, {denied} negadas",
        "chip.overwrite": "substituição",
        "chip.owner": "Dono do servidor",
        "chip.member": "Membro",
        "chip.deletedRole": "Cargo excluído",
        "chip.admin": "Administrador pelo cargo {role}",
        "chip.everyone": "Concedida a @everyone",
        "chip.role": "Concedida pelo cargo {role}",
        "chip.everyone.allowed": "Permitida pela substituição de @everyone deste canal",
        "chip.everyone.denied": "Negada pela substituição de @everyone deste canal",
        "chip.roleOverwrite.allowed": "Permitida pela substituição do cargo {role} neste canal",
        "chip.roleOverwrite.denied": "Negada pela substituição do cargo {role} neste canal",
        "chip.memberOverwrite.allowed": "Permitida por uma substituição para este membro",
        "chip.memberOverwrite.denied": "Negada por uma substituição para este membro",
        "notice.owner": "Dono do servidor: tem todas as permissões, e as substituições de canal não se aplicam.",
        "notice.admin": "Administrador pelo cargo {role}: tem todas as permissões, e as substituições de canal não se aplicam.",
        "notice.adminDeleted": "Administrador por um cargo excluído: tem todas as permissões, e as substituições de canal não se aplicam.",
        "notice.roleAdmin": "Administrador: este cargo tem todas as permissões e ignora as substituições de canal.",
        "notice.overwrite.member": "Substituição de membro: o que não está listado é herdado do servidor.",
        "notice.overwrite.role": "Substituição de cargo: o que não está listado é herdado do servidor.",
        "empty.overwrite": "Esta substituição não permite nem nega nada, então tudo é herdado do servidor.",
        "empty.noOverwrites": "Este canal não tem substituições, então todos têm aqui as permissões dos seus cargos no servidor.",
        "section.inChannel": "Em {channel}",
        "section.serverWide": "No servidor todo",
        "section.you": "Você",
        "section.overwrites": "Substituições",
        "section.roles": "Cargos",
        "this.channel": "este canal",
        "this.server": "este servidor",
        "subtitle.memberChannel": "Permissões em {channel} · {guild}",
        "subtitle.member": "Permissões em {guild}",
        "subtitle.role": "Permissões do cargo · {guild}",
        "subtitle.channel": "Permissões do canal · {overwrites} · {guild}",
        "subtitle.guild": "Permissões do servidor · {roles}",
        "overwrites.count": { one: "{count} substituição", other: "{count} substituições" },
        "roles.count": { one: "{count} cargo", other: "{count} cargos" },
        "menu.view": "Ver permissões",
        "toast.fail": "Não foi possível ler as permissões",
    },
    ru: {
        "perm.CREATE_INSTANT_INVITE": "Создание приглашений",
        "perm.KICK_MEMBERS": "Выгонять участников",
        "perm.BAN_MEMBERS": "Банить участников",
        "perm.ADMINISTRATOR": "Администратор",
        "perm.MANAGE_CHANNELS": "Управление каналами",
        "perm.MANAGE_GUILD": "Управление сервером",
        "perm.ADD_REACTIONS": "Добавление реакций",
        "perm.VIEW_AUDIT_LOG": "Просмотр журнала аудита",
        "perm.PRIORITY_SPEAKER": "Приоритетный режим",
        "perm.STREAM": "Видео",
        "perm.VIEW_CHANNEL": "Просмотр каналов",
        "perm.SEND_MESSAGES": "Отправлять сообщения",
        "perm.SEND_TTS_MESSAGES": "Отправлять TTS-сообщения",
        "perm.MANAGE_MESSAGES": "Управление сообщениями",
        "perm.EMBED_LINKS": "Встраивать ссылки",
        "perm.ATTACH_FILES": "Прикреплять файлы",
        "perm.READ_MESSAGE_HISTORY": "Читать историю сообщений",
        "perm.MENTION_EVERYONE": "Упоминание @everyone, @here и всех ролей",
        "perm.USE_EXTERNAL_EMOJIS": "Использовать внешние эмодзи",
        "perm.VIEW_GUILD_INSIGHTS": "Просмотр аналитики сервера",
        "perm.CONNECT": "Подключаться",
        "perm.SPEAK": "Говорить",
        "perm.MUTE_MEMBERS": "Отключать микрофон участникам",
        "perm.DEAFEN_MEMBERS": "Отключать звук участникам",
        "perm.MOVE_MEMBERS": "Перемещать участников",
        "perm.USE_VAD": "Использовать режим активации по голосу",
        "perm.CHANGE_NICKNAME": "Изменение никнейма",
        "perm.MANAGE_NICKNAMES": "Управление никнеймами",
        "perm.MANAGE_ROLES": "Управление ролями",
        "perm.MANAGE_WEBHOOKS": "Управление вебхуками",
        "perm.MANAGE_GUILD_EXPRESSIONS": "Управление выражениями",
        "perm.USE_APPLICATION_COMMANDS": "Использование команд приложений",
        "perm.REQUEST_TO_SPEAK": "Запрос на выступление",
        "perm.MANAGE_EVENTS": "Управление событиями",
        "perm.MANAGE_THREADS": "Управление ветками",
        "perm.CREATE_PUBLIC_THREADS": "Создание публичных веток",
        "perm.CREATE_PRIVATE_THREADS": "Создание приватных веток",
        "perm.USE_EXTERNAL_STICKERS": "Использовать внешние стикеры",
        "perm.SEND_MESSAGES_IN_THREADS": "Отправлять сообщения в ветках",
        "perm.USE_EMBEDDED_ACTIVITIES": "Использовать активности",
        "perm.MODERATE_MEMBERS": "Отправлять участников подумать о поведении",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Просмотр аналитики подписок сервера",
        "perm.USE_SOUNDBOARD": "Использовать звуковую панель",
        "perm.CREATE_GUILD_EXPRESSIONS": "Создание выражений",
        "perm.CREATE_EVENTS": "Создание событий",
        "perm.USE_EXTERNAL_SOUNDS": "Использовать внешние звуки",
        "perm.SEND_VOICE_MESSAGES": "Отправлять голосовые сообщения",
        "perm.SEND_POLLS": "Создание опросов",
        "perm.USE_EXTERNAL_APPS": "Использовать внешние приложения",
        "perm.PIN_MESSAGES": "Закреплять сообщения",
        "perm.BYPASS_SLOWMODE": "Обход медленного режима",
        "perm.unknown": "Неизвестно (бит {bit})",
        "category.General": "Основные",
        "category.Membership": "Участники",
        "category.Text": "Текст",
        "category.Voice": "Голос",
        "category.Apps": "Приложения",
        "category.Events": "События",
        "category.Advanced": "Расширенные",
        "category.Other": "Прочее",
        "ui.close": "Закрыть",
        "ui.sections": "Разделы",
        "ui.show": "Показать",
        "ui.searchLabel": "Поиск прав",
        "ui.search": "Поиск",
        "ui.showAll": "Показать все права",
        "ui.nothing": "Здесь пока нечего показывать.",
        "filter.all": "Все",
        "filter.granted": "Выданные",
        "filter.notGranted": "Не выданные",
        "filter.allowed": "Разрешённые",
        "filter.denied": "Запрещённые",
        "empty.match.all": "Нет прав, подходящих под «{query}».",
        "empty.match.granted": "Нет выданных прав, подходящих под «{query}».",
        "empty.match.notGranted": "Нет не выданных прав, подходящих под «{query}».",
        "empty.match.allowed": "Нет разрешённых прав, подходящих под «{query}».",
        "empty.match.denied": "Нет запрещённых прав, подходящих под «{query}».",
        "empty.none.granted": "Здесь нет выданных прав.",
        "empty.none.notGranted": "Здесь выданы все права.",
        "empty.none.allowed": "Здесь нет разрешённых прав.",
        "empty.none.denied": "Здесь нет запрещённых прав.",
        "count.of": "{granted} из {total}",
        "count.granted": "Выдано: {count}",
        "count.allowedDenied": "Разрешено: {allowed}, запрещено: {denied}",
        "chip.overwrite": "исключение",
        "chip.owner": "Владелец сервера",
        "chip.member": "Участник",
        "chip.deletedRole": "Удалённая роль",
        "chip.admin": "Администратор через роль «{role}»",
        "chip.everyone": "Выдано роли @everyone",
        "chip.role": "Выдано ролью «{role}»",
        "chip.everyone.allowed": "Разрешено исключением для @everyone в этом канале",
        "chip.everyone.denied": "Запрещено исключением для @everyone в этом канале",
        "chip.roleOverwrite.allowed": "Разрешено исключением для роли «{role}» в этом канале",
        "chip.roleOverwrite.denied": "Запрещено исключением для роли «{role}» в этом канале",
        "chip.memberOverwrite.allowed": "Разрешено исключением для этого участника",
        "chip.memberOverwrite.denied": "Запрещено исключением для этого участника",
        "notice.owner": "Владелец сервера: имеет все права, исключения каналов не действуют.",
        "notice.admin": "Администратор через роль «{role}»: имеет все права, исключения каналов не действуют.",
        "notice.adminDeleted": "Администратор через удалённую роль: имеет все права, исключения каналов не действуют.",
        "notice.roleAdmin": "Администратор: эта роль имеет все права и игнорирует исключения каналов.",
        "notice.overwrite.member": "Исключение для участника: всё, чего нет в списке, наследуется от сервера.",
        "notice.overwrite.role": "Исключение для роли: всё, чего нет в списке, наследуется от сервера.",
        "empty.overwrite": "Это исключение ничего не разрешает и не запрещает, поэтому всё наследуется от сервера.",
        "empty.noOverwrites": "В этом канале нет исключений, поэтому у всех здесь права их ролей на сервере.",
        "section.inChannel": "В канале {channel}",
        "section.serverWide": "На всём сервере",
        "section.you": "Вы",
        "section.overwrites": "Исключения",
        "section.roles": "Роли",
        "this.channel": "этот канал",
        "this.server": "этот сервер",
        "subtitle.memberChannel": "Права в канале {channel} · {guild}",
        "subtitle.member": "Права на сервере {guild}",
        "subtitle.role": "Права роли · {guild}",
        "subtitle.channel": "Права канала · {overwrites} · {guild}",
        "subtitle.guild": "Права сервера · {roles}",
        "overwrites.count": { one: "{count} исключение", few: "{count} исключения", many: "{count} исключений", other: "{count} исключения" },
        "roles.count": { one: "{count} роль", few: "{count} роли", many: "{count} ролей", other: "{count} роли" },
        "menu.view": "Посмотреть права",
        "toast.fail": "Не удалось прочитать права",
    },
    tr: {
        "perm.CREATE_INSTANT_INVITE": "Davet Oluştur",
        "perm.KICK_MEMBERS": "Üyeleri At",
        "perm.BAN_MEMBERS": "Üyeleri Yasakla",
        "perm.ADMINISTRATOR": "Yönetici",
        "perm.MANAGE_CHANNELS": "Kanalları Yönet",
        "perm.MANAGE_GUILD": "Sunucuyu Yönet",
        "perm.ADD_REACTIONS": "Tepki Ekle",
        "perm.VIEW_AUDIT_LOG": "Denetim Kaydını Görüntüle",
        "perm.PRIORITY_SPEAKER": "Öncelikli Konuşmacı",
        "perm.STREAM": "Video",
        "perm.VIEW_CHANNEL": "Kanalları Görüntüle",
        "perm.SEND_MESSAGES": "Mesaj Gönder",
        "perm.SEND_TTS_MESSAGES": "Metin Okuma Mesajı Gönder",
        "perm.MANAGE_MESSAGES": "Mesajları Yönet",
        "perm.EMBED_LINKS": "Bağlantı Yerleştir",
        "perm.ATTACH_FILES": "Dosya Ekle",
        "perm.READ_MESSAGE_HISTORY": "Mesaj Geçmişini Oku",
        "perm.MENTION_EVERYONE": "@everyone, @here ve Tüm Rollerden Bahset",
        "perm.USE_EXTERNAL_EMOJIS": "Harici Emoji Kullan",
        "perm.VIEW_GUILD_INSIGHTS": "Sunucu İstatistiklerini Görüntüle",
        "perm.CONNECT": "Bağlan",
        "perm.SPEAK": "Konuş",
        "perm.MUTE_MEMBERS": "Üyeleri Sustur",
        "perm.DEAFEN_MEMBERS": "Üyeleri Sağırlaştır",
        "perm.MOVE_MEMBERS": "Üyeleri Taşı",
        "perm.USE_VAD": "Ses Algılamayı Kullan",
        "perm.CHANGE_NICKNAME": "Takma Adı Değiştir",
        "perm.MANAGE_NICKNAMES": "Takma Adları Yönet",
        "perm.MANAGE_ROLES": "Rolleri Yönet",
        "perm.MANAGE_WEBHOOKS": "Webhook'ları Yönet",
        "perm.MANAGE_GUILD_EXPRESSIONS": "İfadeleri Yönet",
        "perm.USE_APPLICATION_COMMANDS": "Uygulama Komutlarını Kullan",
        "perm.REQUEST_TO_SPEAK": "Konuşma İsteği Gönder",
        "perm.MANAGE_EVENTS": "Etkinlikleri Yönet",
        "perm.MANAGE_THREADS": "Alt Başlıkları Yönet",
        "perm.CREATE_PUBLIC_THREADS": "Herkese Açık Alt Başlık Oluştur",
        "perm.CREATE_PRIVATE_THREADS": "Özel Alt Başlık Oluştur",
        "perm.USE_EXTERNAL_STICKERS": "Harici Çıkartma Kullan",
        "perm.SEND_MESSAGES_IN_THREADS": "Alt Başlıklarda Mesaj Gönder",
        "perm.USE_EMBEDDED_ACTIVITIES": "Etkinlikleri Kullan",
        "perm.MODERATE_MEMBERS": "Üyelere Zaman Aşımı Uygula",
        "perm.VIEW_CREATOR_MONETIZATION_ANALYTICS": "Sunucu Abonelik İstatistiklerini Görüntüle",
        "perm.USE_SOUNDBOARD": "Ses Tahtasını Kullan",
        "perm.CREATE_GUILD_EXPRESSIONS": "İfade Oluştur",
        "perm.CREATE_EVENTS": "Etkinlik Oluştur",
        "perm.USE_EXTERNAL_SOUNDS": "Harici Ses Kullan",
        "perm.SEND_VOICE_MESSAGES": "Sesli Mesaj Gönder",
        "perm.SEND_POLLS": "Anket Oluştur",
        "perm.USE_EXTERNAL_APPS": "Harici Uygulamaları Kullan",
        "perm.PIN_MESSAGES": "Mesajları Sabitle",
        "perm.BYPASS_SLOWMODE": "Yavaş Modu Atla",
        "perm.unknown": "Bilinmeyen (bit {bit})",
        "category.General": "Genel",
        "category.Membership": "Üyelik",
        "category.Text": "Metin",
        "category.Voice": "Ses",
        "category.Apps": "Uygulamalar",
        "category.Events": "Etkinlikler",
        "category.Advanced": "Gelişmiş",
        "category.Other": "Diğer",
        "ui.close": "Kapat",
        "ui.sections": "Bölümler",
        "ui.show": "Göster",
        "ui.searchLabel": "İzinleri ara",
        "ui.search": "Ara",
        "ui.showAll": "Tüm izinleri göster",
        "ui.nothing": "Gösterilecek bir şey yok.",
        "filter.all": "Tümü",
        "filter.granted": "Verilenler",
        "filter.notGranted": "Verilmeyenler",
        "filter.allowed": "İzin verilenler",
        "filter.denied": "Reddedilenler",
        "empty.match.all": "“{query}” ile eşleşen izin yok.",
        "empty.match.granted": "“{query}” ile eşleşen verilmiş izin yok.",
        "empty.match.notGranted": "“{query}” ile eşleşen verilmemiş izin yok.",
        "empty.match.allowed": "“{query}” ile eşleşen izin verilmiş izin yok.",
        "empty.match.denied": "“{query}” ile eşleşen reddedilmiş izin yok.",
        "empty.none.granted": "Burada verilmiş bir izin yok.",
        "empty.none.notGranted": "Burada tüm izinler verilmiş.",
        "empty.none.allowed": "Burada izin verilmiş bir izin yok.",
        "empty.none.denied": "Burada reddedilmiş bir izin yok.",
        "count.of": "{total} izinden {granted}",
        "count.granted": "{count} verilmiş",
        "count.allowedDenied": "{allowed} izin verilmiş, {denied} reddedilmiş",
        "chip.overwrite": "geçersiz kılma",
        "chip.owner": "Sunucu sahibi",
        "chip.member": "Üye",
        "chip.deletedRole": "Silinmiş rol",
        "chip.admin": "{role} rolü üzerinden yönetici",
        "chip.everyone": "@everyone'a verilmiş",
        "chip.role": "{role} rolü tarafından verilmiş",
        "chip.everyone.allowed": "Bu kanalın @everyone geçersiz kılması tarafından izin verilmiş",
        "chip.everyone.denied": "Bu kanalın @everyone geçersiz kılması tarafından reddedilmiş",
        "chip.roleOverwrite.allowed": "Bu kanalın {role} geçersiz kılması tarafından izin verilmiş",
        "chip.roleOverwrite.denied": "Bu kanalın {role} geçersiz kılması tarafından reddedilmiş",
        "chip.memberOverwrite.allowed": "Bu üyeye özel bir geçersiz kılma tarafından izin verilmiş",
        "chip.memberOverwrite.denied": "Bu üyeye özel bir geçersiz kılma tarafından reddedilmiş",
        "notice.owner": "Sunucu sahibi: tüm izinlere sahiptir ve kanal geçersiz kılmaları geçerli olmaz.",
        "notice.admin": "{role} rolü üzerinden yönetici: tüm izinlere sahiptir ve kanal geçersiz kılmaları geçerli olmaz.",
        "notice.adminDeleted": "Silinmiş bir rol üzerinden yönetici: tüm izinlere sahiptir ve kanal geçersiz kılmaları geçerli olmaz.",
        "notice.roleAdmin": "Yönetici: bu rol tüm izinlere sahiptir ve kanal geçersiz kılmalarını yok sayar.",
        "notice.overwrite.member": "Üye geçersiz kılması: listelenmeyen her şey sunucudan devralınır.",
        "notice.overwrite.role": "Rol geçersiz kılması: listelenmeyen her şey sunucudan devralınır.",
        "empty.overwrite": "Bu geçersiz kılma hiçbir şeye izin vermiyor veya reddetmiyor, bu yüzden her şey sunucudan devralınıyor.",
        "empty.noOverwrites": "Bu kanalda geçersiz kılma yok, bu yüzden burada herkes sunucu rollerinin izinlerine sahip.",
        "section.inChannel": "{channel} kanalında",
        "section.serverWide": "Tüm sunucuda",
        "section.you": "Sen",
        "section.overwrites": "Geçersiz kılmalar",
        "section.roles": "Roller",
        "this.channel": "bu kanal",
        "this.server": "bu sunucu",
        "subtitle.memberChannel": "{channel} kanalındaki izinler · {guild}",
        "subtitle.member": "{guild} sunucusundaki izinler",
        "subtitle.role": "Rol izinleri · {guild}",
        "subtitle.channel": "Kanal izinleri · {overwrites} · {guild}",
        "subtitle.guild": "Sunucu izinleri · {roles}",
        "overwrites.count": { one: "{count} geçersiz kılma", other: "{count} geçersiz kılma" },
        "roles.count": { one: "{count} rol", other: "{count} rol" },
        "menu.view": "İzinleri Görüntüle",
        "toast.fail": "İzinler okunamadı",
    },
});
