import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.edit": "Double-click to edit",
        "settings.edit.description": "Double-click one of your messages to edit it.",
        "settings.editModifier": "Key to hold for editing",
        "settings.editModifier.description": "Hold this key while double-clicking your message, so a stray double-click never opens the editor.",
        "settings.editModifier.none": "None",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Double-click to reply",
        "settings.reply.description": "Double-click someone else's message to reply to it.",
        "settings.replyPing": "Mention when replying",
        "settings.replyPing.description": "Replies start with the mention on, like Discord's Reply button. Turned off, they start without it; you can still switch it on.",
        "settings.delete": "Shift+click to delete",
        "settings.delete.description": "Shift+click one of your messages to delete it straight away, like Shift+clicking Discord's Delete button. There's no undo.",
        "settings.deleteOthers": "Also other people's messages",
        "settings.deleteOthers.description": "Shift+click deletes other people's messages too, where you can manage messages.",
        "toast.deleteFailed": "Couldn't delete that message",
    },
    de: {
        "settings.edit": "Doppelklick zum Bearbeiten",
        "settings.edit.description": "Doppelklicke auf eine deiner Nachrichten, um sie zu bearbeiten.",
        "settings.editModifier": "Taste zum Bearbeiten",
        "settings.editModifier.description": "Halte diese Taste beim Doppelklick auf deine Nachricht, damit ein versehentlicher Doppelklick nie den Editor öffnet.",
        "settings.editModifier.none": "Keine",
        "settings.editModifier.ctrl": "Strg",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Doppelklick zum Antworten",
        "settings.reply.description": "Doppelklicke auf die Nachricht einer anderen Person, um darauf zu antworten.",
        "settings.replyPing": "Beim Antworten erwähnen",
        "settings.replyPing.description": "Antworten beginnen mit eingeschalteter Erwähnung, wie bei Discords Antworten-Knopf. Ausgeschaltet beginnen sie ohne; du kannst sie trotzdem einschalten.",
        "settings.delete": "Umschalt+Klick zum Löschen",
        "settings.delete.description": "Umschalt+Klick auf eine deiner Nachrichten löscht sie sofort, wie Umschalt+Klick auf Discords Löschen-Knopf. Rückgängig machen geht nicht.",
        "settings.deleteOthers": "Auch Nachrichten anderer",
        "settings.deleteOthers.description": "Umschalt+Klick löscht auch Nachrichten anderer Personen, wo du Nachrichten verwalten darfst.",
        "toast.deleteFailed": "Diese Nachricht konnte nicht gelöscht werden",
    },
    es: {
        "settings.edit": "Doble clic para editar",
        "settings.edit.description": "Haz doble clic en uno de tus mensajes para editarlo.",
        "settings.editModifier": "Tecla para editar",
        "settings.editModifier.description": "Mantén esta tecla al hacer doble clic en tu mensaje, para que un doble clic sin querer nunca abra el editor.",
        "settings.editModifier.none": "Ninguna",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Doble clic para responder",
        "settings.reply.description": "Haz doble clic en el mensaje de otra persona para responderle.",
        "settings.replyPing": "Mencionar al responder",
        "settings.replyPing.description": "Las respuestas empiezan con la mención activada, como con el botón Responder de Discord. Desactivado, empiezan sin ella; aún puedes activarla.",
        "settings.delete": "Mayús+clic para eliminar",
        "settings.delete.description": "Mayús+clic en uno de tus mensajes lo elimina al instante, como Mayús+clic en el botón Eliminar de Discord. No se puede deshacer.",
        "settings.deleteOthers": "También mensajes de otros",
        "settings.deleteOthers.description": "Mayús+clic también elimina mensajes de otras personas, donde puedes gestionar mensajes.",
        "toast.deleteFailed": "No se pudo eliminar ese mensaje",
    },
    fr: {
        "settings.edit": "Double-clic pour modifier",
        "settings.edit.description": "Double-clique sur un de tes messages pour le modifier.",
        "settings.editModifier": "Touche pour modifier",
        "settings.editModifier.description": "Maintiens cette touche en double-cliquant sur ton message, pour qu'un double-clic accidentel n'ouvre jamais l'éditeur.",
        "settings.editModifier.none": "Aucune",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Double-clic pour répondre",
        "settings.reply.description": "Double-clique sur le message de quelqu'un d'autre pour y répondre.",
        "settings.replyPing": "Mentionner en répondant",
        "settings.replyPing.description": "Les réponses commencent avec la mention activée, comme avec le bouton Répondre de Discord. Désactivé, elles commencent sans ; tu peux toujours l'activer.",
        "settings.delete": "Maj+clic pour supprimer",
        "settings.delete.description": "Maj+clic sur un de tes messages le supprime tout de suite, comme Maj+clic sur le bouton Supprimer de Discord. Impossible d'annuler.",
        "settings.deleteOthers": "Aussi les messages des autres",
        "settings.deleteOthers.description": "Maj+clic supprime aussi les messages des autres, là où tu peux gérer les messages.",
        "toast.deleteFailed": "Impossible de supprimer ce message",
    },
    ja: {
        "settings.edit": "ダブルクリックで編集",
        "settings.edit.description": "自分のメッセージをダブルクリックすると編集できます。",
        "settings.editModifier": "編集時に押すキー",
        "settings.editModifier.description": "自分のメッセージをダブルクリックするときにこのキーを押します。うっかりダブルクリックしても編集が開きません。",
        "settings.editModifier.none": "なし",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "ダブルクリックで返信",
        "settings.reply.description": "他の人のメッセージをダブルクリックすると返信できます。",
        "settings.replyPing": "返信時にメンションする",
        "settings.replyPing.description": "Discordの返信ボタンと同じく、メンションがオンの状態で返信を始めます。オフにするとメンションなしで始まります(あとからオンにもできます)。",
        "settings.delete": "Shift+クリックで削除",
        "settings.delete.description": "自分のメッセージをShift+クリックするとすぐに削除します。Discordの削除ボタンをShift+クリックするのと同じです。元に戻せません。",
        "settings.deleteOthers": "他の人のメッセージも",
        "settings.deleteOthers.description": "メッセージの管理権限がある場所では、他の人のメッセージもShift+クリックで削除します。",
        "toast.deleteFailed": "メッセージを削除できませんでした",
    },
    pl: {
        "settings.edit": "Dwuklik, aby edytować",
        "settings.edit.description": "Kliknij dwukrotnie swoją wiadomość, aby ją edytować.",
        "settings.editModifier": "Klawisz do edycji",
        "settings.editModifier.description": "Przytrzymaj ten klawisz, klikając dwukrotnie swoją wiadomość, żeby przypadkowy dwuklik nigdy nie otwierał edycji.",
        "settings.editModifier.none": "Brak",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Dwuklik, aby odpowiedzieć",
        "settings.reply.description": "Kliknij dwukrotnie cudzą wiadomość, aby na nią odpowiedzieć.",
        "settings.replyPing": "Wzmianka przy odpowiedzi",
        "settings.replyPing.description": "Odpowiedzi zaczynają się z włączoną wzmianką, jak przy przycisku Odpowiedz w Discordzie. Po wyłączeniu zaczynają się bez niej; nadal możesz ją włączyć.",
        "settings.delete": "Shift+klik, aby usunąć",
        "settings.delete.description": "Shift+klik na swoją wiadomość od razu ją usuwa, jak Shift+klik na przycisk Usuń w Discordzie. Nie da się tego cofnąć.",
        "settings.deleteOthers": "Także cudze wiadomości",
        "settings.deleteOthers.description": "Shift+klik usuwa też wiadomości innych osób tam, gdzie możesz zarządzać wiadomościami.",
        "toast.deleteFailed": "Nie udało się usunąć tej wiadomości",
    },
    "pt-BR": {
        "settings.edit": "Clique duplo para editar",
        "settings.edit.description": "Clique duas vezes em uma mensagem sua para editá-la.",
        "settings.editModifier": "Tecla para editar",
        "settings.editModifier.description": "Segure esta tecla ao clicar duas vezes na sua mensagem, para que um clique duplo sem querer nunca abra o editor.",
        "settings.editModifier.none": "Nenhuma",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Clique duplo para responder",
        "settings.reply.description": "Clique duas vezes na mensagem de outra pessoa para responder.",
        "settings.replyPing": "Mencionar ao responder",
        "settings.replyPing.description": "As respostas começam com a menção ligada, como no botão Responder do Discord. Desligado, começam sem ela; você ainda pode ligá-la.",
        "settings.delete": "Shift+clique para apagar",
        "settings.delete.description": "Shift+clique em uma mensagem sua apaga na hora, como Shift+clique no botão Excluir do Discord. Não dá para desfazer.",
        "settings.deleteOthers": "Também mensagens dos outros",
        "settings.deleteOthers.description": "Shift+clique também apaga mensagens de outras pessoas, onde você pode gerenciar mensagens.",
        "toast.deleteFailed": "Não foi possível apagar essa mensagem",
    },
    ru: {
        "settings.edit": "Двойной клик — изменить",
        "settings.edit.description": "Дважды щёлкните по своему сообщению, чтобы изменить его.",
        "settings.editModifier": "Клавиша для изменения",
        "settings.editModifier.description": "Удерживайте эту клавишу при двойном клике по своему сообщению, чтобы случайный двойной клик не открывал редактор.",
        "settings.editModifier.none": "Нет",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Двойной клик — ответить",
        "settings.reply.description": "Дважды щёлкните по чужому сообщению, чтобы ответить на него.",
        "settings.replyPing": "Упоминать при ответе",
        "settings.replyPing.description": "Ответы начинаются с включённым упоминанием, как у кнопки «Ответить» в Discord. Если выключить, начинаются без него; его всё равно можно включить.",
        "settings.delete": "Shift+клик — удалить",
        "settings.delete.description": "Shift+клик по своему сообщению сразу удаляет его, как Shift+клик по кнопке «Удалить» в Discord. Отменить нельзя.",
        "settings.deleteOthers": "И чужие сообщения",
        "settings.deleteOthers.description": "Shift+клик удаляет и чужие сообщения там, где вы можете управлять сообщениями.",
        "toast.deleteFailed": "Не удалось удалить это сообщение",
    },
    tr: {
        "settings.edit": "Düzenlemek için çift tıkla",
        "settings.edit.description": "Mesajlarından birini düzenlemek için ona çift tıkla.",
        "settings.editModifier": "Düzenleme için basılı tutulacak tuş",
        "settings.editModifier.description": "Mesajına çift tıklarken bu tuşu basılı tut; böylece yanlışlıkla yapılan bir çift tıklama düzenleyiciyi açmaz.",
        "settings.editModifier.none": "Yok",
        "settings.editModifier.ctrl": "Ctrl",
        "settings.editModifier.alt": "Alt",
        "settings.reply": "Yanıtlamak için çift tıkla",
        "settings.reply.description": "Başkasının mesajına yanıt vermek için ona çift tıkla.",
        "settings.replyPing": "Yanıtlarken bahset",
        "settings.replyPing.description": "Yanıtlar, Discord'un Yanıtla düğmesindeki gibi bahsetme açık başlar. Kapalıyken bahsetmesiz başlar; yine de açabilirsin.",
        "settings.delete": "Silmek için Shift+tıkla",
        "settings.delete.description": "Mesajlarından birine Shift+tıklamak onu hemen siler, Discord'un Sil düğmesine Shift+tıklamak gibi. Geri alınamaz.",
        "settings.deleteOthers": "Başkalarının mesajları da",
        "settings.deleteOthers.description": "Mesajları yönetebildiğin yerlerde Shift+tıklama başkalarının mesajlarını da siler.",
        "toast.deleteFailed": "Bu mesaj silinemedi",
    },
});
