import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "menu.open": "Embed Builder",
        "command.description": "Compose embeds and send them through a webhook in this channel",
        "dialog.title": "Embed Builder",
        "dialog.subtitle": "Sends to #{channel} through a webhook",
        "dialog.editing": "Editing a message the webhook sent",
        "webhook.label": "Webhook",
        "webhook.loading": "Loading webhooks…",
        "webhook.none": "This channel has no webhooks yet.",
        "webhook.create": "New webhook",
        "webhook.creating": "Creating…",
        "message.username": "Name",
        "message.avatar": "Avatar URL",
        "message.content": "Message",
        "message.total": "{length} / {limit} characters in embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Author name",
        "embed.authorUrl": "Author link",
        "embed.authorIcon": "Author icon URL",
        "embed.titleField": "Title",
        "embed.url": "Title link",
        "embed.description": "Description",
        "embed.color": "Colour",
        "embed.image": "Image URL",
        "embed.thumbnail": "Thumbnail URL",
        "embed.footerText": "Footer text",
        "embed.footerIcon": "Footer icon URL",
        "embed.timestamp": "Timestamp",
        "group.author": "Author",
        "group.body": "Body",
        "group.fields": "Fields ({count}/{limit})",
        "group.images": "Images",
        "group.footer": "Footer",
        "field.title": "Field {n}",
        "field.inline": "Inline",
        "field.name": "Name",
        "field.value": "Value",
        "action.addEmbed": "Add embed ({count}/{limit})",
        "action.addField": "Add field",
        "action.cancel": "Cancel",
        "action.clear": "Clear",
        "action.clearAll": "Start over",
        "action.close": "Close",
        "action.copyJson": "Copy JSON",
        "action.duplicate": "Duplicate",
        "action.moveUp": "Move up",
        "action.moveDown": "Move down",
        "action.now": "Now",
        "action.removeEmbed": "Remove embed",
        "action.removeField": "Remove field",
        "action.saveEdit": "Save changes",
        "action.send": "Send",
        "action.sending": "Sending…",
        "preview.app": "APP",
        "preview.label": "Preview",
        "preview.today": "Today at {time}",
        "import.button": "Import JSON",
        "import.label": "Paste a webhook message's JSON (Discohook's works too)",
        "import.load": "Load",
        "edit.button": "Edit a sent message",
        "edit.hint": "Right-click a message the selected webhook sent and Copy Message Link.",
        "edit.label": "Message link",
        "edit.load": "Open",
        "edit.loading": "Opening…",
        "edit.stop": "Send as new instead",
        "drafts.button": "Drafts",
        "drafts.title": "Saved drafts",
        "drafts.save": "Save this one",
        "drafts.none": "No saved drafts yet.",
        "drafts.delete": "Delete draft",
        "drafts.untitled": "Untitled",
        "problem.tooLong": "{where} is {length} characters, {limit} at most",
        "problem.tooManyEmbeds": "A message holds {limit} embeds at most",
        "problem.tooManyFields": "An embed holds {limit} fields at most",
        "problem.badUrl": "{where} isn't a link starting with https://",
        "problem.badColor": "{where} isn't a colour like #5865F2",
        "problem.badTimestamp": "{where} isn't a date",
        "problem.emptyEmbed": "{where} needs a title, text, author, footer, field or image",
        "problem.fieldNeedsBoth": "{where} needs both a name and a value",
        "problem.empty": "Write a message or fill in an embed first",
        "problem.more": "and {count} more",
        "where.total": "All embeds together",
        "where.embed": "Embed {n}",
        "where.field": "field {n}",
        "where.content": "The message",
        "where.username": "The name",
        "where.avatarUrl": "The avatar URL",
        "where.title": "title",
        "where.description": "description",
        "where.authorName": "author name",
        "where.authorUrl": "author link",
        "where.authorIcon": "author icon",
        "where.url": "title link",
        "where.image": "image",
        "where.thumbnail": "thumbnail",
        "where.footerText": "footer text",
        "where.footerIcon": "footer icon",
        "where.color": "colour",
        "where.timestamp": "timestamp",
        "where.name": "name",
        "where.value": "value",
        "error.noClient": "Couldn't find Discord's API client",
        "error.createFailed": "Couldn't create the webhook",
        "error.loadWebhooks": "Couldn't load this channel's webhooks",
        "error.rateLimited": "Discord says slow down: try again in {seconds} s",
        "error.notFound": "That webhook or message no longer exists",
        "error.status": "Discord answered with error {status}",
        "error.pickWebhook": "Pick a webhook or make a new one first",
        "error.sendFailed": "Couldn't send it",
        "error.badLink": "That isn't a Discord message link",
        "error.loadMessage": "Couldn't open that message. Was it sent by the selected webhook?",
        "error.notJson": "That isn't valid JSON",
        "error.notMessage": "That JSON isn't a message or an embed",
        "toast.copyFailed": "Couldn't copy",
        "toast.edited": "Message updated",
        "toast.sent": "Sent to #{channel}",
        "toast.draftSaved": "Draft saved",
        "toast.jsonCopied": "JSON copied",
    },
    de: {
        "menu.open": "Embed-Builder",
        "command.description": "Embeds erstellen und über einen Webhook in diesem Kanal senden",
        "dialog.title": "Embed-Builder",
        "dialog.subtitle": "Wird über einen Webhook in #{channel} gesendet",
        "dialog.editing": "Du bearbeitest eine Nachricht des Webhooks",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhooks werden geladen…",
        "webhook.none": "Dieser Kanal hat noch keine Webhooks.",
        "webhook.create": "Neuer Webhook",
        "webhook.creating": "Wird erstellt…",
        "message.username": "Name",
        "message.avatar": "Avatar-URL",
        "message.content": "Nachricht",
        "message.total": "{length} / {limit} Zeichen in Embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Autorname",
        "embed.authorUrl": "Autor-Link",
        "embed.authorIcon": "Autor-Symbol-URL",
        "embed.titleField": "Titel",
        "embed.url": "Titel-Link",
        "embed.description": "Beschreibung",
        "embed.color": "Farbe",
        "embed.image": "Bild-URL",
        "embed.thumbnail": "Vorschaubild-URL",
        "embed.footerText": "Fußzeilentext",
        "embed.footerIcon": "Fußzeilen-Symbol-URL",
        "embed.timestamp": "Zeitstempel",
        "group.author": "Autor",
        "group.body": "Inhalt",
        "group.fields": "Felder ({count}/{limit})",
        "group.images": "Bilder",
        "group.footer": "Fußzeile",
        "field.title": "Feld {n}",
        "field.inline": "In einer Zeile",
        "field.name": "Name",
        "field.value": "Wert",
        "action.addEmbed": "Embed hinzufügen ({count}/{limit})",
        "action.addField": "Feld hinzufügen",
        "action.cancel": "Abbrechen",
        "action.clear": "Leeren",
        "action.clearAll": "Neu anfangen",
        "action.close": "Schließen",
        "action.copyJson": "JSON kopieren",
        "action.duplicate": "Duplizieren",
        "action.moveUp": "Nach oben",
        "action.moveDown": "Nach unten",
        "action.now": "Jetzt",
        "action.removeEmbed": "Embed entfernen",
        "action.removeField": "Feld entfernen",
        "action.saveEdit": "Änderungen speichern",
        "action.send": "Senden",
        "action.sending": "Wird gesendet…",
        "preview.app": "APP",
        "preview.label": "Vorschau",
        "preview.today": "Heute um {time}",
        "import.button": "JSON importieren",
        "import.label": "Füge das JSON einer Webhook-Nachricht ein (auch von Discohook)",
        "import.load": "Laden",
        "edit.button": "Gesendete Nachricht bearbeiten",
        "edit.hint": "Rechtsklicke auf eine Nachricht des gewählten Webhooks und kopiere den Nachrichtenlink.",
        "edit.label": "Nachrichtenlink",
        "edit.load": "Öffnen",
        "edit.loading": "Wird geöffnet…",
        "edit.stop": "Stattdessen neu senden",
        "drafts.button": "Entwürfe",
        "drafts.title": "Gespeicherte Entwürfe",
        "drafts.save": "Diesen speichern",
        "drafts.none": "Noch keine gespeicherten Entwürfe.",
        "drafts.delete": "Entwurf löschen",
        "drafts.untitled": "Ohne Titel",
        "problem.tooLong": "{where} hat {length} Zeichen, höchstens {limit}",
        "problem.tooManyEmbeds": "Eine Nachricht hat höchstens {limit} Embeds",
        "problem.tooManyFields": "Ein Embed hat höchstens {limit} Felder",
        "problem.badUrl": "{where} ist kein Link, der mit https:// beginnt",
        "problem.badColor": "{where} ist keine Farbe wie #5865F2",
        "problem.badTimestamp": "{where} ist kein Datum",
        "problem.emptyEmbed": "{where} braucht einen Titel, Text, Autor, Fußzeile, Feld oder Bild",
        "problem.fieldNeedsBoth": "{where} braucht einen Namen und einen Wert",
        "problem.empty": "Schreib zuerst eine Nachricht oder fülle ein Embed aus",
        "problem.more": "und {count} weitere",
        "where.total": "Alle Embeds zusammen",
        "where.embed": "Embed {n}",
        "where.field": "Feld {n}",
        "where.content": "Die Nachricht",
        "where.username": "Der Name",
        "where.avatarUrl": "Die Avatar-URL",
        "where.title": "Titel",
        "where.description": "Beschreibung",
        "where.authorName": "Autorname",
        "where.authorUrl": "Autor-Link",
        "where.authorIcon": "Autor-Symbol",
        "where.url": "Titel-Link",
        "where.image": "Bild",
        "where.thumbnail": "Vorschaubild",
        "where.footerText": "Fußzeilentext",
        "where.footerIcon": "Fußzeilen-Symbol",
        "where.color": "Farbe",
        "where.timestamp": "Zeitstempel",
        "where.name": "Name",
        "where.value": "Wert",
        "error.noClient": "Discords API-Client wurde nicht gefunden",
        "error.createFailed": "Der Webhook konnte nicht erstellt werden",
        "error.loadWebhooks": "Die Webhooks dieses Kanals konnten nicht geladen werden",
        "error.rateLimited": "Discord bremst: versuche es in {seconds} s erneut",
        "error.notFound": "Dieser Webhook oder diese Nachricht existiert nicht mehr",
        "error.status": "Discord antwortete mit Fehler {status}",
        "error.pickWebhook": "Wähle zuerst einen Webhook oder erstelle einen neuen",
        "error.sendFailed": "Senden fehlgeschlagen",
        "error.badLink": "Das ist kein Discord-Nachrichtenlink",
        "error.loadMessage": "Die Nachricht konnte nicht geöffnet werden. Hat der gewählte Webhook sie gesendet?",
        "error.notJson": "Das ist kein gültiges JSON",
        "error.notMessage": "Dieses JSON ist keine Nachricht und kein Embed",
        "toast.copyFailed": "Kopieren fehlgeschlagen",
        "toast.edited": "Nachricht aktualisiert",
        "toast.sent": "An #{channel} gesendet",
        "toast.draftSaved": "Entwurf gespeichert",
        "toast.jsonCopied": "JSON kopiert",
    },
    es: {
        "menu.open": "Creador de embeds",
        "command.description": "Crea embeds y envíalos con un webhook en este canal",
        "dialog.title": "Creador de embeds",
        "dialog.subtitle": "Se envía a #{channel} con un webhook",
        "dialog.editing": "Editando un mensaje que envió el webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Cargando webhooks…",
        "webhook.none": "Este canal aún no tiene webhooks.",
        "webhook.create": "Nuevo webhook",
        "webhook.creating": "Creando…",
        "message.username": "Nombre",
        "message.avatar": "URL del avatar",
        "message.content": "Mensaje",
        "message.total": "{length} / {limit} caracteres en embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nombre del autor",
        "embed.authorUrl": "Enlace del autor",
        "embed.authorIcon": "URL del icono del autor",
        "embed.titleField": "Título",
        "embed.url": "Enlace del título",
        "embed.description": "Descripción",
        "embed.color": "Color",
        "embed.image": "URL de la imagen",
        "embed.thumbnail": "URL de la miniatura",
        "embed.footerText": "Texto del pie",
        "embed.footerIcon": "URL del icono del pie",
        "embed.timestamp": "Marca de tiempo",
        "group.author": "Autor",
        "group.body": "Cuerpo",
        "group.fields": "Campos ({count}/{limit})",
        "group.images": "Imágenes",
        "group.footer": "Pie",
        "field.title": "Campo {n}",
        "field.inline": "En línea",
        "field.name": "Nombre",
        "field.value": "Valor",
        "action.addEmbed": "Añadir embed ({count}/{limit})",
        "action.addField": "Añadir campo",
        "action.cancel": "Cancelar",
        "action.clear": "Borrar",
        "action.clearAll": "Empezar de nuevo",
        "action.close": "Cerrar",
        "action.copyJson": "Copiar JSON",
        "action.duplicate": "Duplicar",
        "action.moveUp": "Subir",
        "action.moveDown": "Bajar",
        "action.now": "Ahora",
        "action.removeEmbed": "Quitar embed",
        "action.removeField": "Quitar campo",
        "action.saveEdit": "Guardar cambios",
        "action.send": "Enviar",
        "action.sending": "Enviando…",
        "preview.app": "APP",
        "preview.label": "Vista previa",
        "preview.today": "Hoy a las {time}",
        "import.button": "Importar JSON",
        "import.label": "Pega el JSON de un mensaje de webhook (el de Discohook también sirve)",
        "import.load": "Cargar",
        "edit.button": "Editar un mensaje enviado",
        "edit.hint": "Haz clic derecho en un mensaje del webhook elegido y copia el enlace del mensaje.",
        "edit.label": "Enlace del mensaje",
        "edit.load": "Abrir",
        "edit.loading": "Abriendo…",
        "edit.stop": "Enviar como nuevo",
        "drafts.button": "Borradores",
        "drafts.title": "Borradores guardados",
        "drafts.save": "Guardar este",
        "drafts.none": "Aún no hay borradores guardados.",
        "drafts.delete": "Eliminar borrador",
        "drafts.untitled": "Sin título",
        "problem.tooLong": "{where} tiene {length} caracteres, como máximo {limit}",
        "problem.tooManyEmbeds": "Un mensaje admite como máximo {limit} embeds",
        "problem.tooManyFields": "Un embed admite como máximo {limit} campos",
        "problem.badUrl": "{where} no es un enlace que empiece por https://",
        "problem.badColor": "{where} no es un color como #5865F2",
        "problem.badTimestamp": "{where} no es una fecha",
        "problem.emptyEmbed": "{where} necesita un título, texto, autor, pie, campo o imagen",
        "problem.fieldNeedsBoth": "{where} necesita nombre y valor",
        "problem.empty": "Escribe un mensaje o rellena un embed primero",
        "problem.more": "y {count} más",
        "where.total": "Todos los embeds juntos",
        "where.embed": "Embed {n}",
        "where.field": "campo {n}",
        "where.content": "El mensaje",
        "where.username": "El nombre",
        "where.avatarUrl": "La URL del avatar",
        "where.title": "título",
        "where.description": "descripción",
        "where.authorName": "nombre del autor",
        "where.authorUrl": "enlace del autor",
        "where.authorIcon": "icono del autor",
        "where.url": "enlace del título",
        "where.image": "imagen",
        "where.thumbnail": "miniatura",
        "where.footerText": "texto del pie",
        "where.footerIcon": "icono del pie",
        "where.color": "color",
        "where.timestamp": "marca de tiempo",
        "where.name": "nombre",
        "where.value": "valor",
        "error.noClient": "No se encontró el cliente de API de Discord",
        "error.createFailed": "No se pudo crear el webhook",
        "error.loadWebhooks": "No se pudieron cargar los webhooks del canal",
        "error.rateLimited": "Discord pide ir más despacio: inténtalo en {seconds} s",
        "error.notFound": "Ese webhook o mensaje ya no existe",
        "error.status": "Discord respondió con el error {status}",
        "error.pickWebhook": "Elige un webhook o crea uno nuevo primero",
        "error.sendFailed": "No se pudo enviar",
        "error.badLink": "Eso no es un enlace a un mensaje de Discord",
        "error.loadMessage": "No se pudo abrir el mensaje. ¿Lo envió el webhook elegido?",
        "error.notJson": "Eso no es JSON válido",
        "error.notMessage": "Ese JSON no es un mensaje ni un embed",
        "toast.copyFailed": "No se pudo copiar",
        "toast.edited": "Mensaje actualizado",
        "toast.sent": "Enviado a #{channel}",
        "toast.draftSaved": "Borrador guardado",
        "toast.jsonCopied": "JSON copiado",
    },
    fr: {
        "menu.open": "Créateur d'embeds",
        "command.description": "Compose des embeds et envoie-les via un webhook dans ce salon",
        "dialog.title": "Créateur d'embeds",
        "dialog.subtitle": "Envoyé dans #{channel} via un webhook",
        "dialog.editing": "Modification d'un message envoyé par le webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Chargement des webhooks…",
        "webhook.none": "Ce salon n'a pas encore de webhook.",
        "webhook.create": "Nouveau webhook",
        "webhook.creating": "Création…",
        "message.username": "Nom",
        "message.avatar": "URL de l'avatar",
        "message.content": "Message",
        "message.total": "{length} / {limit} caractères dans les embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nom de l'auteur",
        "embed.authorUrl": "Lien de l'auteur",
        "embed.authorIcon": "URL de l'icône de l'auteur",
        "embed.titleField": "Titre",
        "embed.url": "Lien du titre",
        "embed.description": "Description",
        "embed.color": "Couleur",
        "embed.image": "URL de l'image",
        "embed.thumbnail": "URL de la miniature",
        "embed.footerText": "Texte du pied",
        "embed.footerIcon": "URL de l'icône du pied",
        "embed.timestamp": "Horodatage",
        "group.author": "Auteur",
        "group.body": "Corps",
        "group.fields": "Champs ({count}/{limit})",
        "group.images": "Images",
        "group.footer": "Pied",
        "field.title": "Champ {n}",
        "field.inline": "En ligne",
        "field.name": "Nom",
        "field.value": "Valeur",
        "action.addEmbed": "Ajouter un embed ({count}/{limit})",
        "action.addField": "Ajouter un champ",
        "action.cancel": "Annuler",
        "action.clear": "Effacer",
        "action.clearAll": "Recommencer",
        "action.close": "Fermer",
        "action.copyJson": "Copier le JSON",
        "action.duplicate": "Dupliquer",
        "action.moveUp": "Monter",
        "action.moveDown": "Descendre",
        "action.now": "Maintenant",
        "action.removeEmbed": "Retirer l'embed",
        "action.removeField": "Retirer le champ",
        "action.saveEdit": "Enregistrer",
        "action.send": "Envoyer",
        "action.sending": "Envoi…",
        "preview.app": "APP",
        "preview.label": "Aperçu",
        "preview.today": "Aujourd'hui à {time}",
        "import.button": "Importer du JSON",
        "import.label": "Colle le JSON d'un message de webhook (celui de Discohook marche aussi)",
        "import.load": "Charger",
        "edit.button": "Modifier un message envoyé",
        "edit.hint": "Fais un clic droit sur un message du webhook choisi et copie le lien du message.",
        "edit.label": "Lien du message",
        "edit.load": "Ouvrir",
        "edit.loading": "Ouverture…",
        "edit.stop": "Envoyer comme nouveau",
        "drafts.button": "Brouillons",
        "drafts.title": "Brouillons enregistrés",
        "drafts.save": "Enregistrer celui-ci",
        "drafts.none": "Aucun brouillon enregistré.",
        "drafts.delete": "Supprimer le brouillon",
        "drafts.untitled": "Sans titre",
        "problem.tooLong": "{where} fait {length} caractères, {limit} au plus",
        "problem.tooManyEmbeds": "Un message contient {limit} embeds au plus",
        "problem.tooManyFields": "Un embed contient {limit} champs au plus",
        "problem.badUrl": "{where} n'est pas un lien commençant par https://",
        "problem.badColor": "{where} n'est pas une couleur comme #5865F2",
        "problem.badTimestamp": "{where} n'est pas une date",
        "problem.emptyEmbed": "{where} a besoin d'un titre, d'un texte, d'un auteur, d'un pied, d'un champ ou d'une image",
        "problem.fieldNeedsBoth": "{where} a besoin d'un nom et d'une valeur",
        "problem.empty": "Écris d'abord un message ou remplis un embed",
        "problem.more": "et {count} de plus",
        "where.total": "Tous les embeds ensemble",
        "where.embed": "Embed {n}",
        "where.field": "champ {n}",
        "where.content": "Le message",
        "where.username": "Le nom",
        "where.avatarUrl": "L'URL de l'avatar",
        "where.title": "titre",
        "where.description": "description",
        "where.authorName": "nom de l'auteur",
        "where.authorUrl": "lien de l'auteur",
        "where.authorIcon": "icône de l'auteur",
        "where.url": "lien du titre",
        "where.image": "image",
        "where.thumbnail": "miniature",
        "where.footerText": "texte du pied",
        "where.footerIcon": "icône du pied",
        "where.color": "couleur",
        "where.timestamp": "horodatage",
        "where.name": "nom",
        "where.value": "valeur",
        "error.noClient": "Client API de Discord introuvable",
        "error.createFailed": "Impossible de créer le webhook",
        "error.loadWebhooks": "Impossible de charger les webhooks de ce salon",
        "error.rateLimited": "Discord demande de ralentir : réessaie dans {seconds} s",
        "error.notFound": "Ce webhook ou ce message n'existe plus",
        "error.status": "Discord a répondu avec l'erreur {status}",
        "error.pickWebhook": "Choisis d'abord un webhook ou crées-en un",
        "error.sendFailed": "Impossible de l'envoyer",
        "error.badLink": "Ce n'est pas un lien de message Discord",
        "error.loadMessage": "Impossible d'ouvrir ce message. A-t-il été envoyé par le webhook choisi ?",
        "error.notJson": "Ce n'est pas du JSON valide",
        "error.notMessage": "Ce JSON n'est ni un message ni un embed",
        "toast.copyFailed": "Impossible de copier",
        "toast.edited": "Message mis à jour",
        "toast.sent": "Envoyé dans #{channel}",
        "toast.draftSaved": "Brouillon enregistré",
        "toast.jsonCopied": "JSON copié",
    },
    ja: {
        "menu.open": "埋め込みビルダー",
        "command.description": "埋め込みを作成し、このチャンネルのWebhookで送信します",
        "dialog.title": "埋め込みビルダー",
        "dialog.subtitle": "Webhookで #{channel} に送信します",
        "dialog.editing": "Webhookが送信したメッセージを編集中",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhookを読み込み中…",
        "webhook.none": "このチャンネルにはまだWebhookがありません。",
        "webhook.create": "新しいWebhook",
        "webhook.creating": "作成中…",
        "message.username": "名前",
        "message.avatar": "アバターURL",
        "message.content": "メッセージ",
        "message.total": "埋め込み内の文字数 {length} / {limit}",
        "embed.title": "埋め込み {n}",
        "embed.authorName": "作成者名",
        "embed.authorUrl": "作成者のリンク",
        "embed.authorIcon": "作成者アイコンのURL",
        "embed.titleField": "タイトル",
        "embed.url": "タイトルのリンク",
        "embed.description": "説明",
        "embed.color": "色",
        "embed.image": "画像のURL",
        "embed.thumbnail": "サムネイルのURL",
        "embed.footerText": "フッターのテキスト",
        "embed.footerIcon": "フッターアイコンのURL",
        "embed.timestamp": "タイムスタンプ",
        "group.author": "作成者",
        "group.body": "本文",
        "group.fields": "フィールド ({count}/{limit})",
        "group.images": "画像",
        "group.footer": "フッター",
        "field.title": "フィールド {n}",
        "field.inline": "インライン",
        "field.name": "名前",
        "field.value": "値",
        "action.addEmbed": "埋め込みを追加 ({count}/{limit})",
        "action.addField": "フィールドを追加",
        "action.cancel": "キャンセル",
        "action.clear": "クリア",
        "action.clearAll": "最初からやり直す",
        "action.close": "閉じる",
        "action.copyJson": "JSONをコピー",
        "action.duplicate": "複製",
        "action.moveUp": "上へ移動",
        "action.moveDown": "下へ移動",
        "action.now": "現在",
        "action.removeEmbed": "埋め込みを削除",
        "action.removeField": "フィールドを削除",
        "action.saveEdit": "変更を保存",
        "action.send": "送信",
        "action.sending": "送信中…",
        "preview.app": "APP",
        "preview.label": "プレビュー",
        "preview.today": "今日 {time}",
        "import.button": "JSONを読み込む",
        "import.label": "WebhookメッセージのJSONを貼り付けてください(Discohookの形式も使えます)",
        "import.load": "読み込む",
        "edit.button": "送信済みメッセージを編集",
        "edit.hint": "選択したWebhookが送信したメッセージを右クリックして、メッセージリンクをコピーしてください。",
        "edit.label": "メッセージリンク",
        "edit.load": "開く",
        "edit.loading": "開いています…",
        "edit.stop": "新規として送信",
        "drafts.button": "下書き",
        "drafts.title": "保存した下書き",
        "drafts.save": "これを保存",
        "drafts.none": "保存した下書きはまだありません。",
        "drafts.delete": "下書きを削除",
        "drafts.untitled": "無題",
        "problem.tooLong": "{where} は {length} 文字です(最大 {limit})",
        "problem.tooManyEmbeds": "1つのメッセージに入る埋め込みは最大 {limit} 個です",
        "problem.tooManyFields": "1つの埋め込みに入るフィールドは最大 {limit} 個です",
        "problem.badUrl": "{where} が https:// で始まるリンクではありません",
        "problem.badColor": "{where} が #5865F2 のような色ではありません",
        "problem.badTimestamp": "{where} が日付ではありません",
        "problem.emptyEmbed": "{where} にはタイトル、本文、作成者、フッター、フィールド、画像のいずれかが必要です",
        "problem.fieldNeedsBoth": "{where} には名前と値の両方が必要です",
        "problem.empty": "先にメッセージを書くか、埋め込みを入力してください",
        "problem.more": "ほか {count} 件",
        "where.total": "すべての埋め込みの合計",
        "where.embed": "埋め込み {n}",
        "where.field": "フィールド {n}",
        "where.content": "メッセージ",
        "where.username": "名前",
        "where.avatarUrl": "アバターURL",
        "where.title": "タイトル",
        "where.description": "説明",
        "where.authorName": "作成者名",
        "where.authorUrl": "作成者のリンク",
        "where.authorIcon": "作成者アイコン",
        "where.url": "タイトルのリンク",
        "where.image": "画像",
        "where.thumbnail": "サムネイル",
        "where.footerText": "フッターのテキスト",
        "where.footerIcon": "フッターアイコン",
        "where.color": "色",
        "where.timestamp": "タイムスタンプ",
        "where.name": "名前",
        "where.value": "値",
        "error.noClient": "DiscordのAPIクライアントが見つかりませんでした",
        "error.createFailed": "Webhookを作成できませんでした",
        "error.loadWebhooks": "このチャンネルのWebhookを読み込めませんでした",
        "error.rateLimited": "Discordの送信制限中です。{seconds} 秒後にもう一度お試しください",
        "error.notFound": "そのWebhookまたはメッセージはもう存在しません",
        "error.status": "Discordがエラー {status} を返しました",
        "error.pickWebhook": "先にWebhookを選ぶか、新しく作成してください",
        "error.sendFailed": "送信できませんでした",
        "error.badLink": "Discordのメッセージリンクではありません",
        "error.loadMessage": "メッセージを開けませんでした。選択したWebhookが送信したものですか?",
        "error.notJson": "有効なJSONではありません",
        "error.notMessage": "そのJSONはメッセージでも埋め込みでもありません",
        "toast.copyFailed": "コピーできませんでした",
        "toast.edited": "メッセージを更新しました",
        "toast.sent": "#{channel} に送信しました",
        "toast.draftSaved": "下書きを保存しました",
        "toast.jsonCopied": "JSONをコピーしました",
    },
    pl: {
        "menu.open": "Kreator embedów",
        "command.description": "Twórz embedy i wysyłaj je webhookiem na tym kanale",
        "dialog.title": "Kreator embedów",
        "dialog.subtitle": "Wysyłane na #{channel} przez webhook",
        "dialog.editing": "Edytujesz wiadomość wysłaną przez webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Wczytywanie webhooków…",
        "webhook.none": "Ten kanał nie ma jeszcze webhooków.",
        "webhook.create": "Nowy webhook",
        "webhook.creating": "Tworzenie…",
        "message.username": "Nazwa",
        "message.avatar": "URL awatara",
        "message.content": "Wiadomość",
        "message.total": "{length} / {limit} znaków w embedach",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nazwa autora",
        "embed.authorUrl": "Link autora",
        "embed.authorIcon": "URL ikony autora",
        "embed.titleField": "Tytuł",
        "embed.url": "Link tytułu",
        "embed.description": "Opis",
        "embed.color": "Kolor",
        "embed.image": "URL obrazu",
        "embed.thumbnail": "URL miniatury",
        "embed.footerText": "Tekst stopki",
        "embed.footerIcon": "URL ikony stopki",
        "embed.timestamp": "Znacznik czasu",
        "group.author": "Autor",
        "group.body": "Treść",
        "group.fields": "Pola ({count}/{limit})",
        "group.images": "Obrazy",
        "group.footer": "Stopka",
        "field.title": "Pole {n}",
        "field.inline": "W linii",
        "field.name": "Nazwa",
        "field.value": "Wartość",
        "action.addEmbed": "Dodaj embed ({count}/{limit})",
        "action.addField": "Dodaj pole",
        "action.cancel": "Anuluj",
        "action.clear": "Wyczyść",
        "action.clearAll": "Zacznij od nowa",
        "action.close": "Zamknij",
        "action.copyJson": "Kopiuj JSON",
        "action.duplicate": "Duplikuj",
        "action.moveUp": "Przenieś w górę",
        "action.moveDown": "Przenieś w dół",
        "action.now": "Teraz",
        "action.removeEmbed": "Usuń embed",
        "action.removeField": "Usuń pole",
        "action.saveEdit": "Zapisz zmiany",
        "action.send": "Wyślij",
        "action.sending": "Wysyłanie…",
        "preview.app": "APP",
        "preview.label": "Podgląd",
        "preview.today": "Dziś o {time}",
        "import.button": "Importuj JSON",
        "import.label": "Wklej JSON wiadomości webhooka (z Discohooka też działa)",
        "import.load": "Wczytaj",
        "edit.button": "Edytuj wysłaną wiadomość",
        "edit.hint": "Kliknij prawym przyciskiem wiadomość wybranego webhooka i skopiuj link do wiadomości.",
        "edit.label": "Link do wiadomości",
        "edit.load": "Otwórz",
        "edit.loading": "Otwieranie…",
        "edit.stop": "Wyślij jako nową",
        "drafts.button": "Szkice",
        "drafts.title": "Zapisane szkice",
        "drafts.save": "Zapisz ten",
        "drafts.none": "Brak zapisanych szkiców.",
        "drafts.delete": "Usuń szkic",
        "drafts.untitled": "Bez tytułu",
        "problem.tooLong": "{where} ma {length} znaków, maksymalnie {limit}",
        "problem.tooManyEmbeds": "Wiadomość może mieć maksymalnie {limit} embedów",
        "problem.tooManyFields": "Embed może mieć maksymalnie {limit} pól",
        "problem.badUrl": "{where} nie jest linkiem zaczynającym się od https://",
        "problem.badColor": "{where} nie jest kolorem w stylu #5865F2",
        "problem.badTimestamp": "{where} nie jest datą",
        "problem.emptyEmbed": "{where} potrzebuje tytułu, tekstu, autora, stopki, pola lub obrazu",
        "problem.fieldNeedsBoth": "{where} potrzebuje nazwy i wartości",
        "problem.empty": "Najpierw napisz wiadomość albo wypełnij embed",
        "problem.more": "i {count} więcej",
        "where.total": "Wszystkie embedy razem",
        "where.embed": "Embed {n}",
        "where.field": "pole {n}",
        "where.content": "Wiadomość",
        "where.username": "Nazwa",
        "where.avatarUrl": "URL awatara",
        "where.title": "tytuł",
        "where.description": "opis",
        "where.authorName": "nazwa autora",
        "where.authorUrl": "link autora",
        "where.authorIcon": "ikona autora",
        "where.url": "link tytułu",
        "where.image": "obraz",
        "where.thumbnail": "miniatura",
        "where.footerText": "tekst stopki",
        "where.footerIcon": "ikona stopki",
        "where.color": "kolor",
        "where.timestamp": "znacznik czasu",
        "where.name": "nazwa",
        "where.value": "wartość",
        "error.noClient": "Nie znaleziono klienta API Discorda",
        "error.createFailed": "Nie udało się utworzyć webhooka",
        "error.loadWebhooks": "Nie udało się wczytać webhooków kanału",
        "error.rateLimited": "Discord prosi o wolniejsze tempo: spróbuj za {seconds} s",
        "error.notFound": "Ten webhook lub wiadomość już nie istnieje",
        "error.status": "Discord odpowiedział błędem {status}",
        "error.pickWebhook": "Najpierw wybierz webhook albo utwórz nowy",
        "error.sendFailed": "Nie udało się wysłać",
        "error.badLink": "To nie jest link do wiadomości na Discordzie",
        "error.loadMessage": "Nie udało się otworzyć wiadomości. Czy wysłał ją wybrany webhook?",
        "error.notJson": "To nie jest poprawny JSON",
        "error.notMessage": "Ten JSON nie jest wiadomością ani embedem",
        "toast.copyFailed": "Nie udało się skopiować",
        "toast.edited": "Wiadomość zaktualizowana",
        "toast.sent": "Wysłano na #{channel}",
        "toast.draftSaved": "Szkic zapisany",
        "toast.jsonCopied": "Skopiowano JSON",
    },
    "pt-BR": {
        "menu.open": "Criador de embeds",
        "command.description": "Crie embeds e envie por um webhook neste canal",
        "dialog.title": "Criador de embeds",
        "dialog.subtitle": "Enviado para #{channel} por um webhook",
        "dialog.editing": "Editando uma mensagem enviada pelo webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Carregando webhooks…",
        "webhook.none": "Este canal ainda não tem webhooks.",
        "webhook.create": "Novo webhook",
        "webhook.creating": "Criando…",
        "message.username": "Nome",
        "message.avatar": "URL do avatar",
        "message.content": "Mensagem",
        "message.total": "{length} / {limit} caracteres nos embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nome do autor",
        "embed.authorUrl": "Link do autor",
        "embed.authorIcon": "URL do ícone do autor",
        "embed.titleField": "Título",
        "embed.url": "Link do título",
        "embed.description": "Descrição",
        "embed.color": "Cor",
        "embed.image": "URL da imagem",
        "embed.thumbnail": "URL da miniatura",
        "embed.footerText": "Texto do rodapé",
        "embed.footerIcon": "URL do ícone do rodapé",
        "embed.timestamp": "Data e hora",
        "group.author": "Autor",
        "group.body": "Corpo",
        "group.fields": "Campos ({count}/{limit})",
        "group.images": "Imagens",
        "group.footer": "Rodapé",
        "field.title": "Campo {n}",
        "field.inline": "Em linha",
        "field.name": "Nome",
        "field.value": "Valor",
        "action.addEmbed": "Adicionar embed ({count}/{limit})",
        "action.addField": "Adicionar campo",
        "action.cancel": "Cancelar",
        "action.clear": "Limpar",
        "action.clearAll": "Recomeçar",
        "action.close": "Fechar",
        "action.copyJson": "Copiar JSON",
        "action.duplicate": "Duplicar",
        "action.moveUp": "Mover para cima",
        "action.moveDown": "Mover para baixo",
        "action.now": "Agora",
        "action.removeEmbed": "Remover embed",
        "action.removeField": "Remover campo",
        "action.saveEdit": "Salvar alterações",
        "action.send": "Enviar",
        "action.sending": "Enviando…",
        "preview.app": "APP",
        "preview.label": "Prévia",
        "preview.today": "Hoje às {time}",
        "import.button": "Importar JSON",
        "import.label": "Cole o JSON de uma mensagem de webhook (o do Discohook também serve)",
        "import.load": "Carregar",
        "edit.button": "Editar uma mensagem enviada",
        "edit.hint": "Clique com o botão direito numa mensagem do webhook escolhido e copie o link da mensagem.",
        "edit.label": "Link da mensagem",
        "edit.load": "Abrir",
        "edit.loading": "Abrindo…",
        "edit.stop": "Enviar como nova",
        "drafts.button": "Rascunhos",
        "drafts.title": "Rascunhos salvos",
        "drafts.save": "Salvar este",
        "drafts.none": "Nenhum rascunho salvo ainda.",
        "drafts.delete": "Excluir rascunho",
        "drafts.untitled": "Sem título",
        "problem.tooLong": "{where} tem {length} caracteres, no máximo {limit}",
        "problem.tooManyEmbeds": "Uma mensagem tem no máximo {limit} embeds",
        "problem.tooManyFields": "Um embed tem no máximo {limit} campos",
        "problem.badUrl": "{where} não é um link que começa com https://",
        "problem.badColor": "{where} não é uma cor como #5865F2",
        "problem.badTimestamp": "{where} não é uma data",
        "problem.emptyEmbed": "{where} precisa de título, texto, autor, rodapé, campo ou imagem",
        "problem.fieldNeedsBoth": "{where} precisa de nome e valor",
        "problem.empty": "Escreva uma mensagem ou preencha um embed primeiro",
        "problem.more": "e mais {count}",
        "where.total": "Todos os embeds juntos",
        "where.embed": "Embed {n}",
        "where.field": "campo {n}",
        "where.content": "A mensagem",
        "where.username": "O nome",
        "where.avatarUrl": "A URL do avatar",
        "where.title": "título",
        "where.description": "descrição",
        "where.authorName": "nome do autor",
        "where.authorUrl": "link do autor",
        "where.authorIcon": "ícone do autor",
        "where.url": "link do título",
        "where.image": "imagem",
        "where.thumbnail": "miniatura",
        "where.footerText": "texto do rodapé",
        "where.footerIcon": "ícone do rodapé",
        "where.color": "cor",
        "where.timestamp": "data e hora",
        "where.name": "nome",
        "where.value": "valor",
        "error.noClient": "O cliente de API do Discord não foi encontrado",
        "error.createFailed": "Não foi possível criar o webhook",
        "error.loadWebhooks": "Não foi possível carregar os webhooks do canal",
        "error.rateLimited": "O Discord pediu calma: tente de novo em {seconds} s",
        "error.notFound": "Esse webhook ou mensagem não existe mais",
        "error.status": "O Discord respondeu com o erro {status}",
        "error.pickWebhook": "Escolha um webhook ou crie um novo primeiro",
        "error.sendFailed": "Não foi possível enviar",
        "error.badLink": "Isso não é um link de mensagem do Discord",
        "error.loadMessage": "Não foi possível abrir a mensagem. Ela foi enviada pelo webhook escolhido?",
        "error.notJson": "Isso não é um JSON válido",
        "error.notMessage": "Esse JSON não é uma mensagem nem um embed",
        "toast.copyFailed": "Não foi possível copiar",
        "toast.edited": "Mensagem atualizada",
        "toast.sent": "Enviado para #{channel}",
        "toast.draftSaved": "Rascunho salvo",
        "toast.jsonCopied": "JSON copiado",
    },
    ru: {
        "menu.open": "Конструктор эмбедов",
        "command.description": "Создавайте эмбеды и отправляйте их через вебхук в этом канале",
        "dialog.title": "Конструктор эмбедов",
        "dialog.subtitle": "Отправка в #{channel} через вебхук",
        "dialog.editing": "Редактирование сообщения, отправленного вебхуком",
        "webhook.label": "Вебхук",
        "webhook.loading": "Загрузка вебхуков…",
        "webhook.none": "У этого канала пока нет вебхуков.",
        "webhook.create": "Новый вебхук",
        "webhook.creating": "Создание…",
        "message.username": "Имя",
        "message.avatar": "URL аватара",
        "message.content": "Сообщение",
        "message.total": "{length} / {limit} символов в эмбедах",
        "embed.title": "Эмбед {n}",
        "embed.authorName": "Имя автора",
        "embed.authorUrl": "Ссылка автора",
        "embed.authorIcon": "URL значка автора",
        "embed.titleField": "Заголовок",
        "embed.url": "Ссылка заголовка",
        "embed.description": "Описание",
        "embed.color": "Цвет",
        "embed.image": "URL изображения",
        "embed.thumbnail": "URL миниатюры",
        "embed.footerText": "Текст подвала",
        "embed.footerIcon": "URL значка подвала",
        "embed.timestamp": "Отметка времени",
        "group.author": "Автор",
        "group.body": "Основное",
        "group.fields": "Поля ({count}/{limit})",
        "group.images": "Изображения",
        "group.footer": "Подвал",
        "field.title": "Поле {n}",
        "field.inline": "В строку",
        "field.name": "Название",
        "field.value": "Значение",
        "action.addEmbed": "Добавить эмбед ({count}/{limit})",
        "action.addField": "Добавить поле",
        "action.cancel": "Отмена",
        "action.clear": "Очистить",
        "action.clearAll": "Начать заново",
        "action.close": "Закрыть",
        "action.copyJson": "Копировать JSON",
        "action.duplicate": "Дублировать",
        "action.moveUp": "Переместить вверх",
        "action.moveDown": "Переместить вниз",
        "action.now": "Сейчас",
        "action.removeEmbed": "Удалить эмбед",
        "action.removeField": "Удалить поле",
        "action.saveEdit": "Сохранить изменения",
        "action.send": "Отправить",
        "action.sending": "Отправка…",
        "preview.app": "APP",
        "preview.label": "Предпросмотр",
        "preview.today": "Сегодня в {time}",
        "import.button": "Импорт JSON",
        "import.label": "Вставьте JSON сообщения вебхука (формат Discohook тоже подходит)",
        "import.load": "Загрузить",
        "edit.button": "Изменить отправленное сообщение",
        "edit.hint": "Нажмите правой кнопкой на сообщение выбранного вебхука и скопируйте ссылку на сообщение.",
        "edit.label": "Ссылка на сообщение",
        "edit.load": "Открыть",
        "edit.loading": "Открытие…",
        "edit.stop": "Отправить как новое",
        "drafts.button": "Черновики",
        "drafts.title": "Сохранённые черновики",
        "drafts.save": "Сохранить этот",
        "drafts.none": "Сохранённых черновиков пока нет.",
        "drafts.delete": "Удалить черновик",
        "drafts.untitled": "Без названия",
        "problem.tooLong": "{where}: {length} символов, максимум {limit}",
        "problem.tooManyEmbeds": "В сообщении не больше {limit} эмбедов",
        "problem.tooManyFields": "В эмбеде не больше {limit} полей",
        "problem.badUrl": "{where}: это не ссылка, начинающаяся с https://",
        "problem.badColor": "{where}: это не цвет вида #5865F2",
        "problem.badTimestamp": "{where}: это не дата",
        "problem.emptyEmbed": "{where}: нужен заголовок, текст, автор, подвал, поле или изображение",
        "problem.fieldNeedsBoth": "{where}: нужны и название, и значение",
        "problem.empty": "Сначала напишите сообщение или заполните эмбед",
        "problem.more": "и ещё {count}",
        "where.total": "Все эмбеды вместе",
        "where.embed": "Эмбед {n}",
        "where.field": "поле {n}",
        "where.content": "Сообщение",
        "where.username": "Имя",
        "where.avatarUrl": "URL аватара",
        "where.title": "заголовок",
        "where.description": "описание",
        "where.authorName": "имя автора",
        "where.authorUrl": "ссылка автора",
        "where.authorIcon": "значок автора",
        "where.url": "ссылка заголовка",
        "where.image": "изображение",
        "where.thumbnail": "миниатюра",
        "where.footerText": "текст подвала",
        "where.footerIcon": "значок подвала",
        "where.color": "цвет",
        "where.timestamp": "отметка времени",
        "where.name": "название",
        "where.value": "значение",
        "error.noClient": "Не удалось найти API-клиент Discord",
        "error.createFailed": "Не удалось создать вебхук",
        "error.loadWebhooks": "Не удалось загрузить вебхуки канала",
        "error.rateLimited": "Discord просит подождать: попробуйте через {seconds} с",
        "error.notFound": "Этот вебхук или сообщение больше не существует",
        "error.status": "Discord вернул ошибку {status}",
        "error.pickWebhook": "Сначала выберите вебхук или создайте новый",
        "error.sendFailed": "Не удалось отправить",
        "error.badLink": "Это не ссылка на сообщение Discord",
        "error.loadMessage": "Не удалось открыть сообщение. Его отправил выбранный вебхук?",
        "error.notJson": "Это не корректный JSON",
        "error.notMessage": "Этот JSON не является сообщением или эмбедом",
        "toast.copyFailed": "Не удалось скопировать",
        "toast.edited": "Сообщение обновлено",
        "toast.sent": "Отправлено в #{channel}",
        "toast.draftSaved": "Черновик сохранён",
        "toast.jsonCopied": "JSON скопирован",
    },
    tr: {
        "menu.open": "Embed Oluşturucu",
        "command.description": "Embed oluştur ve bu kanalda bir webhook ile gönder",
        "dialog.title": "Embed Oluşturucu",
        "dialog.subtitle": "Bir webhook ile #{channel} kanalına gönderilir",
        "dialog.editing": "Webhook'un gönderdiği bir mesajı düzenliyorsun",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhook'lar yükleniyor…",
        "webhook.none": "Bu kanalda henüz webhook yok.",
        "webhook.create": "Yeni webhook",
        "webhook.creating": "Oluşturuluyor…",
        "message.username": "Ad",
        "message.avatar": "Avatar URL'si",
        "message.content": "Mesaj",
        "message.total": "Embed'lerde {length} / {limit} karakter",
        "embed.title": "Embed {n}",
        "embed.authorName": "Yazar adı",
        "embed.authorUrl": "Yazar bağlantısı",
        "embed.authorIcon": "Yazar simgesi URL'si",
        "embed.titleField": "Başlık",
        "embed.url": "Başlık bağlantısı",
        "embed.description": "Açıklama",
        "embed.color": "Renk",
        "embed.image": "Görsel URL'si",
        "embed.thumbnail": "Küçük resim URL'si",
        "embed.footerText": "Alt bilgi metni",
        "embed.footerIcon": "Alt bilgi simgesi URL'si",
        "embed.timestamp": "Zaman damgası",
        "group.author": "Yazar",
        "group.body": "Gövde",
        "group.fields": "Alanlar ({count}/{limit})",
        "group.images": "Görseller",
        "group.footer": "Alt bilgi",
        "field.title": "Alan {n}",
        "field.inline": "Satır içi",
        "field.name": "Ad",
        "field.value": "Değer",
        "action.addEmbed": "Embed ekle ({count}/{limit})",
        "action.addField": "Alan ekle",
        "action.cancel": "İptal",
        "action.clear": "Temizle",
        "action.clearAll": "Baştan başla",
        "action.close": "Kapat",
        "action.copyJson": "JSON'u kopyala",
        "action.duplicate": "Çoğalt",
        "action.moveUp": "Yukarı taşı",
        "action.moveDown": "Aşağı taşı",
        "action.now": "Şimdi",
        "action.removeEmbed": "Embed'i kaldır",
        "action.removeField": "Alanı kaldır",
        "action.saveEdit": "Değişiklikleri kaydet",
        "action.send": "Gönder",
        "action.sending": "Gönderiliyor…",
        "preview.app": "APP",
        "preview.label": "Önizleme",
        "preview.today": "Bugün {time}",
        "import.button": "JSON içe aktar",
        "import.label": "Bir webhook mesajının JSON'unu yapıştır (Discohook'unki de olur)",
        "import.load": "Yükle",
        "edit.button": "Gönderilmiş bir mesajı düzenle",
        "edit.hint": "Seçili webhook'un gönderdiği bir mesaja sağ tıkla ve Mesaj Bağlantısını Kopyala'yı seç.",
        "edit.label": "Mesaj bağlantısı",
        "edit.load": "Aç",
        "edit.loading": "Açılıyor…",
        "edit.stop": "Yeni olarak gönder",
        "drafts.button": "Taslaklar",
        "drafts.title": "Kayıtlı taslaklar",
        "drafts.save": "Bunu kaydet",
        "drafts.none": "Henüz kayıtlı taslak yok.",
        "drafts.delete": "Taslağı sil",
        "drafts.untitled": "Başlıksız",
        "problem.tooLong": "{where} {length} karakter, en fazla {limit}",
        "problem.tooManyEmbeds": "Bir mesajda en fazla {limit} embed olabilir",
        "problem.tooManyFields": "Bir embed'de en fazla {limit} alan olabilir",
        "problem.badUrl": "{where} https:// ile başlayan bir bağlantı değil",
        "problem.badColor": "{where} #5865F2 gibi bir renk değil",
        "problem.badTimestamp": "{where} bir tarih değil",
        "problem.emptyEmbed": "{where} için başlık, metin, yazar, alt bilgi, alan ya da görsel gerekli",
        "problem.fieldNeedsBoth": "{where} için hem ad hem değer gerekli",
        "problem.empty": "Önce bir mesaj yaz ya da bir embed doldur",
        "problem.more": "ve {count} tane daha",
        "where.total": "Tüm embed'ler birlikte",
        "where.embed": "Embed {n}",
        "where.field": "alan {n}",
        "where.content": "Mesaj",
        "where.username": "Ad",
        "where.avatarUrl": "Avatar URL'si",
        "where.title": "başlık",
        "where.description": "açıklama",
        "where.authorName": "yazar adı",
        "where.authorUrl": "yazar bağlantısı",
        "where.authorIcon": "yazar simgesi",
        "where.url": "başlık bağlantısı",
        "where.image": "görsel",
        "where.thumbnail": "küçük resim",
        "where.footerText": "alt bilgi metni",
        "where.footerIcon": "alt bilgi simgesi",
        "where.color": "renk",
        "where.timestamp": "zaman damgası",
        "where.name": "ad",
        "where.value": "değer",
        "error.noClient": "Discord'un API istemcisi bulunamadı",
        "error.createFailed": "Webhook oluşturulamadı",
        "error.loadWebhooks": "Bu kanalın webhook'ları yüklenemedi",
        "error.rateLimited": "Discord yavaşla diyor: {seconds} sn sonra tekrar dene",
        "error.notFound": "Bu webhook ya da mesaj artık yok",
        "error.status": "Discord {status} hatasıyla yanıt verdi",
        "error.pickWebhook": "Önce bir webhook seç ya da yenisini oluştur",
        "error.sendFailed": "Gönderilemedi",
        "error.badLink": "Bu bir Discord mesaj bağlantısı değil",
        "error.loadMessage": "Mesaj açılamadı. Seçili webhook mu göndermişti?",
        "error.notJson": "Bu geçerli bir JSON değil",
        "error.notMessage": "Bu JSON bir mesaj ya da embed değil",
        "toast.copyFailed": "Kopyalanamadı",
        "toast.edited": "Mesaj güncellendi",
        "toast.sent": "#{channel} kanalına gönderildi",
        "toast.draftSaved": "Taslak kaydedildi",
        "toast.jsonCopied": "JSON kopyalandı",
    },
});
