import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "menu.open": "Embed Builder",
        "command.description": "Compose embeds and send them through a webhook in this channel",
        "dialog.title": "Embed Builder",
        "dialog.subtitle": "Sends to #{channel} through a webhook",
        "dialog.editing": "Editing a message the webhook sent",
        "webhook.label": "Webhook",
        "webhook.loading": "Loading webhooks…",
        "webhook.none": "This channel has no webhooks yet.",
        "webhook.create": "New webhook",
        "webhook.creating": "Creating…",
        "message.username": "Name",
        "message.avatar": "Avatar URL",
        "message.content": "Message",
        "message.total": "{length} / {limit} characters in embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Author name",
        "embed.authorUrl": "Author link",
        "embed.authorIcon": "Author icon URL",
        "embed.titleField": "Title",
        "embed.url": "Title link",
        "embed.description": "Description",
        "embed.color": "Colour",
        "embed.image": "Image URL",
        "embed.thumbnail": "Thumbnail URL",
        "embed.footerText": "Footer text",
        "embed.footerIcon": "Footer icon URL",
        "embed.timestamp": "Timestamp",
        "group.author": "Author",
        "group.body": "Body",
        "group.fields": "Fields ({count}/{limit})",
        "group.images": "Images",
        "group.footer": "Footer",
        "field.title": "Field {n}",
        "field.inline": "Inline",
        "field.name": "Name",
        "field.value": "Value",
        "action.addEmbed": "Add embed ({count}/{limit})",
        "action.addField": "Add field",
        "action.cancel": "Cancel",
        "action.clear": "Clear",
        "action.clearAll": "Start over",
        "action.close": "Close",
        "action.copyJson": "Copy JSON",
        "action.duplicate": "Duplicate",
        "action.moveUp": "Move up",
        "action.moveDown": "Move down",
        "action.now": "Now",
        "action.removeEmbed": "Remove embed",
        "action.removeField": "Remove field",
        "action.saveEdit": "Save changes",
        "action.send": "Send",
        "action.sending": "Sending…",
        "preview.app": "APP",
        "preview.label": "Preview",
        "preview.today": "Today at {time}",
        "import.button": "Import JSON",
        "import.label": "Paste a webhook message's JSON (Discohook's works too)",
        "import.load": "Load",
        "edit.button": "Edit a sent message",
        "edit.hint": "Right-click a message the selected webhook sent and Copy Message Link.",
        "edit.label": "Message link",
        "edit.load": "Open",
        "edit.loading": "Opening…",
        "edit.stop": "Send as new instead",
        "drafts.button": "Drafts",
        "drafts.title": "Saved drafts",
        "drafts.save": "Save this one",
        "drafts.none": "No saved drafts yet.",
        "drafts.delete": "Delete draft",
        "drafts.untitled": "Untitled",
        "problem.tooLong": "{where} is {length} characters, {limit} at most",
        "problem.tooManyEmbeds": "A message holds {limit} embeds at most",
        "problem.tooManyFields": "An embed holds {limit} fields at most",
        "problem.badUrl": "{where} isn't a link starting with https://",
        "problem.badColor": "{where} isn't a colour like #5865F2",
        "problem.badTimestamp": "{where} isn't a date",
        "problem.emptyEmbed": "{where} needs a title, text, author, footer, field or image",
        "problem.fieldNeedsBoth": "{where} needs both a name and a value",
        "problem.empty": "There's nothing to send yet",
        "problem.more": "and {count} more",
        "where.total": "All embeds together",
        "where.embed": "Embed {n}",
        "where.field": "field {n}",
        "where.content": "The message",
        "where.username": "The name",
        "where.avatarUrl": "The avatar URL",
        "where.title": "title",
        "where.description": "description",
        "where.authorName": "author name",
        "where.authorUrl": "author link",
        "where.authorIcon": "author icon",
        "where.url": "title link",
        "where.image": "image",
        "where.thumbnail": "thumbnail",
        "where.footerText": "footer text",
        "where.footerIcon": "footer icon",
        "where.color": "colour",
        "where.timestamp": "timestamp",
        "where.name": "name",
        "where.value": "value",
        "error.noClient": "Couldn't find Discord's API client",
        "error.createFailed": "Couldn't create the webhook",
        "error.loadWebhooks": "Couldn't load this channel's webhooks",
        "error.rateLimited": "Discord says slow down: try again in {seconds} s",
        "error.notFound": "That webhook or message no longer exists",
        "error.status": "Discord answered with error {status}",
        "error.pickWebhook": "Pick a webhook or make a new one first",
        "error.sendFailed": "Couldn't send it",
        "error.badLink": "That isn't a Discord message link",
        "error.loadMessage": "Couldn't open that message. Was it sent by the selected webhook?",
        "error.notJson": "That isn't valid JSON",
        "error.notMessage": "That JSON isn't a message or an embed",
        "toast.copyFailed": "Couldn't copy",
        "toast.edited": "Message updated",
        "toast.sent": "Sent to #{channel}",
        "toast.draftSaved": "Draft saved",
        "toast.jsonCopied": "JSON copied",
        "mode.label": "Message type",
        "mode.classic": "Classic",
        "mode.v2": "Components V2",
        "mode.locked": "A sent message keeps its type",
        "mode.v2Hint": "Build the message from blocks: text, sections, galleries, files and containers. Webhooks can use link buttons only; buttons that do something and menus need a bot.",
        "section.sender": "Sender",
        "section.files": "Files",
        "section.sendAs": "Send as",
        "webhook.auto": "Sending makes a webhook named Evi Embeds in this channel.",
        "json.button": "JSON",
        "files.add": "Add files",
        "files.hint": "Use them in pictures and File components, or as attachment://name.",
        "files.remove": "Remove file",
        "files.copyRef": "Copy attachment:// link",
        "files.kept": "Already on the message",
        "kind.text": "Text",
        "kind.section": "Section",
        "kind.gallery": "Media gallery",
        "kind.separator": "Separator",
        "kind.file": "File",
        "kind.buttons": "Link buttons",
        "kind.container": "Container",
        "kindHint.text": "Text with markdown, mentions and emoji",
        "kindHint.section": "Up to 3 texts with a thumbnail or a link button beside them",
        "kindHint.gallery": "1 to 10 pictures or videos in a grid",
        "kindHint.separator": "Space between components, with or without a line",
        "kindHint.file": "One of the files sent with the message",
        "kindHint.buttons": "Up to 5 buttons that open links",
        "kindHint.container": "A box with an accent colour around other components",
        "add.component": "Add a component",
        "add.toContainer": "Add inside",
        "comp.content": "Text",
        "comp.markdownHint": "Markdown works: **bold**, # headings, -# small text, [links](https://…)",
        "comp.sectionText": "Text {n}",
        "comp.addText": "Add text",
        "comp.removeText": "Remove text",
        "comp.accessory": "Beside the text",
        "comp.accessoryThumbnail": "Thumbnail",
        "comp.accessoryButton": "Link button",
        "comp.thumbnailUrl": "Thumbnail link",
        "comp.mediaUrl": "Picture or video link",
        "comp.useFile": "Use a file",
        "comp.alt": "Description (alt text)",
        "comp.spoiler": "Mark as spoiler",
        "comp.item": "Picture {n}",
        "comp.addItem": "Add picture ({count}/{limit})",
        "comp.removeItem": "Remove picture",
        "comp.divider": "Show a line",
        "comp.spacing": "Spacing",
        "comp.spacingSmall": "Small",
        "comp.spacingLarge": "Large",
        "comp.fileName": "File",
        "comp.filePick": "Pick a file",
        "comp.fileNone": "Add a file under Files below first.",
        "comp.buttonsNote": "Webhooks can only send buttons that open a link.",
        "comp.button": "Button {n}",
        "comp.label": "Label",
        "comp.link": "Link",
        "comp.emoji": "Emoji",
        "comp.addButton": "Add button ({count}/{limit})",
        "comp.removeButton": "Remove button",
        "comp.accent": "Accent colour",
        "comp.inside": "Inside",
        "comp.emptyContainer": "Nothing inside yet.",
        "comp.remove": "Remove component",
        "summary.pictures": "Pictures: {count}",
        "summary.inside": "Inside: {count}",
        "summary.line": "Line",
        "summary.space": "Space",
        "color.none": "No colour",
        "color.custom": "Pick any colour",
        "color.swatch": "Colour {hex}",
        "meter.components": "Components",
        "meter.text": "Text",
        "meter.embedText": "Text in embeds",
        "message.embedChars": "Characters in this embed",
        "preview.empty": "Your message shows here as you build it",
        "preview.spoiler": "Spoiler",
        "empty.v2": "No components yet. Pick one below to start.",
        "problem.emptyComponent": "{where} is empty",
        "problem.buttonNeedsLabel": "{where} needs a label or an emoji",
        "problem.noAttachment": "{where} uses {name}, which isn't among the files",
        "problem.tooManyComponents": "A message holds {limit} components at most (this one has {count})",
        "problem.tooManyFiles": "A message holds {limit} files at most",
        "problem.one": "1 problem",
        "problem.count": "{count} problems",
        "where.component": "Component {n}",
        "where.child": "item {n}",
        "where.text": "text {n}",
        "where.item": "picture {n}",
        "where.button": "button {n}",
        "where.accessory": "the thumbnail or button",
        "where.media": "link",
        "where.alt": "description",
        "where.label": "label",
        "where.link": "link",
        "where.componentText": "All text together",
        "toast.skipped": "Interactive components left out, webhooks can't send them: {count}",
        "toast.refCopied": "attachment:// link copied",
        "error.tooBig": "These files are too big for this server",
        "action.sendShortcut": "Send (Ctrl+Enter)",
    },
    de: {
        "menu.open": "Embed-Builder",
        "command.description": "Embeds erstellen und über einen Webhook in diesem Kanal senden",
        "dialog.title": "Embed-Builder",
        "dialog.subtitle": "Wird über einen Webhook in #{channel} gesendet",
        "dialog.editing": "Du bearbeitest eine Nachricht des Webhooks",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhooks werden geladen…",
        "webhook.none": "Dieser Kanal hat noch keine Webhooks.",
        "webhook.create": "Neuer Webhook",
        "webhook.creating": "Wird erstellt…",
        "message.username": "Name",
        "message.avatar": "Avatar-URL",
        "message.content": "Nachricht",
        "message.total": "{length} / {limit} Zeichen in Embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Autorname",
        "embed.authorUrl": "Autor-Link",
        "embed.authorIcon": "Autor-Symbol-URL",
        "embed.titleField": "Titel",
        "embed.url": "Titel-Link",
        "embed.description": "Beschreibung",
        "embed.color": "Farbe",
        "embed.image": "Bild-URL",
        "embed.thumbnail": "Vorschaubild-URL",
        "embed.footerText": "Fußzeilentext",
        "embed.footerIcon": "Fußzeilen-Symbol-URL",
        "embed.timestamp": "Zeitstempel",
        "group.author": "Autor",
        "group.body": "Inhalt",
        "group.fields": "Felder ({count}/{limit})",
        "group.images": "Bilder",
        "group.footer": "Fußzeile",
        "field.title": "Feld {n}",
        "field.inline": "In einer Zeile",
        "field.name": "Name",
        "field.value": "Wert",
        "action.addEmbed": "Embed hinzufügen ({count}/{limit})",
        "action.addField": "Feld hinzufügen",
        "action.cancel": "Abbrechen",
        "action.clear": "Leeren",
        "action.clearAll": "Neu anfangen",
        "action.close": "Schließen",
        "action.copyJson": "JSON kopieren",
        "action.duplicate": "Duplizieren",
        "action.moveUp": "Nach oben",
        "action.moveDown": "Nach unten",
        "action.now": "Jetzt",
        "action.removeEmbed": "Embed entfernen",
        "action.removeField": "Feld entfernen",
        "action.saveEdit": "Änderungen speichern",
        "action.send": "Senden",
        "action.sending": "Wird gesendet…",
        "preview.app": "APP",
        "preview.label": "Vorschau",
        "preview.today": "Heute um {time}",
        "import.button": "JSON importieren",
        "import.label": "Füge das JSON einer Webhook-Nachricht ein (auch von Discohook)",
        "import.load": "Laden",
        "edit.button": "Gesendete Nachricht bearbeiten",
        "edit.hint": "Rechtsklicke auf eine Nachricht des gewählten Webhooks und kopiere den Nachrichtenlink.",
        "edit.label": "Nachrichtenlink",
        "edit.load": "Öffnen",
        "edit.loading": "Wird geöffnet…",
        "edit.stop": "Stattdessen neu senden",
        "drafts.button": "Entwürfe",
        "drafts.title": "Gespeicherte Entwürfe",
        "drafts.save": "Diesen speichern",
        "drafts.none": "Noch keine gespeicherten Entwürfe.",
        "drafts.delete": "Entwurf löschen",
        "drafts.untitled": "Ohne Titel",
        "problem.tooLong": "{where} hat {length} Zeichen, höchstens {limit}",
        "problem.tooManyEmbeds": "Eine Nachricht hat höchstens {limit} Embeds",
        "problem.tooManyFields": "Ein Embed hat höchstens {limit} Felder",
        "problem.badUrl": "{where} ist kein Link, der mit https:// beginnt",
        "problem.badColor": "{where} ist keine Farbe wie #5865F2",
        "problem.badTimestamp": "{where} ist kein Datum",
        "problem.emptyEmbed": "{where} braucht einen Titel, Text, Autor, Fußzeile, Feld oder Bild",
        "problem.fieldNeedsBoth": "{where} braucht einen Namen und einen Wert",
        "problem.empty": "Es gibt noch nichts zu senden",
        "problem.more": "und {count} weitere",
        "where.total": "Alle Embeds zusammen",
        "where.embed": "Embed {n}",
        "where.field": "Feld {n}",
        "where.content": "Die Nachricht",
        "where.username": "Der Name",
        "where.avatarUrl": "Die Avatar-URL",
        "where.title": "Titel",
        "where.description": "Beschreibung",
        "where.authorName": "Autorname",
        "where.authorUrl": "Autor-Link",
        "where.authorIcon": "Autor-Symbol",
        "where.url": "Titel-Link",
        "where.image": "Bild",
        "where.thumbnail": "Vorschaubild",
        "where.footerText": "Fußzeilentext",
        "where.footerIcon": "Fußzeilen-Symbol",
        "where.color": "Farbe",
        "where.timestamp": "Zeitstempel",
        "where.name": "Name",
        "where.value": "Wert",
        "error.noClient": "Discords API-Client wurde nicht gefunden",
        "error.createFailed": "Der Webhook konnte nicht erstellt werden",
        "error.loadWebhooks": "Die Webhooks dieses Kanals konnten nicht geladen werden",
        "error.rateLimited": "Discord bremst: versuche es in {seconds} s erneut",
        "error.notFound": "Dieser Webhook oder diese Nachricht existiert nicht mehr",
        "error.status": "Discord antwortete mit Fehler {status}",
        "error.pickWebhook": "Wähle zuerst einen Webhook oder erstelle einen neuen",
        "error.sendFailed": "Senden fehlgeschlagen",
        "error.badLink": "Das ist kein Discord-Nachrichtenlink",
        "error.loadMessage": "Die Nachricht konnte nicht geöffnet werden. Hat der gewählte Webhook sie gesendet?",
        "error.notJson": "Das ist kein gültiges JSON",
        "error.notMessage": "Dieses JSON ist keine Nachricht und kein Embed",
        "toast.copyFailed": "Kopieren fehlgeschlagen",
        "toast.edited": "Nachricht aktualisiert",
        "toast.sent": "An #{channel} gesendet",
        "toast.draftSaved": "Entwurf gespeichert",
        "toast.jsonCopied": "JSON kopiert",
        "mode.label": "Nachrichtentyp",
        "mode.classic": "Klassisch",
        "mode.v2": "Komponenten V2",
        "mode.locked": "Eine gesendete Nachricht behält ihren Typ",
        "mode.v2Hint": "Baue die Nachricht aus Blöcken: Text, Abschnitte, Galerien, Dateien und Container. Webhooks können nur Link-Buttons nutzen; Buttons mit Aktionen und Menüs brauchen einen Bot.",
        "section.sender": "Absender",
        "section.files": "Dateien",
        "section.sendAs": "Senden als",
        "webhook.auto": "Beim Senden wird in diesem Kanal ein Webhook namens Evi Embeds erstellt.",
        "json.button": "JSON",
        "files.add": "Dateien hinzufügen",
        "files.hint": "Nutze sie in Bildern und Datei-Komponenten oder als attachment://name.",
        "files.remove": "Datei entfernen",
        "files.copyRef": "attachment://-Link kopieren",
        "files.kept": "Schon in der Nachricht",
        "kind.text": "Text",
        "kind.section": "Abschnitt",
        "kind.gallery": "Mediengalerie",
        "kind.separator": "Trenner",
        "kind.file": "Datei",
        "kind.buttons": "Link-Buttons",
        "kind.container": "Container",
        "kindHint.text": "Text mit Markdown, Erwähnungen und Emojis",
        "kindHint.section": "Bis zu 3 Texte mit einem Vorschaubild oder Link-Button daneben",
        "kindHint.gallery": "1 bis 10 Bilder oder Videos in einem Raster",
        "kindHint.separator": "Abstand zwischen Komponenten, mit oder ohne Linie",
        "kindHint.file": "Eine der Dateien, die mit der Nachricht gesendet werden",
        "kindHint.buttons": "Bis zu 5 Buttons, die Links öffnen",
        "kindHint.container": "Ein Kasten mit Akzentfarbe um andere Komponenten",
        "add.component": "Komponente hinzufügen",
        "add.toContainer": "Darin hinzufügen",
        "comp.content": "Text",
        "comp.markdownHint": "Markdown geht: **fett**, # Überschriften, -# kleiner Text, [Links](https://…)",
        "comp.sectionText": "Text {n}",
        "comp.addText": "Text hinzufügen",
        "comp.removeText": "Text entfernen",
        "comp.accessory": "Neben dem Text",
        "comp.accessoryThumbnail": "Vorschaubild",
        "comp.accessoryButton": "Link-Button",
        "comp.thumbnailUrl": "Link zum Vorschaubild",
        "comp.mediaUrl": "Link zu Bild oder Video",
        "comp.useFile": "Datei verwenden",
        "comp.alt": "Beschreibung (Alternativtext)",
        "comp.spoiler": "Als Spoiler markieren",
        "comp.item": "Bild {n}",
        "comp.addItem": "Bild hinzufügen ({count}/{limit})",
        "comp.removeItem": "Bild entfernen",
        "comp.divider": "Linie zeigen",
        "comp.spacing": "Abstand",
        "comp.spacingSmall": "Klein",
        "comp.spacingLarge": "Groß",
        "comp.fileName": "Datei",
        "comp.filePick": "Datei auswählen",
        "comp.fileNone": "Füge zuerst unten bei Dateien eine Datei hinzu.",
        "comp.buttonsNote": "Webhooks können nur Buttons senden, die einen Link öffnen.",
        "comp.button": "Button {n}",
        "comp.label": "Beschriftung",
        "comp.link": "Link",
        "comp.emoji": "Emoji",
        "comp.addButton": "Button hinzufügen ({count}/{limit})",
        "comp.removeButton": "Button entfernen",
        "comp.accent": "Akzentfarbe",
        "comp.inside": "Inhalt",
        "comp.emptyContainer": "Noch nichts darin.",
        "comp.remove": "Komponente entfernen",
        "summary.pictures": "Bilder: {count}",
        "summary.inside": "Darin: {count}",
        "summary.line": "Linie",
        "summary.space": "Abstand",
        "color.none": "Keine Farbe",
        "color.custom": "Beliebige Farbe wählen",
        "color.swatch": "Farbe {hex}",
        "meter.components": "Komponenten",
        "meter.text": "Text",
        "meter.embedText": "Text in Embeds",
        "message.embedChars": "Zeichen in diesem Embed",
        "preview.empty": "Deine Nachricht erscheint hier, während du sie baust",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Noch keine Komponenten. Wähle unten eine aus, um anzufangen.",
        "problem.emptyComponent": "{where} ist leer",
        "problem.buttonNeedsLabel": "{where} braucht eine Beschriftung oder ein Emoji",
        "problem.noAttachment": "{where} nutzt {name}, aber das ist keine der Dateien",
        "problem.tooManyComponents": "Eine Nachricht fasst höchstens {limit} Komponenten (diese hat {count})",
        "problem.tooManyFiles": "Eine Nachricht fasst höchstens {limit} Dateien",
        "problem.one": "1 Problem",
        "problem.count": "Probleme: {count}",
        "where.component": "Komponente {n}",
        "where.child": "Element {n}",
        "where.text": "Text {n}",
        "where.item": "Bild {n}",
        "where.button": "Button {n}",
        "where.accessory": "Vorschaubild oder Button",
        "where.media": "Link",
        "where.alt": "Beschreibung",
        "where.label": "Beschriftung",
        "where.link": "Link",
        "where.componentText": "Der ganze Text zusammen",
        "toast.skipped": "Interaktive Komponenten weggelassen, Webhooks können sie nicht senden: {count}",
        "toast.refCopied": "attachment://-Link kopiert",
        "error.tooBig": "Diese Dateien sind für diesen Server zu groß",
        "action.sendShortcut": "Senden (Strg+Enter)",
    },
    es: {
        "menu.open": "Creador de embeds",
        "command.description": "Crea embeds y envíalos con un webhook en este canal",
        "dialog.title": "Creador de embeds",
        "dialog.subtitle": "Se envía a #{channel} con un webhook",
        "dialog.editing": "Editando un mensaje que envió el webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Cargando webhooks…",
        "webhook.none": "Este canal aún no tiene webhooks.",
        "webhook.create": "Nuevo webhook",
        "webhook.creating": "Creando…",
        "message.username": "Nombre",
        "message.avatar": "URL del avatar",
        "message.content": "Mensaje",
        "message.total": "{length} / {limit} caracteres en embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nombre del autor",
        "embed.authorUrl": "Enlace del autor",
        "embed.authorIcon": "URL del icono del autor",
        "embed.titleField": "Título",
        "embed.url": "Enlace del título",
        "embed.description": "Descripción",
        "embed.color": "Color",
        "embed.image": "URL de la imagen",
        "embed.thumbnail": "URL de la miniatura",
        "embed.footerText": "Texto del pie",
        "embed.footerIcon": "URL del icono del pie",
        "embed.timestamp": "Marca de tiempo",
        "group.author": "Autor",
        "group.body": "Cuerpo",
        "group.fields": "Campos ({count}/{limit})",
        "group.images": "Imágenes",
        "group.footer": "Pie",
        "field.title": "Campo {n}",
        "field.inline": "En línea",
        "field.name": "Nombre",
        "field.value": "Valor",
        "action.addEmbed": "Añadir embed ({count}/{limit})",
        "action.addField": "Añadir campo",
        "action.cancel": "Cancelar",
        "action.clear": "Borrar",
        "action.clearAll": "Empezar de nuevo",
        "action.close": "Cerrar",
        "action.copyJson": "Copiar JSON",
        "action.duplicate": "Duplicar",
        "action.moveUp": "Subir",
        "action.moveDown": "Bajar",
        "action.now": "Ahora",
        "action.removeEmbed": "Quitar embed",
        "action.removeField": "Quitar campo",
        "action.saveEdit": "Guardar cambios",
        "action.send": "Enviar",
        "action.sending": "Enviando…",
        "preview.app": "APP",
        "preview.label": "Vista previa",
        "preview.today": "Hoy a las {time}",
        "import.button": "Importar JSON",
        "import.label": "Pega el JSON de un mensaje de webhook (el de Discohook también sirve)",
        "import.load": "Cargar",
        "edit.button": "Editar un mensaje enviado",
        "edit.hint": "Haz clic derecho en un mensaje del webhook elegido y copia el enlace del mensaje.",
        "edit.label": "Enlace del mensaje",
        "edit.load": "Abrir",
        "edit.loading": "Abriendo…",
        "edit.stop": "Enviar como nuevo",
        "drafts.button": "Borradores",
        "drafts.title": "Borradores guardados",
        "drafts.save": "Guardar este",
        "drafts.none": "Aún no hay borradores guardados.",
        "drafts.delete": "Eliminar borrador",
        "drafts.untitled": "Sin título",
        "problem.tooLong": "{where} tiene {length} caracteres, como máximo {limit}",
        "problem.tooManyEmbeds": "Un mensaje admite como máximo {limit} embeds",
        "problem.tooManyFields": "Un embed admite como máximo {limit} campos",
        "problem.badUrl": "{where} no es un enlace que empiece por https://",
        "problem.badColor": "{where} no es un color como #5865F2",
        "problem.badTimestamp": "{where} no es una fecha",
        "problem.emptyEmbed": "{where} necesita un título, texto, autor, pie, campo o imagen",
        "problem.fieldNeedsBoth": "{where} necesita nombre y valor",
        "problem.empty": "Todavía no hay nada que enviar",
        "problem.more": "y {count} más",
        "where.total": "Todos los embeds juntos",
        "where.embed": "Embed {n}",
        "where.field": "campo {n}",
        "where.content": "El mensaje",
        "where.username": "El nombre",
        "where.avatarUrl": "La URL del avatar",
        "where.title": "título",
        "where.description": "descripción",
        "where.authorName": "nombre del autor",
        "where.authorUrl": "enlace del autor",
        "where.authorIcon": "icono del autor",
        "where.url": "enlace del título",
        "where.image": "imagen",
        "where.thumbnail": "miniatura",
        "where.footerText": "texto del pie",
        "where.footerIcon": "icono del pie",
        "where.color": "color",
        "where.timestamp": "marca de tiempo",
        "where.name": "nombre",
        "where.value": "valor",
        "error.noClient": "No se encontró el cliente de API de Discord",
        "error.createFailed": "No se pudo crear el webhook",
        "error.loadWebhooks": "No se pudieron cargar los webhooks del canal",
        "error.rateLimited": "Discord pide ir más despacio: inténtalo en {seconds} s",
        "error.notFound": "Ese webhook o mensaje ya no existe",
        "error.status": "Discord respondió con el error {status}",
        "error.pickWebhook": "Elige un webhook o crea uno nuevo primero",
        "error.sendFailed": "No se pudo enviar",
        "error.badLink": "Eso no es un enlace a un mensaje de Discord",
        "error.loadMessage": "No se pudo abrir el mensaje. ¿Lo envió el webhook elegido?",
        "error.notJson": "Eso no es JSON válido",
        "error.notMessage": "Ese JSON no es un mensaje ni un embed",
        "toast.copyFailed": "No se pudo copiar",
        "toast.edited": "Mensaje actualizado",
        "toast.sent": "Enviado a #{channel}",
        "toast.draftSaved": "Borrador guardado",
        "toast.jsonCopied": "JSON copiado",
        "mode.label": "Tipo de mensaje",
        "mode.classic": "Clásico",
        "mode.v2": "Componentes V2",
        "mode.locked": "Un mensaje enviado mantiene su tipo",
        "mode.v2Hint": "Arma el mensaje con bloques: texto, secciones, galerías, archivos y contenedores. Los webhooks solo pueden usar botones de enlace; los botones con acciones y los menús necesitan un bot.",
        "section.sender": "Remitente",
        "section.files": "Archivos",
        "section.sendAs": "Enviar como",
        "webhook.auto": "Al enviar se crea en este canal un webhook llamado Evi Embeds.",
        "json.button": "JSON",
        "files.add": "Añadir archivos",
        "files.hint": "Úsalos en imágenes y componentes de archivo, o como attachment://nombre.",
        "files.remove": "Quitar archivo",
        "files.copyRef": "Copiar enlace attachment://",
        "files.kept": "Ya está en el mensaje",
        "kind.text": "Texto",
        "kind.section": "Sección",
        "kind.gallery": "Galería multimedia",
        "kind.separator": "Separador",
        "kind.file": "Archivo",
        "kind.buttons": "Botones de enlace",
        "kind.container": "Contenedor",
        "kindHint.text": "Texto con markdown, menciones y emojis",
        "kindHint.section": "Hasta 3 textos con una miniatura o un botón de enlace al lado",
        "kindHint.gallery": "De 1 a 10 imágenes o vídeos en cuadrícula",
        "kindHint.separator": "Espacio entre componentes, con o sin línea",
        "kindHint.file": "Uno de los archivos que se envían con el mensaje",
        "kindHint.buttons": "Hasta 5 botones que abren enlaces",
        "kindHint.container": "Un recuadro con color de acento alrededor de otros componentes",
        "add.component": "Añadir un componente",
        "add.toContainer": "Añadir dentro",
        "comp.content": "Texto",
        "comp.markdownHint": "Funciona el markdown: **negrita**, # títulos, -# texto pequeño, [enlaces](https://…)",
        "comp.sectionText": "Texto {n}",
        "comp.addText": "Añadir texto",
        "comp.removeText": "Quitar texto",
        "comp.accessory": "Junto al texto",
        "comp.accessoryThumbnail": "Miniatura",
        "comp.accessoryButton": "Botón de enlace",
        "comp.thumbnailUrl": "Enlace de la miniatura",
        "comp.mediaUrl": "Enlace de la imagen o vídeo",
        "comp.useFile": "Usar un archivo",
        "comp.alt": "Descripción (texto alternativo)",
        "comp.spoiler": "Marcar como spoiler",
        "comp.item": "Imagen {n}",
        "comp.addItem": "Añadir imagen ({count}/{limit})",
        "comp.removeItem": "Quitar imagen",
        "comp.divider": "Mostrar una línea",
        "comp.spacing": "Espaciado",
        "comp.spacingSmall": "Pequeño",
        "comp.spacingLarge": "Grande",
        "comp.fileName": "Archivo",
        "comp.filePick": "Elige un archivo",
        "comp.fileNone": "Primero añade un archivo en Archivos, más abajo.",
        "comp.buttonsNote": "Los webhooks solo pueden enviar botones que abren un enlace.",
        "comp.button": "Botón {n}",
        "comp.label": "Texto del botón",
        "comp.link": "Enlace",
        "comp.emoji": "Emoji",
        "comp.addButton": "Añadir botón ({count}/{limit})",
        "comp.removeButton": "Quitar botón",
        "comp.accent": "Color de acento",
        "comp.inside": "Dentro",
        "comp.emptyContainer": "Todavía no hay nada dentro.",
        "comp.remove": "Quitar componente",
        "summary.pictures": "Imágenes: {count}",
        "summary.inside": "Dentro: {count}",
        "summary.line": "Línea",
        "summary.space": "Espacio",
        "color.none": "Sin color",
        "color.custom": "Elegir cualquier color",
        "color.swatch": "Color {hex}",
        "meter.components": "Componentes",
        "meter.text": "Texto",
        "meter.embedText": "Texto en los embeds",
        "message.embedChars": "Caracteres en este embed",
        "preview.empty": "Tu mensaje aparecerá aquí mientras lo armas",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Aún no hay componentes. Elige uno abajo para empezar.",
        "problem.emptyComponent": "{where} está vacío",
        "problem.buttonNeedsLabel": "{where} necesita un texto o un emoji",
        "problem.noAttachment": "{where} usa {name}, que no está entre los archivos",
        "problem.tooManyComponents": "Un mensaje admite como máximo {limit} componentes (este tiene {count})",
        "problem.tooManyFiles": "Un mensaje admite como máximo {limit} archivos",
        "problem.one": "1 problema",
        "problem.count": "Problemas: {count}",
        "where.component": "Componente {n}",
        "where.child": "elemento {n}",
        "where.text": "texto {n}",
        "where.item": "imagen {n}",
        "where.button": "botón {n}",
        "where.accessory": "la miniatura o el botón",
        "where.media": "enlace",
        "where.alt": "descripción",
        "where.label": "texto del botón",
        "where.link": "enlace",
        "where.componentText": "Todo el texto junto",
        "toast.skipped": "Componentes interactivos omitidos, los webhooks no pueden enviarlos: {count}",
        "toast.refCopied": "Enlace attachment:// copiado",
        "error.tooBig": "Estos archivos son demasiado grandes para este servidor",
        "action.sendShortcut": "Enviar (Ctrl+Intro)",
    },
    fr: {
        "menu.open": "Créateur d'embeds",
        "command.description": "Compose des embeds et envoie-les via un webhook dans ce salon",
        "dialog.title": "Créateur d'embeds",
        "dialog.subtitle": "Envoyé dans #{channel} via un webhook",
        "dialog.editing": "Modification d'un message envoyé par le webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Chargement des webhooks…",
        "webhook.none": "Ce salon n'a pas encore de webhook.",
        "webhook.create": "Nouveau webhook",
        "webhook.creating": "Création…",
        "message.username": "Nom",
        "message.avatar": "URL de l'avatar",
        "message.content": "Message",
        "message.total": "{length} / {limit} caractères dans les embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nom de l'auteur",
        "embed.authorUrl": "Lien de l'auteur",
        "embed.authorIcon": "URL de l'icône de l'auteur",
        "embed.titleField": "Titre",
        "embed.url": "Lien du titre",
        "embed.description": "Description",
        "embed.color": "Couleur",
        "embed.image": "URL de l'image",
        "embed.thumbnail": "URL de la miniature",
        "embed.footerText": "Texte du pied",
        "embed.footerIcon": "URL de l'icône du pied",
        "embed.timestamp": "Horodatage",
        "group.author": "Auteur",
        "group.body": "Corps",
        "group.fields": "Champs ({count}/{limit})",
        "group.images": "Images",
        "group.footer": "Pied",
        "field.title": "Champ {n}",
        "field.inline": "En ligne",
        "field.name": "Nom",
        "field.value": "Valeur",
        "action.addEmbed": "Ajouter un embed ({count}/{limit})",
        "action.addField": "Ajouter un champ",
        "action.cancel": "Annuler",
        "action.clear": "Effacer",
        "action.clearAll": "Recommencer",
        "action.close": "Fermer",
        "action.copyJson": "Copier le JSON",
        "action.duplicate": "Dupliquer",
        "action.moveUp": "Monter",
        "action.moveDown": "Descendre",
        "action.now": "Maintenant",
        "action.removeEmbed": "Retirer l'embed",
        "action.removeField": "Retirer le champ",
        "action.saveEdit": "Enregistrer",
        "action.send": "Envoyer",
        "action.sending": "Envoi…",
        "preview.app": "APP",
        "preview.label": "Aperçu",
        "preview.today": "Aujourd'hui à {time}",
        "import.button": "Importer du JSON",
        "import.label": "Colle le JSON d'un message de webhook (celui de Discohook marche aussi)",
        "import.load": "Charger",
        "edit.button": "Modifier un message envoyé",
        "edit.hint": "Fais un clic droit sur un message du webhook choisi et copie le lien du message.",
        "edit.label": "Lien du message",
        "edit.load": "Ouvrir",
        "edit.loading": "Ouverture…",
        "edit.stop": "Envoyer comme nouveau",
        "drafts.button": "Brouillons",
        "drafts.title": "Brouillons enregistrés",
        "drafts.save": "Enregistrer celui-ci",
        "drafts.none": "Aucun brouillon enregistré.",
        "drafts.delete": "Supprimer le brouillon",
        "drafts.untitled": "Sans titre",
        "problem.tooLong": "{where} fait {length} caractères, {limit} au plus",
        "problem.tooManyEmbeds": "Un message contient {limit} embeds au plus",
        "problem.tooManyFields": "Un embed contient {limit} champs au plus",
        "problem.badUrl": "{where} n'est pas un lien commençant par https://",
        "problem.badColor": "{where} n'est pas une couleur comme #5865F2",
        "problem.badTimestamp": "{where} n'est pas une date",
        "problem.emptyEmbed": "{where} a besoin d'un titre, d'un texte, d'un auteur, d'un pied, d'un champ ou d'une image",
        "problem.fieldNeedsBoth": "{where} a besoin d'un nom et d'une valeur",
        "problem.empty": "Il n'y a encore rien à envoyer",
        "problem.more": "et {count} de plus",
        "where.total": "Tous les embeds ensemble",
        "where.embed": "Embed {n}",
        "where.field": "champ {n}",
        "where.content": "Le message",
        "where.username": "Le nom",
        "where.avatarUrl": "L'URL de l'avatar",
        "where.title": "titre",
        "where.description": "description",
        "where.authorName": "nom de l'auteur",
        "where.authorUrl": "lien de l'auteur",
        "where.authorIcon": "icône de l'auteur",
        "where.url": "lien du titre",
        "where.image": "image",
        "where.thumbnail": "miniature",
        "where.footerText": "texte du pied",
        "where.footerIcon": "icône du pied",
        "where.color": "couleur",
        "where.timestamp": "horodatage",
        "where.name": "nom",
        "where.value": "valeur",
        "error.noClient": "Client API de Discord introuvable",
        "error.createFailed": "Impossible de créer le webhook",
        "error.loadWebhooks": "Impossible de charger les webhooks de ce salon",
        "error.rateLimited": "Discord demande de ralentir : réessaie dans {seconds} s",
        "error.notFound": "Ce webhook ou ce message n'existe plus",
        "error.status": "Discord a répondu avec l'erreur {status}",
        "error.pickWebhook": "Choisis d'abord un webhook ou crées-en un",
        "error.sendFailed": "Impossible de l'envoyer",
        "error.badLink": "Ce n'est pas un lien de message Discord",
        "error.loadMessage": "Impossible d'ouvrir ce message. A-t-il été envoyé par le webhook choisi ?",
        "error.notJson": "Ce n'est pas du JSON valide",
        "error.notMessage": "Ce JSON n'est ni un message ni un embed",
        "toast.copyFailed": "Impossible de copier",
        "toast.edited": "Message mis à jour",
        "toast.sent": "Envoyé dans #{channel}",
        "toast.draftSaved": "Brouillon enregistré",
        "toast.jsonCopied": "JSON copié",
        "mode.label": "Type de message",
        "mode.classic": "Classique",
        "mode.v2": "Composants V2",
        "mode.locked": "Un message envoyé garde son type",
        "mode.v2Hint": "Construis le message avec des blocs : texte, sections, galeries, fichiers et conteneurs. Les webhooks ne peuvent utiliser que des boutons de lien ; les boutons d'action et les menus nécessitent un bot.",
        "section.sender": "Expéditeur",
        "section.files": "Fichiers",
        "section.sendAs": "Envoyer en tant que",
        "webhook.auto": "L'envoi crée dans ce salon un webhook nommé Evi Embeds.",
        "json.button": "JSON",
        "files.add": "Ajouter des fichiers",
        "files.hint": "Utilise-les dans les images et les composants Fichier, ou comme attachment://nom.",
        "files.remove": "Retirer le fichier",
        "files.copyRef": "Copier le lien attachment://",
        "files.kept": "Déjà dans le message",
        "kind.text": "Texte",
        "kind.section": "Section",
        "kind.gallery": "Galerie de médias",
        "kind.separator": "Séparateur",
        "kind.file": "Fichier",
        "kind.buttons": "Boutons de lien",
        "kind.container": "Conteneur",
        "kindHint.text": "Du texte avec markdown, mentions et emojis",
        "kindHint.section": "Jusqu'à 3 textes avec une miniature ou un bouton de lien à côté",
        "kindHint.gallery": "1 à 10 images ou vidéos en grille",
        "kindHint.separator": "De l'espace entre les composants, avec ou sans ligne",
        "kindHint.file": "Un des fichiers envoyés avec le message",
        "kindHint.buttons": "Jusqu'à 5 boutons qui ouvrent des liens",
        "kindHint.container": "Un cadre avec une couleur d'accent autour d'autres composants",
        "add.component": "Ajouter un composant",
        "add.toContainer": "Ajouter dedans",
        "comp.content": "Texte",
        "comp.markdownHint": "Le markdown marche : **gras**, # titres, -# petit texte, [liens](https://…)",
        "comp.sectionText": "Texte {n}",
        "comp.addText": "Ajouter un texte",
        "comp.removeText": "Retirer le texte",
        "comp.accessory": "À côté du texte",
        "comp.accessoryThumbnail": "Miniature",
        "comp.accessoryButton": "Bouton de lien",
        "comp.thumbnailUrl": "Lien de la miniature",
        "comp.mediaUrl": "Lien de l'image ou de la vidéo",
        "comp.useFile": "Utiliser un fichier",
        "comp.alt": "Description (texte alternatif)",
        "comp.spoiler": "Marquer comme spoiler",
        "comp.item": "Image {n}",
        "comp.addItem": "Ajouter une image ({count}/{limit})",
        "comp.removeItem": "Retirer l'image",
        "comp.divider": "Afficher une ligne",
        "comp.spacing": "Espacement",
        "comp.spacingSmall": "Petit",
        "comp.spacingLarge": "Grand",
        "comp.fileName": "Fichier",
        "comp.filePick": "Choisis un fichier",
        "comp.fileNone": "Ajoute d'abord un fichier dans Fichiers, plus bas.",
        "comp.buttonsNote": "Les webhooks ne peuvent envoyer que des boutons qui ouvrent un lien.",
        "comp.button": "Bouton {n}",
        "comp.label": "Libellé",
        "comp.link": "Lien",
        "comp.emoji": "Emoji",
        "comp.addButton": "Ajouter un bouton ({count}/{limit})",
        "comp.removeButton": "Retirer le bouton",
        "comp.accent": "Couleur d'accent",
        "comp.inside": "Contenu",
        "comp.emptyContainer": "Rien dedans pour l'instant.",
        "comp.remove": "Retirer le composant",
        "summary.pictures": "Images : {count}",
        "summary.inside": "Dedans : {count}",
        "summary.line": "Ligne",
        "summary.space": "Espace",
        "color.none": "Pas de couleur",
        "color.custom": "Choisir n'importe quelle couleur",
        "color.swatch": "Couleur {hex}",
        "meter.components": "Composants",
        "meter.text": "Texte",
        "meter.embedText": "Texte des embeds",
        "message.embedChars": "Caractères dans cet embed",
        "preview.empty": "Ton message s'affiche ici pendant que tu le construis",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Pas encore de composants. Choisis-en un ci-dessous pour commencer.",
        "problem.emptyComponent": "{where} est vide",
        "problem.buttonNeedsLabel": "{where} a besoin d'un libellé ou d'un emoji",
        "problem.noAttachment": "{where} utilise {name}, qui ne fait pas partie des fichiers",
        "problem.tooManyComponents": "Un message contient au plus {limit} composants (celui-ci en a {count})",
        "problem.tooManyFiles": "Un message contient au plus {limit} fichiers",
        "problem.one": "1 problème",
        "problem.count": "Problèmes : {count}",
        "where.component": "Composant {n}",
        "where.child": "élément {n}",
        "where.text": "texte {n}",
        "where.item": "image {n}",
        "where.button": "bouton {n}",
        "where.accessory": "la miniature ou le bouton",
        "where.media": "lien",
        "where.alt": "description",
        "where.label": "libellé",
        "where.link": "lien",
        "where.componentText": "Tout le texte réuni",
        "toast.skipped": "Composants interactifs laissés de côté, les webhooks ne peuvent pas les envoyer : {count}",
        "toast.refCopied": "Lien attachment:// copié",
        "error.tooBig": "Ces fichiers sont trop lourds pour ce serveur",
        "action.sendShortcut": "Envoyer (Ctrl+Entrée)",
    },
    ja: {
        "menu.open": "埋め込みビルダー",
        "command.description": "埋め込みを作成し、このチャンネルのWebhookで送信します",
        "dialog.title": "埋め込みビルダー",
        "dialog.subtitle": "Webhookで #{channel} に送信します",
        "dialog.editing": "Webhookが送信したメッセージを編集中",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhookを読み込み中…",
        "webhook.none": "このチャンネルにはまだWebhookがありません。",
        "webhook.create": "新しいWebhook",
        "webhook.creating": "作成中…",
        "message.username": "名前",
        "message.avatar": "アバターURL",
        "message.content": "メッセージ",
        "message.total": "埋め込み内の文字数 {length} / {limit}",
        "embed.title": "埋め込み {n}",
        "embed.authorName": "作成者名",
        "embed.authorUrl": "作成者のリンク",
        "embed.authorIcon": "作成者アイコンのURL",
        "embed.titleField": "タイトル",
        "embed.url": "タイトルのリンク",
        "embed.description": "説明",
        "embed.color": "色",
        "embed.image": "画像のURL",
        "embed.thumbnail": "サムネイルのURL",
        "embed.footerText": "フッターのテキスト",
        "embed.footerIcon": "フッターアイコンのURL",
        "embed.timestamp": "タイムスタンプ",
        "group.author": "作成者",
        "group.body": "本文",
        "group.fields": "フィールド ({count}/{limit})",
        "group.images": "画像",
        "group.footer": "フッター",
        "field.title": "フィールド {n}",
        "field.inline": "インライン",
        "field.name": "名前",
        "field.value": "値",
        "action.addEmbed": "埋め込みを追加 ({count}/{limit})",
        "action.addField": "フィールドを追加",
        "action.cancel": "キャンセル",
        "action.clear": "クリア",
        "action.clearAll": "最初からやり直す",
        "action.close": "閉じる",
        "action.copyJson": "JSONをコピー",
        "action.duplicate": "複製",
        "action.moveUp": "上へ移動",
        "action.moveDown": "下へ移動",
        "action.now": "現在",
        "action.removeEmbed": "埋め込みを削除",
        "action.removeField": "フィールドを削除",
        "action.saveEdit": "変更を保存",
        "action.send": "送信",
        "action.sending": "送信中…",
        "preview.app": "APP",
        "preview.label": "プレビュー",
        "preview.today": "今日 {time}",
        "import.button": "JSONを読み込む",
        "import.label": "WebhookメッセージのJSONを貼り付けてください(Discohookの形式も使えます)",
        "import.load": "読み込む",
        "edit.button": "送信済みメッセージを編集",
        "edit.hint": "選択したWebhookが送信したメッセージを右クリックして、メッセージリンクをコピーしてください。",
        "edit.label": "メッセージリンク",
        "edit.load": "開く",
        "edit.loading": "開いています…",
        "edit.stop": "新規として送信",
        "drafts.button": "下書き",
        "drafts.title": "保存した下書き",
        "drafts.save": "これを保存",
        "drafts.none": "保存した下書きはまだありません。",
        "drafts.delete": "下書きを削除",
        "drafts.untitled": "無題",
        "problem.tooLong": "{where} は {length} 文字です(最大 {limit})",
        "problem.tooManyEmbeds": "1つのメッセージに入る埋め込みは最大 {limit} 個です",
        "problem.tooManyFields": "1つの埋め込みに入るフィールドは最大 {limit} 個です",
        "problem.badUrl": "{where} が https:// で始まるリンクではありません",
        "problem.badColor": "{where} が #5865F2 のような色ではありません",
        "problem.badTimestamp": "{where} が日付ではありません",
        "problem.emptyEmbed": "{where} にはタイトル、本文、作成者、フッター、フィールド、画像のいずれかが必要です",
        "problem.fieldNeedsBoth": "{where} には名前と値の両方が必要です",
        "problem.empty": "まだ送るものがありません",
        "problem.more": "ほか {count} 件",
        "where.total": "すべての埋め込みの合計",
        "where.embed": "埋め込み {n}",
        "where.field": "フィールド {n}",
        "where.content": "メッセージ",
        "where.username": "名前",
        "where.avatarUrl": "アバターURL",
        "where.title": "タイトル",
        "where.description": "説明",
        "where.authorName": "作成者名",
        "where.authorUrl": "作成者のリンク",
        "where.authorIcon": "作成者アイコン",
        "where.url": "タイトルのリンク",
        "where.image": "画像",
        "where.thumbnail": "サムネイル",
        "where.footerText": "フッターのテキスト",
        "where.footerIcon": "フッターアイコン",
        "where.color": "色",
        "where.timestamp": "タイムスタンプ",
        "where.name": "名前",
        "where.value": "値",
        "error.noClient": "DiscordのAPIクライアントが見つかりませんでした",
        "error.createFailed": "Webhookを作成できませんでした",
        "error.loadWebhooks": "このチャンネルのWebhookを読み込めませんでした",
        "error.rateLimited": "Discordの送信制限中です。{seconds} 秒後にもう一度お試しください",
        "error.notFound": "そのWebhookまたはメッセージはもう存在しません",
        "error.status": "Discordがエラー {status} を返しました",
        "error.pickWebhook": "先にWebhookを選ぶか、新しく作成してください",
        "error.sendFailed": "送信できませんでした",
        "error.badLink": "Discordのメッセージリンクではありません",
        "error.loadMessage": "メッセージを開けませんでした。選択したWebhookが送信したものですか?",
        "error.notJson": "有効なJSONではありません",
        "error.notMessage": "そのJSONはメッセージでも埋め込みでもありません",
        "toast.copyFailed": "コピーできませんでした",
        "toast.edited": "メッセージを更新しました",
        "toast.sent": "#{channel} に送信しました",
        "toast.draftSaved": "下書きを保存しました",
        "toast.jsonCopied": "JSONをコピーしました",
        "mode.label": "メッセージの種類",
        "mode.classic": "クラシック",
        "mode.v2": "コンポーネントV2",
        "mode.locked": "送信済みのメッセージは種類を変えられません",
        "mode.v2Hint": "テキスト、セクション、ギャラリー、ファイル、コンテナーのブロックでメッセージを組み立てます。Webhookで使えるのはリンクボタンだけで、操作をするボタンやメニューにはボットが必要です。",
        "section.sender": "送信者",
        "section.files": "ファイル",
        "section.sendAs": "送信者",
        "webhook.auto": "送信すると、このチャンネルに「Evi Embeds」という名前のウェブフックが作成されます。",
        "json.button": "JSON",
        "files.add": "ファイルを追加",
        "files.hint": "画像やファイルコンポーネントで使うか、attachment://名前 として指定できます。",
        "files.remove": "ファイルを削除",
        "files.copyRef": "attachment:// リンクをコピー",
        "files.kept": "メッセージに添付済み",
        "kind.text": "テキスト",
        "kind.section": "セクション",
        "kind.gallery": "メディアギャラリー",
        "kind.separator": "区切り",
        "kind.file": "ファイル",
        "kind.buttons": "リンクボタン",
        "kind.container": "コンテナー",
        "kindHint.text": "Markdown、メンション、絵文字が使えるテキスト",
        "kindHint.section": "最大3つのテキストと、その横にサムネイルかリンクボタン",
        "kindHint.gallery": "1〜10枚の画像や動画をグリッドで表示",
        "kindHint.separator": "コンポーネントの間の余白(線あり・なし)",
        "kindHint.file": "メッセージと一緒に送るファイルの1つ",
        "kindHint.buttons": "リンクを開くボタン(最大5個)",
        "kindHint.container": "ほかのコンポーネントを囲むアクセントカラー付きの枠",
        "add.component": "コンポーネントを追加",
        "add.toContainer": "中に追加",
        "comp.content": "テキスト",
        "comp.markdownHint": "Markdownが使えます: **太字**、# 見出し、-# 小さい文字、[リンク](https://…)",
        "comp.sectionText": "テキスト {n}",
        "comp.addText": "テキストを追加",
        "comp.removeText": "テキストを削除",
        "comp.accessory": "テキストの横",
        "comp.accessoryThumbnail": "サムネイル",
        "comp.accessoryButton": "リンクボタン",
        "comp.thumbnailUrl": "サムネイルのリンク",
        "comp.mediaUrl": "画像または動画のリンク",
        "comp.useFile": "ファイルを使う",
        "comp.alt": "説明(代替テキスト)",
        "comp.spoiler": "ネタバレとして隠す",
        "comp.item": "画像 {n}",
        "comp.addItem": "画像を追加 ({count}/{limit})",
        "comp.removeItem": "画像を削除",
        "comp.divider": "線を表示",
        "comp.spacing": "余白",
        "comp.spacingSmall": "小",
        "comp.spacingLarge": "大",
        "comp.fileName": "ファイル",
        "comp.filePick": "ファイルを選択",
        "comp.fileNone": "先に下の「ファイル」でファイルを追加してください。",
        "comp.buttonsNote": "Webhookが送れるのはリンクを開くボタンだけです。",
        "comp.button": "ボタン {n}",
        "comp.label": "ラベル",
        "comp.link": "リンク",
        "comp.emoji": "絵文字",
        "comp.addButton": "ボタンを追加 ({count}/{limit})",
        "comp.removeButton": "ボタンを削除",
        "comp.accent": "アクセントカラー",
        "comp.inside": "中身",
        "comp.emptyContainer": "まだ何も入っていません。",
        "comp.remove": "コンポーネントを削除",
        "summary.pictures": "画像: {count}",
        "summary.inside": "中身: {count}",
        "summary.line": "線",
        "summary.space": "余白",
        "color.none": "色なし",
        "color.custom": "好きな色を選ぶ",
        "color.swatch": "色 {hex}",
        "meter.components": "コンポーネント",
        "meter.text": "テキスト",
        "meter.embedText": "埋め込みのテキスト",
        "message.embedChars": "この埋め込みの文字数",
        "preview.empty": "組み立てたメッセージがここに表示されます",
        "preview.spoiler": "ネタバレ",
        "empty.v2": "まだコンポーネントがありません。下から選んで始めましょう。",
        "problem.emptyComponent": "{where} が空です",
        "problem.buttonNeedsLabel": "{where} にはラベルか絵文字が必要です",
        "problem.noAttachment": "{where} は {name} を使っていますが、ファイルの中にありません",
        "problem.tooManyComponents": "1つのメッセージに入るコンポーネントは最大 {limit} 個です(今は {count} 個)",
        "problem.tooManyFiles": "1つのメッセージに添付できるファイルは最大 {limit} 個です",
        "problem.one": "問題が1件",
        "problem.count": "問題: {count}件",
        "where.component": "コンポーネント {n}",
        "where.child": "項目 {n}",
        "where.text": "テキスト {n}",
        "where.item": "画像 {n}",
        "where.button": "ボタン {n}",
        "where.accessory": "サムネイルまたはボタン",
        "where.media": "リンク",
        "where.alt": "説明",
        "where.label": "ラベル",
        "where.link": "リンク",
        "where.componentText": "テキスト全体",
        "toast.skipped": "Webhookで送れない操作用コンポーネントを除外しました: {count}",
        "toast.refCopied": "attachment:// リンクをコピーしました",
        "error.tooBig": "このサーバーにはファイルが大きすぎます",
        "action.sendShortcut": "送信 (Ctrl+Enter)",
    },
    pl: {
        "menu.open": "Kreator embedów",
        "command.description": "Twórz embedy i wysyłaj je webhookiem na tym kanale",
        "dialog.title": "Kreator embedów",
        "dialog.subtitle": "Wysyłane na #{channel} przez webhook",
        "dialog.editing": "Edytujesz wiadomość wysłaną przez webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Wczytywanie webhooków…",
        "webhook.none": "Ten kanał nie ma jeszcze webhooków.",
        "webhook.create": "Nowy webhook",
        "webhook.creating": "Tworzenie…",
        "message.username": "Nazwa",
        "message.avatar": "URL awatara",
        "message.content": "Wiadomość",
        "message.total": "{length} / {limit} znaków w embedach",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nazwa autora",
        "embed.authorUrl": "Link autora",
        "embed.authorIcon": "URL ikony autora",
        "embed.titleField": "Tytuł",
        "embed.url": "Link tytułu",
        "embed.description": "Opis",
        "embed.color": "Kolor",
        "embed.image": "URL obrazu",
        "embed.thumbnail": "URL miniatury",
        "embed.footerText": "Tekst stopki",
        "embed.footerIcon": "URL ikony stopki",
        "embed.timestamp": "Znacznik czasu",
        "group.author": "Autor",
        "group.body": "Treść",
        "group.fields": "Pola ({count}/{limit})",
        "group.images": "Obrazy",
        "group.footer": "Stopka",
        "field.title": "Pole {n}",
        "field.inline": "W linii",
        "field.name": "Nazwa",
        "field.value": "Wartość",
        "action.addEmbed": "Dodaj embed ({count}/{limit})",
        "action.addField": "Dodaj pole",
        "action.cancel": "Anuluj",
        "action.clear": "Wyczyść",
        "action.clearAll": "Zacznij od nowa",
        "action.close": "Zamknij",
        "action.copyJson": "Kopiuj JSON",
        "action.duplicate": "Duplikuj",
        "action.moveUp": "Przenieś w górę",
        "action.moveDown": "Przenieś w dół",
        "action.now": "Teraz",
        "action.removeEmbed": "Usuń embed",
        "action.removeField": "Usuń pole",
        "action.saveEdit": "Zapisz zmiany",
        "action.send": "Wyślij",
        "action.sending": "Wysyłanie…",
        "preview.app": "APP",
        "preview.label": "Podgląd",
        "preview.today": "Dziś o {time}",
        "import.button": "Importuj JSON",
        "import.label": "Wklej JSON wiadomości webhooka (z Discohooka też działa)",
        "import.load": "Wczytaj",
        "edit.button": "Edytuj wysłaną wiadomość",
        "edit.hint": "Kliknij prawym przyciskiem wiadomość wybranego webhooka i skopiuj link do wiadomości.",
        "edit.label": "Link do wiadomości",
        "edit.load": "Otwórz",
        "edit.loading": "Otwieranie…",
        "edit.stop": "Wyślij jako nową",
        "drafts.button": "Szkice",
        "drafts.title": "Zapisane szkice",
        "drafts.save": "Zapisz ten",
        "drafts.none": "Brak zapisanych szkiców.",
        "drafts.delete": "Usuń szkic",
        "drafts.untitled": "Bez tytułu",
        "problem.tooLong": "{where} ma {length} znaków, maksymalnie {limit}",
        "problem.tooManyEmbeds": "Wiadomość może mieć maksymalnie {limit} embedów",
        "problem.tooManyFields": "Embed może mieć maksymalnie {limit} pól",
        "problem.badUrl": "{where} nie jest linkiem zaczynającym się od https://",
        "problem.badColor": "{where} nie jest kolorem w stylu #5865F2",
        "problem.badTimestamp": "{where} nie jest datą",
        "problem.emptyEmbed": "{where} potrzebuje tytułu, tekstu, autora, stopki, pola lub obrazu",
        "problem.fieldNeedsBoth": "{where} potrzebuje nazwy i wartości",
        "problem.empty": "Nie ma jeszcze nic do wysłania",
        "problem.more": "i {count} więcej",
        "where.total": "Wszystkie embedy razem",
        "where.embed": "Embed {n}",
        "where.field": "pole {n}",
        "where.content": "Wiadomość",
        "where.username": "Nazwa",
        "where.avatarUrl": "URL awatara",
        "where.title": "tytuł",
        "where.description": "opis",
        "where.authorName": "nazwa autora",
        "where.authorUrl": "link autora",
        "where.authorIcon": "ikona autora",
        "where.url": "link tytułu",
        "where.image": "obraz",
        "where.thumbnail": "miniatura",
        "where.footerText": "tekst stopki",
        "where.footerIcon": "ikona stopki",
        "where.color": "kolor",
        "where.timestamp": "znacznik czasu",
        "where.name": "nazwa",
        "where.value": "wartość",
        "error.noClient": "Nie znaleziono klienta API Discorda",
        "error.createFailed": "Nie udało się utworzyć webhooka",
        "error.loadWebhooks": "Nie udało się wczytać webhooków kanału",
        "error.rateLimited": "Discord prosi o wolniejsze tempo: spróbuj za {seconds} s",
        "error.notFound": "Ten webhook lub wiadomość już nie istnieje",
        "error.status": "Discord odpowiedział błędem {status}",
        "error.pickWebhook": "Najpierw wybierz webhook albo utwórz nowy",
        "error.sendFailed": "Nie udało się wysłać",
        "error.badLink": "To nie jest link do wiadomości na Discordzie",
        "error.loadMessage": "Nie udało się otworzyć wiadomości. Czy wysłał ją wybrany webhook?",
        "error.notJson": "To nie jest poprawny JSON",
        "error.notMessage": "Ten JSON nie jest wiadomością ani embedem",
        "toast.copyFailed": "Nie udało się skopiować",
        "toast.edited": "Wiadomość zaktualizowana",
        "toast.sent": "Wysłano na #{channel}",
        "toast.draftSaved": "Szkic zapisany",
        "toast.jsonCopied": "Skopiowano JSON",
        "mode.label": "Typ wiadomości",
        "mode.classic": "Klasyczna",
        "mode.v2": "Komponenty V2",
        "mode.locked": "Wysłana wiadomość zachowuje swój typ",
        "mode.v2Hint": "Zbuduj wiadomość z bloków: tekst, sekcje, galerie, pliki i kontenery. Webhooki mogą używać tylko przycisków z linkiem; przyciski z akcjami i menu wymagają bota.",
        "section.sender": "Nadawca",
        "section.files": "Pliki",
        "section.sendAs": "Wyślij jako",
        "webhook.auto": "Wysłanie utworzy na tym kanale webhook o nazwie Evi Embeds.",
        "json.button": "JSON",
        "files.add": "Dodaj pliki",
        "files.hint": "Użyj ich w obrazach i komponentach Plik albo jako attachment://nazwa.",
        "files.remove": "Usuń plik",
        "files.copyRef": "Kopiuj link attachment://",
        "files.kept": "Już jest w wiadomości",
        "kind.text": "Tekst",
        "kind.section": "Sekcja",
        "kind.gallery": "Galeria multimediów",
        "kind.separator": "Separator",
        "kind.file": "Plik",
        "kind.buttons": "Przyciski z linkiem",
        "kind.container": "Kontener",
        "kindHint.text": "Tekst z markdownem, wzmiankami i emoji",
        "kindHint.section": "Do 3 tekstów z miniaturą albo przyciskiem z linkiem obok",
        "kindHint.gallery": "Od 1 do 10 obrazów lub filmów w siatce",
        "kindHint.separator": "Odstęp między komponentami, z linią lub bez",
        "kindHint.file": "Jeden z plików wysyłanych z wiadomością",
        "kindHint.buttons": "Do 5 przycisków otwierających linki",
        "kindHint.container": "Ramka w kolorze akcentu wokół innych komponentów",
        "add.component": "Dodaj komponent",
        "add.toContainer": "Dodaj do środka",
        "comp.content": "Tekst",
        "comp.markdownHint": "Działa markdown: **pogrubienie**, # nagłówki, -# mały tekst, [linki](https://…)",
        "comp.sectionText": "Tekst {n}",
        "comp.addText": "Dodaj tekst",
        "comp.removeText": "Usuń tekst",
        "comp.accessory": "Obok tekstu",
        "comp.accessoryThumbnail": "Miniatura",
        "comp.accessoryButton": "Przycisk z linkiem",
        "comp.thumbnailUrl": "Link do miniatury",
        "comp.mediaUrl": "Link do obrazu lub filmu",
        "comp.useFile": "Użyj pliku",
        "comp.alt": "Opis (tekst alternatywny)",
        "comp.spoiler": "Oznacz jako spoiler",
        "comp.item": "Obraz {n}",
        "comp.addItem": "Dodaj obraz ({count}/{limit})",
        "comp.removeItem": "Usuń obraz",
        "comp.divider": "Pokaż linię",
        "comp.spacing": "Odstęp",
        "comp.spacingSmall": "Mały",
        "comp.spacingLarge": "Duży",
        "comp.fileName": "Plik",
        "comp.filePick": "Wybierz plik",
        "comp.fileNone": "Najpierw dodaj plik w sekcji Pliki poniżej.",
        "comp.buttonsNote": "Webhooki mogą wysyłać tylko przyciski, które otwierają link.",
        "comp.button": "Przycisk {n}",
        "comp.label": "Etykieta",
        "comp.link": "Link",
        "comp.emoji": "Emoji",
        "comp.addButton": "Dodaj przycisk ({count}/{limit})",
        "comp.removeButton": "Usuń przycisk",
        "comp.accent": "Kolor akcentu",
        "comp.inside": "W środku",
        "comp.emptyContainer": "Na razie nic tu nie ma.",
        "comp.remove": "Usuń komponent",
        "summary.pictures": "Obrazy: {count}",
        "summary.inside": "W środku: {count}",
        "summary.line": "Linia",
        "summary.space": "Odstęp",
        "color.none": "Bez koloru",
        "color.custom": "Wybierz dowolny kolor",
        "color.swatch": "Kolor {hex}",
        "meter.components": "Komponenty",
        "meter.text": "Tekst",
        "meter.embedText": "Tekst w embedach",
        "message.embedChars": "Znaki w tym embedzie",
        "preview.empty": "Tu zobaczysz wiadomość w trakcie budowania",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Nie ma jeszcze komponentów. Wybierz jeden poniżej, aby zacząć.",
        "problem.emptyComponent": "{where} jest pusty",
        "problem.buttonNeedsLabel": "{where} potrzebuje etykiety albo emoji",
        "problem.noAttachment": "{where} używa {name}, którego nie ma wśród plików",
        "problem.tooManyComponents": "Wiadomość mieści najwyżej {limit} komponentów (ta ma {count})",
        "problem.tooManyFiles": "Wiadomość mieści najwyżej {limit} plików",
        "problem.one": "1 problem",
        "problem.count": "Problemy: {count}",
        "where.component": "Komponent {n}",
        "where.child": "element {n}",
        "where.text": "tekst {n}",
        "where.item": "obraz {n}",
        "where.button": "przycisk {n}",
        "where.accessory": "miniatura lub przycisk",
        "where.media": "link",
        "where.alt": "opis",
        "where.label": "etykieta",
        "where.link": "link",
        "where.componentText": "Cały tekst razem",
        "toast.skipped": "Pominięto komponenty interaktywne, webhooki nie mogą ich wysłać: {count}",
        "toast.refCopied": "Skopiowano link attachment://",
        "error.tooBig": "Te pliki są za duże dla tego serwera",
        "action.sendShortcut": "Wyślij (Ctrl+Enter)",
    },
    "pt-BR": {
        "menu.open": "Criador de embeds",
        "command.description": "Crie embeds e envie por um webhook neste canal",
        "dialog.title": "Criador de embeds",
        "dialog.subtitle": "Enviado para #{channel} por um webhook",
        "dialog.editing": "Editando uma mensagem enviada pelo webhook",
        "webhook.label": "Webhook",
        "webhook.loading": "Carregando webhooks…",
        "webhook.none": "Este canal ainda não tem webhooks.",
        "webhook.create": "Novo webhook",
        "webhook.creating": "Criando…",
        "message.username": "Nome",
        "message.avatar": "URL do avatar",
        "message.content": "Mensagem",
        "message.total": "{length} / {limit} caracteres nos embeds",
        "embed.title": "Embed {n}",
        "embed.authorName": "Nome do autor",
        "embed.authorUrl": "Link do autor",
        "embed.authorIcon": "URL do ícone do autor",
        "embed.titleField": "Título",
        "embed.url": "Link do título",
        "embed.description": "Descrição",
        "embed.color": "Cor",
        "embed.image": "URL da imagem",
        "embed.thumbnail": "URL da miniatura",
        "embed.footerText": "Texto do rodapé",
        "embed.footerIcon": "URL do ícone do rodapé",
        "embed.timestamp": "Data e hora",
        "group.author": "Autor",
        "group.body": "Corpo",
        "group.fields": "Campos ({count}/{limit})",
        "group.images": "Imagens",
        "group.footer": "Rodapé",
        "field.title": "Campo {n}",
        "field.inline": "Em linha",
        "field.name": "Nome",
        "field.value": "Valor",
        "action.addEmbed": "Adicionar embed ({count}/{limit})",
        "action.addField": "Adicionar campo",
        "action.cancel": "Cancelar",
        "action.clear": "Limpar",
        "action.clearAll": "Recomeçar",
        "action.close": "Fechar",
        "action.copyJson": "Copiar JSON",
        "action.duplicate": "Duplicar",
        "action.moveUp": "Mover para cima",
        "action.moveDown": "Mover para baixo",
        "action.now": "Agora",
        "action.removeEmbed": "Remover embed",
        "action.removeField": "Remover campo",
        "action.saveEdit": "Salvar alterações",
        "action.send": "Enviar",
        "action.sending": "Enviando…",
        "preview.app": "APP",
        "preview.label": "Prévia",
        "preview.today": "Hoje às {time}",
        "import.button": "Importar JSON",
        "import.label": "Cole o JSON de uma mensagem de webhook (o do Discohook também serve)",
        "import.load": "Carregar",
        "edit.button": "Editar uma mensagem enviada",
        "edit.hint": "Clique com o botão direito numa mensagem do webhook escolhido e copie o link da mensagem.",
        "edit.label": "Link da mensagem",
        "edit.load": "Abrir",
        "edit.loading": "Abrindo…",
        "edit.stop": "Enviar como nova",
        "drafts.button": "Rascunhos",
        "drafts.title": "Rascunhos salvos",
        "drafts.save": "Salvar este",
        "drafts.none": "Nenhum rascunho salvo ainda.",
        "drafts.delete": "Excluir rascunho",
        "drafts.untitled": "Sem título",
        "problem.tooLong": "{where} tem {length} caracteres, no máximo {limit}",
        "problem.tooManyEmbeds": "Uma mensagem tem no máximo {limit} embeds",
        "problem.tooManyFields": "Um embed tem no máximo {limit} campos",
        "problem.badUrl": "{where} não é um link que começa com https://",
        "problem.badColor": "{where} não é uma cor como #5865F2",
        "problem.badTimestamp": "{where} não é uma data",
        "problem.emptyEmbed": "{where} precisa de título, texto, autor, rodapé, campo ou imagem",
        "problem.fieldNeedsBoth": "{where} precisa de nome e valor",
        "problem.empty": "Ainda não há nada para enviar",
        "problem.more": "e mais {count}",
        "where.total": "Todos os embeds juntos",
        "where.embed": "Embed {n}",
        "where.field": "campo {n}",
        "where.content": "A mensagem",
        "where.username": "O nome",
        "where.avatarUrl": "A URL do avatar",
        "where.title": "título",
        "where.description": "descrição",
        "where.authorName": "nome do autor",
        "where.authorUrl": "link do autor",
        "where.authorIcon": "ícone do autor",
        "where.url": "link do título",
        "where.image": "imagem",
        "where.thumbnail": "miniatura",
        "where.footerText": "texto do rodapé",
        "where.footerIcon": "ícone do rodapé",
        "where.color": "cor",
        "where.timestamp": "data e hora",
        "where.name": "nome",
        "where.value": "valor",
        "error.noClient": "O cliente de API do Discord não foi encontrado",
        "error.createFailed": "Não foi possível criar o webhook",
        "error.loadWebhooks": "Não foi possível carregar os webhooks do canal",
        "error.rateLimited": "O Discord pediu calma: tente de novo em {seconds} s",
        "error.notFound": "Esse webhook ou mensagem não existe mais",
        "error.status": "O Discord respondeu com o erro {status}",
        "error.pickWebhook": "Escolha um webhook ou crie um novo primeiro",
        "error.sendFailed": "Não foi possível enviar",
        "error.badLink": "Isso não é um link de mensagem do Discord",
        "error.loadMessage": "Não foi possível abrir a mensagem. Ela foi enviada pelo webhook escolhido?",
        "error.notJson": "Isso não é um JSON válido",
        "error.notMessage": "Esse JSON não é uma mensagem nem um embed",
        "toast.copyFailed": "Não foi possível copiar",
        "toast.edited": "Mensagem atualizada",
        "toast.sent": "Enviado para #{channel}",
        "toast.draftSaved": "Rascunho salvo",
        "toast.jsonCopied": "JSON copiado",
        "mode.label": "Tipo de mensagem",
        "mode.classic": "Clássica",
        "mode.v2": "Componentes V2",
        "mode.locked": "Uma mensagem enviada mantém o tipo dela",
        "mode.v2Hint": "Monte a mensagem com blocos: texto, seções, galerias, arquivos e contêineres. Webhooks só podem usar botões de link; botões com ações e menus precisam de um bot.",
        "section.sender": "Remetente",
        "section.files": "Arquivos",
        "section.sendAs": "Enviar como",
        "webhook.auto": "Ao enviar, um webhook chamado Evi Embeds é criado neste canal.",
        "json.button": "JSON",
        "files.add": "Adicionar arquivos",
        "files.hint": "Use-os em imagens e componentes de arquivo, ou como attachment://nome.",
        "files.remove": "Remover arquivo",
        "files.copyRef": "Copiar link attachment://",
        "files.kept": "Já está na mensagem",
        "kind.text": "Texto",
        "kind.section": "Seção",
        "kind.gallery": "Galeria de mídia",
        "kind.separator": "Separador",
        "kind.file": "Arquivo",
        "kind.buttons": "Botões de link",
        "kind.container": "Contêiner",
        "kindHint.text": "Texto com markdown, menções e emojis",
        "kindHint.section": "Até 3 textos com uma miniatura ou um botão de link ao lado",
        "kindHint.gallery": "De 1 a 10 imagens ou vídeos em grade",
        "kindHint.separator": "Espaço entre componentes, com ou sem linha",
        "kindHint.file": "Um dos arquivos enviados com a mensagem",
        "kindHint.buttons": "Até 5 botões que abrem links",
        "kindHint.container": "Uma caixa com cor de destaque em volta de outros componentes",
        "add.component": "Adicionar um componente",
        "add.toContainer": "Adicionar dentro",
        "comp.content": "Texto",
        "comp.markdownHint": "Markdown funciona: **negrito**, # títulos, -# texto pequeno, [links](https://…)",
        "comp.sectionText": "Texto {n}",
        "comp.addText": "Adicionar texto",
        "comp.removeText": "Remover texto",
        "comp.accessory": "Ao lado do texto",
        "comp.accessoryThumbnail": "Miniatura",
        "comp.accessoryButton": "Botão de link",
        "comp.thumbnailUrl": "Link da miniatura",
        "comp.mediaUrl": "Link da imagem ou vídeo",
        "comp.useFile": "Usar um arquivo",
        "comp.alt": "Descrição (texto alternativo)",
        "comp.spoiler": "Marcar como spoiler",
        "comp.item": "Imagem {n}",
        "comp.addItem": "Adicionar imagem ({count}/{limit})",
        "comp.removeItem": "Remover imagem",
        "comp.divider": "Mostrar uma linha",
        "comp.spacing": "Espaçamento",
        "comp.spacingSmall": "Pequeno",
        "comp.spacingLarge": "Grande",
        "comp.fileName": "Arquivo",
        "comp.filePick": "Escolha um arquivo",
        "comp.fileNone": "Primeiro adicione um arquivo em Arquivos, mais abaixo.",
        "comp.buttonsNote": "Webhooks só podem enviar botões que abrem um link.",
        "comp.button": "Botão {n}",
        "comp.label": "Rótulo",
        "comp.link": "Link",
        "comp.emoji": "Emoji",
        "comp.addButton": "Adicionar botão ({count}/{limit})",
        "comp.removeButton": "Remover botão",
        "comp.accent": "Cor de destaque",
        "comp.inside": "Dentro",
        "comp.emptyContainer": "Nada aqui dentro ainda.",
        "comp.remove": "Remover componente",
        "summary.pictures": "Imagens: {count}",
        "summary.inside": "Dentro: {count}",
        "summary.line": "Linha",
        "summary.space": "Espaço",
        "color.none": "Sem cor",
        "color.custom": "Escolher qualquer cor",
        "color.swatch": "Cor {hex}",
        "meter.components": "Componentes",
        "meter.text": "Texto",
        "meter.embedText": "Texto nos embeds",
        "message.embedChars": "Caracteres neste embed",
        "preview.empty": "Sua mensagem aparece aqui enquanto você monta",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Ainda não há componentes. Escolha um abaixo para começar.",
        "problem.emptyComponent": "{where} está vazio",
        "problem.buttonNeedsLabel": "{where} precisa de um rótulo ou de um emoji",
        "problem.noAttachment": "{where} usa {name}, que não está entre os arquivos",
        "problem.tooManyComponents": "Uma mensagem aceita no máximo {limit} componentes (esta tem {count})",
        "problem.tooManyFiles": "Uma mensagem aceita no máximo {limit} arquivos",
        "problem.one": "1 problema",
        "problem.count": "Problemas: {count}",
        "where.component": "Componente {n}",
        "where.child": "item {n}",
        "where.text": "texto {n}",
        "where.item": "imagem {n}",
        "where.button": "botão {n}",
        "where.accessory": "a miniatura ou o botão",
        "where.media": "link",
        "where.alt": "descrição",
        "where.label": "rótulo",
        "where.link": "link",
        "where.componentText": "Todo o texto junto",
        "toast.skipped": "Componentes interativos deixados de fora, webhooks não podem enviá-los: {count}",
        "toast.refCopied": "Link attachment:// copiado",
        "error.tooBig": "Esses arquivos são grandes demais para este servidor",
        "action.sendShortcut": "Enviar (Ctrl+Enter)",
    },
    ru: {
        "menu.open": "Конструктор эмбедов",
        "command.description": "Создавайте эмбеды и отправляйте их через вебхук в этом канале",
        "dialog.title": "Конструктор эмбедов",
        "dialog.subtitle": "Отправка в #{channel} через вебхук",
        "dialog.editing": "Редактирование сообщения, отправленного вебхуком",
        "webhook.label": "Вебхук",
        "webhook.loading": "Загрузка вебхуков…",
        "webhook.none": "У этого канала пока нет вебхуков.",
        "webhook.create": "Новый вебхук",
        "webhook.creating": "Создание…",
        "message.username": "Имя",
        "message.avatar": "URL аватара",
        "message.content": "Сообщение",
        "message.total": "{length} / {limit} символов в эмбедах",
        "embed.title": "Эмбед {n}",
        "embed.authorName": "Имя автора",
        "embed.authorUrl": "Ссылка автора",
        "embed.authorIcon": "URL значка автора",
        "embed.titleField": "Заголовок",
        "embed.url": "Ссылка заголовка",
        "embed.description": "Описание",
        "embed.color": "Цвет",
        "embed.image": "URL изображения",
        "embed.thumbnail": "URL миниатюры",
        "embed.footerText": "Текст подвала",
        "embed.footerIcon": "URL значка подвала",
        "embed.timestamp": "Отметка времени",
        "group.author": "Автор",
        "group.body": "Основное",
        "group.fields": "Поля ({count}/{limit})",
        "group.images": "Изображения",
        "group.footer": "Подвал",
        "field.title": "Поле {n}",
        "field.inline": "В строку",
        "field.name": "Название",
        "field.value": "Значение",
        "action.addEmbed": "Добавить эмбед ({count}/{limit})",
        "action.addField": "Добавить поле",
        "action.cancel": "Отмена",
        "action.clear": "Очистить",
        "action.clearAll": "Начать заново",
        "action.close": "Закрыть",
        "action.copyJson": "Копировать JSON",
        "action.duplicate": "Дублировать",
        "action.moveUp": "Переместить вверх",
        "action.moveDown": "Переместить вниз",
        "action.now": "Сейчас",
        "action.removeEmbed": "Удалить эмбед",
        "action.removeField": "Удалить поле",
        "action.saveEdit": "Сохранить изменения",
        "action.send": "Отправить",
        "action.sending": "Отправка…",
        "preview.app": "APP",
        "preview.label": "Предпросмотр",
        "preview.today": "Сегодня в {time}",
        "import.button": "Импорт JSON",
        "import.label": "Вставьте JSON сообщения вебхука (формат Discohook тоже подходит)",
        "import.load": "Загрузить",
        "edit.button": "Изменить отправленное сообщение",
        "edit.hint": "Нажмите правой кнопкой на сообщение выбранного вебхука и скопируйте ссылку на сообщение.",
        "edit.label": "Ссылка на сообщение",
        "edit.load": "Открыть",
        "edit.loading": "Открытие…",
        "edit.stop": "Отправить как новое",
        "drafts.button": "Черновики",
        "drafts.title": "Сохранённые черновики",
        "drafts.save": "Сохранить этот",
        "drafts.none": "Сохранённых черновиков пока нет.",
        "drafts.delete": "Удалить черновик",
        "drafts.untitled": "Без названия",
        "problem.tooLong": "{where}: {length} символов, максимум {limit}",
        "problem.tooManyEmbeds": "В сообщении не больше {limit} эмбедов",
        "problem.tooManyFields": "В эмбеде не больше {limit} полей",
        "problem.badUrl": "{where}: это не ссылка, начинающаяся с https://",
        "problem.badColor": "{where}: это не цвет вида #5865F2",
        "problem.badTimestamp": "{where}: это не дата",
        "problem.emptyEmbed": "{where}: нужен заголовок, текст, автор, подвал, поле или изображение",
        "problem.fieldNeedsBoth": "{where}: нужны и название, и значение",
        "problem.empty": "Пока нечего отправлять",
        "problem.more": "и ещё {count}",
        "where.total": "Все эмбеды вместе",
        "where.embed": "Эмбед {n}",
        "where.field": "поле {n}",
        "where.content": "Сообщение",
        "where.username": "Имя",
        "where.avatarUrl": "URL аватара",
        "where.title": "заголовок",
        "where.description": "описание",
        "where.authorName": "имя автора",
        "where.authorUrl": "ссылка автора",
        "where.authorIcon": "значок автора",
        "where.url": "ссылка заголовка",
        "where.image": "изображение",
        "where.thumbnail": "миниатюра",
        "where.footerText": "текст подвала",
        "where.footerIcon": "значок подвала",
        "where.color": "цвет",
        "where.timestamp": "отметка времени",
        "where.name": "название",
        "where.value": "значение",
        "error.noClient": "Не удалось найти API-клиент Discord",
        "error.createFailed": "Не удалось создать вебхук",
        "error.loadWebhooks": "Не удалось загрузить вебхуки канала",
        "error.rateLimited": "Discord просит подождать: попробуйте через {seconds} с",
        "error.notFound": "Этот вебхук или сообщение больше не существует",
        "error.status": "Discord вернул ошибку {status}",
        "error.pickWebhook": "Сначала выберите вебхук или создайте новый",
        "error.sendFailed": "Не удалось отправить",
        "error.badLink": "Это не ссылка на сообщение Discord",
        "error.loadMessage": "Не удалось открыть сообщение. Его отправил выбранный вебхук?",
        "error.notJson": "Это не корректный JSON",
        "error.notMessage": "Этот JSON не является сообщением или эмбедом",
        "toast.copyFailed": "Не удалось скопировать",
        "toast.edited": "Сообщение обновлено",
        "toast.sent": "Отправлено в #{channel}",
        "toast.draftSaved": "Черновик сохранён",
        "toast.jsonCopied": "JSON скопирован",
        "mode.label": "Тип сообщения",
        "mode.classic": "Классическое",
        "mode.v2": "Компоненты V2",
        "mode.locked": "Отправленное сообщение сохраняет свой тип",
        "mode.v2Hint": "Соберите сообщение из блоков: текст, разделы, галереи, файлы и контейнеры. Вебхуки могут использовать только кнопки-ссылки; кнопкам с действиями и меню нужен бот.",
        "section.sender": "Отправитель",
        "section.files": "Файлы",
        "section.sendAs": "Отправить как",
        "webhook.auto": "При отправке в этом канале будет создан вебхук Evi Embeds.",
        "json.button": "JSON",
        "files.add": "Добавить файлы",
        "files.hint": "Используйте их в картинках и компонентах «Файл» или как attachment://имя.",
        "files.remove": "Убрать файл",
        "files.copyRef": "Копировать ссылку attachment://",
        "files.kept": "Уже в сообщении",
        "kind.text": "Текст",
        "kind.section": "Раздел",
        "kind.gallery": "Медиагалерея",
        "kind.separator": "Разделитель",
        "kind.file": "Файл",
        "kind.buttons": "Кнопки-ссылки",
        "kind.container": "Контейнер",
        "kindHint.text": "Текст с markdown, упоминаниями и эмодзи",
        "kindHint.section": "До 3 текстов с миниатюрой или кнопкой-ссылкой рядом",
        "kindHint.gallery": "От 1 до 10 картинок или видео сеткой",
        "kindHint.separator": "Отступ между компонентами, с линией или без",
        "kindHint.file": "Один из файлов, отправляемых с сообщением",
        "kindHint.buttons": "До 5 кнопок, открывающих ссылки",
        "kindHint.container": "Рамка с цветным акцентом вокруг других компонентов",
        "add.component": "Добавить компонент",
        "add.toContainer": "Добавить внутрь",
        "comp.content": "Текст",
        "comp.markdownHint": "Работает markdown: **жирный**, # заголовки, -# мелкий текст, [ссылки](https://…)",
        "comp.sectionText": "Текст {n}",
        "comp.addText": "Добавить текст",
        "comp.removeText": "Убрать текст",
        "comp.accessory": "Рядом с текстом",
        "comp.accessoryThumbnail": "Миниатюра",
        "comp.accessoryButton": "Кнопка-ссылка",
        "comp.thumbnailUrl": "Ссылка на миниатюру",
        "comp.mediaUrl": "Ссылка на картинку или видео",
        "comp.useFile": "Взять файл",
        "comp.alt": "Описание (альтернативный текст)",
        "comp.spoiler": "Скрыть как спойлер",
        "comp.item": "Картинка {n}",
        "comp.addItem": "Добавить картинку ({count}/{limit})",
        "comp.removeItem": "Убрать картинку",
        "comp.divider": "Показывать линию",
        "comp.spacing": "Отступ",
        "comp.spacingSmall": "Маленький",
        "comp.spacingLarge": "Большой",
        "comp.fileName": "Файл",
        "comp.filePick": "Выберите файл",
        "comp.fileNone": "Сначала добавьте файл в разделе «Файлы» ниже.",
        "comp.buttonsNote": "Вебхуки могут отправлять только кнопки, которые открывают ссылку.",
        "comp.button": "Кнопка {n}",
        "comp.label": "Надпись",
        "comp.link": "Ссылка",
        "comp.emoji": "Эмодзи",
        "comp.addButton": "Добавить кнопку ({count}/{limit})",
        "comp.removeButton": "Убрать кнопку",
        "comp.accent": "Цвет акцента",
        "comp.inside": "Внутри",
        "comp.emptyContainer": "Внутри пока ничего нет.",
        "comp.remove": "Убрать компонент",
        "summary.pictures": "Картинки: {count}",
        "summary.inside": "Внутри: {count}",
        "summary.line": "Линия",
        "summary.space": "Отступ",
        "color.none": "Без цвета",
        "color.custom": "Выбрать любой цвет",
        "color.swatch": "Цвет {hex}",
        "meter.components": "Компоненты",
        "meter.text": "Текст",
        "meter.embedText": "Текст во вставках",
        "message.embedChars": "Символов в этой вставке",
        "preview.empty": "Здесь появится сообщение, пока вы его собираете",
        "preview.spoiler": "Спойлер",
        "empty.v2": "Компонентов пока нет. Выберите один ниже, чтобы начать.",
        "problem.emptyComponent": "{where}: пусто",
        "problem.buttonNeedsLabel": "{where}: нужна надпись или эмодзи",
        "problem.noAttachment": "{where} использует {name}, но такого файла нет",
        "problem.tooManyComponents": "В сообщении может быть не больше {limit} компонентов (сейчас {count})",
        "problem.tooManyFiles": "В сообщении может быть не больше {limit} файлов",
        "problem.one": "1 проблема",
        "problem.count": "Проблем: {count}",
        "where.component": "Компонент {n}",
        "where.child": "элемент {n}",
        "where.text": "текст {n}",
        "where.item": "картинка {n}",
        "where.button": "кнопка {n}",
        "where.accessory": "миниатюра или кнопка",
        "where.media": "ссылка",
        "where.alt": "описание",
        "where.label": "надпись",
        "where.link": "ссылка",
        "where.componentText": "Весь текст вместе",
        "toast.skipped": "Интерактивные компоненты пропущены, вебхуки не могут их отправить: {count}",
        "toast.refCopied": "Ссылка attachment:// скопирована",
        "error.tooBig": "Эти файлы слишком большие для этого сервера",
        "action.sendShortcut": "Отправить (Ctrl+Enter)",
    },
    tr: {
        "menu.open": "Embed Oluşturucu",
        "command.description": "Embed oluştur ve bu kanalda bir webhook ile gönder",
        "dialog.title": "Embed Oluşturucu",
        "dialog.subtitle": "Bir webhook ile #{channel} kanalına gönderilir",
        "dialog.editing": "Webhook'un gönderdiği bir mesajı düzenliyorsun",
        "webhook.label": "Webhook",
        "webhook.loading": "Webhook'lar yükleniyor…",
        "webhook.none": "Bu kanalda henüz webhook yok.",
        "webhook.create": "Yeni webhook",
        "webhook.creating": "Oluşturuluyor…",
        "message.username": "Ad",
        "message.avatar": "Avatar URL'si",
        "message.content": "Mesaj",
        "message.total": "Embed'lerde {length} / {limit} karakter",
        "embed.title": "Embed {n}",
        "embed.authorName": "Yazar adı",
        "embed.authorUrl": "Yazar bağlantısı",
        "embed.authorIcon": "Yazar simgesi URL'si",
        "embed.titleField": "Başlık",
        "embed.url": "Başlık bağlantısı",
        "embed.description": "Açıklama",
        "embed.color": "Renk",
        "embed.image": "Görsel URL'si",
        "embed.thumbnail": "Küçük resim URL'si",
        "embed.footerText": "Alt bilgi metni",
        "embed.footerIcon": "Alt bilgi simgesi URL'si",
        "embed.timestamp": "Zaman damgası",
        "group.author": "Yazar",
        "group.body": "Gövde",
        "group.fields": "Alanlar ({count}/{limit})",
        "group.images": "Görseller",
        "group.footer": "Alt bilgi",
        "field.title": "Alan {n}",
        "field.inline": "Satır içi",
        "field.name": "Ad",
        "field.value": "Değer",
        "action.addEmbed": "Embed ekle ({count}/{limit})",
        "action.addField": "Alan ekle",
        "action.cancel": "İptal",
        "action.clear": "Temizle",
        "action.clearAll": "Baştan başla",
        "action.close": "Kapat",
        "action.copyJson": "JSON'u kopyala",
        "action.duplicate": "Çoğalt",
        "action.moveUp": "Yukarı taşı",
        "action.moveDown": "Aşağı taşı",
        "action.now": "Şimdi",
        "action.removeEmbed": "Embed'i kaldır",
        "action.removeField": "Alanı kaldır",
        "action.saveEdit": "Değişiklikleri kaydet",
        "action.send": "Gönder",
        "action.sending": "Gönderiliyor…",
        "preview.app": "APP",
        "preview.label": "Önizleme",
        "preview.today": "Bugün {time}",
        "import.button": "JSON içe aktar",
        "import.label": "Bir webhook mesajının JSON'unu yapıştır (Discohook'unki de olur)",
        "import.load": "Yükle",
        "edit.button": "Gönderilmiş bir mesajı düzenle",
        "edit.hint": "Seçili webhook'un gönderdiği bir mesaja sağ tıkla ve Mesaj Bağlantısını Kopyala'yı seç.",
        "edit.label": "Mesaj bağlantısı",
        "edit.load": "Aç",
        "edit.loading": "Açılıyor…",
        "edit.stop": "Yeni olarak gönder",
        "drafts.button": "Taslaklar",
        "drafts.title": "Kayıtlı taslaklar",
        "drafts.save": "Bunu kaydet",
        "drafts.none": "Henüz kayıtlı taslak yok.",
        "drafts.delete": "Taslağı sil",
        "drafts.untitled": "Başlıksız",
        "problem.tooLong": "{where} {length} karakter, en fazla {limit}",
        "problem.tooManyEmbeds": "Bir mesajda en fazla {limit} embed olabilir",
        "problem.tooManyFields": "Bir embed'de en fazla {limit} alan olabilir",
        "problem.badUrl": "{where} https:// ile başlayan bir bağlantı değil",
        "problem.badColor": "{where} #5865F2 gibi bir renk değil",
        "problem.badTimestamp": "{where} bir tarih değil",
        "problem.emptyEmbed": "{where} için başlık, metin, yazar, alt bilgi, alan ya da görsel gerekli",
        "problem.fieldNeedsBoth": "{where} için hem ad hem değer gerekli",
        "problem.empty": "Henüz gönderilecek bir şey yok",
        "problem.more": "ve {count} tane daha",
        "where.total": "Tüm embed'ler birlikte",
        "where.embed": "Embed {n}",
        "where.field": "alan {n}",
        "where.content": "Mesaj",
        "where.username": "Ad",
        "where.avatarUrl": "Avatar URL'si",
        "where.title": "başlık",
        "where.description": "açıklama",
        "where.authorName": "yazar adı",
        "where.authorUrl": "yazar bağlantısı",
        "where.authorIcon": "yazar simgesi",
        "where.url": "başlık bağlantısı",
        "where.image": "görsel",
        "where.thumbnail": "küçük resim",
        "where.footerText": "alt bilgi metni",
        "where.footerIcon": "alt bilgi simgesi",
        "where.color": "renk",
        "where.timestamp": "zaman damgası",
        "where.name": "ad",
        "where.value": "değer",
        "error.noClient": "Discord'un API istemcisi bulunamadı",
        "error.createFailed": "Webhook oluşturulamadı",
        "error.loadWebhooks": "Bu kanalın webhook'ları yüklenemedi",
        "error.rateLimited": "Discord yavaşla diyor: {seconds} sn sonra tekrar dene",
        "error.notFound": "Bu webhook ya da mesaj artık yok",
        "error.status": "Discord {status} hatasıyla yanıt verdi",
        "error.pickWebhook": "Önce bir webhook seç ya da yenisini oluştur",
        "error.sendFailed": "Gönderilemedi",
        "error.badLink": "Bu bir Discord mesaj bağlantısı değil",
        "error.loadMessage": "Mesaj açılamadı. Seçili webhook mu göndermişti?",
        "error.notJson": "Bu geçerli bir JSON değil",
        "error.notMessage": "Bu JSON bir mesaj ya da embed değil",
        "toast.copyFailed": "Kopyalanamadı",
        "toast.edited": "Mesaj güncellendi",
        "toast.sent": "#{channel} kanalına gönderildi",
        "toast.draftSaved": "Taslak kaydedildi",
        "toast.jsonCopied": "JSON kopyalandı",
        "mode.label": "Mesaj türü",
        "mode.classic": "Klasik",
        "mode.v2": "Bileşenler V2",
        "mode.locked": "Gönderilmiş bir mesaj türünü korur",
        "mode.v2Hint": "Mesajı bloklarla kur: metin, bölümler, galeriler, dosyalar ve kapsayıcılar. Webhook'lar yalnızca bağlantı düğmeleri kullanabilir; işlem yapan düğmeler ve menüler için bot gerekir.",
        "section.sender": "Gönderen",
        "section.files": "Dosyalar",
        "section.sendAs": "Gönderen",
        "webhook.auto": "Gönderince bu kanalda Evi Embeds adlı bir webhook oluşturulur.",
        "json.button": "JSON",
        "files.add": "Dosya ekle",
        "files.hint": "Resimlerde ve Dosya bileşenlerinde ya da attachment://ad olarak kullan.",
        "files.remove": "Dosyayı kaldır",
        "files.copyRef": "attachment:// bağlantısını kopyala",
        "files.kept": "Mesajda zaten var",
        "kind.text": "Metin",
        "kind.section": "Bölüm",
        "kind.gallery": "Medya galerisi",
        "kind.separator": "Ayırıcı",
        "kind.file": "Dosya",
        "kind.buttons": "Bağlantı düğmeleri",
        "kind.container": "Kapsayıcı",
        "kindHint.text": "Markdown, bahsetme ve emoji içeren metin",
        "kindHint.section": "Yanında küçük resim ya da bağlantı düğmesi olan en fazla 3 metin",
        "kindHint.gallery": "Izgara hâlinde 1 ile 10 arası resim ya da video",
        "kindHint.separator": "Bileşenler arasında çizgili ya da çizgisiz boşluk",
        "kindHint.file": "Mesajla gönderilen dosyalardan biri",
        "kindHint.buttons": "Bağlantı açan en fazla 5 düğme",
        "kindHint.container": "Diğer bileşenlerin çevresinde vurgu renkli bir kutu",
        "add.component": "Bileşen ekle",
        "add.toContainer": "İçine ekle",
        "comp.content": "Metin",
        "comp.markdownHint": "Markdown çalışır: **kalın**, # başlıklar, -# küçük metin, [bağlantılar](https://…)",
        "comp.sectionText": "Metin {n}",
        "comp.addText": "Metin ekle",
        "comp.removeText": "Metni kaldır",
        "comp.accessory": "Metnin yanında",
        "comp.accessoryThumbnail": "Küçük resim",
        "comp.accessoryButton": "Bağlantı düğmesi",
        "comp.thumbnailUrl": "Küçük resim bağlantısı",
        "comp.mediaUrl": "Resim ya da video bağlantısı",
        "comp.useFile": "Dosya kullan",
        "comp.alt": "Açıklama (alternatif metin)",
        "comp.spoiler": "Spoiler olarak işaretle",
        "comp.item": "Resim {n}",
        "comp.addItem": "Resim ekle ({count}/{limit})",
        "comp.removeItem": "Resmi kaldır",
        "comp.divider": "Çizgi göster",
        "comp.spacing": "Boşluk",
        "comp.spacingSmall": "Küçük",
        "comp.spacingLarge": "Büyük",
        "comp.fileName": "Dosya",
        "comp.filePick": "Dosya seç",
        "comp.fileNone": "Önce aşağıdaki Dosyalar bölümünden bir dosya ekle.",
        "comp.buttonsNote": "Webhook'lar yalnızca bağlantı açan düğmeler gönderebilir.",
        "comp.button": "Düğme {n}",
        "comp.label": "Etiket",
        "comp.link": "Bağlantı",
        "comp.emoji": "Emoji",
        "comp.addButton": "Düğme ekle ({count}/{limit})",
        "comp.removeButton": "Düğmeyi kaldır",
        "comp.accent": "Vurgu rengi",
        "comp.inside": "İçindekiler",
        "comp.emptyContainer": "İçinde henüz bir şey yok.",
        "comp.remove": "Bileşeni kaldır",
        "summary.pictures": "Resimler: {count}",
        "summary.inside": "İçinde: {count}",
        "summary.line": "Çizgi",
        "summary.space": "Boşluk",
        "color.none": "Renk yok",
        "color.custom": "İstediğin rengi seç",
        "color.swatch": "Renk {hex}",
        "meter.components": "Bileşenler",
        "meter.text": "Metin",
        "meter.embedText": "Embed'lerdeki metin",
        "message.embedChars": "Bu embed'deki karakterler",
        "preview.empty": "Mesajın sen kurdukça burada görünür",
        "preview.spoiler": "Spoiler",
        "empty.v2": "Henüz bileşen yok. Başlamak için aşağıdan birini seç.",
        "problem.emptyComponent": "{where} boş",
        "problem.buttonNeedsLabel": "{where} için bir etiket ya da emoji gerekli",
        "problem.noAttachment": "{where} {name} dosyasını kullanıyor ama bu dosya listede yok",
        "problem.tooManyComponents": "Bir mesajda en fazla {limit} bileşen olabilir (bunda {count} var)",
        "problem.tooManyFiles": "Bir mesajda en fazla {limit} dosya olabilir",
        "problem.one": "1 sorun",
        "problem.count": "Sorunlar: {count}",
        "where.component": "Bileşen {n}",
        "where.child": "öğe {n}",
        "where.text": "metin {n}",
        "where.item": "resim {n}",
        "where.button": "düğme {n}",
        "where.accessory": "küçük resim ya da düğme",
        "where.media": "bağlantı",
        "where.alt": "açıklama",
        "where.label": "etiket",
        "where.link": "bağlantı",
        "where.componentText": "Tüm metin birlikte",
        "toast.skipped": "Etkileşimli bileşenler dışarıda bırakıldı, webhook'lar bunları gönderemez: {count}",
        "toast.refCopied": "attachment:// bağlantısı kopyalandı",
        "error.tooBig": "Bu dosyalar bu sunucu için çok büyük",
        "action.sendShortcut": "Gönder (Ctrl+Enter)",
    },
});
