import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "title.danger": "This link looks dangerous",
        "title.caution": "This link might not be safe",
        "subtitle.danger": "It has signs of a scam or phishing link.",
        "subtitle.caution": "Something about it is unusual. Check where it goes before you open it.",
        "label.destination": "Where it really goes",
        "hint.written": "Written as {host}",
        "button.open": "Open anyway",
        "button.back": "Go back",
        "settings.threshold": "Warn me about",
        "settings.threshold.description": "Which links get a warning before they open.",
        "settings.threshold.caution": "Suspicious and dangerous links",
        "settings.threshold.danger": "Only dangerous links",
        "settings.allowlist": "Trusted domains",
        "settings.allowlist.description": "Links to these domains and their subdomains never get a warning. Separate them with commas or new lines.",
        "settings.allowlist.placeholder": "example.com, mysite.dev",
        "finding.unreadable": "This link couldn't be read as a normal web address.",
        "finding.allowlisted": "{domain} is on your allowlist.",
        "finding.masked-mismatch": "The link says {shown} but actually goes to {host}.",
        "finding.masked-mention": "The link text mentions {shown}, but the link goes to {host}.",
        "finding.userinfo-host": "Everything before the \"@\" is ignored: this link starts with \"{fake}\" but goes to {host}.",
        "finding.userinfo-hidden": "The link has a hidden \"name@\" part before the address. It goes to {host}.",
        "finding.ip-address": "Goes to a bare IP address ({host}) instead of a named website. Real services almost never link like this.",
        "finding.mixed-script": "The address mixes alphabets (like Latin with Cyrillic or Greek) in \"{labels}\", a trick to make a fake domain look real.",
        "finding.punycode": "The address uses international characters ({display}, written {host}). Some of these are lookalikes of normal letters.",
        "finding.subdomain-trick": "Starts with {hit} but the site is really {domain}. Everything to the left of it is just a label its owner picked.",
        "finding.brand-tld": "Uses {brand}'s name on a domain {brand} doesn't own: this is {domain}, not {official}.",
        "finding.lookalike-swap": "{domain} is made to look like {official} by swapping lookalike characters. It isn't run by {brand}.",
        "finding.lookalike": "{domain} imitates {brand}'s name with lookalike characters. It isn't run by {brand}.",
        "finding.brand-scam": "Puts {brand}'s name next to words like \"gift\", \"free\" or \"login\" on a site {brand} doesn't run ({domain}). That's how most phishing links look.",
        "finding.brand-mention": "Has {brand}'s name in it but isn't one of {brand}'s sites: {domain} is run by someone else.",
        "finding.typosquat": "{domain} is one or two letters off from {official}. Typo domains like this are often used to steal accounts.",
        "finding.file-tld": "The address ends in .{tld}, which looks like a file name but is a website.",
        "finding.shortener": "{domain} is a link shortener: where it really leads is hidden until you open it.",
        "finding.free-hosting": "Hosted on {suffix}, where anyone can make a site for free.",
        "finding.scam-words-free-nitro": "Mentions free Nitro, the most common bait in Discord scams.",
        "finding.scam-words-nitro-giveaway": "Mentions a Nitro giveaway, the most common bait in Discord scams.",
        "finding.scam-words-discord-gift": "Mentions a Discord gift, the most common bait in Discord scams.",
        "finding.scam-words-steam": "Mentions a Steam gift or trade, the most common bait in Discord scams.",
        "finding.scam-words-currency": "Mentions free in-game currency or skins, the most common bait in Discord scams.",
        "finding.scam-words-crypto": "Mentions a crypto airdrop, the most common bait in Discord scams.",
        "finding.dangerous-file-disguised": "Downloads \"{file}\", a program disguised as a .{fake} file.",
        "finding.dangerous-file": "Downloads a .{ext} file (\"{file}\"), which can run code on your computer. Only open it if you trust the sender.",
        "finding.http": "The connection to this site isn't encrypted (http).",
    },
    de: {
        "title.danger": "Dieser Link sieht gefährlich aus",
        "title.caution": "Dieser Link ist möglicherweise nicht sicher",
        "subtitle.danger": "Er weist Anzeichen eines Betrugs- oder Phishing-Links auf.",
        "subtitle.caution": "Etwas daran ist ungewöhnlich. Prüfe, wohin er führt, bevor du ihn öffnest.",
        "label.destination": "Wohin er wirklich führt",
        "hint.written": "Geschrieben als {host}",
        "button.open": "Trotzdem öffnen",
        "button.back": "Zurück",
        "settings.threshold": "Warnen bei",
        "settings.threshold.description": "Bei welchen Links vor dem Öffnen gewarnt wird.",
        "settings.threshold.caution": "Verdächtigen und gefährlichen Links",
        "settings.threshold.danger": "Nur gefährlichen Links",
        "settings.allowlist": "Vertrauenswürdige Domains",
        "settings.allowlist.description": "Bei Links zu diesen Domains und ihren Subdomains wird nie gewarnt. Trenne sie mit Kommas oder Zeilenumbrüchen.",
        "settings.allowlist.placeholder": "example.com, meineseite.de",
        "finding.unreadable": "Dieser Link konnte nicht als normale Webadresse gelesen werden.",
        "finding.allowlisted": "{domain} steht auf deiner Liste vertrauenswürdiger Domains.",
        "finding.masked-mismatch": "Der Link gibt {shown} an, führt aber in Wirklichkeit zu {host}.",
        "finding.masked-mention": "Der Linktext erwähnt {shown}, der Link führt aber zu {host}.",
        "finding.userinfo-host": "Alles vor dem „@“ wird ignoriert: Dieser Link beginnt mit „{fake}“, führt aber zu {host}.",
        "finding.userinfo-hidden": "Der Link hat vor der Adresse einen versteckten „Name@“-Teil. Er führt zu {host}.",
        "finding.ip-address": "Führt zu einer nackten IP-Adresse ({host}) statt zu einer Website mit Namen. Echte Dienste verlinken fast nie so.",
        "finding.mixed-script": "Die Adresse mischt Alphabete (etwa lateinisch mit kyrillisch oder griechisch) in „{labels}“, ein Trick, um eine gefälschte Domain echt aussehen zu lassen.",
        "finding.punycode": "Die Adresse enthält internationale Zeichen ({display}, geschrieben {host}). Manche davon sehen normalen Buchstaben zum Verwechseln ähnlich.",
        "finding.subdomain-trick": "Beginnt mit {hit}, die Seite ist aber in Wirklichkeit {domain}. Alles links davon ist nur eine Bezeichnung, die sich der Betreiber ausgesucht hat.",
        "finding.brand-tld": "Verwendet den Namen {brand} auf einer Domain, die {brand} nicht gehört: Das ist {domain}, nicht {official}.",
        "finding.lookalike-swap": "{domain} soll durch ähnlich aussehende Zeichen wie {official} wirken. Sie wird nicht von {brand} betrieben.",
        "finding.lookalike": "{domain} ahmt den Namen {brand} mit ähnlich aussehenden Zeichen nach. Sie wird nicht von {brand} betrieben.",
        "finding.brand-scam": "Setzt den Namen {brand} neben Wörter wie „gift“, „free“ oder „login“ auf einer Seite, die nicht von {brand} betrieben wird ({domain}). So sehen die meisten Phishing-Links aus.",
        "finding.brand-mention": "Enthält den Namen {brand}, ist aber keine Seite von {brand}: {domain} gehört jemand anderem.",
        "finding.typosquat": "{domain} unterscheidet sich nur um ein oder zwei Buchstaben von {official}. Solche Tippfehler-Domains werden oft benutzt, um Konten zu stehlen.",
        "finding.file-tld": "Die Adresse endet auf .{tld}, was wie ein Dateiname aussieht, aber eine Website ist.",
        "finding.shortener": "{domain} ist ein Link-Verkürzer: Wohin der Link wirklich führt, siehst du erst nach dem Öffnen.",
        "finding.free-hosting": "Gehostet auf {suffix}, wo jeder kostenlos eine Website erstellen kann.",
        "finding.scam-words-free-nitro": "Erwähnt kostenloses Nitro, den häufigsten Köder bei Discord-Betrug.",
        "finding.scam-words-nitro-giveaway": "Erwähnt ein Nitro-Gewinnspiel, den häufigsten Köder bei Discord-Betrug.",
        "finding.scam-words-discord-gift": "Erwähnt ein Discord-Geschenk, den häufigsten Köder bei Discord-Betrug.",
        "finding.scam-words-steam": "Erwähnt ein Steam-Geschenk oder einen Steam-Handel, den häufigsten Köder bei Discord-Betrug.",
        "finding.scam-words-currency": "Erwähnt kostenlose Spielwährung oder Skins, den häufigsten Köder bei Discord-Betrug.",
        "finding.scam-words-crypto": "Erwähnt einen Krypto-Airdrop, den häufigsten Köder bei Discord-Betrug.",
        "finding.dangerous-file-disguised": "Lädt „{file}“ herunter, ein Programm, das als .{fake}-Datei getarnt ist.",
        "finding.dangerous-file": "Lädt eine .{ext}-Datei („{file}“) herunter, die Code auf deinem Computer ausführen kann. Öffne sie nur, wenn du dem Absender vertraust.",
        "finding.http": "Die Verbindung zu dieser Seite ist nicht verschlüsselt (http).",
    },
    es: {
        "title.danger": "Este enlace parece peligroso",
        "title.caution": "Este enlace podría no ser seguro",
        "subtitle.danger": "Tiene señales de ser un enlace de estafa o phishing.",
        "subtitle.caution": "Hay algo raro en él. Comprueba adónde lleva antes de abrirlo.",
        "label.destination": "Adónde lleva realmente",
        "hint.written": "Escrito como {host}",
        "button.open": "Abrir de todos modos",
        "button.back": "Volver",
        "settings.threshold": "Avisarme de",
        "settings.threshold.description": "Qué enlaces muestran una advertencia antes de abrirse.",
        "settings.threshold.caution": "Enlaces sospechosos y peligrosos",
        "settings.threshold.danger": "Solo enlaces peligrosos",
        "settings.allowlist": "Dominios de confianza",
        "settings.allowlist.description": "Los enlaces a estos dominios y sus subdominios nunca muestran advertencia. Sepáralos con comas o saltos de línea.",
        "settings.allowlist.placeholder": "example.com, misitio.es",
        "finding.unreadable": "Este enlace no se pudo leer como una dirección web normal.",
        "finding.allowlisted": "{domain} está en tu lista de dominios de confianza.",
        "finding.masked-mismatch": "El enlace dice {shown}, pero en realidad lleva a {host}.",
        "finding.masked-mention": "El texto del enlace menciona {shown}, pero el enlace lleva a {host}.",
        "finding.userinfo-host": "Todo lo que va antes de la «@» se ignora: este enlace empieza por «{fake}», pero lleva a {host}.",
        "finding.userinfo-hidden": "El enlace tiene una parte «nombre@» oculta antes de la dirección. Lleva a {host}.",
        "finding.ip-address": "Lleva a una dirección IP sin más ({host}) en lugar de a un sitio web con nombre. Los servicios reales casi nunca enlazan así.",
        "finding.mixed-script": "La dirección mezcla alfabetos (como latino con cirílico o griego) en «{labels}», un truco para que un dominio falso parezca real.",
        "finding.punycode": "La dirección usa caracteres internacionales ({display}, escrito {host}). Algunos se parecen a letras normales.",
        "finding.subdomain-trick": "Empieza por {hit}, pero el sitio es en realidad {domain}. Todo lo que hay a su izquierda es solo una etiqueta que eligió su dueño.",
        "finding.brand-tld": "Usa el nombre de {brand} en un dominio que {brand} no posee: esto es {domain}, no {official}.",
        "finding.lookalike-swap": "{domain} está hecho para parecerse a {official} cambiando caracteres parecidos. No es de {brand}.",
        "finding.lookalike": "{domain} imita el nombre de {brand} con caracteres parecidos. No es de {brand}.",
        "finding.brand-scam": "Pone el nombre de {brand} junto a palabras como «gift», «free» o «login» en un sitio que {brand} no gestiona ({domain}). Así son la mayoría de los enlaces de phishing.",
        "finding.brand-mention": "Contiene el nombre de {brand}, pero no es un sitio de {brand}: {domain} pertenece a otra persona.",
        "finding.typosquat": "{domain} se diferencia en una o dos letras de {official}. Los dominios con erratas como este se suelen usar para robar cuentas.",
        "finding.file-tld": "La dirección termina en .{tld}, que parece el nombre de un archivo pero es un sitio web.",
        "finding.shortener": "{domain} es un acortador de enlaces: no sabrás adónde lleva realmente hasta que lo abras.",
        "finding.free-hosting": "Alojado en {suffix}, donde cualquiera puede crear un sitio gratis.",
        "finding.scam-words-free-nitro": "Menciona Nitro gratis, el cebo más común en las estafas de Discord.",
        "finding.scam-words-nitro-giveaway": "Menciona un sorteo de Nitro, el cebo más común en las estafas de Discord.",
        "finding.scam-words-discord-gift": "Menciona un regalo de Discord, el cebo más común en las estafas de Discord.",
        "finding.scam-words-steam": "Menciona un regalo o intercambio de Steam, el cebo más común en las estafas de Discord.",
        "finding.scam-words-currency": "Menciona moneda de juego o skins gratis, el cebo más común en las estafas de Discord.",
        "finding.scam-words-crypto": "Menciona un airdrop de criptomonedas, el cebo más común en las estafas de Discord.",
        "finding.dangerous-file-disguised": "Descarga «{file}», un programa disfrazado de archivo .{fake}.",
        "finding.dangerous-file": "Descarga un archivo .{ext} («{file}») que puede ejecutar código en tu ordenador. Ábrelo solo si confías en quien te lo envió.",
        "finding.http": "La conexión con este sitio no está cifrada (http).",
    },
    fr: {
        "title.danger": "Ce lien semble dangereux",
        "title.caution": "Ce lien n'est peut-être pas sûr",
        "subtitle.danger": "Il présente des signes d'arnaque ou de lien d'hameçonnage.",
        "subtitle.caution": "Quelque chose d'inhabituel. Vérifiez où il mène avant de l'ouvrir.",
        "label.destination": "Où il mène vraiment",
        "hint.written": "Écrit comme {host}",
        "button.open": "Ouvrir quand même",
        "button.back": "Retour",
        "settings.threshold": "M'avertir pour",
        "settings.threshold.description": "Les liens qui déclenchent un avertissement avant d'être ouverts.",
        "settings.threshold.caution": "Les liens suspects et dangereux",
        "settings.threshold.danger": "Uniquement les liens dangereux",
        "settings.allowlist": "Domaines de confiance",
        "settings.allowlist.description": "Les liens vers ces domaines et leurs sous-domaines n'affichent jamais d'avertissement. Séparez-les par des virgules ou des retours à la ligne.",
        "settings.allowlist.placeholder": "example.com, monsite.fr",
        "finding.unreadable": "Ce lien n'a pas pu être lu comme une adresse web normale.",
        "finding.allowlisted": "{domain} figure dans votre liste de confiance.",
        "finding.masked-mismatch": "Le lien affiche {shown} mais mène en réalité à {host}.",
        "finding.masked-mention": "Le texte du lien mentionne {shown}, mais le lien mène à {host}.",
        "finding.userinfo-host": "Tout ce qui précède le « @ » est ignoré : ce lien commence par « {fake} » mais mène à {host}.",
        "finding.userinfo-hidden": "Le lien contient une partie « nom@ » cachée avant l'adresse. Il mène à {host}.",
        "finding.ip-address": "Mène à une simple adresse IP ({host}) plutôt qu'à un site nommé. Les vrais services ne font presque jamais de liens comme ça.",
        "finding.mixed-script": "L'adresse mélange des alphabets (comme le latin avec le cyrillique ou le grec) dans « {labels} », une astuce pour qu'un faux domaine paraisse authentique.",
        "finding.punycode": "L'adresse utilise des caractères internationaux ({display}, écrit {host}). Certains ressemblent à des lettres normales.",
        "finding.subdomain-trick": "Commence par {hit} mais le site est en réalité {domain}. Tout ce qui se trouve à gauche n'est qu'une étiquette choisie par son propriétaire.",
        "finding.brand-tld": "Utilise le nom de {brand} sur un domaine qui n'appartient pas à {brand} : il s'agit de {domain}, pas de {official}.",
        "finding.lookalike-swap": "{domain} est fait pour ressembler à {official} en remplaçant des caractères par d'autres qui leur ressemblent. Ce site n'est pas géré par {brand}.",
        "finding.lookalike": "{domain} imite le nom de {brand} avec des caractères qui y ressemblent. Ce site n'est pas géré par {brand}.",
        "finding.brand-scam": "Place le nom de {brand} à côté de mots comme « gift », « free » ou « login » sur un site que {brand} ne gère pas ({domain}). C'est l'allure de la plupart des liens d'hameçonnage.",
        "finding.brand-mention": "Contient le nom de {brand} mais n'est pas un site de {brand} : {domain} appartient à quelqu'un d'autre.",
        "finding.typosquat": "{domain} diffère de {official} d'une ou deux lettres. Ces domaines avec faute de frappe servent souvent à voler des comptes.",
        "finding.file-tld": "L'adresse se termine par .{tld}, qui ressemble à un nom de fichier mais désigne un site web.",
        "finding.shortener": "{domain} est un raccourcisseur de liens : impossible de savoir où il mène avant de l'ouvrir.",
        "finding.free-hosting": "Hébergé sur {suffix}, où n'importe qui peut créer un site gratuitement.",
        "finding.scam-words-free-nitro": "Mentionne du Nitro gratuit, l'appât le plus courant des arnaques sur Discord.",
        "finding.scam-words-nitro-giveaway": "Mentionne un giveaway Nitro, l'appât le plus courant des arnaques sur Discord.",
        "finding.scam-words-discord-gift": "Mentionne un cadeau Discord, l'appât le plus courant des arnaques sur Discord.",
        "finding.scam-words-steam": "Mentionne un cadeau ou un échange Steam, l'appât le plus courant des arnaques sur Discord.",
        "finding.scam-words-currency": "Mentionne de la monnaie de jeu ou des skins gratuits, l'appât le plus courant des arnaques sur Discord.",
        "finding.scam-words-crypto": "Mentionne un airdrop de cryptomonnaie, l'appât le plus courant des arnaques sur Discord.",
        "finding.dangerous-file-disguised": "Télécharge « {file} », un programme déguisé en fichier .{fake}.",
        "finding.dangerous-file": "Télécharge un fichier .{ext} (« {file} ») qui peut exécuter du code sur votre ordinateur. Ne l'ouvrez que si vous faites confiance à l'expéditeur.",
        "finding.http": "La connexion à ce site n'est pas chiffrée (http).",
    },
    ja: {
        "title.danger": "このリンクは危険そうです",
        "title.caution": "このリンクは安全でない可能性があります",
        "subtitle.danger": "詐欺やフィッシングのリンクの特徴があります。",
        "subtitle.caution": "不審な点があります。開く前にリンク先を確認してください。",
        "label.destination": "実際のリンク先",
        "hint.written": "表記: {host}",
        "button.open": "このまま開く",
        "button.back": "戻る",
        "settings.threshold": "警告するリンク",
        "settings.threshold.description": "開く前に警告を表示するリンクを選びます。",
        "settings.threshold.caution": "不審なリンクと危険なリンク",
        "settings.threshold.danger": "危険なリンクのみ",
        "settings.allowlist": "信頼するドメイン",
        "settings.allowlist.description": "これらのドメインとそのサブドメインへのリンクには警告を表示しません。カンマまたは改行で区切ってください。",
        "settings.allowlist.placeholder": "example.com, mysite.dev",
        "finding.unreadable": "このリンクは通常のウェブアドレスとして読み取れませんでした。",
        "finding.allowlisted": "{domain} は信頼するドメインに登録されています。",
        "finding.masked-mismatch": "リンクには {shown} と表示されていますが、実際のリンク先は {host} です。",
        "finding.masked-mention": "リンクの文字列に {shown} とありますが、実際のリンク先は {host} です。",
        "finding.userinfo-host": "「@」より前の部分は無視されます。このリンクは「{fake}」で始まっていますが、実際のリンク先は {host} です。",
        "finding.userinfo-hidden": "アドレスの前に「名前@」という隠された部分があります。リンク先は {host} です。",
        "finding.ip-address": "名前のあるウェブサイトではなく、IPアドレス ({host}) に直接つながります。正規のサービスがこのようなリンクを使うことはほとんどありません。",
        "finding.mixed-script": "アドレスの「{labels}」に複数の文字体系(ラテン文字とキリル文字やギリシャ文字など)が混在しています。偽のドメインを本物に見せかける手口です。",
        "finding.punycode": "アドレスに国際文字が使われています ({display}、実際の表記は {host})。通常の文字にそっくりなものもあります。",
        "finding.subdomain-trick": "{hit} で始まっていますが、実際のサイトは {domain} です。その左側にあるのは、所有者が好きに付けたラベルにすぎません。",
        "finding.brand-tld": "{brand} 以外が所有するドメインで {brand} の名前を使っています。これは {official} ではなく {domain} です。",
        "finding.lookalike-swap": "{domain} は、似た文字に置き換えて {official} に見せかけています。{brand} が運営しているものではありません。",
        "finding.lookalike": "{domain} は、似た文字を使って {brand} の名前をまねています。{brand} が運営しているものではありません。",
        "finding.brand-scam": "{brand} が運営していないサイト ({domain}) で、{brand} の名前を「gift」「free」「login」などの言葉と並べています。フィッシングリンクによくある形です。",
        "finding.brand-mention": "{brand} の名前が含まれていますが、{brand} のサイトではありません。{domain} は別の誰かが運営しています。",
        "finding.typosquat": "{domain} は {official} と1〜2文字しか違いません。このようなタイプミスを狙ったドメインは、アカウントの乗っ取りによく使われます。",
        "finding.file-tld": "アドレスが .{tld} で終わっています。ファイル名のように見えますが、ウェブサイトです。",
        "finding.shortener": "{domain} は短縮URLサービスです。開くまで本当のリンク先はわかりません。",
        "finding.free-hosting": "誰でも無料でサイトを作れる {suffix} で公開されています。",
        "finding.scam-words-free-nitro": "無料のNitroに言及しています。Discord詐欺で最もよくある餌です。",
        "finding.scam-words-nitro-giveaway": "Nitroのプレゼント企画に言及しています。Discord詐欺で最もよくある餌です。",
        "finding.scam-words-discord-gift": "Discordのギフトに言及しています。Discord詐欺で最もよくある餌です。",
        "finding.scam-words-steam": "Steamのギフトやトレードに言及しています。Discord詐欺で最もよくある餌です。",
        "finding.scam-words-currency": "無料のゲーム内通貨やスキンに言及しています。Discord詐欺で最もよくある餌です。",
        "finding.scam-words-crypto": "暗号資産のエアドロップに言及しています。Discord詐欺で最もよくある餌です。",
        "finding.dangerous-file-disguised": "「{file}」をダウンロードします。.{fake} ファイルに偽装したプログラムです。",
        "finding.dangerous-file": ".{ext} ファイル(「{file}」)をダウンロードします。パソコン上でコードが実行される可能性があります。送信者が信頼できる場合のみ開いてください。",
        "finding.http": "このサイトとの接続は暗号化されていません (http)。",
    },
    pl: {
        "title.danger": "Ten link wygląda niebezpiecznie",
        "title.caution": "Ten link może być niebezpieczny",
        "subtitle.danger": "Ma cechy linku oszukańczego lub phishingowego.",
        "subtitle.caution": "Coś w nim jest nietypowego. Sprawdź, dokąd prowadzi, zanim go otworzysz.",
        "label.destination": "Dokąd naprawdę prowadzi",
        "hint.written": "Zapisano jako {host}",
        "button.open": "Otwórz mimo to",
        "button.back": "Wróć",
        "settings.threshold": "Ostrzegaj przed",
        "settings.threshold.description": "Które linki wyświetlają ostrzeżenie przed otwarciem.",
        "settings.threshold.caution": "Podejrzanymi i niebezpiecznymi linkami",
        "settings.threshold.danger": "Tylko niebezpiecznymi linkami",
        "settings.allowlist": "Zaufane domeny",
        "settings.allowlist.description": "Linki do tych domen i ich subdomen nigdy nie wyświetlają ostrzeżenia. Oddziel je przecinkami lub nowymi wierszami.",
        "settings.allowlist.placeholder": "example.com, mojastrona.pl",
        "finding.unreadable": "Nie udało się odczytać tego linku jako zwykłego adresu internetowego.",
        "finding.allowlisted": "{domain} jest na twojej liście zaufanych domen.",
        "finding.masked-mismatch": "Link pokazuje {shown}, ale w rzeczywistości prowadzi do {host}.",
        "finding.masked-mention": "Tekst linku wspomina o {shown}, ale link prowadzi do {host}.",
        "finding.userinfo-host": "Wszystko przed „@” jest ignorowane: ten link zaczyna się od „{fake}”, ale prowadzi do {host}.",
        "finding.userinfo-hidden": "Link ma przed adresem ukrytą część „nazwa@”. Prowadzi do {host}.",
        "finding.ip-address": "Prowadzi do samego adresu IP ({host}) zamiast do strony z nazwą. Prawdziwe usługi prawie nigdy tak nie linkują.",
        "finding.mixed-script": "Adres miesza alfabety (np. łaciński z cyrylicą lub greką) w „{labels}” — to sztuczka, by fałszywa domena wyglądała wiarygodnie.",
        "finding.punycode": "Adres zawiera znaki międzynarodowe ({display}, zapisane jako {host}). Niektóre z nich wyglądają jak zwykłe litery.",
        "finding.subdomain-trick": "Zaczyna się od {hit}, ale strona to naprawdę {domain}. Wszystko po lewej to tylko nazwa wybrana przez właściciela.",
        "finding.brand-tld": "Używa nazwy {brand} w domenie, która nie należy do {brand}: to {domain}, a nie {official}.",
        "finding.lookalike-swap": "{domain} ma udawać {official} dzięki podmienionym, podobnie wyglądającym znakom. Nie należy do {brand}.",
        "finding.lookalike": "{domain} podszywa się pod nazwę {brand} za pomocą podobnie wyglądających znaków. Nie należy do {brand}.",
        "finding.brand-scam": "Zestawia nazwę {brand} ze słowami takimi jak „gift”, „free” czy „login” na stronie, której {brand} nie prowadzi ({domain}). Tak wygląda większość linków phishingowych.",
        "finding.brand-mention": "Zawiera nazwę {brand}, ale nie jest stroną {brand}: {domain} należy do kogoś innego.",
        "finding.typosquat": "{domain} różni się od {official} o jedną lub dwie litery. Takie domeny z literówką często służą do kradzieży kont.",
        "finding.file-tld": "Adres kończy się na .{tld}, co wygląda jak nazwa pliku, ale jest stroną internetową.",
        "finding.shortener": "{domain} to skracacz linków: dokąd naprawdę prowadzi, zobaczysz dopiero po otwarciu.",
        "finding.free-hosting": "Hostowane na {suffix}, gdzie każdy może za darmo założyć stronę.",
        "finding.scam-words-free-nitro": "Wspomina o darmowym Nitro, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.scam-words-nitro-giveaway": "Wspomina o rozdaniu Nitro, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.scam-words-discord-gift": "Wspomina o prezencie od Discorda, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.scam-words-steam": "Wspomina o prezencie lub wymianie na Steamie, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.scam-words-currency": "Wspomina o darmowej walucie w grze lub skinach, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.scam-words-crypto": "Wspomina o airdropie kryptowalut, najczęstszej przynęcie w oszustwach na Discordzie.",
        "finding.dangerous-file-disguised": "Pobiera „{file}”, program udający plik .{fake}.",
        "finding.dangerous-file": "Pobiera plik .{ext} („{file}”), który może uruchomić kod na twoim komputerze. Otwieraj go tylko wtedy, gdy ufasz nadawcy.",
        "finding.http": "Połączenie z tą stroną nie jest szyfrowane (http).",
    },
    "pt-BR": {
        "title.danger": "Este link parece perigoso",
        "title.caution": "Este link pode não ser seguro",
        "subtitle.danger": "Ele tem sinais de golpe ou de link de phishing.",
        "subtitle.caution": "Tem algo estranho nele. Confira para onde ele leva antes de abrir.",
        "label.destination": "Para onde ele realmente leva",
        "hint.written": "Escrito como {host}",
        "button.open": "Abrir mesmo assim",
        "button.back": "Voltar",
        "settings.threshold": "Avisar sobre",
        "settings.threshold.description": "Quais links mostram um aviso antes de abrir.",
        "settings.threshold.caution": "Links suspeitos e perigosos",
        "settings.threshold.danger": "Só links perigosos",
        "settings.allowlist": "Domínios confiáveis",
        "settings.allowlist.description": "Links para esses domínios e seus subdomínios nunca mostram aviso. Separe-os com vírgulas ou quebras de linha.",
        "settings.allowlist.placeholder": "example.com, meusite.com.br",
        "finding.unreadable": "Não foi possível ler este link como um endereço web normal.",
        "finding.allowlisted": "{domain} está na sua lista de domínios confiáveis.",
        "finding.masked-mismatch": "O link diz {shown}, mas na verdade leva para {host}.",
        "finding.masked-mention": "O texto do link menciona {shown}, mas o link leva para {host}.",
        "finding.userinfo-host": "Tudo antes do \"@\" é ignorado: este link começa com \"{fake}\", mas leva para {host}.",
        "finding.userinfo-hidden": "O link tem uma parte \"nome@\" escondida antes do endereço. Ele leva para {host}.",
        "finding.ip-address": "Leva para um endereço IP puro ({host}) em vez de um site com nome. Serviços de verdade quase nunca usam links assim.",
        "finding.mixed-script": "O endereço mistura alfabetos (como latino com cirílico ou grego) em \"{labels}\", um truque para fazer um domínio falso parecer verdadeiro.",
        "finding.punycode": "O endereço usa caracteres internacionais ({display}, escrito {host}). Alguns deles são parecidos com letras comuns.",
        "finding.subdomain-trick": "Começa com {hit}, mas o site na verdade é {domain}. Tudo que está à esquerda é só um rótulo escolhido pelo dono.",
        "finding.brand-tld": "Usa o nome {brand} em um domínio que não pertence à {brand}: este é {domain}, não {official}.",
        "finding.lookalike-swap": "{domain} foi feito para parecer {official} trocando caracteres parecidos. Ele não é da {brand}.",
        "finding.lookalike": "{domain} imita o nome {brand} com caracteres parecidos. Ele não é da {brand}.",
        "finding.brand-scam": "Coloca o nome {brand} ao lado de palavras como \"gift\", \"free\" ou \"login\" em um site que a {brand} não administra ({domain}). É assim que a maioria dos links de phishing se parece.",
        "finding.brand-mention": "Tem o nome {brand} nele, mas não é um site da {brand}: {domain} pertence a outra pessoa.",
        "finding.typosquat": "{domain} tem só uma ou duas letras de diferença de {official}. Domínios com erro de digitação como esse costumam ser usados para roubar contas.",
        "finding.file-tld": "O endereço termina em .{tld}, que parece nome de arquivo, mas é um site.",
        "finding.shortener": "{domain} é um encurtador de links: só dá para saber para onde ele leva depois de abrir.",
        "finding.free-hosting": "Hospedado em {suffix}, onde qualquer pessoa pode criar um site de graça.",
        "finding.scam-words-free-nitro": "Menciona Nitro grátis, a isca mais comum nos golpes do Discord.",
        "finding.scam-words-nitro-giveaway": "Menciona um sorteio de Nitro, a isca mais comum nos golpes do Discord.",
        "finding.scam-words-discord-gift": "Menciona um presente do Discord, a isca mais comum nos golpes do Discord.",
        "finding.scam-words-steam": "Menciona um presente ou troca da Steam, a isca mais comum nos golpes do Discord.",
        "finding.scam-words-currency": "Menciona moeda de jogo ou skins grátis, a isca mais comum nos golpes do Discord.",
        "finding.scam-words-crypto": "Menciona um airdrop de criptomoedas, a isca mais comum nos golpes do Discord.",
        "finding.dangerous-file-disguised": "Baixa \"{file}\", um programa disfarçado de arquivo .{fake}.",
        "finding.dangerous-file": "Baixa um arquivo .{ext} (\"{file}\"), que pode executar código no seu computador. Só abra se confiar em quem enviou.",
        "finding.http": "A conexão com este site não é criptografada (http).",
    },
    ru: {
        "title.danger": "Эта ссылка выглядит опасной",
        "title.caution": "Эта ссылка может быть небезопасной",
        "subtitle.danger": "Есть признаки мошеннической или фишинговой ссылки.",
        "subtitle.caution": "В ней есть что-то необычное. Проверьте, куда она ведёт, прежде чем открывать.",
        "label.destination": "Куда она ведёт на самом деле",
        "hint.written": "Записано как {host}",
        "button.open": "Всё равно открыть",
        "button.back": "Назад",
        "settings.threshold": "Предупреждать о",
        "settings.threshold.description": "О каких ссылках предупреждать перед открытием.",
        "settings.threshold.caution": "Подозрительных и опасных ссылках",
        "settings.threshold.danger": "Только опасных ссылках",
        "settings.allowlist": "Доверенные домены",
        "settings.allowlist.description": "Для ссылок на эти домены и их поддомены предупреждение никогда не показывается. Разделяйте запятыми или переносами строк.",
        "settings.allowlist.placeholder": "example.com, mysite.ru",
        "finding.unreadable": "Эту ссылку не удалось прочитать как обычный веб-адрес.",
        "finding.allowlisted": "{domain} есть в вашем списке доверенных доменов.",
        "finding.masked-mismatch": "В ссылке написано {shown}, но на самом деле она ведёт на {host}.",
        "finding.masked-mention": "В тексте ссылки упоминается {shown}, но ведёт она на {host}.",
        "finding.userinfo-host": "Всё, что стоит перед «@», игнорируется: ссылка начинается с «{fake}», но ведёт на {host}.",
        "finding.userinfo-hidden": "Перед адресом в ссылке спрятана часть «имя@». Ведёт она на {host}.",
        "finding.ip-address": "Ведёт на голый IP-адрес ({host}), а не на сайт с названием. Настоящие сервисы почти никогда так не ссылаются.",
        "finding.mixed-script": "В адресе «{labels}» смешаны алфавиты (например, латиница с кириллицей или греческим). Так поддельный домен выдают за настоящий.",
        "finding.punycode": "В адресе есть международные символы ({display}, в записи {host}). Некоторые из них похожи на обычные буквы.",
        "finding.subdomain-trick": "Начинается с {hit}, но на самом деле сайт — {domain}. Всё, что слева, — просто название, которое выбрал владелец.",
        "finding.brand-tld": "Использует название {brand} на домене, который {brand} не принадлежит: это {domain}, а не {official}.",
        "finding.lookalike-swap": "{domain} сделан похожим на {official} с помощью подмены символов. Он не принадлежит {brand}.",
        "finding.lookalike": "{domain} подделывает название {brand} похожими символами. Он не принадлежит {brand}.",
        "finding.brand-scam": "Название {brand} стоит рядом со словами вроде «gift», «free» или «login» на сайте, который {brand} не ведёт ({domain}). Так выглядит большинство фишинговых ссылок.",
        "finding.brand-mention": "Содержит название {brand}, но это не сайт {brand}: {domain} принадлежит кому-то другому.",
        "finding.typosquat": "{domain} отличается от {official} на одну-две буквы. Домены с опечатками часто используют для кражи аккаунтов.",
        "finding.file-tld": "Адрес заканчивается на .{tld}: это похоже на имя файла, но на деле сайт.",
        "finding.shortener": "{domain} — сервис сокращения ссылок: куда она ведёт на самом деле, видно только после открытия.",
        "finding.free-hosting": "Размещён на {suffix}, где любой может бесплатно создать сайт.",
        "finding.scam-words-free-nitro": "Упоминает бесплатный Nitro — самую частую приманку в мошенничестве в Discord.",
        "finding.scam-words-nitro-giveaway": "Упоминает раздачу Nitro — самую частую приманку в мошенничестве в Discord.",
        "finding.scam-words-discord-gift": "Упоминает подарок Discord — самую частую приманку в мошенничестве в Discord.",
        "finding.scam-words-steam": "Упоминает подарок или обмен в Steam — самую частую приманку в мошенничестве в Discord.",
        "finding.scam-words-currency": "Упоминает бесплатную игровую валюту или скины — самую частую приманку в мошенничестве в Discord.",
        "finding.scam-words-crypto": "Упоминает криптоэирдроп — самую частую приманку в мошенничестве в Discord.",
        "finding.dangerous-file-disguised": "Скачивает «{file}» — программу, замаскированную под файл .{fake}.",
        "finding.dangerous-file": "Скачивает файл .{ext} («{file}»), который может выполнить код на вашем компьютере. Открывайте его, только если доверяете отправителю.",
        "finding.http": "Соединение с этим сайтом не зашифровано (http).",
    },
    tr: {
        "title.danger": "Bu bağlantı tehlikeli görünüyor",
        "title.caution": "Bu bağlantı güvenli olmayabilir",
        "subtitle.danger": "Dolandırıcılık veya kimlik avı bağlantısı belirtileri taşıyor.",
        "subtitle.caution": "Bir şeyler alışılmadık. Açmadan önce nereye gittiğini kontrol et.",
        "label.destination": "Gerçekte nereye gidiyor",
        "hint.written": "{host} olarak yazılmış",
        "button.open": "Yine de aç",
        "button.back": "Geri dön",
        "settings.threshold": "Şunlar için uyar",
        "settings.threshold.description": "Hangi bağlantılar açılmadan önce uyarı gösterir.",
        "settings.threshold.caution": "Şüpheli ve tehlikeli bağlantılar",
        "settings.threshold.danger": "Yalnızca tehlikeli bağlantılar",
        "settings.allowlist": "Güvenilen alan adları",
        "settings.allowlist.description": "Bu alan adlarına ve alt alan adlarına giden bağlantılar için asla uyarı gösterilmez. Virgül veya yeni satırla ayır.",
        "settings.allowlist.placeholder": "example.com, sitem.dev",
        "finding.unreadable": "Bu bağlantı normal bir web adresi olarak okunamadı.",
        "finding.allowlisted": "{domain} güvenilen alan adları listende.",
        "finding.masked-mismatch": "Bağlantı {shown} diyor ama aslında {host} adresine gidiyor.",
        "finding.masked-mention": "Bağlantı metni {shown} adresinden söz ediyor ama bağlantı {host} adresine gidiyor.",
        "finding.userinfo-host": "\"@\" işaretinden önceki her şey yok sayılır: bu bağlantı \"{fake}\" ile başlıyor ama {host} adresine gidiyor.",
        "finding.userinfo-hidden": "Bağlantının adresten önce gizli bir \"ad@\" kısmı var. {host} adresine gidiyor.",
        "finding.ip-address": "Adı olan bir web sitesi yerine çıplak bir IP adresine ({host}) gidiyor. Gerçek hizmetler neredeyse hiç böyle bağlantı vermez.",
        "finding.mixed-script": "Adres, \"{labels}\" içinde alfabeleri karıştırıyor (Latin ile Kiril veya Yunan gibi). Sahte bir alan adını gerçek gibi göstermek için kullanılan bir hile.",
        "finding.punycode": "Adres uluslararası karakterler kullanıyor ({display}, {host} olarak yazılmış). Bunların bir kısmı normal harflere çok benzer.",
        "finding.subdomain-trick": "{hit} ile başlıyor ama site aslında {domain}. Soldaki her şey, sahibinin seçtiği bir etiketten ibaret.",
        "finding.brand-tld": "{brand} adını, {brand} markasına ait olmayan bir alan adında kullanıyor: bu {official} değil, {domain}.",
        "finding.lookalike-swap": "{domain}, benzer karakterler değiştirilerek {official} gibi görünecek şekilde yapılmış. {brand} tarafından işletilmiyor.",
        "finding.lookalike": "{domain}, benzer karakterlerle {brand} adını taklit ediyor. {brand} tarafından işletilmiyor.",
        "finding.brand-scam": "{brand} adını, {brand} tarafından işletilmeyen bir sitede ({domain}) \"gift\", \"free\" veya \"login\" gibi sözcüklerin yanına koyuyor. Kimlik avı bağlantılarının çoğu böyle görünür.",
        "finding.brand-mention": "İçinde {brand} adı geçiyor ama {brand} sitelerinden biri değil: {domain} başkasına ait.",
        "finding.typosquat": "{domain}, {official} adresinden bir iki harf farklı. Bu tür yazım hatalı alan adları genellikle hesap çalmak için kullanılır.",
        "finding.file-tld": "Adres .{tld} ile bitiyor; bu bir dosya adına benziyor ama aslında bir web sitesi.",
        "finding.shortener": "{domain} bir bağlantı kısaltıcı: gerçekte nereye gittiği, açana kadar gizli.",
        "finding.free-hosting": "Herkesin ücretsiz site açabildiği {suffix} üzerinde barındırılıyor.",
        "finding.scam-words-free-nitro": "Bedava Nitro'dan söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.scam-words-nitro-giveaway": "Nitro çekilişinden söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.scam-words-discord-gift": "Discord hediyesinden söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.scam-words-steam": "Steam hediyesi veya takasından söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.scam-words-currency": "Bedava oyun içi para birimi veya kostümlerden söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.scam-words-crypto": "Kripto airdrop'undan söz ediyor; Discord dolandırıcılıklarında en yaygın yem.",
        "finding.dangerous-file-disguised": "\"{file}\" dosyasını indiriyor; .{fake} dosyası gibi görünen bir program.",
        "finding.dangerous-file": "Bilgisayarında kod çalıştırabilen bir .{ext} dosyası (\"{file}\") indiriyor. Yalnızca göndereni tanıyorsan aç.",
        "finding.http": "Bu siteyle bağlantı şifrelenmemiş (http).",
    },
});
