import { defineStrings } from "@evi/api";

import { EN_WORDS } from "./tz";

export const t = defineStrings({
    en: {
        ...EN_WORDS,
        "settings.timeFormat": "Time format",
        "settings.timeFormat.description": "Auto follows Discord's language.",
        "settings.timeFormat.auto": "Auto",
        "settings.timeFormat.12h": "12-hour (3:42 PM)",
        "settings.timeFormat.24h": "24-hour (15:42)",
        "settings.chatTime": "Time in chat",
        "settings.chatTime.description": "Their time right now, or what their clock said when they sent the message.",
        "settings.chatTime.current": "Current time",
        "settings.chatTime.sent": "When the message was sent",
        "settings.inChat": "In chat",
        "settings.inChat.description": "After the name on each message.",
        "settings.onProfiles": "On profiles",
        "settings.onProfiles.description": "A clock next to the badges; hover it for their time.",
        "settings.inMemberList": "In the member list",
        "settings.inMemberList.description": "After each name in the member list.",
        "user.them": "them",
        "tooltip.theirs": "Their time",
        "tooltip.sent": "Their time when sent",
        "picker.title": "Set timezone for {name}",
        "picker.now": "Now {city}, {time} there.",
        "picker.hint": "Search a city, a region, an abbreviation like EST, or an offset like UTC+3.",
        "picker.close": "Close",
        "picker.search": "Search timezones",
        "picker.placeholder": "Istanbul, PST, UTC+3…",
        "picker.list": "Timezones",
        "picker.empty": "No timezone matches “{query}”.",
        "picker.you": "You",
        "toast.set": "Timezone set for {name}: {city}",
        "saved.people": "People",
        "saved.nobody": "Nobody yet. Right-click someone and choose Set Timezone.",
        "saved.change": "Change",
        "saved.remove": "Remove",
        "menu.set": "Set Timezone",
        "menu.remove": "Remove Timezone",
    },
    de: {
        "diff.same": "gleiche Zeit wie du",
        "diff.ahead": "{amount} vor dir",
        "diff.behind": "{amount} hinter dir",
        "amount.h": "{h} Std.",
        "amount.m": "{m} Min.",
        "amount.hm": "{h} Std. {m} Min.",
        "settings.timeFormat": "Zeitformat",
        "settings.timeFormat.description": "Automatisch richtet sich nach der Sprache von Discord.",
        "settings.timeFormat.auto": "Automatisch",
        "settings.timeFormat.12h": "12-Stunden (3:42 PM)",
        "settings.timeFormat.24h": "24-Stunden (15:42)",
        "settings.chatTime": "Zeit im Chat",
        "settings.chatTime.description": "Die aktuelle Uhrzeit der Person oder die, die bei ihr galt, als sie die Nachricht gesendet hat.",
        "settings.chatTime.current": "Aktuelle Uhrzeit",
        "settings.chatTime.sent": "Beim Senden der Nachricht",
        "settings.inChat": "Im Chat",
        "settings.inChat.description": "Hinter dem Namen bei jeder Nachricht.",
        "settings.onProfiles": "In Profilen",
        "settings.onProfiles.description": "Eine Uhr neben den Abzeichen. Fahre darüber, um die Uhrzeit zu sehen.",
        "settings.inMemberList": "In der Mitgliederliste",
        "settings.inMemberList.description": "Hinter jedem Namen in der Mitgliederliste.",
        "user.them": "die Person",
        "tooltip.theirs": "Ortszeit",
        "tooltip.sent": "Ortszeit beim Senden",
        "picker.title": "Zeitzone für {name} festlegen",
        "picker.now": "Dort ist es jetzt {time} ({city}).",
        "picker.hint": "Suche nach einer Stadt, einer Region, einer Abkürzung wie EST oder einem Offset wie UTC+3.",
        "picker.close": "Schließen",
        "picker.search": "Zeitzonen durchsuchen",
        "picker.placeholder": "Istanbul, PST, UTC+3…",
        "picker.list": "Zeitzonen",
        "picker.empty": "Keine Zeitzone passt zu „{query}“.",
        "picker.you": "Du",
        "toast.set": "Zeitzone für {name} festgelegt: {city}",
        "saved.people": "Personen",
        "saved.nobody": "Noch niemand. Klicke jemanden mit der rechten Maustaste an und wähle „Zeitzone festlegen“.",
        "saved.change": "Ändern",
        "saved.remove": "Entfernen",
        "menu.set": "Zeitzone festlegen",
        "menu.remove": "Zeitzone entfernen",
    },
    es: {
        "diff.same": "la misma hora que tú",
        "diff.ahead": "{amount} por delante de ti",
        "diff.behind": "{amount} por detrás de ti",
        "amount.h": "{h} h",
        "amount.m": "{m} min",
        "amount.hm": "{h} h {m} min",
        "settings.timeFormat": "Formato de hora",
        "settings.timeFormat.description": "Automático sigue el idioma de Discord.",
        "settings.timeFormat.auto": "Automático",
        "settings.timeFormat.12h": "12 horas (3:42 PM)",
        "settings.timeFormat.24h": "24 horas (15:42)",
        "settings.chatTime": "Hora en el chat",
        "settings.chatTime.description": "Su hora actual, o la que marcaba su reloj cuando envió el mensaje.",
        "settings.chatTime.current": "Hora actual",
        "settings.chatTime.sent": "Cuando se envió el mensaje",
        "settings.inChat": "En el chat",
        "settings.inChat.description": "Después del nombre en cada mensaje.",
        "settings.onProfiles": "En los perfiles",
        "settings.onProfiles.description": "Un reloj junto a las insignias; pasa el cursor por encima para ver su hora.",
        "settings.inMemberList": "En la lista de miembros",
        "settings.inMemberList.description": "Después de cada nombre en la lista de miembros.",
        "user.them": "esta persona",
        "tooltip.theirs": "Su hora",
        "tooltip.sent": "Su hora al enviarlo",
        "picker.title": "Establecer la zona horaria de {name}",
        "picker.now": "Ahora en {city} son las {time}.",
        "picker.hint": "Busca una ciudad, una región, una abreviatura como EST o un desfase como UTC+3.",
        "picker.close": "Cerrar",
        "picker.search": "Buscar zonas horarias",
        "picker.placeholder": "Estambul, PST, UTC+3…",
        "picker.list": "Zonas horarias",
        "picker.empty": "Ninguna zona horaria coincide con «{query}».",
        "picker.you": "Tú",
        "toast.set": "Zona horaria de {name} establecida: {city}",
        "saved.people": "Personas",
        "saved.nobody": "Todavía nadie. Haz clic derecho en alguien y elige Establecer zona horaria.",
        "saved.change": "Cambiar",
        "saved.remove": "Quitar",
        "menu.set": "Establecer zona horaria",
        "menu.remove": "Quitar zona horaria",
    },
    fr: {
        "diff.same": "même heure que toi",
        "diff.ahead": "{amount} d'avance sur toi",
        "diff.behind": "{amount} de retard sur toi",
        "amount.h": "{h} h",
        "amount.m": "{m} min",
        "amount.hm": "{h} h {m} min",
        "settings.timeFormat": "Format de l'heure",
        "settings.timeFormat.description": "Auto suit la langue de Discord.",
        "settings.timeFormat.auto": "Auto",
        "settings.timeFormat.12h": "12 heures (3:42 PM)",
        "settings.timeFormat.24h": "24 heures (15:42)",
        "settings.chatTime": "Heure dans le chat",
        "settings.chatTime.description": "Son heure actuelle, ou l'heure qu'il était chez cette personne quand elle a envoyé le message.",
        "settings.chatTime.current": "Heure actuelle",
        "settings.chatTime.sent": "À l'envoi du message",
        "settings.inChat": "Dans le chat",
        "settings.inChat.description": "Après le nom sur chaque message.",
        "settings.onProfiles": "Sur les profils",
        "settings.onProfiles.description": "Une horloge à côté des badges ; survole-la pour voir son heure.",
        "settings.inMemberList": "Dans la liste des membres",
        "settings.inMemberList.description": "Après chaque nom dans la liste des membres.",
        "user.them": "cette personne",
        "tooltip.theirs": "Son heure",
        "tooltip.sent": "Son heure à l'envoi",
        "picker.title": "Définir le fuseau horaire de {name}",
        "picker.now": "Là-bas ({city}), il est {time}.",
        "picker.hint": "Cherche une ville, une région, une abréviation comme EST ou un décalage comme UTC+3.",
        "picker.close": "Fermer",
        "picker.search": "Rechercher un fuseau horaire",
        "picker.placeholder": "Istanbul, PST, UTC+3…",
        "picker.list": "Fuseaux horaires",
        "picker.empty": "Aucun fuseau horaire ne correspond à « {query} ».",
        "picker.you": "Toi",
        "toast.set": "Fuseau horaire de {name} défini : {city}",
        "saved.people": "Personnes",
        "saved.nobody": "Personne pour l'instant. Fais un clic droit sur quelqu'un et choisis Définir le fuseau horaire.",
        "saved.change": "Modifier",
        "saved.remove": "Retirer",
        "menu.set": "Définir le fuseau horaire",
        "menu.remove": "Retirer le fuseau horaire",
    },
    ja: {
        "diff.same": "あなたと同じ時刻",
        "diff.ahead": "あなたより{amount}進んでいます",
        "diff.behind": "あなたより{amount}遅れています",
        "amount.h": "{h}時間",
        "amount.m": "{m}分",
        "amount.hm": "{h}時間{m}分",
        "settings.timeFormat": "時刻の形式",
        "settings.timeFormat.description": "「自動」は Discord の言語に合わせます。",
        "settings.timeFormat.auto": "自動",
        "settings.timeFormat.12h": "12時間制（3:42 PM）",
        "settings.timeFormat.24h": "24時間制（15:42）",
        "settings.chatTime": "チャットの時刻",
        "settings.chatTime.description": "相手の現在の時刻、またはメッセージを送信したときの相手の時計の時刻。",
        "settings.chatTime.current": "現在の時刻",
        "settings.chatTime.sent": "メッセージ送信時",
        "settings.inChat": "チャット",
        "settings.inChat.description": "各メッセージの名前の後ろに表示します。",
        "settings.onProfiles": "プロフィール",
        "settings.onProfiles.description": "バッジの横に時計を表示します。マウスを重ねると相手の時刻が表示されます。",
        "settings.inMemberList": "メンバーリスト",
        "settings.inMemberList.description": "メンバーリストの各名前の後ろに表示します。",
        "user.them": "この人",
        "tooltip.theirs": "相手の時刻",
        "tooltip.sent": "送信時の相手の時刻",
        "picker.title": "{name}のタイムゾーンを設定",
        "picker.now": "現在、{city}は{time}です。",
        "picker.hint": "都市名、地域名、EST などの略称、UTC+3 などのオフセットで検索できます。",
        "picker.close": "閉じる",
        "picker.search": "タイムゾーンを検索",
        "picker.placeholder": "Istanbul、PST、UTC+3…",
        "picker.list": "タイムゾーン",
        "picker.empty": "「{query}」に一致するタイムゾーンはありません。",
        "picker.you": "あなた",
        "toast.set": "{name}のタイムゾーンを設定しました：{city}",
        "saved.people": "ユーザー",
        "saved.nobody": "まだ誰も設定されていません。ユーザーを右クリックして「タイムゾーンを設定」を選んでください。",
        "saved.change": "変更",
        "saved.remove": "削除",
        "menu.set": "タイムゾーンを設定",
        "menu.remove": "タイムゾーンを削除",
    },
    pl: {
        "diff.same": "ta sama godzina co u Ciebie",
        "diff.ahead": "{amount} do przodu względem Ciebie",
        "diff.behind": "{amount} do tyłu względem Ciebie",
        "amount.h": "{h} godz.",
        "amount.m": "{m} min",
        "amount.hm": "{h} godz. {m} min",
        "settings.timeFormat": "Format czasu",
        "settings.timeFormat.description": "Automatyczny dopasowuje się do języka Discorda.",
        "settings.timeFormat.auto": "Automatyczny",
        "settings.timeFormat.12h": "12-godzinny (3:42 PM)",
        "settings.timeFormat.24h": "24-godzinny (15:42)",
        "settings.chatTime": "Czas na czacie",
        "settings.chatTime.description": "Aktualna godzina u tej osoby albo ta, którą miała na zegarze, gdy wysłała wiadomość.",
        "settings.chatTime.current": "Aktualny czas",
        "settings.chatTime.sent": "W chwili wysłania wiadomości",
        "settings.inChat": "Na czacie",
        "settings.inChat.description": "Po nazwie przy każdej wiadomości.",
        "settings.onProfiles": "W profilach",
        "settings.onProfiles.description": "Zegar obok odznak. Najedź na niego, aby zobaczyć godzinę tej osoby.",
        "settings.inMemberList": "Na liście członków",
        "settings.inMemberList.description": "Po każdej nazwie na liście członków.",
        "user.them": "ta osoba",
        "tooltip.theirs": "Czas tej osoby",
        "tooltip.sent": "Czas tej osoby w chwili wysłania",
        "picker.title": "Ustaw strefę czasową dla: {name}",
        "picker.now": "Teraz w miejscowości {city} jest {time}.",
        "picker.hint": "Wyszukaj miasto, region, skrót taki jak EST albo przesunięcie takie jak UTC+3.",
        "picker.close": "Zamknij",
        "picker.search": "Szukaj stref czasowych",
        "picker.placeholder": "Stambuł, PST, UTC+3…",
        "picker.list": "Strefy czasowe",
        "picker.empty": "Żadna strefa czasowa nie pasuje do „{query}”.",
        "picker.you": "Ty",
        "toast.set": "Ustawiono strefę czasową dla {name}: {city}",
        "saved.people": "Osoby",
        "saved.nobody": "Jeszcze nikogo. Kliknij kogoś prawym przyciskiem myszy i wybierz Ustaw strefę czasową.",
        "saved.change": "Zmień",
        "saved.remove": "Usuń",
        "menu.set": "Ustaw strefę czasową",
        "menu.remove": "Usuń strefę czasową",
    },
    "pt-BR": {
        "diff.same": "mesmo horário que o seu",
        "diff.ahead": "{amount} à frente de você",
        "diff.behind": "{amount} atrás de você",
        "amount.h": "{h}h",
        "amount.m": "{m}min",
        "amount.hm": "{h}h {m}min",
        "settings.timeFormat": "Formato de hora",
        "settings.timeFormat.description": "Automático segue o idioma do Discord.",
        "settings.timeFormat.auto": "Automático",
        "settings.timeFormat.12h": "12 horas (3:42 PM)",
        "settings.timeFormat.24h": "24 horas (15:42)",
        "settings.chatTime": "Hora no chat",
        "settings.chatTime.description": "A hora atual da pessoa, ou a que o relógio dela marcava quando ela enviou a mensagem.",
        "settings.chatTime.current": "Hora atual",
        "settings.chatTime.sent": "Quando a mensagem foi enviada",
        "settings.inChat": "No chat",
        "settings.inChat.description": "Depois do nome em cada mensagem.",
        "settings.onProfiles": "Nos perfis",
        "settings.onProfiles.description": "Um relógio ao lado das insígnias; passe o mouse por cima para ver a hora da pessoa.",
        "settings.inMemberList": "Na lista de membros",
        "settings.inMemberList.description": "Depois de cada nome na lista de membros.",
        "user.them": "essa pessoa",
        "tooltip.theirs": "Hora dela",
        "tooltip.sent": "Hora dela quando enviou",
        "picker.title": "Definir fuso horário de {name}",
        "picker.now": "Agora em {city} são {time}.",
        "picker.hint": "Pesquise uma cidade, uma região, uma abreviação como EST ou um deslocamento como UTC+3.",
        "picker.close": "Fechar",
        "picker.search": "Pesquisar fusos horários",
        "picker.placeholder": "Istambul, PST, UTC+3…",
        "picker.list": "Fusos horários",
        "picker.empty": "Nenhum fuso horário corresponde a “{query}”.",
        "picker.you": "Você",
        "toast.set": "Fuso horário de {name} definido: {city}",
        "saved.people": "Pessoas",
        "saved.nobody": "Ninguém ainda. Clique com o botão direito em alguém e escolha Definir fuso horário.",
        "saved.change": "Alterar",
        "saved.remove": "Remover",
        "menu.set": "Definir fuso horário",
        "menu.remove": "Remover fuso horário",
    },
    ru: {
        "diff.same": "то же время, что и у вас",
        "diff.ahead": "на {amount} впереди вас",
        "diff.behind": "на {amount} позади вас",
        "amount.h": "{h} ч",
        "amount.m": "{m} мин",
        "amount.hm": "{h} ч {m} мин",
        "settings.timeFormat": "Формат времени",
        "settings.timeFormat.description": "«Авто» следует языку Discord.",
        "settings.timeFormat.auto": "Авто",
        "settings.timeFormat.12h": "12-часовой (3:42 PM)",
        "settings.timeFormat.24h": "24-часовой (15:42)",
        "settings.chatTime": "Время в чате",
        "settings.chatTime.description": "Текущее время у человека или то, которое было на его часах, когда он отправил сообщение.",
        "settings.chatTime.current": "Текущее время",
        "settings.chatTime.sent": "Когда отправлено сообщение",
        "settings.inChat": "В чате",
        "settings.inChat.description": "После имени в каждом сообщении.",
        "settings.onProfiles": "В профилях",
        "settings.onProfiles.description": "Часы рядом со значками. Наведите на них курсор, чтобы увидеть время человека.",
        "settings.inMemberList": "В списке участников",
        "settings.inMemberList.description": "После каждого имени в списке участников.",
        "user.them": "этого человека",
        "tooltip.theirs": "Время у человека",
        "tooltip.sent": "Время у человека при отправке",
        "picker.title": "Часовой пояс для {name}",
        "picker.now": "Сейчас там ({city}) {time}.",
        "picker.hint": "Ищите город, регион, сокращение вроде EST или смещение вроде UTC+3.",
        "picker.close": "Закрыть",
        "picker.search": "Поиск часовых поясов",
        "picker.placeholder": "Стамбул, PST, UTC+3…",
        "picker.list": "Часовые пояса",
        "picker.empty": "Нет часовых поясов, подходящих под «{query}».",
        "picker.you": "Вы",
        "toast.set": "Часовой пояс для {name} задан: {city}",
        "saved.people": "Люди",
        "saved.nobody": "Пока никого. Нажмите правой кнопкой мыши на пользователя и выберите «Задать часовой пояс».",
        "saved.change": "Изменить",
        "saved.remove": "Удалить",
        "menu.set": "Задать часовой пояс",
        "menu.remove": "Убрать часовой пояс",
    },
    tr: {
        "diff.same": "seninle aynı saat",
        "diff.ahead": "senden {amount} ileride",
        "diff.behind": "senden {amount} geride",
        "amount.h": "{h} sa",
        "amount.m": "{m} dk",
        "amount.hm": "{h} sa {m} dk",
        "settings.timeFormat": "Saat biçimi",
        "settings.timeFormat.description": "Otomatik, Discord'un diline uyar.",
        "settings.timeFormat.auto": "Otomatik",
        "settings.timeFormat.12h": "12 saatlik (3:42 PM)",
        "settings.timeFormat.24h": "24 saatlik (15:42)",
        "settings.chatTime": "Sohbetteki saat",
        "settings.chatTime.description": "Kişinin şu anki saati veya mesajı gönderdiği andaki saati.",
        "settings.chatTime.current": "Şu anki saat",
        "settings.chatTime.sent": "Mesajın gönderildiği an",
        "settings.inChat": "Sohbette",
        "settings.inChat.description": "Her mesajda adın yanında.",
        "settings.onProfiles": "Profillerde",
        "settings.onProfiles.description": "Rozetlerin yanında bir saat; kişinin saatini görmek için üzerine gel.",
        "settings.inMemberList": "Üye listesinde",
        "settings.inMemberList.description": "Üye listesinde her adın yanında.",
        "user.them": "bu kişi",
        "tooltip.theirs": "Kişinin saati",
        "tooltip.sent": "Gönderildiği andaki saati",
        "picker.title": "{name} için saat dilimi ayarla",
        "picker.now": "Şu an {city} için saat {time}.",
        "picker.hint": "Bir şehir, bölge, EST gibi bir kısaltma veya UTC+3 gibi bir fark ara.",
        "picker.close": "Kapat",
        "picker.search": "Saat dilimlerinde ara",
        "picker.placeholder": "İstanbul, PST, UTC+3…",
        "picker.list": "Saat dilimleri",
        "picker.empty": "“{query}” ile eşleşen saat dilimi yok.",
        "picker.you": "Sen",
        "toast.set": "{name} için saat dilimi ayarlandı: {city}",
        "saved.people": "Kişiler",
        "saved.nobody": "Henüz kimse yok. Birine sağ tıkla ve Saat Dilimi Ayarla'yı seç.",
        "saved.change": "Değiştir",
        "saved.remove": "Kaldır",
        "menu.set": "Saat Dilimi Ayarla",
        "menu.remove": "Saat Dilimini Kaldır",
    },
});
