import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Your own Discord application's ID: your status shows as it. The setup guide below shows how to make one.",
        "toast.imagesFailed": "Rich Presence: Discord didn't accept the pictures. Check the links and the Application ID.",
        "panel.presets": "Presets",
        "panel.new": "New",
        "panel.newTitle": "Preset {n}",
        "panel.copyOf": "{title} (copy)",
        "panel.untitled": "Untitled",
        "panel.empty": "No presets yet. Make one with New, and show it on your profile.",
        "panel.pluginOff": "Rich Presence Builder is off: you can set up presets now, and they show once you turn it on.",
        "panel.showing": "On your profile",
        "panel.show": "Show on my profile",
        "panel.hide": "Stop showing",
        "panel.duplicate": "Duplicate",
        "panel.delete": "Delete",
        "panel.deleteConfirm": "Click again to delete",
        "panel.whoSees": "Everyone who can see your activity sees this, while Discord is open on this computer. Buttons only work for others: Discord doesn't show them to you.",
        "section.text": "Text",
        "section.images": "Pictures",
        "section.buttons": "Buttons",
        "section.more": "Time and party",
        "field.title": "Preset name",
        "field.title.hint": "Only you see this.",
        "field.type": "Activity",
        "field.name": "Name",
        "field.name.placeholder": "What you're doing",
        "field.details": "First line",
        "field.details.placeholder": "In the main menu",
        "field.state": "Second line",
        "field.state.placeholder": "Looking for a team",
        "field.streamUrl": "Stream link",
        "field.streamUrl.hint": "Discord only shows Streaming with a Twitch or YouTube link.",
        "field.largeImage": "Big picture",
        "field.imageHint": "An https link to a picture, or the key of an art asset you uploaded.",
        "field.largeText": "Big picture's hover text",
        "field.smallImage": "Small picture",
        "field.smallText": "Small picture's hover text",
        "field.buttonLabel": "Button {n} text",
        "field.buttonUrl": "Button {n} link",
        "field.buttons.hint": "Up to two buttons, each with an https link.",
        "field.time": "Timer",
        "field.timeStart": "Counting from",
        "field.timeEnd": "Counting down to",
        "field.party": "Party",
        "field.party.hint": "Shows as \"(2 of 4)\" after the second line. Leave empty for none.",
        "field.partySize": "People in the party",
        "field.partyOf": "of",
        "field.partyMax": "Party size",
        "type.playing": "Playing",
        "type.listening": "Listening",
        "type.watching": "Watching",
        "type.competing": "Competing",
        "type.streaming": "Streaming",
        "time.none": "None",
        "time.elapsed": "Time since it went on",
        "time.localTime": "Your local time",
        "time.start": "Since a set time",
        "time.end": "Countdown to a set time",
        "problem.noAppId": "Add an Application ID first.",
        "problem.noName": "Give it a name.",
        "problem.badLargeImage": "The big picture needs an https link.",
        "problem.badSmallImage": "The small picture needs an https link.",
        "problem.badStreamUrl": "Streaming needs a Twitch or YouTube link.",
        "problem.buttonLabel": "A button with a link needs text.",
        "problem.buttonUrl": "Each button needs an https link.",
        "problem.badParty": "The party can't have more people than its size.",
        "problem.noTime": "Pick a time for the timer.",
        "preview.title": "Preview",
        "preview.elapsed": "{time} elapsed",
        "preview.left": "{time} left",
        "preview.party": "({size} of {max})",
        "guide.title": "Set up Rich Presence",
        "guide.intro": "Your status shows as a Discord application of your own. It takes about two minutes, and you only do it once.",
        "guide.step1.title": "Open the Developer Portal",
        "guide.step1.body": "Log in with your Discord account. Making an application is free, and nobody sees it until you use it.",
        "guide.step1.button": "Open Developer Portal",
        "guide.step2.title": "Create an application",
        "guide.step2.body": "Click New Application at the top right and give it a name. A preset's Name shows after \"Playing\"; leave it empty and this application's name shows instead.",
        "guide.step3.title": "Copy its Application ID",
        "guide.step3.body": "On the General Information page, find Application ID and click Copy.",
        "guide.step4.title": "Paste it here",
        "guide.step4.placeholder": "Application ID, like 123456789012345678",
        "guide.step4.check": "Check",
        "guide.step4.checking": "Checking…",
        "guide.step4.invalid": "That isn't an Application ID: it's 17 to 20 digits.",
        "guide.step4.notFound": "Discord doesn't know an application with that ID. Copy it again from General Information.",
        "guide.step4.failed": "Couldn't check it right now: {error}",
        "guide.step4.ok": "Found {name}. You're all set.",
        "guide.step5.title": "Optional: upload your own pictures",
        "guide.step5.body": "Picture fields take any https link to a picture. You can also upload pictures in the portal under Rich Presence → Art Assets and type their key instead, like \"logo\".",
        "guide.done": "Start building",
        "guide.reopen": "How to set up",
        "guide.change": "Use a different application",
        "field.name.hintApp": "Leave empty to show your application's name, {name}.",
    },
    de: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Die ID deiner eigenen Discord-Anwendung: Dein Status erscheint als sie. Die Anleitung unten zeigt, wie du eine erstellst.",
        "toast.imagesFailed": "Rich Presence: Discord hat die Bilder nicht angenommen. Prüfe die Links und die Application ID.",
        "panel.presets": "Vorlagen",
        "panel.new": "Neu",
        "panel.newTitle": "Vorlage {n}",
        "panel.copyOf": "{title} (Kopie)",
        "panel.untitled": "Ohne Namen",
        "panel.empty": "Noch keine Vorlagen. Erstelle eine mit Neu und zeige sie in deinem Profil.",
        "panel.pluginOff": "Rich Presence Builder ist aus: Du kannst jetzt Vorlagen anlegen, sie erscheinen, sobald du es einschaltest.",
        "panel.showing": "In deinem Profil",
        "panel.show": "In meinem Profil zeigen",
        "panel.hide": "Nicht mehr zeigen",
        "panel.duplicate": "Duplizieren",
        "panel.delete": "Löschen",
        "panel.deleteConfirm": "Zum Löschen erneut klicken",
        "panel.whoSees": "Alle, die deine Aktivität sehen können, sehen das, solange Discord auf diesem Computer offen ist. Die Buttons funktionieren nur für andere: Dir zeigt Discord sie nicht.",
        "section.text": "Text",
        "section.images": "Bilder",
        "section.buttons": "Buttons",
        "section.more": "Zeit und Gruppe",
        "field.title": "Name der Vorlage",
        "field.title.hint": "Nur du siehst das.",
        "field.type": "Aktivität",
        "field.name": "Name",
        "field.name.placeholder": "Was du gerade machst",
        "field.details": "Erste Zeile",
        "field.details.placeholder": "Im Hauptmenü",
        "field.state": "Zweite Zeile",
        "field.state.placeholder": "Sucht ein Team",
        "field.streamUrl": "Stream-Link",
        "field.streamUrl.hint": "Discord zeigt „Streamt“ nur mit einem Twitch- oder YouTube-Link.",
        "field.largeImage": "Großes Bild",
        "field.imageHint": "Ein https-Link zu einem Bild oder der Schlüssel eines hochgeladenen Art Assets.",
        "field.largeText": "Hover-Text des großen Bilds",
        "field.smallImage": "Kleines Bild",
        "field.smallText": "Hover-Text des kleinen Bilds",
        "field.buttonLabel": "Text von Button {n}",
        "field.buttonUrl": "Link von Button {n}",
        "field.buttons.hint": "Bis zu zwei Buttons, jeder mit einem https-Link.",
        "field.time": "Timer",
        "field.timeStart": "Zählt ab",
        "field.timeEnd": "Zählt herunter bis",
        "field.party": "Gruppe",
        "field.party.hint": "Erscheint als „(2 von 4)“ nach der zweiten Zeile. Leer lassen für keine.",
        "field.partySize": "Personen in der Gruppe",
        "field.partyOf": "von",
        "field.partyMax": "Gruppengröße",
        "type.playing": "Spielt",
        "type.listening": "Hört",
        "type.watching": "Schaut",
        "type.competing": "Tritt an",
        "type.streaming": "Streamt",
        "time.none": "Keiner",
        "time.elapsed": "Zeit seit dem Einschalten",
        "time.localTime": "Deine Uhrzeit",
        "time.start": "Seit einer festen Zeit",
        "time.end": "Countdown bis zu einer festen Zeit",
        "problem.noAppId": "Füge zuerst eine Application ID hinzu.",
        "problem.noName": "Gib ihr einen Namen.",
        "problem.badLargeImage": "Das große Bild braucht einen https-Link.",
        "problem.badSmallImage": "Das kleine Bild braucht einen https-Link.",
        "problem.badStreamUrl": "Streamen braucht einen Twitch- oder YouTube-Link.",
        "problem.buttonLabel": "Ein Button mit Link braucht einen Text.",
        "problem.buttonUrl": "Jeder Button braucht einen https-Link.",
        "problem.badParty": "Die Gruppe kann nicht mehr Personen haben als ihre Größe.",
        "problem.noTime": "Wähle eine Zeit für den Timer.",
        "preview.title": "Vorschau",
        "preview.elapsed": "{time} vergangen",
        "preview.left": "noch {time}",
        "preview.party": "({size} von {max})",
        "guide.title": "Rich Presence einrichten",
        "guide.intro": "Dein Status erscheint als eigene Discord-Anwendung. Das dauert etwa zwei Minuten und ist nur einmal nötig.",
        "guide.step1.title": "Öffne das Developer Portal",
        "guide.step1.body": "Melde dich mit deinem Discord-Konto an. Eine Anwendung zu erstellen ist kostenlos, und niemand sieht sie, bevor du sie nutzt.",
        "guide.step1.button": "Developer Portal öffnen",
        "guide.step2.title": "Erstelle eine Anwendung",
        "guide.step2.body": "Klicke oben rechts auf New Application und gib ihr einen Namen. Nach „Spielt“ steht der Name der Vorlage; lässt du ihn leer, erscheint stattdessen der Name dieser Anwendung.",
        "guide.step3.title": "Kopiere ihre Application ID",
        "guide.step3.body": "Suche auf der Seite General Information die Application ID und klicke auf Copy.",
        "guide.step4.title": "Füge sie hier ein",
        "guide.step4.placeholder": "Application ID, z. B. 123456789012345678",
        "guide.step4.check": "Prüfen",
        "guide.step4.checking": "Wird geprüft …",
        "guide.step4.invalid": "Das ist keine Application ID: Sie hat 17 bis 20 Ziffern.",
        "guide.step4.notFound": "Discord kennt keine Anwendung mit dieser ID. Kopiere sie noch einmal unter General Information.",
        "guide.step4.failed": "Konnte gerade nicht geprüft werden: {error}",
        "guide.step4.ok": "{name} gefunden. Alles bereit.",
        "guide.step5.title": "Optional: eigene Bilder hochladen",
        "guide.step5.body": "Bildfelder nehmen jeden https-Link zu einem Bild. Du kannst im Portal auch unter Rich Presence → Art Assets Bilder hochladen und stattdessen ihren Schlüssel eingeben, z. B. „logo“.",
        "guide.done": "Los geht’s",
        "guide.reopen": "So richtest du es ein",
        "guide.change": "Andere Anwendung verwenden",
        "field.name.hintApp": "Leer lassen, um den Namen deiner Anwendung zu zeigen: {name}.",
    },
    es: {
        "settings.appId": "Application ID",
        "settings.appId.description": "El ID de tu propia aplicación de Discord: tu estado aparece como ella. La guía de abajo explica cómo crear una.",
        "toast.imagesFailed": "Rich Presence: Discord no aceptó las imágenes. Revisa los enlaces y el Application ID.",
        "panel.presets": "Ajustes guardados",
        "panel.new": "Nuevo",
        "panel.newTitle": "Ajuste {n}",
        "panel.copyOf": "{title} (copia)",
        "panel.untitled": "Sin nombre",
        "panel.empty": "Aún no hay ninguno. Crea uno con Nuevo y muéstralo en tu perfil.",
        "panel.pluginOff": "Rich Presence Builder está desactivado: puedes preparar ajustes ahora y aparecerán cuando lo actives.",
        "panel.showing": "En tu perfil",
        "panel.show": "Mostrar en mi perfil",
        "panel.hide": "Dejar de mostrar",
        "panel.duplicate": "Duplicar",
        "panel.delete": "Eliminar",
        "panel.deleteConfirm": "Haz clic otra vez para eliminar",
        "panel.whoSees": "Lo ve todo el que pueda ver tu actividad, mientras Discord esté abierto en este ordenador. Los botones solo funcionan para los demás: Discord no te los muestra a ti.",
        "section.text": "Texto",
        "section.images": "Imágenes",
        "section.buttons": "Botones",
        "section.more": "Tiempo y grupo",
        "field.title": "Nombre del ajuste",
        "field.title.hint": "Solo lo ves tú.",
        "field.type": "Actividad",
        "field.name": "Nombre",
        "field.name.placeholder": "Lo que estás haciendo",
        "field.details": "Primera línea",
        "field.details.placeholder": "En el menú principal",
        "field.state": "Segunda línea",
        "field.state.placeholder": "Buscando equipo",
        "field.streamUrl": "Enlace del directo",
        "field.streamUrl.hint": "Discord solo muestra «Transmitiendo» con un enlace de Twitch o YouTube.",
        "field.largeImage": "Imagen grande",
        "field.imageHint": "Un enlace https a una imagen, o la clave de un Art Asset que subiste.",
        "field.largeText": "Texto al pasar sobre la imagen grande",
        "field.smallImage": "Imagen pequeña",
        "field.smallText": "Texto al pasar sobre la imagen pequeña",
        "field.buttonLabel": "Texto del botón {n}",
        "field.buttonUrl": "Enlace del botón {n}",
        "field.buttons.hint": "Hasta dos botones, cada uno con un enlace https.",
        "field.time": "Temporizador",
        "field.timeStart": "Contando desde",
        "field.timeEnd": "Cuenta atrás hasta",
        "field.party": "Grupo",
        "field.party.hint": "Aparece como «(2 de 4)» tras la segunda línea. Déjalo vacío para no mostrarlo.",
        "field.partySize": "Personas en el grupo",
        "field.partyOf": "de",
        "field.partyMax": "Tamaño del grupo",
        "type.playing": "Jugando",
        "type.listening": "Escuchando",
        "type.watching": "Viendo",
        "type.competing": "Compitiendo",
        "type.streaming": "Transmitiendo",
        "time.none": "Ninguno",
        "time.elapsed": "Tiempo desde que se activó",
        "time.localTime": "Tu hora local",
        "time.start": "Desde una hora fija",
        "time.end": "Cuenta atrás hasta una hora fija",
        "problem.noAppId": "Primero añade un Application ID.",
        "problem.noName": "Ponle un nombre.",
        "problem.badLargeImage": "La imagen grande necesita un enlace https.",
        "problem.badSmallImage": "La imagen pequeña necesita un enlace https.",
        "problem.badStreamUrl": "Transmitiendo necesita un enlace de Twitch o YouTube.",
        "problem.buttonLabel": "Un botón con enlace necesita texto.",
        "problem.buttonUrl": "Cada botón necesita un enlace https.",
        "problem.badParty": "El grupo no puede tener más personas que su tamaño.",
        "problem.noTime": "Elige una hora para el temporizador.",
        "preview.title": "Vista previa",
        "preview.elapsed": "{time} transcurrido",
        "preview.left": "quedan {time}",
        "preview.party": "({size} de {max})",
        "guide.title": "Configurar Rich Presence",
        "guide.intro": "Tu estado aparece como una aplicación de Discord propia. Lleva unos dos minutos y solo se hace una vez.",
        "guide.step1.title": "Abre el Developer Portal",
        "guide.step1.body": "Inicia sesión con tu cuenta de Discord. Crear una aplicación es gratis y nadie la ve hasta que la usas.",
        "guide.step1.button": "Abrir Developer Portal",
        "guide.step2.title": "Crea una aplicación",
        "guide.step2.body": "Haz clic en New Application arriba a la derecha y ponle un nombre. Tras \"Jugando\" aparece el Nombre del preajuste; si lo dejas vacío, aparece el nombre de esta aplicación.",
        "guide.step3.title": "Copia su Application ID",
        "guide.step3.body": "En la página General Information, busca Application ID y haz clic en Copy.",
        "guide.step4.title": "Pégalo aquí",
        "guide.step4.placeholder": "Application ID, como 123456789012345678",
        "guide.step4.check": "Comprobar",
        "guide.step4.checking": "Comprobando…",
        "guide.step4.invalid": "Eso no es un Application ID: tiene de 17 a 20 dígitos.",
        "guide.step4.notFound": "Discord no conoce ninguna aplicación con ese ID. Cópialo de nuevo desde General Information.",
        "guide.step4.failed": "No se pudo comprobar ahora: {error}",
        "guide.step4.ok": "{name} encontrada. Todo listo.",
        "guide.step5.title": "Opcional: sube tus propias imágenes",
        "guide.step5.body": "Los campos de imagen aceptan cualquier enlace https a una imagen. También puedes subir imágenes en el portal en Rich Presence → Art Assets y escribir su clave, como \"logo\".",
        "guide.done": "Empezar",
        "guide.reopen": "Cómo configurarlo",
        "guide.change": "Usar otra aplicación",
        "field.name.hintApp": "Déjalo vacío para mostrar el nombre de tu aplicación: {name}.",
    },
    fr: {
        "settings.appId": "Application ID",
        "settings.appId.description": "L'ID de ta propre application Discord : ton statut s'affiche sous son nom. Le guide ci-dessous montre comment en créer une.",
        "toast.imagesFailed": "Rich Presence : Discord n'a pas accepté les images. Vérifie les liens et l'Application ID.",
        "panel.presets": "Préréglages",
        "panel.new": "Nouveau",
        "panel.newTitle": "Préréglage {n}",
        "panel.copyOf": "{title} (copie)",
        "panel.untitled": "Sans nom",
        "panel.empty": "Aucun préréglage pour l'instant. Crées-en un avec Nouveau et affiche-le sur ton profil.",
        "panel.pluginOff": "Rich Presence Builder est désactivé : tu peux préparer des préréglages maintenant, ils apparaîtront quand tu l'activeras.",
        "panel.showing": "Sur ton profil",
        "panel.show": "Afficher sur mon profil",
        "panel.hide": "Ne plus afficher",
        "panel.duplicate": "Dupliquer",
        "panel.delete": "Supprimer",
        "panel.deleteConfirm": "Clique encore pour supprimer",
        "panel.whoSees": "Tous ceux qui voient ton activité le voient, tant que Discord est ouvert sur cet ordinateur. Les boutons ne marchent que pour les autres : Discord ne te les montre pas.",
        "section.text": "Texte",
        "section.images": "Images",
        "section.buttons": "Boutons",
        "section.more": "Temps et groupe",
        "field.title": "Nom du préréglage",
        "field.title.hint": "Toi seul le vois.",
        "field.type": "Activité",
        "field.name": "Nom",
        "field.name.placeholder": "Ce que tu fais",
        "field.details": "Première ligne",
        "field.details.placeholder": "Dans le menu principal",
        "field.state": "Deuxième ligne",
        "field.state.placeholder": "Cherche une équipe",
        "field.streamUrl": "Lien du stream",
        "field.streamUrl.hint": "Discord n'affiche « En direct » qu'avec un lien Twitch ou YouTube.",
        "field.largeImage": "Grande image",
        "field.imageHint": "Un lien https vers une image, ou la clé d'un Art Asset que tu as importé.",
        "field.largeText": "Texte au survol de la grande image",
        "field.smallImage": "Petite image",
        "field.smallText": "Texte au survol de la petite image",
        "field.buttonLabel": "Texte du bouton {n}",
        "field.buttonUrl": "Lien du bouton {n}",
        "field.buttons.hint": "Jusqu'à deux boutons, chacun avec un lien https.",
        "field.time": "Minuteur",
        "field.timeStart": "Compte depuis",
        "field.timeEnd": "Compte à rebours jusqu'à",
        "field.party": "Groupe",
        "field.party.hint": "S'affiche comme « (2 sur 4) » après la deuxième ligne. Laisse vide pour aucun.",
        "field.partySize": "Personnes dans le groupe",
        "field.partyOf": "sur",
        "field.partyMax": "Taille du groupe",
        "type.playing": "Joue",
        "type.listening": "Écoute",
        "type.watching": "Regarde",
        "type.competing": "En compétition",
        "type.streaming": "En direct",
        "time.none": "Aucun",
        "time.elapsed": "Temps depuis l'activation",
        "time.localTime": "Ton heure locale",
        "time.start": "Depuis une heure précise",
        "time.end": "Compte à rebours jusqu'à une heure précise",
        "problem.noAppId": "Ajoute d'abord un Application ID.",
        "problem.noName": "Donne-lui un nom.",
        "problem.badLargeImage": "La grande image a besoin d'un lien https.",
        "problem.badSmallImage": "La petite image a besoin d'un lien https.",
        "problem.badStreamUrl": "En direct a besoin d'un lien Twitch ou YouTube.",
        "problem.buttonLabel": "Un bouton avec un lien a besoin d'un texte.",
        "problem.buttonUrl": "Chaque bouton a besoin d'un lien https.",
        "problem.badParty": "Le groupe ne peut pas compter plus de personnes que sa taille.",
        "problem.noTime": "Choisis une heure pour le minuteur.",
        "preview.title": "Aperçu",
        "preview.elapsed": "{time} écoulé",
        "preview.left": "{time} restant",
        "preview.party": "({size} sur {max})",
        "guide.title": "Configurer Rich Presence",
        "guide.intro": "Ton statut s'affiche comme une application Discord à toi. Ça prend environ deux minutes, une seule fois.",
        "guide.step1.title": "Ouvre le Developer Portal",
        "guide.step1.body": "Connecte-toi avec ton compte Discord. Créer une application est gratuit et personne ne la voit avant que tu l'utilises.",
        "guide.step1.button": "Ouvrir le Developer Portal",
        "guide.step2.title": "Crée une application",
        "guide.step2.body": "Clique sur New Application en haut à droite et donne-lui un nom. Après « Joue à » s'affiche le Nom du préréglage ; laisse-le vide et c'est le nom de cette application qui s'affiche.",
        "guide.step3.title": "Copie son Application ID",
        "guide.step3.body": "Sur la page General Information, trouve Application ID et clique sur Copy.",
        "guide.step4.title": "Colle-le ici",
        "guide.step4.placeholder": "Application ID, comme 123456789012345678",
        "guide.step4.check": "Vérifier",
        "guide.step4.checking": "Vérification…",
        "guide.step4.invalid": "Ce n'est pas un Application ID : il compte 17 à 20 chiffres.",
        "guide.step4.notFound": "Discord ne connaît aucune application avec cet ID. Copie-le à nouveau depuis General Information.",
        "guide.step4.failed": "Impossible de vérifier pour l'instant : {error}",
        "guide.step4.ok": "{name} trouvée. Tout est prêt.",
        "guide.step5.title": "Facultatif : importe tes propres images",
        "guide.step5.body": "Les champs d'image acceptent n'importe quel lien https vers une image. Tu peux aussi importer des images dans le portail sous Rich Presence → Art Assets et taper leur clé à la place, comme « logo ».",
        "guide.done": "Commencer",
        "guide.reopen": "Comment configurer",
        "guide.change": "Utiliser une autre application",
        "field.name.hintApp": "Laisse vide pour afficher le nom de ton application : {name}.",
    },
    ja: {
        "settings.appId": "Application ID",
        "settings.appId.description": "自分のDiscordアプリケーションのID。ステータスはそのアプリとして表示されます。作り方は下のガイドを参照してください。",
        "toast.imagesFailed": "Rich Presence: Discordが画像を受け付けませんでした。リンクとApplication IDを確認してください。",
        "panel.presets": "プリセット",
        "panel.new": "新規",
        "panel.newTitle": "プリセット {n}",
        "panel.copyOf": "{title}(コピー)",
        "panel.untitled": "無題",
        "panel.empty": "プリセットはまだありません。「新規」で作成して、プロフィールに表示しましょう。",
        "panel.pluginOff": "Rich Presence Builderはオフです。今プリセットを用意しておけば、オンにしたときに表示されます。",
        "panel.showing": "プロフィールに表示中",
        "panel.show": "プロフィールに表示",
        "panel.hide": "表示をやめる",
        "panel.duplicate": "複製",
        "panel.delete": "削除",
        "panel.deleteConfirm": "もう一度クリックで削除",
        "panel.whoSees": "このパソコンでDiscordを開いている間、あなたのアクティビティを見られる全員に表示されます。ボタンは他の人にだけ機能し、あなた自身には表示されません。",
        "section.text": "テキスト",
        "section.images": "画像",
        "section.buttons": "ボタン",
        "section.more": "時間とパーティー",
        "field.title": "プリセット名",
        "field.title.hint": "あなたにだけ表示されます。",
        "field.type": "アクティビティ",
        "field.name": "名前",
        "field.name.placeholder": "していること",
        "field.details": "1行目",
        "field.details.placeholder": "メインメニュー",
        "field.state": "2行目",
        "field.state.placeholder": "チームを募集中",
        "field.streamUrl": "配信リンク",
        "field.streamUrl.hint": "DiscordはTwitchかYouTubeのリンクがある場合のみ「配信中」と表示します。",
        "field.largeImage": "大きい画像",
        "field.imageHint": "画像へのhttpsリンク、またはアップロードしたArt Assetのキー。",
        "field.largeText": "大きい画像のホバーテキスト",
        "field.smallImage": "小さい画像",
        "field.smallText": "小さい画像のホバーテキスト",
        "field.buttonLabel": "ボタン{n}のテキスト",
        "field.buttonUrl": "ボタン{n}のリンク",
        "field.buttons.hint": "ボタンは2つまで、それぞれhttpsリンクが必要です。",
        "field.time": "タイマー",
        "field.timeStart": "開始時刻",
        "field.timeEnd": "カウントダウンの終了時刻",
        "field.party": "パーティー",
        "field.party.hint": "2行目のあとに「(2 / 4)」のように表示されます。不要なら空欄に。",
        "field.partySize": "パーティーの人数",
        "field.partyOf": "/",
        "field.partyMax": "パーティーの定員",
        "type.playing": "プレイ中",
        "type.listening": "再生中",
        "type.watching": "視聴中",
        "type.competing": "参戦中",
        "type.streaming": "配信中",
        "time.none": "なし",
        "time.elapsed": "表示を始めてからの時間",
        "time.localTime": "現地時刻",
        "time.start": "指定時刻から",
        "time.end": "指定時刻までのカウントダウン",
        "problem.noAppId": "先にApplication IDを追加してください。",
        "problem.noName": "名前を入力してください。",
        "problem.badLargeImage": "大きい画像にはhttpsリンクが必要です。",
        "problem.badSmallImage": "小さい画像にはhttpsリンクが必要です。",
        "problem.badStreamUrl": "配信中にはTwitchかYouTubeのリンクが必要です。",
        "problem.buttonLabel": "リンクのあるボタンにはテキストが必要です。",
        "problem.buttonUrl": "各ボタンにhttpsリンクが必要です。",
        "problem.badParty": "パーティーの人数は定員を超えられません。",
        "problem.noTime": "タイマーの時刻を選んでください。",
        "preview.title": "プレビュー",
        "preview.elapsed": "{time} 経過",
        "preview.left": "残り {time}",
        "preview.party": "({size} / {max})",
        "guide.title": "Rich Presenceの設定",
        "guide.intro": "ステータスは自分のDiscordアプリケーションとして表示されます。2分ほどで終わり、最初の一度だけです。",
        "guide.step1.title": "Developer Portalを開く",
        "guide.step1.body": "Discordアカウントでログインします。アプリケーションの作成は無料で、使うまで誰にも見えません。",
        "guide.step1.button": "Developer Portalを開く",
        "guide.step2.title": "アプリケーションを作成",
        "guide.step2.body": "右上のNew Applicationをクリックして名前を付けます。「プレイ中」の後にはプリセットの名前が表示され、空欄ならこのアプリケーションの名前が表示されます。",
        "guide.step3.title": "Application IDをコピー",
        "guide.step3.body": "General InformationページでApplication IDを見つけ、Copyをクリックします。",
        "guide.step4.title": "ここに貼り付け",
        "guide.step4.placeholder": "Application ID(例: 123456789012345678)",
        "guide.step4.check": "確認",
        "guide.step4.checking": "確認中…",
        "guide.step4.invalid": "Application IDではありません。17〜20桁の数字です。",
        "guide.step4.notFound": "そのIDのアプリケーションは見つかりません。General Informationからもう一度コピーしてください。",
        "guide.step4.failed": "今は確認できませんでした: {error}",
        "guide.step4.ok": "{name}が見つかりました。準備完了です。",
        "guide.step5.title": "任意: 自分の画像をアップロード",
        "guide.step5.body": "画像欄には画像へのhttpsリンクを入力できます。ポータルのRich Presence → Art Assetsで画像をアップロードし、そのキー(例: \"logo\")を入力することもできます。",
        "guide.done": "作り始める",
        "guide.reopen": "設定方法",
        "guide.change": "別のアプリケーションを使う",
        "field.name.hintApp": "空欄にするとアプリケーション名「{name}」が表示されます。",
    },
    pl: {
        "settings.appId": "Application ID",
        "settings.appId.description": "ID Twojej własnej aplikacji Discord: Twój status pokazuje się jako ona. Poniższy przewodnik pokazuje, jak ją utworzyć.",
        "toast.imagesFailed": "Rich Presence: Discord nie przyjął obrazów. Sprawdź linki i Application ID.",
        "panel.presets": "Ustawienia",
        "panel.new": "Nowe",
        "panel.newTitle": "Ustawienie {n}",
        "panel.copyOf": "{title} (kopia)",
        "panel.untitled": "Bez nazwy",
        "panel.empty": "Nie ma jeszcze żadnych. Utwórz jedno przyciskiem Nowe i pokaż je na profilu.",
        "panel.pluginOff": "Rich Presence Builder jest wyłączony: możesz już przygotować ustawienia, pokażą się po jego włączeniu.",
        "panel.showing": "Na twoim profilu",
        "panel.show": "Pokaż na moim profilu",
        "panel.hide": "Przestań pokazywać",
        "panel.duplicate": "Duplikuj",
        "panel.delete": "Usuń",
        "panel.deleteConfirm": "Kliknij ponownie, aby usunąć",
        "panel.whoSees": "Widzi to każdy, kto widzi twoją aktywność, gdy Discord jest otwarty na tym komputerze. Przyciski działają tylko dla innych: Discord ich tobie nie pokazuje.",
        "section.text": "Tekst",
        "section.images": "Obrazy",
        "section.buttons": "Przyciski",
        "section.more": "Czas i drużyna",
        "field.title": "Nazwa ustawienia",
        "field.title.hint": "Widzisz ją tylko ty.",
        "field.type": "Aktywność",
        "field.name": "Nazwa",
        "field.name.placeholder": "Co robisz",
        "field.details": "Pierwsza linia",
        "field.details.placeholder": "W menu głównym",
        "field.state": "Druga linia",
        "field.state.placeholder": "Szuka drużyny",
        "field.streamUrl": "Link do streamu",
        "field.streamUrl.hint": "Discord pokazuje „Transmituje” tylko z linkiem do Twitcha lub YouTube.",
        "field.largeImage": "Duży obraz",
        "field.imageHint": "Link https do obrazu albo klucz wgranego Art Asset.",
        "field.largeText": "Tekst po najechaniu na duży obraz",
        "field.smallImage": "Mały obraz",
        "field.smallText": "Tekst po najechaniu na mały obraz",
        "field.buttonLabel": "Tekst przycisku {n}",
        "field.buttonUrl": "Link przycisku {n}",
        "field.buttons.hint": "Do dwóch przycisków, każdy z linkiem https.",
        "field.time": "Licznik",
        "field.timeStart": "Liczy od",
        "field.timeEnd": "Odlicza do",
        "field.party": "Drużyna",
        "field.party.hint": "Pokazuje się jako „(2 z 4)” po drugiej linii. Zostaw puste, by nie pokazywać.",
        "field.partySize": "Osoby w drużynie",
        "field.partyOf": "z",
        "field.partyMax": "Rozmiar drużyny",
        "type.playing": "Gra",
        "type.listening": "Słucha",
        "type.watching": "Ogląda",
        "type.competing": "Rywalizuje",
        "type.streaming": "Transmituje",
        "time.none": "Brak",
        "time.elapsed": "Czas od włączenia",
        "time.localTime": "Twój czas lokalny",
        "time.start": "Od ustalonej godziny",
        "time.end": "Odliczanie do ustalonej godziny",
        "problem.noAppId": "Najpierw dodaj Application ID.",
        "problem.noName": "Nadaj mu nazwę.",
        "problem.badLargeImage": "Duży obraz potrzebuje linku https.",
        "problem.badSmallImage": "Mały obraz potrzebuje linku https.",
        "problem.badStreamUrl": "Transmisja potrzebuje linku do Twitcha lub YouTube.",
        "problem.buttonLabel": "Przycisk z linkiem potrzebuje tekstu.",
        "problem.buttonUrl": "Każdy przycisk potrzebuje linku https.",
        "problem.badParty": "Drużyna nie może mieć więcej osób niż jej rozmiar.",
        "problem.noTime": "Wybierz godzinę dla licznika.",
        "preview.title": "Podgląd",
        "preview.elapsed": "minęło {time}",
        "preview.left": "zostało {time}",
        "preview.party": "({size} z {max})",
        "guide.title": "Konfiguracja Rich Presence",
        "guide.intro": "Twój status pokazuje się jako Twoja własna aplikacja Discord. Zajmuje to około dwóch minut i robisz to tylko raz.",
        "guide.step1.title": "Otwórz Developer Portal",
        "guide.step1.body": "Zaloguj się kontem Discord. Utworzenie aplikacji jest darmowe i nikt jej nie widzi, dopóki jej nie użyjesz.",
        "guide.step1.button": "Otwórz Developer Portal",
        "guide.step2.title": "Utwórz aplikację",
        "guide.step2.body": "Kliknij New Application w prawym górnym rogu i nadaj jej nazwę. Po „Gra w” pokazuje się Nazwa ustawienia; jeśli zostawisz ją pustą, pokaże się nazwa tej aplikacji.",
        "guide.step3.title": "Skopiuj jej Application ID",
        "guide.step3.body": "Na stronie General Information znajdź Application ID i kliknij Copy.",
        "guide.step4.title": "Wklej je tutaj",
        "guide.step4.placeholder": "Application ID, np. 123456789012345678",
        "guide.step4.check": "Sprawdź",
        "guide.step4.checking": "Sprawdzanie…",
        "guide.step4.invalid": "To nie jest Application ID: ma od 17 do 20 cyfr.",
        "guide.step4.notFound": "Discord nie zna aplikacji o tym ID. Skopiuj je jeszcze raz z General Information.",
        "guide.step4.failed": "Nie udało się teraz sprawdzić: {error}",
        "guide.step4.ok": "Znaleziono {name}. Wszystko gotowe.",
        "guide.step5.title": "Opcjonalnie: wgraj własne obrazy",
        "guide.step5.body": "Pola obrazów przyjmują dowolny link https do obrazu. Możesz też wgrać obrazy w portalu w Rich Presence → Art Assets i wpisać ich klucz, np. „logo”.",
        "guide.done": "Zaczynamy",
        "guide.reopen": "Jak to skonfigurować",
        "guide.change": "Użyj innej aplikacji",
        "field.name.hintApp": "Zostaw puste, aby pokazać nazwę aplikacji: {name}.",
    },
    "pt-BR": {
        "settings.appId": "Application ID",
        "settings.appId.description": "O ID do seu próprio aplicativo do Discord: seu status aparece como ele. O guia abaixo mostra como criar um.",
        "toast.imagesFailed": "Rich Presence: o Discord não aceitou as imagens. Confira os links e o Application ID.",
        "panel.presets": "Predefinições",
        "panel.new": "Nova",
        "panel.newTitle": "Predefinição {n}",
        "panel.copyOf": "{title} (cópia)",
        "panel.untitled": "Sem nome",
        "panel.empty": "Ainda não há predefinições. Crie uma com Nova e mostre no seu perfil.",
        "panel.pluginOff": "O Rich Presence Builder está desligado: você já pode preparar predefinições, elas aparecem quando você ligá-lo.",
        "panel.showing": "No seu perfil",
        "panel.show": "Mostrar no meu perfil",
        "panel.hide": "Parar de mostrar",
        "panel.duplicate": "Duplicar",
        "panel.delete": "Excluir",
        "panel.deleteConfirm": "Clique de novo para excluir",
        "panel.whoSees": "Todos que podem ver sua atividade veem isso, enquanto o Discord estiver aberto neste computador. Os botões só funcionam para os outros: o Discord não os mostra para você.",
        "section.text": "Texto",
        "section.images": "Imagens",
        "section.buttons": "Botões",
        "section.more": "Tempo e grupo",
        "field.title": "Nome da predefinição",
        "field.title.hint": "Só você vê isso.",
        "field.type": "Atividade",
        "field.name": "Nome",
        "field.name.placeholder": "O que você está fazendo",
        "field.details": "Primeira linha",
        "field.details.placeholder": "No menu principal",
        "field.state": "Segunda linha",
        "field.state.placeholder": "Procurando equipe",
        "field.streamUrl": "Link da transmissão",
        "field.streamUrl.hint": "O Discord só mostra \"Transmitindo\" com um link da Twitch ou do YouTube.",
        "field.largeImage": "Imagem grande",
        "field.imageHint": "Um link https para uma imagem, ou a chave de um Art Asset que você enviou.",
        "field.largeText": "Texto ao passar o mouse na imagem grande",
        "field.smallImage": "Imagem pequena",
        "field.smallText": "Texto ao passar o mouse na imagem pequena",
        "field.buttonLabel": "Texto do botão {n}",
        "field.buttonUrl": "Link do botão {n}",
        "field.buttons.hint": "Até dois botões, cada um com um link https.",
        "field.time": "Cronômetro",
        "field.timeStart": "Contando desde",
        "field.timeEnd": "Contagem regressiva até",
        "field.party": "Grupo",
        "field.party.hint": "Aparece como \"(2 de 4)\" depois da segunda linha. Deixe vazio para nenhum.",
        "field.partySize": "Pessoas no grupo",
        "field.partyOf": "de",
        "field.partyMax": "Tamanho do grupo",
        "type.playing": "Jogando",
        "type.listening": "Ouvindo",
        "type.watching": "Assistindo",
        "type.competing": "Competindo",
        "type.streaming": "Transmitindo",
        "time.none": "Nenhum",
        "time.elapsed": "Tempo desde que foi ativada",
        "time.localTime": "Seu horário local",
        "time.start": "Desde um horário definido",
        "time.end": "Contagem regressiva até um horário definido",
        "problem.noAppId": "Adicione um Application ID primeiro.",
        "problem.noName": "Dê um nome a ela.",
        "problem.badLargeImage": "A imagem grande precisa de um link https.",
        "problem.badSmallImage": "A imagem pequena precisa de um link https.",
        "problem.badStreamUrl": "Transmitindo precisa de um link da Twitch ou do YouTube.",
        "problem.buttonLabel": "Um botão com link precisa de texto.",
        "problem.buttonUrl": "Cada botão precisa de um link https.",
        "problem.badParty": "O grupo não pode ter mais pessoas que o tamanho dele.",
        "problem.noTime": "Escolha um horário para o cronômetro.",
        "preview.title": "Prévia",
        "preview.elapsed": "{time} decorrido",
        "preview.left": "faltam {time}",
        "preview.party": "({size} de {max})",
        "guide.title": "Configurar o Rich Presence",
        "guide.intro": "Seu status aparece como um aplicativo do Discord seu. Leva uns dois minutos e só precisa ser feito uma vez.",
        "guide.step1.title": "Abra o Developer Portal",
        "guide.step1.body": "Entre com sua conta do Discord. Criar um aplicativo é grátis e ninguém o vê até você usá-lo.",
        "guide.step1.button": "Abrir o Developer Portal",
        "guide.step2.title": "Crie um aplicativo",
        "guide.step2.body": "Clique em New Application no canto superior direito e dê um nome. Depois de \"Jogando\" aparece o Nome da predefinição; deixe vazio e aparece o nome deste aplicativo.",
        "guide.step3.title": "Copie o Application ID",
        "guide.step3.body": "Na página General Information, encontre Application ID e clique em Copy.",
        "guide.step4.title": "Cole aqui",
        "guide.step4.placeholder": "Application ID, como 123456789012345678",
        "guide.step4.check": "Verificar",
        "guide.step4.checking": "Verificando…",
        "guide.step4.invalid": "Isso não é um Application ID: ele tem de 17 a 20 dígitos.",
        "guide.step4.notFound": "O Discord não conhece um aplicativo com esse ID. Copie de novo em General Information.",
        "guide.step4.failed": "Não deu para verificar agora: {error}",
        "guide.step4.ok": "{name} encontrado. Tudo pronto.",
        "guide.step5.title": "Opcional: envie suas próprias imagens",
        "guide.step5.body": "Os campos de imagem aceitam qualquer link https para uma imagem. Você também pode enviar imagens no portal em Rich Presence → Art Assets e digitar a chave delas, como \"logo\".",
        "guide.done": "Começar",
        "guide.reopen": "Como configurar",
        "guide.change": "Usar outro aplicativo",
        "field.name.hintApp": "Deixe vazio para mostrar o nome do seu aplicativo: {name}.",
    },
    ru: {
        "settings.appId": "Application ID",
        "settings.appId.description": "ID вашего собственного приложения Discord: статус показывается от его имени. Как его создать, показано в руководстве ниже.",
        "toast.imagesFailed": "Rich Presence: Discord не принял картинки. Проверьте ссылки и Application ID.",
        "panel.presets": "Пресеты",
        "panel.new": "Новый",
        "panel.newTitle": "Пресет {n}",
        "panel.copyOf": "{title} (копия)",
        "panel.untitled": "Без названия",
        "panel.empty": "Пресетов пока нет. Создайте его кнопкой «Новый» и покажите в профиле.",
        "panel.pluginOff": "Rich Presence Builder выключен: пресеты можно подготовить уже сейчас, они появятся, когда вы его включите.",
        "panel.showing": "В вашем профиле",
        "panel.show": "Показать в профиле",
        "panel.hide": "Больше не показывать",
        "panel.duplicate": "Дублировать",
        "panel.delete": "Удалить",
        "panel.deleteConfirm": "Нажмите ещё раз для удаления",
        "panel.whoSees": "Это видят все, кому видна ваша активность, пока Discord открыт на этом компьютере. Кнопки работают только для других: вам Discord их не показывает.",
        "section.text": "Текст",
        "section.images": "Картинки",
        "section.buttons": "Кнопки",
        "section.more": "Время и группа",
        "field.title": "Название пресета",
        "field.title.hint": "Видно только вам.",
        "field.type": "Активность",
        "field.name": "Название",
        "field.name.placeholder": "Чем вы заняты",
        "field.details": "Первая строка",
        "field.details.placeholder": "В главном меню",
        "field.state": "Вторая строка",
        "field.state.placeholder": "Ищет команду",
        "field.streamUrl": "Ссылка на трансляцию",
        "field.streamUrl.hint": "Discord показывает «Стримит» только со ссылкой на Twitch или YouTube.",
        "field.largeImage": "Большая картинка",
        "field.imageHint": "https-ссылка на изображение или ключ загруженного Art Asset.",
        "field.largeText": "Подсказка большой картинки",
        "field.smallImage": "Маленькая картинка",
        "field.smallText": "Подсказка маленькой картинки",
        "field.buttonLabel": "Текст кнопки {n}",
        "field.buttonUrl": "Ссылка кнопки {n}",
        "field.buttons.hint": "До двух кнопок, у каждой ссылка https.",
        "field.time": "Таймер",
        "field.timeStart": "Отсчёт с",
        "field.timeEnd": "Обратный отсчёт до",
        "field.party": "Группа",
        "field.party.hint": "Показывается как «(2 из 4)» после второй строки. Оставьте пустым, чтобы не показывать.",
        "field.partySize": "Людей в группе",
        "field.partyOf": "из",
        "field.partyMax": "Размер группы",
        "type.playing": "Играет",
        "type.listening": "Слушает",
        "type.watching": "Смотрит",
        "type.competing": "Соревнуется",
        "type.streaming": "Стримит",
        "time.none": "Нет",
        "time.elapsed": "Время с момента включения",
        "time.localTime": "Ваше местное время",
        "time.start": "С заданного времени",
        "time.end": "Обратный отсчёт до заданного времени",
        "problem.noAppId": "Сначала добавьте Application ID.",
        "problem.noName": "Дайте ему название.",
        "problem.badLargeImage": "Для большой картинки нужна ссылка https.",
        "problem.badSmallImage": "Для маленькой картинки нужна ссылка https.",
        "problem.badStreamUrl": "Для стрима нужна ссылка на Twitch или YouTube.",
        "problem.buttonLabel": "Кнопке со ссылкой нужен текст.",
        "problem.buttonUrl": "Каждой кнопке нужна ссылка https.",
        "problem.badParty": "В группе не может быть больше людей, чем её размер.",
        "problem.noTime": "Выберите время для таймера.",
        "preview.title": "Предпросмотр",
        "preview.elapsed": "прошло {time}",
        "preview.left": "осталось {time}",
        "preview.party": "({size} из {max})",
        "guide.title": "Настройка Rich Presence",
        "guide.intro": "Статус показывается от имени вашего собственного приложения Discord. Это займёт около двух минут, и делается один раз.",
        "guide.step1.title": "Откройте Developer Portal",
        "guide.step1.body": "Войдите в свой аккаунт Discord. Создать приложение бесплатно, и его никто не видит, пока вы им не пользуетесь.",
        "guide.step1.button": "Открыть Developer Portal",
        "guide.step2.title": "Создайте приложение",
        "guide.step2.body": "Нажмите New Application справа вверху и дайте ему имя. После «Играет в» показывается Название пресета; если оставить его пустым, будет показано имя этого приложения.",
        "guide.step3.title": "Скопируйте его Application ID",
        "guide.step3.body": "На странице General Information найдите Application ID и нажмите Copy.",
        "guide.step4.title": "Вставьте его сюда",
        "guide.step4.placeholder": "Application ID, например 123456789012345678",
        "guide.step4.check": "Проверить",
        "guide.step4.checking": "Проверка…",
        "guide.step4.invalid": "Это не Application ID: в нём от 17 до 20 цифр.",
        "guide.step4.notFound": "Discord не знает приложения с таким ID. Скопируйте его ещё раз в General Information.",
        "guide.step4.failed": "Сейчас не удалось проверить: {error}",
        "guide.step4.ok": "Найдено: {name}. Всё готово.",
        "guide.step5.title": "Необязательно: загрузите свои картинки",
        "guide.step5.body": "В поля картинок можно вставить любую https-ссылку на изображение. Также можно загрузить картинки в портале в Rich Presence → Art Assets и указать их ключ, например «logo».",
        "guide.done": "Начать",
        "guide.reopen": "Как настроить",
        "guide.change": "Другое приложение",
        "field.name.hintApp": "Оставьте пустым, чтобы показывалось имя приложения: {name}.",
    },
    tr: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Kendi Discord uygulamanın ID'si: durumun onun olarak görünür. Aşağıdaki rehber nasıl oluşturulacağını gösterir.",
        "toast.imagesFailed": "Rich Presence: Discord resimleri kabul etmedi. Bağlantıları ve Application ID'yi kontrol et.",
        "panel.presets": "Hazır ayarlar",
        "panel.new": "Yeni",
        "panel.newTitle": "Hazır ayar {n}",
        "panel.copyOf": "{title} (kopya)",
        "panel.untitled": "Adsız",
        "panel.empty": "Henüz hazır ayar yok. Yeni ile bir tane oluştur ve profilinde göster.",
        "panel.pluginOff": "Rich Presence Builder kapalı: hazır ayarları şimdi hazırlayabilirsin, açtığında görünürler.",
        "panel.showing": "Profilinde",
        "panel.show": "Profilimde göster",
        "panel.hide": "Göstermeyi bırak",
        "panel.duplicate": "Çoğalt",
        "panel.delete": "Sil",
        "panel.deleteConfirm": "Silmek için tekrar tıkla",
        "panel.whoSees": "Bu bilgisayarda Discord açık olduğu sürece etkinliğini görebilen herkes bunu görür. Butonlar yalnızca başkaları için çalışır: Discord onları sana göstermez.",
        "section.text": "Metin",
        "section.images": "Resimler",
        "section.buttons": "Butonlar",
        "section.more": "Süre ve grup",
        "field.title": "Hazır ayar adı",
        "field.title.hint": "Bunu yalnızca sen görürsün.",
        "field.type": "Etkinlik",
        "field.name": "Ad",
        "field.name.placeholder": "Ne yapıyorsun",
        "field.details": "İlk satır",
        "field.details.placeholder": "Ana menüde",
        "field.state": "İkinci satır",
        "field.state.placeholder": "Takım arıyor",
        "field.streamUrl": "Yayın bağlantısı",
        "field.streamUrl.hint": "Discord \"Yayında\" durumunu yalnızca Twitch veya YouTube bağlantısıyla gösterir.",
        "field.largeImage": "Büyük resim",
        "field.imageHint": "Bir resme giden https bağlantısı ya da yüklediğin bir Art Asset'in anahtarı.",
        "field.largeText": "Büyük resmin üzerine gelince çıkan metin",
        "field.smallImage": "Küçük resim",
        "field.smallText": "Küçük resmin üzerine gelince çıkan metin",
        "field.buttonLabel": "Buton {n} metni",
        "field.buttonUrl": "Buton {n} bağlantısı",
        "field.buttons.hint": "En fazla iki buton, her biri bir https bağlantısıyla.",
        "field.time": "Sayaç",
        "field.timeStart": "Şu andan itibaren say",
        "field.timeEnd": "Şu ana kadar geri say",
        "field.party": "Grup",
        "field.party.hint": "İkinci satırdan sonra \"(2/4)\" gibi görünür. İstemiyorsan boş bırak.",
        "field.partySize": "Gruptaki kişi sayısı",
        "field.partyOf": "/",
        "field.partyMax": "Grup boyutu",
        "type.playing": "Oynuyor",
        "type.listening": "Dinliyor",
        "type.watching": "İzliyor",
        "type.competing": "Yarışıyor",
        "type.streaming": "Yayında",
        "time.none": "Yok",
        "time.elapsed": "Açıldığından beri geçen süre",
        "time.localTime": "Yerel saatin",
        "time.start": "Belirli bir zamandan beri",
        "time.end": "Belirli bir zamana geri sayım",
        "problem.noAppId": "Önce bir Application ID ekle.",
        "problem.noName": "Bir ad ver.",
        "problem.badLargeImage": "Büyük resim için https bağlantısı gerekiyor.",
        "problem.badSmallImage": "Küçük resim için https bağlantısı gerekiyor.",
        "problem.badStreamUrl": "Yayın için Twitch veya YouTube bağlantısı gerekiyor.",
        "problem.buttonLabel": "Bağlantısı olan bir butonun metni olmalı.",
        "problem.buttonUrl": "Her butonun bir https bağlantısı olmalı.",
        "problem.badParty": "Gruptaki kişi sayısı grup boyutunu geçemez.",
        "problem.noTime": "Sayaç için bir zaman seç.",
        "preview.title": "Önizleme",
        "preview.elapsed": "{time} geçti",
        "preview.left": "{time} kaldı",
        "preview.party": "({size}/{max})",
        "guide.title": "Rich Presence kurulumu",
        "guide.intro": "Durumun kendi Discord uygulaman olarak görünür. Yaklaşık iki dakika sürer ve yalnızca bir kez yapılır.",
        "guide.step1.title": "Developer Portal'ı aç",
        "guide.step1.body": "Discord hesabınla giriş yap. Uygulama oluşturmak ücretsizdir ve sen kullanana kadar kimse görmez.",
        "guide.step1.button": "Developer Portal'ı aç",
        "guide.step2.title": "Bir uygulama oluştur",
        "guide.step2.body": "Sağ üstte New Application'a tıkla ve bir ad ver. \"Oynuyor\"dan sonra ön ayarın Adı görünür; boş bırakırsan bu uygulamanın adı görünür.",
        "guide.step3.title": "Application ID'sini kopyala",
        "guide.step3.body": "General Information sayfasında Application ID'yi bul ve Copy'ye tıkla.",
        "guide.step4.title": "Buraya yapıştır",
        "guide.step4.placeholder": "Application ID, ör. 123456789012345678",
        "guide.step4.check": "Kontrol et",
        "guide.step4.checking": "Kontrol ediliyor…",
        "guide.step4.invalid": "Bu bir Application ID değil: 17 ile 20 basamaklıdır.",
        "guide.step4.notFound": "Discord bu ID'ye sahip bir uygulama bilmiyor. General Information'dan yeniden kopyala.",
        "guide.step4.failed": "Şu an kontrol edilemedi: {error}",
        "guide.step4.ok": "{name} bulundu. Her şey hazır.",
        "guide.step5.title": "İsteğe bağlı: kendi resimlerini yükle",
        "guide.step5.body": "Resim alanları bir resme giden herhangi bir https bağlantısını kabul eder. Portalda Rich Presence → Art Assets altında resim yükleyip bunun yerine anahtarını da yazabilirsin, ör. \"logo\".",
        "guide.done": "Başla",
        "guide.reopen": "Nasıl kurulur",
        "guide.change": "Başka bir uygulama kullan",
        "field.name.hintApp": "Boş bırakırsan uygulamanın adı görünür: {name}.",
    },
});
