import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.appId": "Application ID",
        "settings.appId.description": "The Discord application your status shows as. Create one at discord.com/developers/applications, name it whatever you like, and paste its Application ID here.",
        "settings.appId.descriptionDefault": "Leave empty to use Evi's own. To use your own, create an application at discord.com/developers/applications and paste its Application ID here.",
        "toast.imagesFailed": "Rich Presence: Discord didn't accept the pictures. Check the links and the Application ID.",
        "panel.presets": "Presets",
        "panel.new": "New",
        "panel.newTitle": "Preset {n}",
        "panel.copyOf": "{title} (copy)",
        "panel.untitled": "Untitled",
        "panel.empty": "No presets yet. Make one with New, and show it on your profile.",
        "panel.noAppId": "Rich Presence needs a Discord application to show as. Create one at discord.com/developers/applications (any name works), copy its Application ID, and paste it in the Application ID setting above.",
        "panel.pluginOff": "Rich Presence Builder is off: you can set up presets now, and they show once you turn it on.",
        "panel.showing": "On your profile",
        "panel.show": "Show on my profile",
        "panel.hide": "Stop showing",
        "panel.duplicate": "Duplicate",
        "panel.delete": "Delete",
        "panel.deleteConfirm": "Click again to delete",
        "panel.whoSees": "Everyone who can see your activity sees this, while Discord is open on this computer. Buttons only work for others: Discord doesn't show them to you.",
        "section.text": "Text",
        "section.images": "Pictures",
        "section.buttons": "Buttons",
        "section.more": "Time and party",
        "field.title": "Preset name",
        "field.title.hint": "Only you see this.",
        "field.type": "Activity",
        "field.name": "Name",
        "field.name.placeholder": "What you're doing",
        "field.details": "First line",
        "field.details.placeholder": "In the main menu",
        "field.state": "Second line",
        "field.state.placeholder": "Looking for a team",
        "field.streamUrl": "Stream link",
        "field.streamUrl.hint": "Discord only shows Streaming with a Twitch or YouTube link.",
        "field.largeImage": "Big picture",
        "field.imageHint": "An https link to a picture.",
        "field.largeText": "Big picture's hover text",
        "field.smallImage": "Small picture",
        "field.smallText": "Small picture's hover text",
        "field.buttonLabel": "Button {n} text",
        "field.buttonUrl": "Button {n} link",
        "field.buttons.hint": "Up to two buttons, each with an https link.",
        "field.time": "Timer",
        "field.timeStart": "Counting from",
        "field.timeEnd": "Counting down to",
        "field.party": "Party",
        "field.party.hint": "Shows as \"(2 of 4)\" after the second line. Leave empty for none.",
        "field.partySize": "People in the party",
        "field.partyOf": "of",
        "field.partyMax": "Party size",
        "type.playing": "Playing",
        "type.listening": "Listening",
        "type.watching": "Watching",
        "type.competing": "Competing",
        "type.streaming": "Streaming",
        "time.none": "None",
        "time.elapsed": "Time since it went on",
        "time.localTime": "Your local time",
        "time.start": "Since a set time",
        "time.end": "Countdown to a set time",
        "problem.noAppId": "Add an Application ID first.",
        "problem.noName": "Give it a name.",
        "problem.badLargeImage": "The big picture needs an https link.",
        "problem.badSmallImage": "The small picture needs an https link.",
        "problem.badStreamUrl": "Streaming needs a Twitch or YouTube link.",
        "problem.buttonLabel": "A button with a link needs text.",
        "problem.buttonUrl": "Each button needs an https link.",
        "problem.badParty": "The party can't have more people than its size.",
        "problem.noTime": "Pick a time for the timer.",
        "preview.title": "Preview",
        "preview.elapsed": "{time} elapsed",
        "preview.left": "{time} left",
        "preview.party": "({size} of {max})",
    },
    de: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Die Discord-Anwendung, als die dein Status erscheint. Erstelle eine unter discord.com/developers/applications, benenne sie beliebig und füge hier ihre Application ID ein.",
        "settings.appId.descriptionDefault": "Leer lassen, um Evis eigene zu nutzen. Für eine eigene erstelle eine Anwendung unter discord.com/developers/applications und füge hier ihre Application ID ein.",
        "toast.imagesFailed": "Rich Presence: Discord hat die Bilder nicht angenommen. Prüfe die Links und die Application ID.",
        "panel.presets": "Vorlagen",
        "panel.new": "Neu",
        "panel.newTitle": "Vorlage {n}",
        "panel.copyOf": "{title} (Kopie)",
        "panel.untitled": "Ohne Namen",
        "panel.empty": "Noch keine Vorlagen. Erstelle eine mit Neu und zeige sie in deinem Profil.",
        "panel.noAppId": "Rich Presence braucht eine Discord-Anwendung, als die sie erscheint. Erstelle eine unter discord.com/developers/applications (jeder Name geht), kopiere ihre Application ID und füge sie oben bei Application ID ein.",
        "panel.pluginOff": "Rich Presence Builder ist aus: Du kannst jetzt Vorlagen anlegen, sie erscheinen, sobald du es einschaltest.",
        "panel.showing": "In deinem Profil",
        "panel.show": "In meinem Profil zeigen",
        "panel.hide": "Nicht mehr zeigen",
        "panel.duplicate": "Duplizieren",
        "panel.delete": "Löschen",
        "panel.deleteConfirm": "Zum Löschen erneut klicken",
        "panel.whoSees": "Alle, die deine Aktivität sehen können, sehen das, solange Discord auf diesem Computer offen ist. Die Buttons funktionieren nur für andere: Dir zeigt Discord sie nicht.",
        "section.text": "Text",
        "section.images": "Bilder",
        "section.buttons": "Buttons",
        "section.more": "Zeit und Gruppe",
        "field.title": "Name der Vorlage",
        "field.title.hint": "Nur du siehst das.",
        "field.type": "Aktivität",
        "field.name": "Name",
        "field.name.placeholder": "Was du gerade machst",
        "field.details": "Erste Zeile",
        "field.details.placeholder": "Im Hauptmenü",
        "field.state": "Zweite Zeile",
        "field.state.placeholder": "Sucht ein Team",
        "field.streamUrl": "Stream-Link",
        "field.streamUrl.hint": "Discord zeigt „Streamt“ nur mit einem Twitch- oder YouTube-Link.",
        "field.largeImage": "Großes Bild",
        "field.imageHint": "Ein https-Link zu einem Bild.",
        "field.largeText": "Hover-Text des großen Bilds",
        "field.smallImage": "Kleines Bild",
        "field.smallText": "Hover-Text des kleinen Bilds",
        "field.buttonLabel": "Text von Button {n}",
        "field.buttonUrl": "Link von Button {n}",
        "field.buttons.hint": "Bis zu zwei Buttons, jeder mit einem https-Link.",
        "field.time": "Timer",
        "field.timeStart": "Zählt ab",
        "field.timeEnd": "Zählt herunter bis",
        "field.party": "Gruppe",
        "field.party.hint": "Erscheint als „(2 von 4)“ nach der zweiten Zeile. Leer lassen für keine.",
        "field.partySize": "Personen in der Gruppe",
        "field.partyOf": "von",
        "field.partyMax": "Gruppengröße",
        "type.playing": "Spielt",
        "type.listening": "Hört",
        "type.watching": "Schaut",
        "type.competing": "Tritt an",
        "type.streaming": "Streamt",
        "time.none": "Keiner",
        "time.elapsed": "Zeit seit dem Einschalten",
        "time.localTime": "Deine Uhrzeit",
        "time.start": "Seit einer festen Zeit",
        "time.end": "Countdown bis zu einer festen Zeit",
        "problem.noAppId": "Füge zuerst eine Application ID hinzu.",
        "problem.noName": "Gib ihr einen Namen.",
        "problem.badLargeImage": "Das große Bild braucht einen https-Link.",
        "problem.badSmallImage": "Das kleine Bild braucht einen https-Link.",
        "problem.badStreamUrl": "Streamen braucht einen Twitch- oder YouTube-Link.",
        "problem.buttonLabel": "Ein Button mit Link braucht einen Text.",
        "problem.buttonUrl": "Jeder Button braucht einen https-Link.",
        "problem.badParty": "Die Gruppe kann nicht mehr Personen haben als ihre Größe.",
        "problem.noTime": "Wähle eine Zeit für den Timer.",
        "preview.title": "Vorschau",
        "preview.elapsed": "{time} vergangen",
        "preview.left": "noch {time}",
        "preview.party": "({size} von {max})",
    },
    es: {
        "settings.appId": "Application ID",
        "settings.appId.description": "La aplicación de Discord con la que aparece tu estado. Crea una en discord.com/developers/applications, ponle el nombre que quieras y pega aquí su Application ID.",
        "settings.appId.descriptionDefault": "Déjalo vacío para usar la de Evi. Para usar la tuya, crea una aplicación en discord.com/developers/applications y pega aquí su Application ID.",
        "toast.imagesFailed": "Rich Presence: Discord no aceptó las imágenes. Revisa los enlaces y el Application ID.",
        "panel.presets": "Ajustes guardados",
        "panel.new": "Nuevo",
        "panel.newTitle": "Ajuste {n}",
        "panel.copyOf": "{title} (copia)",
        "panel.untitled": "Sin nombre",
        "panel.empty": "Aún no hay ninguno. Crea uno con Nuevo y muéstralo en tu perfil.",
        "panel.noAppId": "Rich Presence necesita una aplicación de Discord con la que aparecer. Crea una en discord.com/developers/applications (cualquier nombre sirve), copia su Application ID y pégalo arriba en Application ID.",
        "panel.pluginOff": "Rich Presence Builder está desactivado: puedes preparar ajustes ahora y aparecerán cuando lo actives.",
        "panel.showing": "En tu perfil",
        "panel.show": "Mostrar en mi perfil",
        "panel.hide": "Dejar de mostrar",
        "panel.duplicate": "Duplicar",
        "panel.delete": "Eliminar",
        "panel.deleteConfirm": "Haz clic otra vez para eliminar",
        "panel.whoSees": "Lo ve todo el que pueda ver tu actividad, mientras Discord esté abierto en este ordenador. Los botones solo funcionan para los demás: Discord no te los muestra a ti.",
        "section.text": "Texto",
        "section.images": "Imágenes",
        "section.buttons": "Botones",
        "section.more": "Tiempo y grupo",
        "field.title": "Nombre del ajuste",
        "field.title.hint": "Solo lo ves tú.",
        "field.type": "Actividad",
        "field.name": "Nombre",
        "field.name.placeholder": "Lo que estás haciendo",
        "field.details": "Primera línea",
        "field.details.placeholder": "En el menú principal",
        "field.state": "Segunda línea",
        "field.state.placeholder": "Buscando equipo",
        "field.streamUrl": "Enlace del directo",
        "field.streamUrl.hint": "Discord solo muestra «Transmitiendo» con un enlace de Twitch o YouTube.",
        "field.largeImage": "Imagen grande",
        "field.imageHint": "Un enlace https a una imagen.",
        "field.largeText": "Texto al pasar sobre la imagen grande",
        "field.smallImage": "Imagen pequeña",
        "field.smallText": "Texto al pasar sobre la imagen pequeña",
        "field.buttonLabel": "Texto del botón {n}",
        "field.buttonUrl": "Enlace del botón {n}",
        "field.buttons.hint": "Hasta dos botones, cada uno con un enlace https.",
        "field.time": "Temporizador",
        "field.timeStart": "Contando desde",
        "field.timeEnd": "Cuenta atrás hasta",
        "field.party": "Grupo",
        "field.party.hint": "Aparece como «(2 de 4)» tras la segunda línea. Déjalo vacío para no mostrarlo.",
        "field.partySize": "Personas en el grupo",
        "field.partyOf": "de",
        "field.partyMax": "Tamaño del grupo",
        "type.playing": "Jugando",
        "type.listening": "Escuchando",
        "type.watching": "Viendo",
        "type.competing": "Compitiendo",
        "type.streaming": "Transmitiendo",
        "time.none": "Ninguno",
        "time.elapsed": "Tiempo desde que se activó",
        "time.localTime": "Tu hora local",
        "time.start": "Desde una hora fija",
        "time.end": "Cuenta atrás hasta una hora fija",
        "problem.noAppId": "Primero añade un Application ID.",
        "problem.noName": "Ponle un nombre.",
        "problem.badLargeImage": "La imagen grande necesita un enlace https.",
        "problem.badSmallImage": "La imagen pequeña necesita un enlace https.",
        "problem.badStreamUrl": "Transmitiendo necesita un enlace de Twitch o YouTube.",
        "problem.buttonLabel": "Un botón con enlace necesita texto.",
        "problem.buttonUrl": "Cada botón necesita un enlace https.",
        "problem.badParty": "El grupo no puede tener más personas que su tamaño.",
        "problem.noTime": "Elige una hora para el temporizador.",
        "preview.title": "Vista previa",
        "preview.elapsed": "{time} transcurrido",
        "preview.left": "quedan {time}",
        "preview.party": "({size} de {max})",
    },
    fr: {
        "settings.appId": "Application ID",
        "settings.appId.description": "L'application Discord sous laquelle ton statut apparaît. Crées-en une sur discord.com/developers/applications, donne-lui le nom que tu veux et colle ici son Application ID.",
        "settings.appId.descriptionDefault": "Laisse vide pour utiliser celle d'Evi. Pour utiliser la tienne, crée une application sur discord.com/developers/applications et colle ici son Application ID.",
        "toast.imagesFailed": "Rich Presence : Discord n'a pas accepté les images. Vérifie les liens et l'Application ID.",
        "panel.presets": "Préréglages",
        "panel.new": "Nouveau",
        "panel.newTitle": "Préréglage {n}",
        "panel.copyOf": "{title} (copie)",
        "panel.untitled": "Sans nom",
        "panel.empty": "Aucun préréglage pour l'instant. Crées-en un avec Nouveau et affiche-le sur ton profil.",
        "panel.noAppId": "Rich Presence a besoin d'une application Discord sous laquelle apparaître. Crées-en une sur discord.com/developers/applications (n'importe quel nom), copie son Application ID et colle-le dans le réglage Application ID ci-dessus.",
        "panel.pluginOff": "Rich Presence Builder est désactivé : tu peux préparer des préréglages maintenant, ils apparaîtront quand tu l'activeras.",
        "panel.showing": "Sur ton profil",
        "panel.show": "Afficher sur mon profil",
        "panel.hide": "Ne plus afficher",
        "panel.duplicate": "Dupliquer",
        "panel.delete": "Supprimer",
        "panel.deleteConfirm": "Clique encore pour supprimer",
        "panel.whoSees": "Tous ceux qui voient ton activité le voient, tant que Discord est ouvert sur cet ordinateur. Les boutons ne marchent que pour les autres : Discord ne te les montre pas.",
        "section.text": "Texte",
        "section.images": "Images",
        "section.buttons": "Boutons",
        "section.more": "Temps et groupe",
        "field.title": "Nom du préréglage",
        "field.title.hint": "Toi seul le vois.",
        "field.type": "Activité",
        "field.name": "Nom",
        "field.name.placeholder": "Ce que tu fais",
        "field.details": "Première ligne",
        "field.details.placeholder": "Dans le menu principal",
        "field.state": "Deuxième ligne",
        "field.state.placeholder": "Cherche une équipe",
        "field.streamUrl": "Lien du stream",
        "field.streamUrl.hint": "Discord n'affiche « En direct » qu'avec un lien Twitch ou YouTube.",
        "field.largeImage": "Grande image",
        "field.imageHint": "Un lien https vers une image.",
        "field.largeText": "Texte au survol de la grande image",
        "field.smallImage": "Petite image",
        "field.smallText": "Texte au survol de la petite image",
        "field.buttonLabel": "Texte du bouton {n}",
        "field.buttonUrl": "Lien du bouton {n}",
        "field.buttons.hint": "Jusqu'à deux boutons, chacun avec un lien https.",
        "field.time": "Minuteur",
        "field.timeStart": "Compte depuis",
        "field.timeEnd": "Compte à rebours jusqu'à",
        "field.party": "Groupe",
        "field.party.hint": "S'affiche comme « (2 sur 4) » après la deuxième ligne. Laisse vide pour aucun.",
        "field.partySize": "Personnes dans le groupe",
        "field.partyOf": "sur",
        "field.partyMax": "Taille du groupe",
        "type.playing": "Joue",
        "type.listening": "Écoute",
        "type.watching": "Regarde",
        "type.competing": "En compétition",
        "type.streaming": "En direct",
        "time.none": "Aucun",
        "time.elapsed": "Temps depuis l'activation",
        "time.localTime": "Ton heure locale",
        "time.start": "Depuis une heure précise",
        "time.end": "Compte à rebours jusqu'à une heure précise",
        "problem.noAppId": "Ajoute d'abord un Application ID.",
        "problem.noName": "Donne-lui un nom.",
        "problem.badLargeImage": "La grande image a besoin d'un lien https.",
        "problem.badSmallImage": "La petite image a besoin d'un lien https.",
        "problem.badStreamUrl": "En direct a besoin d'un lien Twitch ou YouTube.",
        "problem.buttonLabel": "Un bouton avec un lien a besoin d'un texte.",
        "problem.buttonUrl": "Chaque bouton a besoin d'un lien https.",
        "problem.badParty": "Le groupe ne peut pas compter plus de personnes que sa taille.",
        "problem.noTime": "Choisis une heure pour le minuteur.",
        "preview.title": "Aperçu",
        "preview.elapsed": "{time} écoulé",
        "preview.left": "{time} restant",
        "preview.party": "({size} sur {max})",
    },
    ja: {
        "settings.appId": "Application ID",
        "settings.appId.description": "ステータスに表示されるDiscordアプリケーションです。discord.com/developers/applications で作成し(名前は自由)、そのApplication IDをここに貼り付けてください。",
        "settings.appId.descriptionDefault": "空欄ならEvi のものを使います。自分のものを使うには discord.com/developers/applications でアプリケーションを作成し、そのApplication IDをここに貼り付けてください。",
        "toast.imagesFailed": "Rich Presence: Discordが画像を受け付けませんでした。リンクとApplication IDを確認してください。",
        "panel.presets": "プリセット",
        "panel.new": "新規",
        "panel.newTitle": "プリセット {n}",
        "panel.copyOf": "{title}(コピー)",
        "panel.untitled": "無題",
        "panel.empty": "プリセットはまだありません。「新規」で作成して、プロフィールに表示しましょう。",
        "panel.noAppId": "Rich Presenceには表示元となるDiscordアプリケーションが必要です。discord.com/developers/applications で作成し(名前は自由)、Application IDをコピーして上のApplication ID設定に貼り付けてください。",
        "panel.pluginOff": "Rich Presence Builderはオフです。今プリセットを用意しておけば、オンにしたときに表示されます。",
        "panel.showing": "プロフィールに表示中",
        "panel.show": "プロフィールに表示",
        "panel.hide": "表示をやめる",
        "panel.duplicate": "複製",
        "panel.delete": "削除",
        "panel.deleteConfirm": "もう一度クリックで削除",
        "panel.whoSees": "このパソコンでDiscordを開いている間、あなたのアクティビティを見られる全員に表示されます。ボタンは他の人にだけ機能し、あなた自身には表示されません。",
        "section.text": "テキスト",
        "section.images": "画像",
        "section.buttons": "ボタン",
        "section.more": "時間とパーティー",
        "field.title": "プリセット名",
        "field.title.hint": "あなたにだけ表示されます。",
        "field.type": "アクティビティ",
        "field.name": "名前",
        "field.name.placeholder": "していること",
        "field.details": "1行目",
        "field.details.placeholder": "メインメニュー",
        "field.state": "2行目",
        "field.state.placeholder": "チームを募集中",
        "field.streamUrl": "配信リンク",
        "field.streamUrl.hint": "DiscordはTwitchかYouTubeのリンクがある場合のみ「配信中」と表示します。",
        "field.largeImage": "大きい画像",
        "field.imageHint": "画像へのhttpsリンク。",
        "field.largeText": "大きい画像のホバーテキスト",
        "field.smallImage": "小さい画像",
        "field.smallText": "小さい画像のホバーテキスト",
        "field.buttonLabel": "ボタン{n}のテキスト",
        "field.buttonUrl": "ボタン{n}のリンク",
        "field.buttons.hint": "ボタンは2つまで、それぞれhttpsリンクが必要です。",
        "field.time": "タイマー",
        "field.timeStart": "開始時刻",
        "field.timeEnd": "カウントダウンの終了時刻",
        "field.party": "パーティー",
        "field.party.hint": "2行目のあとに「(2 / 4)」のように表示されます。不要なら空欄に。",
        "field.partySize": "パーティーの人数",
        "field.partyOf": "/",
        "field.partyMax": "パーティーの定員",
        "type.playing": "プレイ中",
        "type.listening": "再生中",
        "type.watching": "視聴中",
        "type.competing": "参戦中",
        "type.streaming": "配信中",
        "time.none": "なし",
        "time.elapsed": "表示を始めてからの時間",
        "time.localTime": "現地時刻",
        "time.start": "指定時刻から",
        "time.end": "指定時刻までのカウントダウン",
        "problem.noAppId": "先にApplication IDを追加してください。",
        "problem.noName": "名前を入力してください。",
        "problem.badLargeImage": "大きい画像にはhttpsリンクが必要です。",
        "problem.badSmallImage": "小さい画像にはhttpsリンクが必要です。",
        "problem.badStreamUrl": "配信中にはTwitchかYouTubeのリンクが必要です。",
        "problem.buttonLabel": "リンクのあるボタンにはテキストが必要です。",
        "problem.buttonUrl": "各ボタンにhttpsリンクが必要です。",
        "problem.badParty": "パーティーの人数は定員を超えられません。",
        "problem.noTime": "タイマーの時刻を選んでください。",
        "preview.title": "プレビュー",
        "preview.elapsed": "{time} 経過",
        "preview.left": "残り {time}",
        "preview.party": "({size} / {max})",
    },
    pl: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Aplikacja Discorda, jako która pokazuje się twój status. Utwórz ją na discord.com/developers/applications, nazwij dowolnie i wklej tu jej Application ID.",
        "settings.appId.descriptionDefault": "Zostaw puste, aby użyć aplikacji Evi. Aby użyć własnej, utwórz aplikację na discord.com/developers/applications i wklej tu jej Application ID.",
        "toast.imagesFailed": "Rich Presence: Discord nie przyjął obrazów. Sprawdź linki i Application ID.",
        "panel.presets": "Ustawienia",
        "panel.new": "Nowe",
        "panel.newTitle": "Ustawienie {n}",
        "panel.copyOf": "{title} (kopia)",
        "panel.untitled": "Bez nazwy",
        "panel.empty": "Nie ma jeszcze żadnych. Utwórz jedno przyciskiem Nowe i pokaż je na profilu.",
        "panel.noAppId": "Rich Presence potrzebuje aplikacji Discorda, jako która się pokaże. Utwórz ją na discord.com/developers/applications (dowolna nazwa), skopiuj jej Application ID i wklej je powyżej w ustawieniu Application ID.",
        "panel.pluginOff": "Rich Presence Builder jest wyłączony: możesz już przygotować ustawienia, pokażą się po jego włączeniu.",
        "panel.showing": "Na twoim profilu",
        "panel.show": "Pokaż na moim profilu",
        "panel.hide": "Przestań pokazywać",
        "panel.duplicate": "Duplikuj",
        "panel.delete": "Usuń",
        "panel.deleteConfirm": "Kliknij ponownie, aby usunąć",
        "panel.whoSees": "Widzi to każdy, kto widzi twoją aktywność, gdy Discord jest otwarty na tym komputerze. Przyciski działają tylko dla innych: Discord ich tobie nie pokazuje.",
        "section.text": "Tekst",
        "section.images": "Obrazy",
        "section.buttons": "Przyciski",
        "section.more": "Czas i drużyna",
        "field.title": "Nazwa ustawienia",
        "field.title.hint": "Widzisz ją tylko ty.",
        "field.type": "Aktywność",
        "field.name": "Nazwa",
        "field.name.placeholder": "Co robisz",
        "field.details": "Pierwsza linia",
        "field.details.placeholder": "W menu głównym",
        "field.state": "Druga linia",
        "field.state.placeholder": "Szuka drużyny",
        "field.streamUrl": "Link do streamu",
        "field.streamUrl.hint": "Discord pokazuje „Transmituje” tylko z linkiem do Twitcha lub YouTube.",
        "field.largeImage": "Duży obraz",
        "field.imageHint": "Link https do obrazu.",
        "field.largeText": "Tekst po najechaniu na duży obraz",
        "field.smallImage": "Mały obraz",
        "field.smallText": "Tekst po najechaniu na mały obraz",
        "field.buttonLabel": "Tekst przycisku {n}",
        "field.buttonUrl": "Link przycisku {n}",
        "field.buttons.hint": "Do dwóch przycisków, każdy z linkiem https.",
        "field.time": "Licznik",
        "field.timeStart": "Liczy od",
        "field.timeEnd": "Odlicza do",
        "field.party": "Drużyna",
        "field.party.hint": "Pokazuje się jako „(2 z 4)” po drugiej linii. Zostaw puste, by nie pokazywać.",
        "field.partySize": "Osoby w drużynie",
        "field.partyOf": "z",
        "field.partyMax": "Rozmiar drużyny",
        "type.playing": "Gra",
        "type.listening": "Słucha",
        "type.watching": "Ogląda",
        "type.competing": "Rywalizuje",
        "type.streaming": "Transmituje",
        "time.none": "Brak",
        "time.elapsed": "Czas od włączenia",
        "time.localTime": "Twój czas lokalny",
        "time.start": "Od ustalonej godziny",
        "time.end": "Odliczanie do ustalonej godziny",
        "problem.noAppId": "Najpierw dodaj Application ID.",
        "problem.noName": "Nadaj mu nazwę.",
        "problem.badLargeImage": "Duży obraz potrzebuje linku https.",
        "problem.badSmallImage": "Mały obraz potrzebuje linku https.",
        "problem.badStreamUrl": "Transmisja potrzebuje linku do Twitcha lub YouTube.",
        "problem.buttonLabel": "Przycisk z linkiem potrzebuje tekstu.",
        "problem.buttonUrl": "Każdy przycisk potrzebuje linku https.",
        "problem.badParty": "Drużyna nie może mieć więcej osób niż jej rozmiar.",
        "problem.noTime": "Wybierz godzinę dla licznika.",
        "preview.title": "Podgląd",
        "preview.elapsed": "minęło {time}",
        "preview.left": "zostało {time}",
        "preview.party": "({size} z {max})",
    },
    "pt-BR": {
        "settings.appId": "Application ID",
        "settings.appId.description": "O aplicativo do Discord com que seu status aparece. Crie um em discord.com/developers/applications, dê o nome que quiser e cole aqui o Application ID dele.",
        "settings.appId.descriptionDefault": "Deixe vazio para usar o do Evi. Para usar o seu, crie um aplicativo em discord.com/developers/applications e cole aqui o Application ID dele.",
        "toast.imagesFailed": "Rich Presence: o Discord não aceitou as imagens. Confira os links e o Application ID.",
        "panel.presets": "Predefinições",
        "panel.new": "Nova",
        "panel.newTitle": "Predefinição {n}",
        "panel.copyOf": "{title} (cópia)",
        "panel.untitled": "Sem nome",
        "panel.empty": "Ainda não há predefinições. Crie uma com Nova e mostre no seu perfil.",
        "panel.noAppId": "O Rich Presence precisa de um aplicativo do Discord para aparecer. Crie um em discord.com/developers/applications (qualquer nome serve), copie o Application ID dele e cole na configuração Application ID acima.",
        "panel.pluginOff": "O Rich Presence Builder está desligado: você já pode preparar predefinições, elas aparecem quando você ligá-lo.",
        "panel.showing": "No seu perfil",
        "panel.show": "Mostrar no meu perfil",
        "panel.hide": "Parar de mostrar",
        "panel.duplicate": "Duplicar",
        "panel.delete": "Excluir",
        "panel.deleteConfirm": "Clique de novo para excluir",
        "panel.whoSees": "Todos que podem ver sua atividade veem isso, enquanto o Discord estiver aberto neste computador. Os botões só funcionam para os outros: o Discord não os mostra para você.",
        "section.text": "Texto",
        "section.images": "Imagens",
        "section.buttons": "Botões",
        "section.more": "Tempo e grupo",
        "field.title": "Nome da predefinição",
        "field.title.hint": "Só você vê isso.",
        "field.type": "Atividade",
        "field.name": "Nome",
        "field.name.placeholder": "O que você está fazendo",
        "field.details": "Primeira linha",
        "field.details.placeholder": "No menu principal",
        "field.state": "Segunda linha",
        "field.state.placeholder": "Procurando equipe",
        "field.streamUrl": "Link da transmissão",
        "field.streamUrl.hint": "O Discord só mostra \"Transmitindo\" com um link da Twitch ou do YouTube.",
        "field.largeImage": "Imagem grande",
        "field.imageHint": "Um link https para uma imagem.",
        "field.largeText": "Texto ao passar o mouse na imagem grande",
        "field.smallImage": "Imagem pequena",
        "field.smallText": "Texto ao passar o mouse na imagem pequena",
        "field.buttonLabel": "Texto do botão {n}",
        "field.buttonUrl": "Link do botão {n}",
        "field.buttons.hint": "Até dois botões, cada um com um link https.",
        "field.time": "Cronômetro",
        "field.timeStart": "Contando desde",
        "field.timeEnd": "Contagem regressiva até",
        "field.party": "Grupo",
        "field.party.hint": "Aparece como \"(2 de 4)\" depois da segunda linha. Deixe vazio para nenhum.",
        "field.partySize": "Pessoas no grupo",
        "field.partyOf": "de",
        "field.partyMax": "Tamanho do grupo",
        "type.playing": "Jogando",
        "type.listening": "Ouvindo",
        "type.watching": "Assistindo",
        "type.competing": "Competindo",
        "type.streaming": "Transmitindo",
        "time.none": "Nenhum",
        "time.elapsed": "Tempo desde que foi ativada",
        "time.localTime": "Seu horário local",
        "time.start": "Desde um horário definido",
        "time.end": "Contagem regressiva até um horário definido",
        "problem.noAppId": "Adicione um Application ID primeiro.",
        "problem.noName": "Dê um nome a ela.",
        "problem.badLargeImage": "A imagem grande precisa de um link https.",
        "problem.badSmallImage": "A imagem pequena precisa de um link https.",
        "problem.badStreamUrl": "Transmitindo precisa de um link da Twitch ou do YouTube.",
        "problem.buttonLabel": "Um botão com link precisa de texto.",
        "problem.buttonUrl": "Cada botão precisa de um link https.",
        "problem.badParty": "O grupo não pode ter mais pessoas que o tamanho dele.",
        "problem.noTime": "Escolha um horário para o cronômetro.",
        "preview.title": "Prévia",
        "preview.elapsed": "{time} decorrido",
        "preview.left": "faltam {time}",
        "preview.party": "({size} de {max})",
    },
    ru: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Приложение Discord, от имени которого показывается ваш статус. Создайте его на discord.com/developers/applications с любым названием и вставьте сюда его Application ID.",
        "settings.appId.descriptionDefault": "Оставьте пустым, чтобы использовать приложение Evi. Чтобы использовать своё, создайте приложение на discord.com/developers/applications и вставьте сюда его Application ID.",
        "toast.imagesFailed": "Rich Presence: Discord не принял картинки. Проверьте ссылки и Application ID.",
        "panel.presets": "Пресеты",
        "panel.new": "Новый",
        "panel.newTitle": "Пресет {n}",
        "panel.copyOf": "{title} (копия)",
        "panel.untitled": "Без названия",
        "panel.empty": "Пресетов пока нет. Создайте его кнопкой «Новый» и покажите в профиле.",
        "panel.noAppId": "Rich Presence нужно приложение Discord, от имени которого он показывается. Создайте его на discord.com/developers/applications (название любое), скопируйте Application ID и вставьте в настройку Application ID выше.",
        "panel.pluginOff": "Rich Presence Builder выключен: пресеты можно подготовить уже сейчас, они появятся, когда вы его включите.",
        "panel.showing": "В вашем профиле",
        "panel.show": "Показать в профиле",
        "panel.hide": "Больше не показывать",
        "panel.duplicate": "Дублировать",
        "panel.delete": "Удалить",
        "panel.deleteConfirm": "Нажмите ещё раз для удаления",
        "panel.whoSees": "Это видят все, кому видна ваша активность, пока Discord открыт на этом компьютере. Кнопки работают только для других: вам Discord их не показывает.",
        "section.text": "Текст",
        "section.images": "Картинки",
        "section.buttons": "Кнопки",
        "section.more": "Время и группа",
        "field.title": "Название пресета",
        "field.title.hint": "Видно только вам.",
        "field.type": "Активность",
        "field.name": "Название",
        "field.name.placeholder": "Чем вы заняты",
        "field.details": "Первая строка",
        "field.details.placeholder": "В главном меню",
        "field.state": "Вторая строка",
        "field.state.placeholder": "Ищет команду",
        "field.streamUrl": "Ссылка на трансляцию",
        "field.streamUrl.hint": "Discord показывает «Стримит» только со ссылкой на Twitch или YouTube.",
        "field.largeImage": "Большая картинка",
        "field.imageHint": "Ссылка https на картинку.",
        "field.largeText": "Подсказка большой картинки",
        "field.smallImage": "Маленькая картинка",
        "field.smallText": "Подсказка маленькой картинки",
        "field.buttonLabel": "Текст кнопки {n}",
        "field.buttonUrl": "Ссылка кнопки {n}",
        "field.buttons.hint": "До двух кнопок, у каждой ссылка https.",
        "field.time": "Таймер",
        "field.timeStart": "Отсчёт с",
        "field.timeEnd": "Обратный отсчёт до",
        "field.party": "Группа",
        "field.party.hint": "Показывается как «(2 из 4)» после второй строки. Оставьте пустым, чтобы не показывать.",
        "field.partySize": "Людей в группе",
        "field.partyOf": "из",
        "field.partyMax": "Размер группы",
        "type.playing": "Играет",
        "type.listening": "Слушает",
        "type.watching": "Смотрит",
        "type.competing": "Соревнуется",
        "type.streaming": "Стримит",
        "time.none": "Нет",
        "time.elapsed": "Время с момента включения",
        "time.localTime": "Ваше местное время",
        "time.start": "С заданного времени",
        "time.end": "Обратный отсчёт до заданного времени",
        "problem.noAppId": "Сначала добавьте Application ID.",
        "problem.noName": "Дайте ему название.",
        "problem.badLargeImage": "Для большой картинки нужна ссылка https.",
        "problem.badSmallImage": "Для маленькой картинки нужна ссылка https.",
        "problem.badStreamUrl": "Для стрима нужна ссылка на Twitch или YouTube.",
        "problem.buttonLabel": "Кнопке со ссылкой нужен текст.",
        "problem.buttonUrl": "Каждой кнопке нужна ссылка https.",
        "problem.badParty": "В группе не может быть больше людей, чем её размер.",
        "problem.noTime": "Выберите время для таймера.",
        "preview.title": "Предпросмотр",
        "preview.elapsed": "прошло {time}",
        "preview.left": "осталось {time}",
        "preview.party": "({size} из {max})",
    },
    tr: {
        "settings.appId": "Application ID",
        "settings.appId.description": "Durumunun gösterildiği Discord uygulaması. discord.com/developers/applications adresinde istediğin adla bir tane oluştur ve Application ID'sini buraya yapıştır.",
        "settings.appId.descriptionDefault": "Evi'nin kendi uygulamasını kullanmak için boş bırak. Kendininkini kullanmak için discord.com/developers/applications adresinde bir uygulama oluştur ve Application ID'sini buraya yapıştır.",
        "toast.imagesFailed": "Rich Presence: Discord resimleri kabul etmedi. Bağlantıları ve Application ID'yi kontrol et.",
        "panel.presets": "Hazır ayarlar",
        "panel.new": "Yeni",
        "panel.newTitle": "Hazır ayar {n}",
        "panel.copyOf": "{title} (kopya)",
        "panel.untitled": "Adsız",
        "panel.empty": "Henüz hazır ayar yok. Yeni ile bir tane oluştur ve profilinde göster.",
        "panel.noAppId": "Rich Presence'ın görüneceği bir Discord uygulaması gerekiyor. discord.com/developers/applications adresinde bir tane oluştur (adı önemli değil), Application ID'sini kopyala ve yukarıdaki Application ID ayarına yapıştır.",
        "panel.pluginOff": "Rich Presence Builder kapalı: hazır ayarları şimdi hazırlayabilirsin, açtığında görünürler.",
        "panel.showing": "Profilinde",
        "panel.show": "Profilimde göster",
        "panel.hide": "Göstermeyi bırak",
        "panel.duplicate": "Çoğalt",
        "panel.delete": "Sil",
        "panel.deleteConfirm": "Silmek için tekrar tıkla",
        "panel.whoSees": "Bu bilgisayarda Discord açık olduğu sürece etkinliğini görebilen herkes bunu görür. Butonlar yalnızca başkaları için çalışır: Discord onları sana göstermez.",
        "section.text": "Metin",
        "section.images": "Resimler",
        "section.buttons": "Butonlar",
        "section.more": "Süre ve grup",
        "field.title": "Hazır ayar adı",
        "field.title.hint": "Bunu yalnızca sen görürsün.",
        "field.type": "Etkinlik",
        "field.name": "Ad",
        "field.name.placeholder": "Ne yapıyorsun",
        "field.details": "İlk satır",
        "field.details.placeholder": "Ana menüde",
        "field.state": "İkinci satır",
        "field.state.placeholder": "Takım arıyor",
        "field.streamUrl": "Yayın bağlantısı",
        "field.streamUrl.hint": "Discord \"Yayında\" durumunu yalnızca Twitch veya YouTube bağlantısıyla gösterir.",
        "field.largeImage": "Büyük resim",
        "field.imageHint": "Bir resme giden https bağlantısı.",
        "field.largeText": "Büyük resmin üzerine gelince çıkan metin",
        "field.smallImage": "Küçük resim",
        "field.smallText": "Küçük resmin üzerine gelince çıkan metin",
        "field.buttonLabel": "Buton {n} metni",
        "field.buttonUrl": "Buton {n} bağlantısı",
        "field.buttons.hint": "En fazla iki buton, her biri bir https bağlantısıyla.",
        "field.time": "Sayaç",
        "field.timeStart": "Şu andan itibaren say",
        "field.timeEnd": "Şu ana kadar geri say",
        "field.party": "Grup",
        "field.party.hint": "İkinci satırdan sonra \"(2/4)\" gibi görünür. İstemiyorsan boş bırak.",
        "field.partySize": "Gruptaki kişi sayısı",
        "field.partyOf": "/",
        "field.partyMax": "Grup boyutu",
        "type.playing": "Oynuyor",
        "type.listening": "Dinliyor",
        "type.watching": "İzliyor",
        "type.competing": "Yarışıyor",
        "type.streaming": "Yayında",
        "time.none": "Yok",
        "time.elapsed": "Açıldığından beri geçen süre",
        "time.localTime": "Yerel saatin",
        "time.start": "Belirli bir zamandan beri",
        "time.end": "Belirli bir zamana geri sayım",
        "problem.noAppId": "Önce bir Application ID ekle.",
        "problem.noName": "Bir ad ver.",
        "problem.badLargeImage": "Büyük resim için https bağlantısı gerekiyor.",
        "problem.badSmallImage": "Küçük resim için https bağlantısı gerekiyor.",
        "problem.badStreamUrl": "Yayın için Twitch veya YouTube bağlantısı gerekiyor.",
        "problem.buttonLabel": "Bağlantısı olan bir butonun metni olmalı.",
        "problem.buttonUrl": "Her butonun bir https bağlantısı olmalı.",
        "problem.badParty": "Gruptaki kişi sayısı grup boyutunu geçemez.",
        "problem.noTime": "Sayaç için bir zaman seç.",
        "preview.title": "Önizleme",
        "preview.elapsed": "{time} geçti",
        "preview.left": "{time} kaldı",
        "preview.party": "({size}/{max})",
    },
});
