import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.servers": "Server list",
        "settings.servers.description": "Skip servers far out of view and remove the pills' GPU-layer hack.",
        "settings.chat": "Chat (experimental)",
        "settings.chat.description": "Skip messages far above or below what you're reading. Not measured yet.",
        "settings.members": "Member list (experimental)",
        "settings.members.description": "Skip members far out of view. Not measured yet.",
        "settings.margin": "Render distance (screens)",
        "settings.margin.description": "How many screen heights above and below stay fully rendered. Higher never shows an unrendered row even on very fast scrolls, lower saves more work.",
    },
    de: {
        "settings.servers": "Serverliste",
        "settings.servers.description": "Überspringt Server weit außerhalb des Sichtbereichs und entfernt den GPU-Ebenen-Trick der Pillen.",
        "settings.chat": "Chat (experimentell)",
        "settings.chat.description": "Überspringt Nachrichten weit über oder unter dem, was du gerade liest. Noch nicht gemessen.",
        "settings.members": "Mitgliederliste (experimentell)",
        "settings.members.description": "Überspringt Mitglieder weit außerhalb des Sichtbereichs. Noch nicht gemessen.",
        "settings.margin": "Renderdistanz (Bildschirme)",
        "settings.margin.description": "Wie viele Bildschirmhöhen darüber und darunter vollständig gerendert bleiben. Höher zeigt selbst bei sehr schnellem Scrollen nie eine ungerenderte Zeile, niedriger spart mehr Arbeit.",
    },
    es: {
        "settings.servers": "Lista de servidores",
        "settings.servers.description": "Omite los servidores muy fuera de la vista y quita el truco de capa GPU de las píldoras.",
        "settings.chat": "Chat (experimental)",
        "settings.chat.description": "Omite los mensajes muy por encima o por debajo de lo que estás leyendo. Aún sin medir.",
        "settings.members": "Lista de miembros (experimental)",
        "settings.members.description": "Omite los miembros muy fuera de la vista. Aún sin medir.",
        "settings.margin": "Distancia de renderizado (pantallas)",
        "settings.margin.description": "Cuántas alturas de pantalla por encima y por debajo se mantienen totalmente renderizadas. Más alto nunca muestra una fila sin renderizar, ni siquiera al desplazarte muy rápido; más bajo ahorra más trabajo.",
    },
    fr: {
        "settings.servers": "Liste des serveurs",
        "settings.servers.description": "Ignore les serveurs très loin de la vue et supprime l'astuce de couche GPU des pastilles.",
        "settings.chat": "Chat (expérimental)",
        "settings.chat.description": "Ignore les messages très au-dessus ou en dessous de ce que tu lis. Pas encore mesuré.",
        "settings.members": "Liste des membres (expérimental)",
        "settings.members.description": "Ignore les membres très loin de la vue. Pas encore mesuré.",
        "settings.margin": "Distance de rendu (écrans)",
        "settings.margin.description": "Combien de hauteurs d'écran au-dessus et en dessous restent entièrement rendues. Plus élevé, aucune ligne non rendue n'apparaît, même en défilant très vite ; plus bas, on économise plus de travail.",
    },
    ja: {
        "settings.servers": "サーバーリスト",
        "settings.servers.description": "画面から大きく外れたサーバーの描画を省き、ピルの GPU レイヤー対策を取り除きます。",
        "settings.chat": "チャット（試験的）",
        "settings.chat.description": "読んでいる位置から大きく離れた上下のメッセージの描画を省きます。効果はまだ計測していません。",
        "settings.members": "メンバーリスト（試験的）",
        "settings.members.description": "画面から大きく外れたメンバーの描画を省きます。効果はまだ計測していません。",
        "settings.margin": "描画範囲（画面数）",
        "settings.margin.description": "上下それぞれ、画面何枚分の高さを常にきちんと描画するかです。大きくすると、とても速くスクロールしても未描画の行が見えません。小さくすると、より多くの処理を節約できます。",
    },
    pl: {
        "settings.servers": "Lista serwerów",
        "settings.servers.description": "Pomija serwery daleko poza widokiem i usuwa sztuczkę z warstwą GPU dla wskaźników.",
        "settings.chat": "Czat (eksperymentalne)",
        "settings.chat.description": "Pomija wiadomości daleko powyżej lub poniżej tego, co czytasz. Jeszcze niezmierzone.",
        "settings.members": "Lista członków (eksperymentalne)",
        "settings.members.description": "Pomija członków daleko poza widokiem. Jeszcze niezmierzone.",
        "settings.margin": "Zasięg renderowania (ekrany)",
        "settings.margin.description": "Ile wysokości ekranu powyżej i poniżej pozostaje w pełni wyrenderowane. Wyższa wartość sprawia, że nawet przy bardzo szybkim przewijaniu nie zobaczysz niewyrenderowanego wiersza, niższa oszczędza więcej pracy.",
    },
    "pt-BR": {
        "settings.servers": "Lista de servidores",
        "settings.servers.description": "Pula servidores bem fora da tela e remove o truque de camada de GPU das pílulas.",
        "settings.chat": "Chat (experimental)",
        "settings.chat.description": "Pula mensagens bem acima ou abaixo do que você está lendo. Ainda não medido.",
        "settings.members": "Lista de membros (experimental)",
        "settings.members.description": "Pula membros bem fora da tela. Ainda não medido.",
        "settings.margin": "Distância de renderização (telas)",
        "settings.margin.description": "Quantas alturas de tela acima e abaixo continuam totalmente renderizadas. Mais alto nunca mostra uma linha sem renderizar, nem em rolagens muito rápidas; mais baixo economiza mais trabalho.",
    },
    ru: {
        "settings.servers": "Список серверов",
        "settings.servers.description": "Пропускает серверы далеко за пределами экрана и убирает хак GPU-слоя для индикаторов.",
        "settings.chat": "Чат (экспериментально)",
        "settings.chat.description": "Пропускает сообщения далеко выше или ниже того, что вы читаете. Пока не измерено.",
        "settings.members": "Список участников (экспериментально)",
        "settings.members.description": "Пропускает участников далеко за пределами экрана. Пока не измерено.",
        "settings.margin": "Дальность отрисовки (экранов)",
        "settings.margin.description": "Сколько высот экрана выше и ниже остаётся полностью отрисованным. Чем больше, тем меньше шанс увидеть неотрисованную строку даже при очень быстрой прокрутке; чем меньше, тем больше экономия ресурсов.",
    },
    tr: {
        "settings.servers": "Sunucu listesi",
        "settings.servers.description": "Görüş alanının çok dışındaki sunucuları atlar ve rozetlerin GPU katmanı hilesini kaldırır.",
        "settings.chat": "Sohbet (deneysel)",
        "settings.chat.description": "Okuduğun yerin çok üstündeki veya altındaki mesajları atlar. Henüz ölçülmedi.",
        "settings.members": "Üye listesi (deneysel)",
        "settings.members.description": "Görüş alanının çok dışındaki üyeleri atlar. Henüz ölçülmedi.",
        "settings.margin": "Oluşturma mesafesi (ekran)",
        "settings.margin.description": "Üstte ve altta kaç ekran yüksekliğinin tamamen oluşturulmuş kalacağı. Yüksek değer çok hızlı kaydırmada bile oluşturulmamış satır göstermez, düşük değer daha çok işten tasarruf sağlar.",
    },
});
