/**
 * delight install    [--flavor stable|ptb|canary|development|all] [--dev] [--restart]
 * delight uninstall  [--flavor ...] [--restart]
 * delight status
 */
import { existsSync, mkdirSync, renameSync, rmSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { parseArgs } from "util";

import { readAsarFile } from "../shared/asar";
import { createShimAsar, ORIGINAL_ASAR } from "../shared/shim";
import { DiscordInstall, findInstalls, FLAVORS, injectionState, isDiscordRunning, killDiscord, startDiscord } from "./discord";

interface Embed {
    version: string;
    core: Record<string, string>;
    plugins: Record<string, Record<string, string>>;
}

const DATA_DIR = join(process.env.APPDATA ?? "", "Delight");

const { values: flags, positionals } = parseArgs({
    args: Bun.argv.slice(2),
    allowPositionals: true,
    options: {
        flavor: { type: "string", default: "stable" },
        dev: { type: "boolean", default: false },
        restart: { type: "boolean", default: false },
        help: { type: "boolean", short: "h", default: false },
    },
});

const c = {
    ok: (s: string) => `\x1b[32m${s}\x1b[0m`,
    warn: (s: string) => `\x1b[33m${s}\x1b[0m`,
    err: (s: string) => `\x1b[31m${s}\x1b[0m`,
    dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
    bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
};

function fail(message: string): never {
    console.error(c.err(`✗ ${message}`));
    process.exit(1);
}

function selectedInstalls() {
    const installs = findInstalls();
    if (!installs.length) fail("No Discord installation found in %LOCALAPPDATA%.");
    if (flags.flavor === "all") return installs;
    if (!(flags.flavor! in FLAVORS)) fail(`Unknown flavor "${flags.flavor}". Use one of: ${Object.keys(FLAVORS).join(", ")}, all`);

    const install = installs.find(i => i.flavor === flags.flavor);
    if (!install) fail(`Discord ${flags.flavor} isn't installed. Found: ${installs.map(i => i.flavor).join(", ")}`);
    return [install];
}

async function loadEmbed(): Promise<Embed> {
    try {
        // @ts-ignore Generated by scripts/build.ts, and bundled into the compiled exe
        return (await import("../../dist/embed.json")).default;
    } catch {
        fail("No build found. Run `bun run build` first, or use --dev.");
    }
}

/** Where the shim should point: the repo build in dev mode, otherwise a copy in the data folder */
async function prepareCore(): Promise<{ corePath: string; devPluginsDir?: string; }> {
    if (flags.dev) {
        const root = resolve(import.meta.dir, "..", "..");
        const corePath = join(root, "dist", "core", "main.js");
        if (!existsSync(corePath)) fail("dist/core/main.js is missing. Run `bun run build` (or `bun run dev`) first.");
        return { corePath, devPluginsDir: join(root, "dist", "plugins") };
    }

    const embed = await loadEmbed();
    const coreDir = join(DATA_DIR, "core");
    rmSync(coreDir, { recursive: true, force: true });
    mkdirSync(coreDir, { recursive: true });
    for (const [file, content] of Object.entries(embed.core)) writeFileSync(join(coreDir, file), content);
    writeFileSync(join(coreDir, "package.json"), JSON.stringify({ type: "commonjs" }));

    // Official plugins are refreshed, user plugins in other folders are never touched
    for (const [id, files] of Object.entries(embed.plugins)) {
        const dir = join(DATA_DIR, "plugins", id);
        rmSync(dir, { recursive: true, force: true });
        mkdirSync(dir, { recursive: true });
        for (const [file, content] of Object.entries(files)) writeFileSync(join(dir, file), content);
    }

    return { corePath: join(coreDir, "main.js") };
}

/**
 * Discord keeps app.asar open while running, so it has to be closed to swap the archives.
 * Returns false when it's running and we weren't allowed to close it.
 */
async function withDiscordClosed(install: DiscordInstall, action: () => void) {
    const running = isDiscordRunning(install);
    if (running && !flags.restart) {
        console.error(c.err(`✗ Discord ${install.flavor} is running. Quit it fully (tray icon > Quit), or pass --restart.`));
        return false;
    }
    if (running) await killDiscord(install);
    try {
        action();
    } finally {
        if (running) startDiscord(install);
    }
    return true;
}

async function install() {
    const installs = selectedInstalls();
    const core = await prepareCore();

    for (const discord of installs) {
        const { resources, version } = discord.versions[0];
        const state = injectionState(resources);
        const asar = join(resources, "app.asar");
        const original = join(resources, ORIGINAL_ASAR);

        if (state === "other-mod") {
            console.error(c.err(`✗ ${discord.flavor} ${version}: another client mod (Vencord, Equicord, ...) is installed. Uninstall it first.`));
            continue;
        }

        const done = await withDiscordClosed(discord, () => {
            if (state === "clean") renameSync(asar, original);
            const pkg = JSON.parse(readAsarFile(original, "package.json"));
            writeFileSync(asar, createShimAsar(core, pkg));
        });
        if (!done) continue;

        console.log(c.ok(`✓ ${state === "delight" ? "Updated" : "Installed"} Delight in Discord ${discord.flavor} ${version}`) + c.dim(flags.dev ? " (dev build)" : ""));
    }
}

async function uninstall() {
    for (const discord of selectedInstalls()) {
        let removed = 0;
        const done = await withDiscordClosed(discord, () => {
            // Every version folder, the auto-repair may have injected older ones too
            for (const { resources } of discord.versions) {
                if (injectionState(resources) !== "delight") continue;
                const asar = join(resources, "app.asar");
                rmSync(asar);
                renameSync(join(resources, ORIGINAL_ASAR), asar);
                removed++;
            }
        });
        if (!done) continue;
        console.log(removed ? c.ok(`✓ Removed Delight from Discord ${discord.flavor}`) : c.dim(`  Delight wasn't installed in Discord ${discord.flavor}`));
    }
}

function status() {
    const installs = findInstalls();
    if (!installs.length) return console.log("No Discord installation found.");

    for (const discord of installs) {
        const { version, resources } = discord.versions[0];
        const state = injectionState(resources);
        const label = { clean: c.dim("not installed"), delight: c.ok("installed"), "other-mod": c.warn("another mod is installed") }[state];
        const running = isDiscordRunning(discord) ? c.dim(" · running") : "";
        console.log(`${c.bold(discord.flavor.padEnd(12))} ${version.padEnd(10)} ${label}${running}`);
    }
    console.log(c.dim(`\nData folder: ${DATA_DIR}`));
}

function help() {
    console.log(`${c.bold("delight")} — Discord client mod installer

  install     Install or update Delight
  uninstall   Remove Delight, Discord goes back to vanilla
  status      Show every Discord install and whether Delight is in it

Options
  --flavor <stable|ptb|canary|development|all>   Which Discord (default: stable)
  --restart                                      Quit and reopen Discord for you
  --dev                                          Point Discord at this repo's dist/ (hot reload)

Launch Discord with --vanilla to start it once without Delight.`);
}

const commands: Record<string, () => unknown> = { install, repair: install, uninstall, status, help };
const command = flags.help ? "help" : positionals[0] ?? "help";
if (!(command in commands)) fail(`Unknown command "${command}". Run \`delight help\`.`);
await commands[command]();
