/**
 * evi install    [--flavor stable|ptb|canary|development|all] [--dev] [--restart]
 * evi uninstall  [--flavor ...] [--restart]
 * evi status
 * evi update     [--check] [--flavor ...] [--restart]
 */
import { existsSync, mkdirSync, renameSync, rmSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { parseArgs } from "util";

import pkg from "../../package.json";
import { readAsarFile } from "../shared/asar";
import { createShimAsar, ORIGINAL_ASAR } from "../shared/shim";
import { DiscordInstall, findInstalls, FLAVORS, injectionState, isDiscordRunning, killDiscord, startDiscord } from "./discord";
import { cleanupPreviousUpdate, COMPILED, downloadVerified, fetchLatestRelease, isNewer, replaceExecutable, UpdateError } from "./update";

interface Embed {
    version: string;
    core: Record<string, string>;
    plugins: Record<string, Record<string, string>>;
}

const DATA_DIR = join(process.env.APPDATA ?? "", "Evi");

// Before the rename to Evi the data folder was %APPDATA%/Delight: move it over once
const LEGACY_DATA_DIR = join(process.env.APPDATA ?? "", "Delight");
if (process.env.APPDATA && !existsSync(DATA_DIR) && existsSync(LEGACY_DATA_DIR)) {
    try {
        renameSync(LEGACY_DATA_DIR, DATA_DIR);
    } catch { }
}

const { values: flags, positionals } = parseArgs({
    args: Bun.argv.slice(2),
    allowPositionals: true,
    options: {
        flavor: { type: "string", default: "stable" },
        dev: { type: "boolean", default: false },
        restart: { type: "boolean", default: false },
        check: { type: "boolean", default: false },
        help: { type: "boolean", short: "h", default: false },
    },
});

const c = {
    ok: (s: string) => `\x1b[32m${s}\x1b[0m`,
    warn: (s: string) => `\x1b[33m${s}\x1b[0m`,
    err: (s: string) => `\x1b[31m${s}\x1b[0m`,
    dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
    bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
};

function fail(message: string): never {
    console.error(c.err(`✗ ${message}`));
    process.exit(1);
}

function selectedInstalls() {
    const installs = findInstalls();
    if (!installs.length) fail("No Discord installation found in %LOCALAPPDATA%.");
    if (flags.flavor === "all") return installs;
    if (!(flags.flavor! in FLAVORS)) fail(`Unknown flavor "${flags.flavor}". Use one of: ${Object.keys(FLAVORS).join(", ")}, all`);

    const install = installs.find(i => i.flavor === flags.flavor);
    if (!install) fail(`Discord ${flags.flavor} isn't installed. Found: ${installs.map(i => i.flavor).join(", ")}`);
    return [install];
}

async function loadEmbed(): Promise<Embed> {
    try {
        // @ts-ignore Generated by scripts/build.ts, and bundled into the compiled exe
        return (await import("../../dist/embed.json")).default;
    } catch {
        fail("No build found. Run `bun run build` first, or use --dev.");
    }
}

/** Where the shim should point: the repo build in dev mode, otherwise a copy in the data folder */
async function prepareCore(): Promise<{ corePath: string; devPluginsDir?: string; }> {
    if (flags.dev) {
        const root = resolve(import.meta.dir, "..", "..");
        const corePath = join(root, "dist", "core", "main.js");
        if (!existsSync(corePath)) fail("dist/core/main.js is missing. Run `bun run build` (or `bun run dev`) first.");
        return { corePath, devPluginsDir: join(root, "dist", "plugins") };
    }

    const embed = await loadEmbed();
    const coreDir = join(DATA_DIR, "core");
    rmSync(coreDir, { recursive: true, force: true });
    mkdirSync(coreDir, { recursive: true });
    for (const [file, content] of Object.entries(embed.core)) writeFileSync(join(coreDir, file), content);
    writeFileSync(join(coreDir, "package.json"), JSON.stringify({ type: "commonjs" }));

    // Official plugins are refreshed, user plugins in other folders are never touched
    for (const [id, files] of Object.entries(embed.plugins)) {
        const dir = join(DATA_DIR, "plugins", id);
        rmSync(dir, { recursive: true, force: true });
        mkdirSync(dir, { recursive: true });
        for (const [file, content] of Object.entries(files)) writeFileSync(join(dir, file), content);
    }

    return { corePath: join(coreDir, "main.js") };
}

/**
 * Discord keeps app.asar open while running, so it has to be closed to swap the archives.
 * Returns false when it's running and we weren't allowed to close it.
 */
async function withDiscordClosed(install: DiscordInstall, action: () => void) {
    const running = isDiscordRunning(install);
    if (running && !flags.restart) {
        console.error(c.err(`✗ Discord ${install.flavor} is running. Quit it fully (tray icon > Quit), or pass --restart.`));
        return false;
    }
    if (running) await killDiscord(install);
    try {
        action();
    } finally {
        if (running) startDiscord(install);
    }
    return true;
}

async function install() {
    const installs = selectedInstalls();
    const core = await prepareCore();

    for (const discord of installs) {
        const { resources, version } = discord.versions[0];
        const state = injectionState(resources);
        const asar = join(resources, "app.asar");
        const original = join(resources, ORIGINAL_ASAR);

        if (state === "other-mod") {
            console.error(c.err(`✗ ${discord.flavor} ${version}: another client mod (Vencord, Equicord, ...) is installed. Uninstall it first.`));
            continue;
        }

        const done = await withDiscordClosed(discord, () => {
            if (state === "clean") renameSync(asar, original);
            const pkg = JSON.parse(readAsarFile(original, "package.json"));
            writeFileSync(asar, createShimAsar(core, pkg));
        });
        if (!done) continue;

        console.log(c.ok(`✓ ${state === "evi" ? "Updated" : "Installed"} Evi in Discord ${discord.flavor} ${version}`) + c.dim(flags.dev ? " (dev build)" : ""));
    }
}

async function uninstall() {
    for (const discord of selectedInstalls()) {
        let removed = 0;
        const done = await withDiscordClosed(discord, () => {
            // Every version folder, the auto-repair may have injected older ones too
            for (const { resources } of discord.versions) {
                if (injectionState(resources) !== "evi") continue;
                const asar = join(resources, "app.asar");
                rmSync(asar);
                renameSync(join(resources, ORIGINAL_ASAR), asar);
                removed++;
            }
        });
        if (!done) continue;
        console.log(removed ? c.ok(`✓ Removed Evi from Discord ${discord.flavor}`) : c.dim(`  Evi wasn't installed in Discord ${discord.flavor}`));
    }
}

function status() {
    const installs = findInstalls();
    if (!installs.length) return console.log("No Discord installation found.");

    for (const discord of installs) {
        const { version, resources } = discord.versions[0];
        const state = injectionState(resources);
        const label = { clean: c.dim("not installed"), evi: c.ok("installed"), "other-mod": c.warn("another mod is installed") }[state];
        const running = isDiscordRunning(discord) ? c.dim(" · running") : "";
        console.log(`${c.bold(discord.flavor.padEnd(12))} ${version.padEnd(10)} ${label}${running}`);
    }
    console.log(c.dim(`\nData folder: ${DATA_DIR}`));
}

/** Replaces this exe with the latest published release, then lets the new exe run `install` */
async function update() {
    const current = pkg.version;
    const sourceHint = "This is a source checkout. Update it with `git pull` and `bun run build`.";

    let release;
    try {
        release = await fetchLatestRelease();
    } catch (e) {
        fail(e instanceof UpdateError ? e.message : String(e));
    }

    if (!release) {
        console.log(`No Evi release has been published yet. You have ${current}.`);
        if (!COMPILED) console.log(c.dim(sourceHint));
        return;
    }
    if (!isNewer(release.tag, current)) {
        console.log(c.ok(`✓ Evi ${current} is up to date`) + c.dim(` (latest release: ${release.tag})`));
        return;
    }

    console.log(`Evi ${release.version} is available, you have ${current}.`);
    if (!COMPILED) return console.log(c.dim(sourceHint));
    if (flags.check) return console.log(c.dim(`Run \`evi update\` to install it. ${release.url}`));

    const exe = process.execPath;
    try {
        console.log(c.dim(`Downloading ${release.tag}…`));
        const bytes = await downloadVerified(release);
        replaceExecutable(exe, bytes);
    } catch (e) {
        fail(e instanceof UpdateError ? e.message : String(e));
    }
    console.log(c.ok(`✓ Updated ${exe} to ${release.version}`));

    // Refresh only Discords that already have Evi: updating must never inject into one you didn't choose.
    // The new exe carries the new core and official plugins, so it does the install.
    const installed = findInstalls().filter(d => injectionState(d.versions[0].resources) === "evi");
    if (!installed.length) {
        console.log(c.dim("Evi isn't installed in any Discord yet. Run `evi install` to add it."));
        return;
    }
    for (const discord of installed) {
        const args = [exe, "install", "--flavor", discord.flavor, ...(flags.restart ? ["--restart"] : [])];
        const code = await Bun.spawn(args, { stdio: ["inherit", "inherit", "inherit"] }).exited;
        if (code !== 0) fail(`The new version is in place, but refreshing Discord ${discord.flavor} failed. Run \`evi install --flavor ${discord.flavor}\` to retry.`);
    }
}

function help() {
    console.log(`${c.bold("evi")} ${pkg.version} — Discord client mod installer

  install     Install or update Evi
  uninstall   Remove Evi, Discord goes back to vanilla
  status      Show every Discord install and whether Evi is in it
  update      Download the latest evi.exe and refresh every Discord that has Evi

Options
  --flavor <stable|ptb|canary|development|all>   Which Discord (default: stable)
  --restart                                      Quit and reopen Discord for you
  --dev                                          Point Discord at this repo's dist/ (hot reload)
  --check                                        With update: only report whether a newer release exists

Launch Discord with --vanilla to start it once without Evi.`);
}

if (COMPILED) cleanupPreviousUpdate(process.execPath);

const commands: Record<string, () => unknown> = { install, repair: install, uninstall, status, update, help };
const command = flags.help ? "help" : positionals[0] ?? "help";
if (!(command in commands)) fail(`Unknown command "${command}". Run \`evi help\`.`);
await commands[command]();
