import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "menu.add": "Add to Server",
        "menu.slots": "{count} slots left",
        "menu.noSlots": "No slots left",
        "menu.noServers": "No servers where you can add sounds",
        "menu.download": "Download",
        "menu.copyLink": "Copy Sound Link",
        "menu.sound": "Sound {number}",
        "dialog.title": "Add sound to a server",
        "dialog.close": "Close",
        "dialog.preview": "Play",
        "dialog.stop": "Stop",
        "dialog.loading": "Loading the sound…",
        "dialog.details": "{seconds} s · {size} KB · {type}",
        "dialog.tooLong": "{seconds} s long: Discord takes {limit} s at most",
        "dialog.name": "Name",
        "dialog.nameHint": "2 to 32 characters.",
        "dialog.server": "Server",
        "dialog.full": "full",
        "dialog.slots": "{left} of {limit} slots left",
        "dialog.noPermission": "You can't add sounds to any of your servers. You need Create Expressions or Manage Expressions.",
        "dialog.emojiDropped": "Its custom emoji isn't in that server, so the copy goes without one.",
        "dialog.cancel": "Cancel",
        "dialog.submit": "Add sound",
        "dialog.uploading": "Adding…",
        "toast.added": "Added {name} to {server}",
        "toast.failed": "Couldn't add the sound: {message}",
        "toast.linkCopied": "Sound link copied",
        "toast.copyFailed": "Couldn't copy",
        "toast.downloadFailed": "Couldn't download the sound: {message}",
        "error.download": "Discord's CDN answered {status}",
        "error.notAudio": "That isn't an MP3 or Ogg sound.",
        "error.tooBig": "The sound is {size} KB: Discord takes {limit} KB at most.",
        "error.noUpload": "Couldn't find Discord's sound upload.",
        "error.failed": "Discord didn't take the sound.",
        "file.fallback": "sound",
    },
    de: {
        "menu.add": "Zum Server hinzufügen",
        "menu.slots": "Noch {count} Plätze",
        "menu.noSlots": "Keine Plätze frei",
        "menu.noServers": "Keine Server, auf denen du Sounds hinzufügen kannst",
        "menu.download": "Herunterladen",
        "menu.copyLink": "Sound-Link kopieren",
        "menu.sound": "Sound {number}",
        "dialog.title": "Sound zu einem Server hinzufügen",
        "dialog.close": "Schließen",
        "dialog.preview": "Abspielen",
        "dialog.stop": "Stoppen",
        "dialog.loading": "Sound wird geladen…",
        "dialog.details": "{seconds} s · {size} KB · {type}",
        "dialog.tooLong": "{seconds} s lang: Discord nimmt höchstens {limit} s",
        "dialog.name": "Name",
        "dialog.nameHint": "2 bis 32 Zeichen.",
        "dialog.server": "Server",
        "dialog.full": "voll",
        "dialog.slots": "{left} von {limit} Plätzen frei",
        "dialog.noPermission": "Du kannst auf keinem deiner Server Sounds hinzufügen. Dafür brauchst du „Ausdrücke erstellen“ oder „Ausdrücke verwalten“.",
        "dialog.emojiDropped": "Sein eigenes Emoji gibt es auf diesem Server nicht, die Kopie kommt also ohne.",
        "dialog.cancel": "Abbrechen",
        "dialog.submit": "Sound hinzufügen",
        "dialog.uploading": "Wird hinzugefügt…",
        "toast.added": "{name} zu {server} hinzugefügt",
        "toast.failed": "Sound konnte nicht hinzugefügt werden: {message}",
        "toast.linkCopied": "Sound-Link kopiert",
        "toast.copyFailed": "Kopieren fehlgeschlagen",
        "toast.downloadFailed": "Sound konnte nicht heruntergeladen werden: {message}",
        "error.download": "Discords CDN antwortete mit {status}",
        "error.notAudio": "Das ist kein MP3- oder Ogg-Sound.",
        "error.tooBig": "Der Sound hat {size} KB: Discord nimmt höchstens {limit} KB.",
        "error.noUpload": "Discords Sound-Upload wurde nicht gefunden.",
        "error.failed": "Discord hat den Sound nicht angenommen.",
        "file.fallback": "sound",
    },
    es: {
        "menu.add": "Añadir al servidor",
        "menu.slots": "Quedan {count} espacios",
        "menu.noSlots": "No quedan espacios",
        "menu.noServers": "No hay servidores donde puedas añadir sonidos",
        "menu.download": "Descargar",
        "menu.copyLink": "Copiar enlace del sonido",
        "menu.sound": "Sonido {number}",
        "dialog.title": "Añadir sonido a un servidor",
        "dialog.close": "Cerrar",
        "dialog.preview": "Reproducir",
        "dialog.stop": "Detener",
        "dialog.loading": "Cargando el sonido…",
        "dialog.details": "{seconds} s · {size} KB · {type}",
        "dialog.tooLong": "Dura {seconds} s: Discord acepta {limit} s como máximo",
        "dialog.name": "Nombre",
        "dialog.nameHint": "De 2 a 32 caracteres.",
        "dialog.server": "Servidor",
        "dialog.full": "lleno",
        "dialog.slots": "Quedan {left} de {limit} espacios",
        "dialog.noPermission": "No puedes añadir sonidos en ninguno de tus servidores. Necesitas Crear expresiones o Gestionar expresiones.",
        "dialog.emojiDropped": "Su emoji personalizado no está en ese servidor, así que la copia va sin él.",
        "dialog.cancel": "Cancelar",
        "dialog.submit": "Añadir sonido",
        "dialog.uploading": "Añadiendo…",
        "toast.added": "{name} añadido a {server}",
        "toast.failed": "No se pudo añadir el sonido: {message}",
        "toast.linkCopied": "Enlace del sonido copiado",
        "toast.copyFailed": "No se pudo copiar",
        "toast.downloadFailed": "No se pudo descargar el sonido: {message}",
        "error.download": "La CDN de Discord respondió {status}",
        "error.notAudio": "No es un sonido MP3 ni Ogg.",
        "error.tooBig": "El sonido pesa {size} KB: Discord acepta {limit} KB como máximo.",
        "error.noUpload": "No se encontró la subida de sonidos de Discord.",
        "error.failed": "Discord no aceptó el sonido.",
        "file.fallback": "sonido",
    },
    fr: {
        "menu.add": "Ajouter au serveur",
        "menu.slots": "{count} emplacements restants",
        "menu.noSlots": "Plus d'emplacement",
        "menu.noServers": "Aucun serveur où tu peux ajouter des sons",
        "menu.download": "Télécharger",
        "menu.copyLink": "Copier le lien du son",
        "menu.sound": "Son {number}",
        "dialog.title": "Ajouter le son à un serveur",
        "dialog.close": "Fermer",
        "dialog.preview": "Lire",
        "dialog.stop": "Arrêter",
        "dialog.loading": "Chargement du son…",
        "dialog.details": "{seconds} s · {size} Ko · {type}",
        "dialog.tooLong": "Dure {seconds} s : Discord accepte {limit} s au maximum",
        "dialog.name": "Nom",
        "dialog.nameHint": "De 2 à 32 caractères.",
        "dialog.server": "Serveur",
        "dialog.full": "plein",
        "dialog.slots": "{left} emplacements sur {limit} restants",
        "dialog.noPermission": "Tu ne peux ajouter de sons sur aucun de tes serveurs. Il te faut Créer des expressions ou Gérer les expressions.",
        "dialog.emojiDropped": "Son emoji personnalisé n'est pas sur ce serveur, la copie s'en passera.",
        "dialog.cancel": "Annuler",
        "dialog.submit": "Ajouter le son",
        "dialog.uploading": "Ajout…",
        "toast.added": "{name} ajouté à {server}",
        "toast.failed": "Impossible d'ajouter le son : {message}",
        "toast.linkCopied": "Lien du son copié",
        "toast.copyFailed": "Impossible de copier",
        "toast.downloadFailed": "Impossible de télécharger le son : {message}",
        "error.download": "Le CDN de Discord a répondu {status}",
        "error.notAudio": "Ce n'est pas un son MP3 ou Ogg.",
        "error.tooBig": "Le son fait {size} Ko : Discord accepte {limit} Ko au maximum.",
        "error.noUpload": "Impossible de trouver l'envoi de sons de Discord.",
        "error.failed": "Discord n'a pas accepté le son.",
        "file.fallback": "son",
    },
    ja: {
        "menu.add": "サーバーに追加",
        "menu.slots": "残り{count}枠",
        "menu.noSlots": "空き枠がありません",
        "menu.noServers": "サウンドを追加できるサーバーがありません",
        "menu.download": "ダウンロード",
        "menu.copyLink": "サウンドのリンクをコピー",
        "menu.sound": "サウンド{number}",
        "dialog.title": "サウンドをサーバーに追加",
        "dialog.close": "閉じる",
        "dialog.preview": "再生",
        "dialog.stop": "停止",
        "dialog.loading": "サウンドを読み込み中…",
        "dialog.details": "{seconds}秒 · {size} KB · {type}",
        "dialog.tooLong": "{seconds}秒あります。Discordは最大{limit}秒までです",
        "dialog.name": "名前",
        "dialog.nameHint": "2〜32文字。",
        "dialog.server": "サーバー",
        "dialog.full": "満杯",
        "dialog.slots": "{limit}枠中、残り{left}枠",
        "dialog.noPermission": "サウンドを追加できるサーバーがありません。「エクスプレッションの作成」または「エクスプレッションの管理」の権限が必要です。",
        "dialog.emojiDropped": "カスタム絵文字がそのサーバーにないため、絵文字なしでコピーされます。",
        "dialog.cancel": "キャンセル",
        "dialog.submit": "サウンドを追加",
        "dialog.uploading": "追加中…",
        "toast.added": "{name}を{server}に追加しました",
        "toast.failed": "サウンドを追加できませんでした: {message}",
        "toast.linkCopied": "サウンドのリンクをコピーしました",
        "toast.copyFailed": "コピーできませんでした",
        "toast.downloadFailed": "サウンドをダウンロードできませんでした: {message}",
        "error.download": "DiscordのCDNが{status}を返しました",
        "error.notAudio": "MP3またはOggのサウンドではありません。",
        "error.tooBig": "サウンドは{size} KBです。Discordは最大{limit} KBまでです。",
        "error.noUpload": "Discordのサウンドアップロードが見つかりませんでした。",
        "error.failed": "Discordがサウンドを受け付けませんでした。",
        "file.fallback": "sound",
    },
    pl: {
        "menu.add": "Dodaj do serwera",
        "menu.slots": "Zostało miejsc: {count}",
        "menu.noSlots": "Brak wolnych miejsc",
        "menu.noServers": "Brak serwerów, na które możesz dodać dźwięki",
        "menu.download": "Pobierz",
        "menu.copyLink": "Kopiuj link do dźwięku",
        "menu.sound": "Dźwięk {number}",
        "dialog.title": "Dodaj dźwięk do serwera",
        "dialog.close": "Zamknij",
        "dialog.preview": "Odtwórz",
        "dialog.stop": "Zatrzymaj",
        "dialog.loading": "Wczytywanie dźwięku…",
        "dialog.details": "{seconds} s · {size} KB · {type}",
        "dialog.tooLong": "Trwa {seconds} s: Discord przyjmuje najwyżej {limit} s",
        "dialog.name": "Nazwa",
        "dialog.nameHint": "Od 2 do 32 znaków.",
        "dialog.server": "Serwer",
        "dialog.full": "pełny",
        "dialog.slots": "Wolne miejsca: {left} z {limit}",
        "dialog.noPermission": "Nie możesz dodawać dźwięków na żadnym ze swoich serwerów. Potrzebujesz uprawnienia Tworzenie ekspresji lub Zarządzanie ekspresjami.",
        "dialog.emojiDropped": "Jego własnej emotki nie ma na tym serwerze, więc kopia będzie bez niej.",
        "dialog.cancel": "Anuluj",
        "dialog.submit": "Dodaj dźwięk",
        "dialog.uploading": "Dodawanie…",
        "toast.added": "Dodano {name} do {server}",
        "toast.failed": "Nie udało się dodać dźwięku: {message}",
        "toast.linkCopied": "Skopiowano link do dźwięku",
        "toast.copyFailed": "Nie udało się skopiować",
        "toast.downloadFailed": "Nie udało się pobrać dźwięku: {message}",
        "error.download": "CDN Discorda odpowiedział {status}",
        "error.notAudio": "To nie jest dźwięk MP3 ani Ogg.",
        "error.tooBig": "Dźwięk ma {size} KB: Discord przyjmuje najwyżej {limit} KB.",
        "error.noUpload": "Nie znaleziono wysyłania dźwięków Discorda.",
        "error.failed": "Discord nie przyjął dźwięku.",
        "file.fallback": "dzwiek",
    },
    "pt-BR": {
        "menu.add": "Adicionar ao servidor",
        "menu.slots": "Restam {count} espaços",
        "menu.noSlots": "Sem espaços livres",
        "menu.noServers": "Nenhum servidor onde você possa adicionar sons",
        "menu.download": "Baixar",
        "menu.copyLink": "Copiar link do som",
        "menu.sound": "Som {number}",
        "dialog.title": "Adicionar som a um servidor",
        "dialog.close": "Fechar",
        "dialog.preview": "Tocar",
        "dialog.stop": "Parar",
        "dialog.loading": "Carregando o som…",
        "dialog.details": "{seconds} s · {size} KB · {type}",
        "dialog.tooLong": "Dura {seconds} s: o Discord aceita no máximo {limit} s",
        "dialog.name": "Nome",
        "dialog.nameHint": "De 2 a 32 caracteres.",
        "dialog.server": "Servidor",
        "dialog.full": "cheio",
        "dialog.slots": "Restam {left} de {limit} espaços",
        "dialog.noPermission": "Você não pode adicionar sons em nenhum dos seus servidores. É preciso Criar expressões ou Gerenciar expressões.",
        "dialog.emojiDropped": "O emoji personalizado dele não está nesse servidor, então a cópia vai sem ele.",
        "dialog.cancel": "Cancelar",
        "dialog.submit": "Adicionar som",
        "dialog.uploading": "Adicionando…",
        "toast.added": "{name} adicionado a {server}",
        "toast.failed": "Não foi possível adicionar o som: {message}",
        "toast.linkCopied": "Link do som copiado",
        "toast.copyFailed": "Não foi possível copiar",
        "toast.downloadFailed": "Não foi possível baixar o som: {message}",
        "error.download": "A CDN do Discord respondeu {status}",
        "error.notAudio": "Não é um som MP3 nem Ogg.",
        "error.tooBig": "O som tem {size} KB: o Discord aceita no máximo {limit} KB.",
        "error.noUpload": "Não foi possível encontrar o envio de sons do Discord.",
        "error.failed": "O Discord não aceitou o som.",
        "file.fallback": "som",
    },
    ru: {
        "menu.add": "Добавить на сервер",
        "menu.slots": "Свободно мест: {count}",
        "menu.noSlots": "Нет свободных мест",
        "menu.noServers": "Нет серверов, куда вы можете добавлять звуки",
        "menu.download": "Скачать",
        "menu.copyLink": "Копировать ссылку на звук",
        "menu.sound": "Звук {number}",
        "dialog.title": "Добавить звук на сервер",
        "dialog.close": "Закрыть",
        "dialog.preview": "Воспроизвести",
        "dialog.stop": "Остановить",
        "dialog.loading": "Загрузка звука…",
        "dialog.details": "{seconds} с · {size} КБ · {type}",
        "dialog.tooLong": "Длится {seconds} с: Discord принимает не больше {limit} с",
        "dialog.name": "Название",
        "dialog.nameHint": "От 2 до 32 символов.",
        "dialog.server": "Сервер",
        "dialog.full": "заполнен",
        "dialog.slots": "Свободно {left} из {limit} мест",
        "dialog.noPermission": "Вы не можете добавлять звуки ни на один из своих серверов. Нужно право «Создание выражений» или «Управление выражениями».",
        "dialog.emojiDropped": "Его собственного эмодзи нет на этом сервере, поэтому копия будет без него.",
        "dialog.cancel": "Отмена",
        "dialog.submit": "Добавить звук",
        "dialog.uploading": "Добавление…",
        "toast.added": "{name} добавлен на {server}",
        "toast.failed": "Не удалось добавить звук: {message}",
        "toast.linkCopied": "Ссылка на звук скопирована",
        "toast.copyFailed": "Не удалось скопировать",
        "toast.downloadFailed": "Не удалось скачать звук: {message}",
        "error.download": "CDN Discord ответил {status}",
        "error.notAudio": "Это не звук MP3 или Ogg.",
        "error.tooBig": "Звук весит {size} КБ: Discord принимает не больше {limit} КБ.",
        "error.noUpload": "Не удалось найти загрузку звуков Discord.",
        "error.failed": "Discord не принял звук.",
        "file.fallback": "sound",
    },
    tr: {
        "menu.add": "Sunucuya ekle",
        "menu.slots": "{count} yer kaldı",
        "menu.noSlots": "Boş yer yok",
        "menu.noServers": "Ses ekleyebileceğin sunucu yok",
        "menu.download": "İndir",
        "menu.copyLink": "Ses bağlantısını kopyala",
        "menu.sound": "Ses {number}",
        "dialog.title": "Sesi bir sunucuya ekle",
        "dialog.close": "Kapat",
        "dialog.preview": "Oynat",
        "dialog.stop": "Durdur",
        "dialog.loading": "Ses yükleniyor…",
        "dialog.details": "{seconds} sn · {size} KB · {type}",
        "dialog.tooLong": "{seconds} sn uzunluğunda: Discord en fazla {limit} sn kabul eder",
        "dialog.name": "Ad",
        "dialog.nameHint": "2 ile 32 karakter arası.",
        "dialog.server": "Sunucu",
        "dialog.full": "dolu",
        "dialog.slots": "{limit} yerden {left} boş",
        "dialog.noPermission": "Sunucularının hiçbirine ses ekleyemiyorsun. İfade Oluştur veya İfadeleri Yönet izni gerekir.",
        "dialog.emojiDropped": "Kendi emojisi o sunucuda yok, bu yüzden kopya emojisiz eklenir.",
        "dialog.cancel": "İptal",
        "dialog.submit": "Sesi ekle",
        "dialog.uploading": "Ekleniyor…",
        "toast.added": "{name}, {server} sunucusuna eklendi",
        "toast.failed": "Ses eklenemedi: {message}",
        "toast.linkCopied": "Ses bağlantısı kopyalandı",
        "toast.copyFailed": "Kopyalanamadı",
        "toast.downloadFailed": "Ses indirilemedi: {message}",
        "error.download": "Discord'un CDN'i {status} yanıtını verdi",
        "error.notAudio": "Bu bir MP3 veya Ogg sesi değil.",
        "error.tooBig": "Ses {size} KB: Discord en fazla {limit} KB kabul eder.",
        "error.noUpload": "Discord'un ses yükleme özelliği bulunamadı.",
        "error.failed": "Discord sesi kabul etmedi.",
        "file.fallback": "ses",
    },
});
