import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.active": "Hide blocked messages",
        "settings.active.description": "Turn off to get Discord's collapsed \"blocked messages\" rows back. /hideblocked flips this.",
        "settings.ignored": "Ignored users too",
        "settings.ignored.description": "Treat users you ignored like users you blocked.",
        "settings.replies": "Hide replies to them",
        "settings.replies.description": "Also hide messages replying to a hidden user. When off, the reply stays and its quote reads \"Blocked message\".",
        "settings.memberList": "Hide from the member list",
        "settings.memberList.description": "Leave them out of a server's member list. Takes effect as the list updates.",
        "settings.voice": "Hide from voice channels",
        "settings.voice.description": "Leave them out of voice: the users under voice channels, call tiles, speaking rings, join sounds and soundboard.",
        "command.description": "Toggle hiding blocked users' messages",
        "command.on": "Blocked users' messages are hidden.",
        "command.off": "Blocked users' messages show as Discord's collapsed rows again.",
        "settings.mute": "Mute their audio",
        "settings.mute.description": "Locally mutes their voice and stream audio, so you never hear them. Undone when they're unblocked or this is turned off.",
        "settings.dms": "Hide your DMs with them",
        "settings.dms.description": "Drop DMs with them from your direct messages list.",
    },
    de: {
        "settings.active": "Blockierte Nachrichten ausblenden",
        "settings.active.description": "Ausschalten, um Discords eingeklappte Zeilen „blockierte Nachrichten“ zurückzubekommen. /hideblocked schaltet das um.",
        "settings.ignored": "Auch ignorierte Nutzer",
        "settings.ignored.description": "Ignorierte Nutzer wie blockierte Nutzer behandeln.",
        "settings.replies": "Antworten auf sie ausblenden",
        "settings.replies.description": "Blendet auch Nachrichten aus, die auf einen ausgeblendeten Nutzer antworten. Wenn aus, bleibt die Antwort stehen und ihr Zitat lautet „Blockierte Nachricht“.",
        "settings.memberList": "In der Mitgliederliste ausblenden",
        "settings.memberList.description": "Lässt sie in der Mitgliederliste eines Servers weg. Wirkt, sobald sich die Liste aktualisiert.",
        "settings.voice": "In Sprachkanälen ausblenden",
        "settings.voice.description": "Lässt sie in Sprachkanälen weg: in der Nutzerliste darunter, in Anrufkacheln, Sprechringen, Beitrittstönen und im Soundboard.",
        "command.description": "Ausblenden der Nachrichten blockierter Nutzer ein- oder ausschalten",
        "command.on": "Nachrichten blockierter Nutzer werden ausgeblendet.",
        "command.off": "Nachrichten blockierter Nutzer erscheinen wieder als Discords eingeklappte Zeilen.",
        "settings.mute": "Ihren Ton stummschalten",
        "settings.mute.description": "Schaltet ihre Stimme und ihren Stream-Ton lokal stumm, damit du sie nie hörst. Wird aufgehoben, wenn du sie entblockst oder das ausschaltest.",
        "settings.dms": "Deine DMs mit ihnen ausblenden",
        "settings.dms.description": "Entfernt DMs mit ihnen aus deiner Liste der Direktnachrichten.",
    },
    es: {
        "settings.active": "Ocultar mensajes bloqueados",
        "settings.active.description": "Desactívalo para recuperar las filas plegadas de «mensajes bloqueados» de Discord. /hideblocked lo activa o desactiva.",
        "settings.ignored": "También usuarios ignorados",
        "settings.ignored.description": "Trata a los usuarios que ignoraste como a los que bloqueaste.",
        "settings.replies": "Ocultar respuestas a ellos",
        "settings.replies.description": "También oculta los mensajes que responden a un usuario oculto. Si está desactivado, la respuesta se queda y su cita dice «Mensaje bloqueado».",
        "settings.memberList": "Ocultar de la lista de miembros",
        "settings.memberList.description": "Los deja fuera de la lista de miembros de un servidor. Surte efecto cuando se actualiza la lista.",
        "settings.voice": "Ocultar de los canales de voz",
        "settings.voice.description": "Los deja fuera de la voz: la lista bajo los canales de voz, los recuadros de llamada, los anillos al hablar, los sonidos de entrada y la caja de sonidos.",
        "command.description": "Activa o desactiva la ocultación de mensajes de usuarios bloqueados",
        "command.on": "Los mensajes de usuarios bloqueados están ocultos.",
        "command.off": "Los mensajes de usuarios bloqueados vuelven a mostrarse como las filas plegadas de Discord.",
        "settings.mute": "Silenciar su audio",
        "settings.mute.description": "Silencia localmente su voz y el audio de su transmisión, para que nunca los oigas. Se deshace al desbloquearlos o al desactivar esto.",
        "settings.dms": "Ocultar tus MD con ellos",
        "settings.dms.description": "Quita los MD con ellos de tu lista de mensajes directos.",
    },
    fr: {
        "settings.active": "Masquer les messages bloqués",
        "settings.active.description": "Désactive pour retrouver les lignes repliées « messages bloqués » de Discord. /hideblocked l'active ou le désactive.",
        "settings.ignored": "Aussi les utilisateurs ignorés",
        "settings.ignored.description": "Traite les utilisateurs que tu as ignorés comme ceux que tu as bloqués.",
        "settings.replies": "Masquer les réponses à ces utilisateurs",
        "settings.replies.description": "Masque aussi les messages qui répondent à un utilisateur masqué. Désactivé, la réponse reste et sa citation affiche « Message bloqué ».",
        "settings.memberList": "Masquer de la liste des membres",
        "settings.memberList.description": "Les retire de la liste des membres d'un serveur. Prend effet à la mise à jour de la liste.",
        "settings.voice": "Masquer des salons vocaux",
        "settings.voice.description": "Les retire de la voix : la liste sous les salons vocaux, les tuiles d'appel, les anneaux de parole, les sons d'arrivée et la soundboard.",
        "command.description": "Active ou désactive le masquage des messages des utilisateurs bloqués",
        "command.on": "Les messages des utilisateurs bloqués sont masqués.",
        "command.off": "Les messages des utilisateurs bloqués s'affichent de nouveau en lignes repliées de Discord.",
        "settings.mute": "Couper leur son",
        "settings.mute.description": "Coupe localement leur voix et le son de leur stream, pour que tu ne les entendes jamais. Annulé quand tu les débloques ou désactives ceci.",
        "settings.dms": "Masquer tes MP avec eux",
        "settings.dms.description": "Retire les MP avec eux de ta liste de messages privés.",
    },
    ja: {
        "settings.active": "ブロックしたメッセージを非表示",
        "settings.active.description": "オフにすると、Discord の折りたたまれた「ブロックしたメッセージ」の行が戻ります。/hideblocked で切り替えられます。",
        "settings.ignored": "無視したユーザーも対象にする",
        "settings.ignored.description": "無視したユーザーを、ブロックしたユーザーと同じように扱います。",
        "settings.replies": "そのユーザーへの返信を非表示",
        "settings.replies.description": "非表示のユーザーへの返信メッセージも隠します。オフの場合、返信は残り、引用部分は「ブロックしたメッセージ」と表示されます。",
        "settings.memberList": "メンバーリストから非表示",
        "settings.memberList.description": "サーバーのメンバーリストに表示しません。リストが更新されると反映されます。",
        "settings.voice": "ボイスチャンネルから非表示",
        "settings.voice.description": "ボイスから除外します:ボイスチャンネル下のユーザー一覧、通話タイル、発言中の枠、参加音、サウンドボード。",
        "command.description": "ブロックしたユーザーのメッセージの非表示を切り替える",
        "command.on": "ブロックしたユーザーのメッセージを非表示にしました。",
        "command.off": "ブロックしたユーザーのメッセージが、Discord の折りたたみ行として表示されるようになりました。",
        "settings.mute": "音声をミュート",
        "settings.mute.description": "相手の声と配信の音声をローカルでミュートし、聞こえないようにします。ブロック解除するか、これをオフにすると元に戻ります。",
        "settings.dms": "相手とのDMを非表示",
        "settings.dms.description": "相手とのDMをダイレクトメッセージ一覧から外します。",
    },
    pl: {
        "settings.active": "Ukrywaj zablokowane wiadomości",
        "settings.active.description": "Wyłącz, aby wróciły zwinięte wiersze „zablokowanych wiadomości” z Discorda. Przełączysz to poleceniem /hideblocked.",
        "settings.ignored": "Także ignorowani użytkownicy",
        "settings.ignored.description": "Traktuj zignorowanych użytkowników tak jak zablokowanych.",
        "settings.replies": "Ukrywaj odpowiedzi do nich",
        "settings.replies.description": "Ukrywa też wiadomości odpowiadające ukrytemu użytkownikowi. Gdy wyłączone, odpowiedź zostaje, a jej cytat brzmi „Zablokowana wiadomość”.",
        "settings.memberList": "Ukrywaj na liście członków",
        "settings.memberList.description": "Pomija ich na liście członków serwera. Działa po odświeżeniu listy.",
        "settings.voice": "Ukrywaj na kanałach głosowych",
        "settings.voice.description": "Pomija ich w głosie: na liście pod kanałami głosowymi, w kafelkach rozmowy, pierścieniach mówienia, dźwiękach dołączania i soundboardzie.",
        "command.description": "Włącz lub wyłącz ukrywanie wiadomości zablokowanych użytkowników",
        "command.on": "Wiadomości zablokowanych użytkowników są ukryte.",
        "command.off": "Wiadomości zablokowanych użytkowników znów pojawiają się jako zwinięte wiersze Discorda.",
        "settings.mute": "Wycisz ich dźwięk",
        "settings.mute.description": "Lokalnie wycisza ich głos i dźwięk transmisji, więc nigdy ich nie słyszysz. Cofnięte, gdy ich odblokujesz lub to wyłączysz.",
        "settings.dms": "Ukryj DM z nimi",
        "settings.dms.description": "Usuwa DM z nimi z listy wiadomości prywatnych.",
    },
    "pt-BR": {
        "settings.active": "Ocultar mensagens bloqueadas",
        "settings.active.description": "Desative para voltar às linhas recolhidas de “mensagens bloqueadas” do Discord. /hideblocked ativa ou desativa.",
        "settings.ignored": "Usuários ignorados também",
        "settings.ignored.description": "Trata os usuários que você ignorou como os que você bloqueou.",
        "settings.replies": "Ocultar respostas a eles",
        "settings.replies.description": "Também oculta mensagens que respondem a um usuário oculto. Desativado, a resposta continua e a citação mostra “Mensagem bloqueada”.",
        "settings.memberList": "Ocultar da lista de membros",
        "settings.memberList.description": "Deixa eles de fora da lista de membros de um servidor. Vale quando a lista for atualizada.",
        "settings.voice": "Ocultar dos canais de voz",
        "settings.voice.description": "Deixa eles de fora da voz: a lista sob os canais de voz, os blocos da chamada, os anéis de fala, os sons de entrada e o soundboard.",
        "command.description": "Ativa ou desativa a ocultação das mensagens de usuários bloqueados",
        "command.on": "As mensagens de usuários bloqueados estão ocultas.",
        "command.off": "As mensagens de usuários bloqueados voltam a aparecer como as linhas recolhidas do Discord.",
        "settings.mute": "Silenciar o áudio deles",
        "settings.mute.description": "Silencia localmente a voz e o áudio da transmissão deles, para você nunca ouvi-los. Desfeito ao desbloqueá-los ou desativar isso.",
        "settings.dms": "Ocultar suas DMs com eles",
        "settings.dms.description": "Tira as DMs com eles da sua lista de mensagens diretas.",
    },
    ru: {
        "settings.active": "Скрывать сообщения заблокированных",
        "settings.active.description": "Выключите, чтобы вернуть свёрнутые строки Discord «заблокированные сообщения». Команда /hideblocked переключает это.",
        "settings.ignored": "И игнорируемых пользователей",
        "settings.ignored.description": "Относиться к игнорируемым пользователям так же, как к заблокированным.",
        "settings.replies": "Скрывать ответы им",
        "settings.replies.description": "Также скрывает сообщения-ответы скрытому пользователю. Если выключено, ответ остаётся, а в его цитате написано «Заблокированное сообщение».",
        "settings.memberList": "Скрывать в списке участников",
        "settings.memberList.description": "Не показывать их в списке участников сервера. Вступает в силу при обновлении списка.",
        "settings.voice": "Скрывать в голосовых каналах",
        "settings.voice.description": "Убирает их из голоса: из списка под голосовыми каналами, плиток звонка, колец говорящего, звуков входа и звуковой панели.",
        "command.description": "Включить или выключить скрытие сообщений заблокированных пользователей",
        "command.on": "Сообщения заблокированных пользователей скрыты.",
        "command.off": "Сообщения заблокированных пользователей снова показываются свёрнутыми строками Discord.",
        "settings.mute": "Заглушить их звук",
        "settings.mute.description": "Локально заглушает их голос и звук трансляции, чтобы вы их не слышали. Отменяется, когда вы их разблокируете или выключите это.",
        "settings.dms": "Скрыть ваши ЛС с ними",
        "settings.dms.description": "Убирает ЛС с ними из списка личных сообщений.",
    },
    tr: {
        "settings.active": "Engellenen mesajları gizle",
        "settings.active.description": "Kapatırsan Discord'un daralmış \"engellenen mesajlar\" satırları geri gelir. /hideblocked bunu açıp kapatır.",
        "settings.ignored": "Yok sayılan kullanıcılar da",
        "settings.ignored.description": "Yok saydığın kullanıcılara engellediğin kullanıcılar gibi davran.",
        "settings.replies": "Onlara verilen yanıtları gizle",
        "settings.replies.description": "Gizlenen bir kullanıcıya yanıt veren mesajları da gizler. Kapalıyken yanıt kalır ve alıntısında \"Engellenen mesaj\" yazar.",
        "settings.memberList": "Üye listesinde gizle",
        "settings.memberList.description": "Bir sunucunun üye listesinde görünmezler. Liste güncellenince geçerli olur.",
        "settings.voice": "Ses kanallarında gizle",
        "settings.voice.description": "Onları seste göstermez: ses kanallarının altındaki liste, arama kutuları, konuşma halkaları, katılma sesleri ve ses paneli.",
        "command.description": "Engellenen kullanıcıların mesajlarını gizlemeyi aç veya kapat",
        "command.on": "Engellenen kullanıcıların mesajları gizlendi.",
        "command.off": "Engellenen kullanıcıların mesajları yine Discord'un daralmış satırları olarak görünüyor.",
        "settings.mute": "Seslerini kapat",
        "settings.mute.description": "Seslerini ve yayın seslerini yerel olarak kapatır, böylece onları hiç duymazsın. Engeli kaldırınca ya da bunu kapatınca geri alınır.",
        "settings.dms": "Onlarla DM'lerini gizle",
        "settings.dms.description": "Onlarla olan DM'leri direkt mesaj listenden çıkarır.",
    },
});
