import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "title.hidden.text": "This is a hidden text channel",
        "title.locked.text": "This is a locked text channel",
        "title.hidden.voice": "This is a hidden voice channel",
        "title.locked.voice": "This is a locked voice channel",
        "title.hidden.announcement": "This is a hidden announcement channel",
        "title.locked.announcement": "This is a locked announcement channel",
        "title.hidden.stage": "This is a hidden stage channel",
        "title.locked.stage": "This is a locked stage channel",
        "title.hidden.forum": "This is a hidden forum channel",
        "title.locked.forum": "This is a locked forum channel",
        "title.hidden.media": "This is a hidden media channel",
        "title.locked.media": "This is a locked media channel",
        "title.hidden.other": "This is a hidden channel",
        "title.locked.other": "This is a locked channel",
        "lead.messages": "You can't see the messages in this channel.",
        "lead.posts": "You can't see the posts in this channel.",
        "lead.guidelines": " Its guidelines are below.",
        "last.message": "Last message: {date}",
        "last.post": "Last post: {date}",
        "last.pin": "Last pin: {date}",
        "slowmode": "Slowmode: {duration}",
        "slowmode.thread": "Default thread slowmode: {duration}",
        "bitrate": "Bitrate: {kbps} kbps",
        "region": "Region: {region}",
        "automatic": "Automatic",
        "video.quality": "Video quality: {quality}",
        "archive.threads": "Threads archive after {duration} of inactivity",
        "archive.posts": "Posts archive after {duration} of inactivity",
        "layout": "Default layout: {layout}",
        "layout.0": "Not set",
        "layout.1": "List view",
        "layout.2": "Gallery view",
        "sort": "Default sort order: {order}",
        "sort.0": "Latest activity",
        "sort.1": "Creation date",
        "reaction": "Default reaction:",
        "tag.required": "Posts in this forum need a tag.",
        "tags": "Available tags",
        "allowed": "Allowed users and roles",
        "allowed.hide": "Hide allowed users and roles",
        "allowed.show": "Show allowed users and roles",
        "nsfw": "NSFW",
        "emoji": "emoji",
        "hidden.channel": "Hidden channel",
        "crashed": "Couldn't show this hidden channel.",
        "duration.day": { one: "{count} day", other: "{count} days" },
        "duration.hour": { one: "{count} hour", other: "{count} hours" },
        "duration.minute": { one: "{count} minute", other: "{count} minutes" },
        "duration.second": { one: "{count} second", other: "{count} seconds" },
        "settings.showMode": "How hidden channels look",
        "settings.showMode.description": "Takes effect after a reload for voice channels.",
        "settings.showMode.lock": "A lock instead of the channel icon",
        "settings.showMode.muted": "Muted, with a crossed-out eye after the name",
        "settings.hideUnreads": "Hide unreads",
        "settings.hideUnreads.description": "Hidden channels never show as unread.",
        "settings.showAllowed": "Show who can see it",
        "settings.showAllowed.description": "Open the allowed users and roles list on a hidden channel's page by default.",
    },
    de: {
        "title.hidden.text": "Dies ist ein versteckter Textkanal",
        "title.locked.text": "Dies ist ein gesperrter Textkanal",
        "title.hidden.voice": "Dies ist ein versteckter Sprachkanal",
        "title.locked.voice": "Dies ist ein gesperrter Sprachkanal",
        "title.hidden.announcement": "Dies ist ein versteckter Ankündigungskanal",
        "title.locked.announcement": "Dies ist ein gesperrter Ankündigungskanal",
        "title.hidden.stage": "Dies ist ein versteckter Bühnenkanal",
        "title.locked.stage": "Dies ist ein gesperrter Bühnenkanal",
        "title.hidden.forum": "Dies ist ein verstecktes Forum",
        "title.locked.forum": "Dies ist ein gesperrtes Forum",
        "title.hidden.media": "Dies ist ein versteckter Medienkanal",
        "title.locked.media": "Dies ist ein gesperrter Medienkanal",
        "title.hidden.other": "Dies ist ein versteckter Kanal",
        "title.locked.other": "Dies ist ein gesperrter Kanal",
        "lead.messages": "Du kannst die Nachrichten in diesem Kanal nicht sehen.",
        "lead.posts": "Du kannst die Beiträge in diesem Kanal nicht sehen.",
        "lead.guidelines": " Die Richtlinien stehen unten.",
        "last.message": "Letzte Nachricht: {date}",
        "last.post": "Letzter Beitrag: {date}",
        "last.pin": "Zuletzt angeheftet: {date}",
        "slowmode": "Langsammodus: {duration}",
        "slowmode.thread": "Standard-Langsammodus für Threads: {duration}",
        "bitrate": "Bitrate: {kbps} kbps",
        "region": "Region: {region}",
        "automatic": "Automatisch",
        "video.quality": "Videoqualität: {quality}",
        "archive.threads": "Threads werden nach {duration} Inaktivität archiviert",
        "archive.posts": "Beiträge werden nach {duration} Inaktivität archiviert",
        "layout": "Standardlayout: {layout}",
        "layout.0": "Nicht festgelegt",
        "layout.1": "Listenansicht",
        "layout.2": "Galerieansicht",
        "sort": "Standardsortierung: {order}",
        "sort.0": "Letzte Aktivität",
        "sort.1": "Erstellungsdatum",
        "reaction": "Standardreaktion:",
        "tag.required": "Beiträge in diesem Forum brauchen einen Tag.",
        "tags": "Verfügbare Tags",
        "allowed": "Erlaubte Nutzer und Rollen",
        "allowed.hide": "Erlaubte Nutzer und Rollen ausblenden",
        "allowed.show": "Erlaubte Nutzer und Rollen anzeigen",
        "nsfw": "NSFW",
        "emoji": "Emoji",
        "hidden.channel": "Versteckter Kanal",
        "crashed": "Dieser versteckte Kanal konnte nicht angezeigt werden.",
        "duration.day": { one: "{count} Tag", other: "{count} Tage" },
        "duration.hour": { one: "{count} Stunde", other: "{count} Stunden" },
        "duration.minute": { one: "{count} Minute", other: "{count} Minuten" },
        "duration.second": { one: "{count} Sekunde", other: "{count} Sekunden" },
        "settings.showMode": "Aussehen versteckter Kanäle",
        "settings.showMode.description": "Wirkt bei Sprachkanälen erst nach einem Neuladen.",
        "settings.showMode.lock": "Ein Schloss statt des Kanalsymbols",
        "settings.showMode.muted": "Stummgeschaltet, mit durchgestrichenem Auge hinter dem Namen",
        "settings.hideUnreads": "Ungelesenes ausblenden",
        "settings.hideUnreads.description": "Versteckte Kanäle werden nie als ungelesen angezeigt.",
        "settings.showAllowed": "Anzeigen, wer ihn sehen kann",
        "settings.showAllowed.description": "Die Liste der erlaubten Nutzer und Rollen auf der Seite eines versteckten Kanals standardmäßig öffnen.",
    },
    es: {
        "title.hidden.text": "Este es un canal de texto oculto",
        "title.locked.text": "Este es un canal de texto bloqueado",
        "title.hidden.voice": "Este es un canal de voz oculto",
        "title.locked.voice": "Este es un canal de voz bloqueado",
        "title.hidden.announcement": "Este es un canal de anuncios oculto",
        "title.locked.announcement": "Este es un canal de anuncios bloqueado",
        "title.hidden.stage": "Este es un canal de escenario oculto",
        "title.locked.stage": "Este es un canal de escenario bloqueado",
        "title.hidden.forum": "Este es un canal de foro oculto",
        "title.locked.forum": "Este es un canal de foro bloqueado",
        "title.hidden.media": "Este es un canal multimedia oculto",
        "title.locked.media": "Este es un canal multimedia bloqueado",
        "title.hidden.other": "Este es un canal oculto",
        "title.locked.other": "Este es un canal bloqueado",
        "lead.messages": "No puedes ver los mensajes de este canal.",
        "lead.posts": "No puedes ver las publicaciones de este canal.",
        "lead.guidelines": " Sus normas están debajo.",
        "last.message": "Último mensaje: {date}",
        "last.post": "Última publicación: {date}",
        "last.pin": "Último mensaje fijado: {date}",
        "slowmode": "Modo pausado: {duration}",
        "slowmode.thread": "Modo pausado predeterminado de los hilos: {duration}",
        "bitrate": "Tasa de bits: {kbps} kbps",
        "region": "Región: {region}",
        "automatic": "Automática",
        "video.quality": "Calidad de vídeo: {quality}",
        "archive.threads": "Los hilos se archivan tras {duration} de inactividad",
        "archive.posts": "Las publicaciones se archivan tras {duration} de inactividad",
        "layout": "Diseño predeterminado: {layout}",
        "layout.0": "Sin definir",
        "layout.1": "Vista de lista",
        "layout.2": "Vista de galería",
        "sort": "Orden predeterminado: {order}",
        "sort.0": "Actividad más reciente",
        "sort.1": "Fecha de creación",
        "reaction": "Reacción predeterminada:",
        "tag.required": "Las publicaciones de este foro necesitan una etiqueta.",
        "tags": "Etiquetas disponibles",
        "allowed": "Usuarios y roles con acceso",
        "allowed.hide": "Ocultar usuarios y roles con acceso",
        "allowed.show": "Mostrar usuarios y roles con acceso",
        "nsfw": "NSFW",
        "emoji": "emoji",
        "hidden.channel": "Canal oculto",
        "crashed": "No se pudo mostrar este canal oculto.",
        "duration.day": { one: "{count} día", other: "{count} días" },
        "duration.hour": { one: "{count} hora", other: "{count} horas" },
        "duration.minute": { one: "{count} minuto", other: "{count} minutos" },
        "duration.second": { one: "{count} segundo", other: "{count} segundos" },
        "settings.showMode": "Aspecto de los canales ocultos",
        "settings.showMode.description": "En los canales de voz se aplica tras recargar.",
        "settings.showMode.lock": "Un candado en lugar del icono del canal",
        "settings.showMode.muted": "Silenciado, con un ojo tachado tras el nombre",
        "settings.hideUnreads": "Ocultar no leídos",
        "settings.hideUnreads.description": "Los canales ocultos nunca aparecen como no leídos.",
        "settings.showAllowed": "Mostrar quién puede verlo",
        "settings.showAllowed.description": "Abre por defecto la lista de usuarios y roles con acceso en la página de un canal oculto.",
    },
    fr: {
        "title.hidden.text": "Ceci est un salon textuel masqué",
        "title.locked.text": "Ceci est un salon textuel verrouillé",
        "title.hidden.voice": "Ceci est un salon vocal masqué",
        "title.locked.voice": "Ceci est un salon vocal verrouillé",
        "title.hidden.announcement": "Ceci est un salon d'annonces masqué",
        "title.locked.announcement": "Ceci est un salon d'annonces verrouillé",
        "title.hidden.stage": "Ceci est un salon de conférence masqué",
        "title.locked.stage": "Ceci est un salon de conférence verrouillé",
        "title.hidden.forum": "Ceci est un forum masqué",
        "title.locked.forum": "Ceci est un forum verrouillé",
        "title.hidden.media": "Ceci est un salon média masqué",
        "title.locked.media": "Ceci est un salon média verrouillé",
        "title.hidden.other": "Ceci est un salon masqué",
        "title.locked.other": "Ceci est un salon verrouillé",
        "lead.messages": "Tu ne peux pas voir les messages de ce salon.",
        "lead.posts": "Tu ne peux pas voir les posts de ce salon.",
        "lead.guidelines": " Ses règles se trouvent ci-dessous.",
        "last.message": "Dernier message : {date}",
        "last.post": "Dernier post : {date}",
        "last.pin": "Dernier épinglage : {date}",
        "slowmode": "Mode lent : {duration}",
        "slowmode.thread": "Mode lent par défaut des fils : {duration}",
        "bitrate": "Débit : {kbps} kbit/s",
        "region": "Région : {region}",
        "automatic": "Automatique",
        "video.quality": "Qualité vidéo : {quality}",
        "archive.threads": "Les fils sont archivés après {duration} d'inactivité",
        "archive.posts": "Les posts sont archivés après {duration} d'inactivité",
        "layout": "Disposition par défaut : {layout}",
        "layout.0": "Non défini",
        "layout.1": "Vue en liste",
        "layout.2": "Vue en galerie",
        "sort": "Tri par défaut : {order}",
        "sort.0": "Activité la plus récente",
        "sort.1": "Date de création",
        "reaction": "Réaction par défaut :",
        "tag.required": "Les posts de ce forum doivent avoir un tag.",
        "tags": "Tags disponibles",
        "allowed": "Utilisateurs et rôles autorisés",
        "allowed.hide": "Masquer les utilisateurs et rôles autorisés",
        "allowed.show": "Afficher les utilisateurs et rôles autorisés",
        "nsfw": "NSFW",
        "emoji": "émoji",
        "hidden.channel": "Salon masqué",
        "crashed": "Impossible d'afficher ce salon masqué.",
        "duration.day": { one: "{count} jour", other: "{count} jours" },
        "duration.hour": { one: "{count} heure", other: "{count} heures" },
        "duration.minute": { one: "{count} minute", other: "{count} minutes" },
        "duration.second": { one: "{count} seconde", other: "{count} secondes" },
        "settings.showMode": "Apparence des salons masqués",
        "settings.showMode.description": "Pour les salons vocaux, prend effet après un rechargement.",
        "settings.showMode.lock": "Un cadenas à la place de l'icône du salon",
        "settings.showMode.muted": "En sourdine, avec un œil barré après le nom",
        "settings.hideUnreads": "Masquer les non lus",
        "settings.hideUnreads.description": "Les salons masqués n'apparaissent jamais comme non lus.",
        "settings.showAllowed": "Afficher qui peut le voir",
        "settings.showAllowed.description": "Ouvre par défaut la liste des utilisateurs et rôles autorisés sur la page d'un salon masqué.",
    },
    ja: {
        "title.hidden.text": "これは非表示のテキストチャンネルです",
        "title.locked.text": "これはロックされたテキストチャンネルです",
        "title.hidden.voice": "これは非表示のボイスチャンネルです",
        "title.locked.voice": "これはロックされたボイスチャンネルです",
        "title.hidden.announcement": "これは非表示のアナウンスチャンネルです",
        "title.locked.announcement": "これはロックされたアナウンスチャンネルです",
        "title.hidden.stage": "これは非表示のステージチャンネルです",
        "title.locked.stage": "これはロックされたステージチャンネルです",
        "title.hidden.forum": "これは非表示のフォーラムチャンネルです",
        "title.locked.forum": "これはロックされたフォーラムチャンネルです",
        "title.hidden.media": "これは非表示のメディアチャンネルです",
        "title.locked.media": "これはロックされたメディアチャンネルです",
        "title.hidden.other": "これは非表示のチャンネルです",
        "title.locked.other": "これはロックされたチャンネルです",
        "lead.messages": "このチャンネルのメッセージは表示できません。",
        "lead.posts": "このチャンネルの投稿は表示できません。",
        "lead.guidelines": " ガイドラインは下にあります。",
        "last.message": "最後のメッセージ: {date}",
        "last.post": "最後の投稿: {date}",
        "last.pin": "最後のピン留め: {date}",
        "slowmode": "スローモード: {duration}",
        "slowmode.thread": "スレッドのデフォルトのスローモード: {duration}",
        "bitrate": "ビットレート: {kbps} kbps",
        "region": "リージョン: {region}",
        "automatic": "自動",
        "video.quality": "ビデオ品質: {quality}",
        "archive.threads": "スレッドは {duration} 操作がないとアーカイブされます",
        "archive.posts": "投稿は {duration} 操作がないとアーカイブされます",
        "layout": "デフォルトのレイアウト: {layout}",
        "layout.0": "未設定",
        "layout.1": "リスト表示",
        "layout.2": "ギャラリー表示",
        "sort": "デフォルトの並べ替え: {order}",
        "sort.0": "最新のアクティビティ",
        "sort.1": "作成日",
        "reaction": "デフォルトのリアクション:",
        "tag.required": "このフォーラムの投稿にはタグが必要です。",
        "tags": "利用可能なタグ",
        "allowed": "許可されたユーザーとロール",
        "allowed.hide": "許可されたユーザーとロールを隠す",
        "allowed.show": "許可されたユーザーとロールを表示",
        "nsfw": "NSFW",
        "emoji": "絵文字",
        "hidden.channel": "非表示のチャンネル",
        "crashed": "この非表示のチャンネルを表示できませんでした。",
        "duration.day": "{count}日",
        "duration.hour": "{count}時間",
        "duration.minute": "{count}分",
        "duration.second": "{count}秒",
        "settings.showMode": "非表示チャンネルの見た目",
        "settings.showMode.description": "ボイスチャンネルには再読み込み後に反映されます。",
        "settings.showMode.lock": "チャンネルアイコンの代わりに鍵を表示",
        "settings.showMode.muted": "ミュート表示にして、名前の後ろに斜線入りの目を表示",
        "settings.hideUnreads": "未読を非表示",
        "settings.hideUnreads.description": "非表示チャンネルは未読として表示されません。",
        "settings.showAllowed": "閲覧できる人を表示",
        "settings.showAllowed.description": "非表示チャンネルのページで、許可されたユーザーとロールの一覧を最初から開いておきます。",
    },
    pl: {
        "title.hidden.text": "To jest ukryty kanał tekstowy",
        "title.locked.text": "To jest zablokowany kanał tekstowy",
        "title.hidden.voice": "To jest ukryty kanał głosowy",
        "title.locked.voice": "To jest zablokowany kanał głosowy",
        "title.hidden.announcement": "To jest ukryty kanał ogłoszeń",
        "title.locked.announcement": "To jest zablokowany kanał ogłoszeń",
        "title.hidden.stage": "To jest ukryty kanał sceny",
        "title.locked.stage": "To jest zablokowany kanał sceny",
        "title.hidden.forum": "To jest ukryte forum",
        "title.locked.forum": "To jest zablokowane forum",
        "title.hidden.media": "To jest ukryty kanał multimediów",
        "title.locked.media": "To jest zablokowany kanał multimediów",
        "title.hidden.other": "To jest ukryty kanał",
        "title.locked.other": "To jest zablokowany kanał",
        "lead.messages": "Nie możesz zobaczyć wiadomości na tym kanale.",
        "lead.posts": "Nie możesz zobaczyć postów na tym kanale.",
        "lead.guidelines": " Jego zasady znajdziesz poniżej.",
        "last.message": "Ostatnia wiadomość: {date}",
        "last.post": "Ostatni post: {date}",
        "last.pin": "Ostatnie przypięcie: {date}",
        "slowmode": "Tryb powolny: {duration}",
        "slowmode.thread": "Domyślny tryb powolny wątków: {duration}",
        "bitrate": "Bitrate: {kbps} kb/s",
        "region": "Region: {region}",
        "automatic": "Automatyczna",
        "video.quality": "Jakość wideo: {quality}",
        "archive.threads": "Wątki są archiwizowane po {duration} bezczynności",
        "archive.posts": "Posty są archiwizowane po {duration} bezczynności",
        "layout": "Domyślny układ: {layout}",
        "layout.0": "Nie ustawiono",
        "layout.1": "Widok listy",
        "layout.2": "Widok galerii",
        "sort": "Domyślne sortowanie: {order}",
        "sort.0": "Ostatnia aktywność",
        "sort.1": "Data utworzenia",
        "reaction": "Domyślna reakcja:",
        "tag.required": "Posty na tym forum wymagają tagu.",
        "tags": "Dostępne tagi",
        "allowed": "Dozwoleni użytkownicy i role",
        "allowed.hide": "Ukryj dozwolonych użytkowników i role",
        "allowed.show": "Pokaż dozwolonych użytkowników i role",
        "nsfw": "NSFW",
        "emoji": "emoji",
        "hidden.channel": "Ukryty kanał",
        "crashed": "Nie udało się wyświetlić tego ukrytego kanału.",
        "duration.day": { one: "{count} dzień", few: "{count} dni", many: "{count} dni", other: "{count} dnia" },
        "duration.hour": { one: "{count} godzina", few: "{count} godziny", many: "{count} godzin", other: "{count} godziny" },
        "duration.minute": { one: "{count} minuta", few: "{count} minuty", many: "{count} minut", other: "{count} minuty" },
        "duration.second": { one: "{count} sekunda", few: "{count} sekundy", many: "{count} sekund", other: "{count} sekundy" },
        "settings.showMode": "Wygląd ukrytych kanałów",
        "settings.showMode.description": "W przypadku kanałów głosowych działa po ponownym załadowaniu.",
        "settings.showMode.lock": "Kłódka zamiast ikony kanału",
        "settings.showMode.muted": "Wyciszony, z przekreślonym okiem po nazwie",
        "settings.hideUnreads": "Ukryj nieprzeczytane",
        "settings.hideUnreads.description": "Ukryte kanały nigdy nie pokazują się jako nieprzeczytane.",
        "settings.showAllowed": "Pokaż, kto go widzi",
        "settings.showAllowed.description": "Domyślnie rozwija listę dozwolonych użytkowników i ról na stronie ukrytego kanału.",
    },
    "pt-BR": {
        "title.hidden.text": "Este é um canal de texto oculto",
        "title.locked.text": "Este é um canal de texto bloqueado",
        "title.hidden.voice": "Este é um canal de voz oculto",
        "title.locked.voice": "Este é um canal de voz bloqueado",
        "title.hidden.announcement": "Este é um canal de anúncios oculto",
        "title.locked.announcement": "Este é um canal de anúncios bloqueado",
        "title.hidden.stage": "Este é um canal de palco oculto",
        "title.locked.stage": "Este é um canal de palco bloqueado",
        "title.hidden.forum": "Este é um canal de fórum oculto",
        "title.locked.forum": "Este é um canal de fórum bloqueado",
        "title.hidden.media": "Este é um canal de mídia oculto",
        "title.locked.media": "Este é um canal de mídia bloqueado",
        "title.hidden.other": "Este é um canal oculto",
        "title.locked.other": "Este é um canal bloqueado",
        "lead.messages": "Você não pode ver as mensagens deste canal.",
        "lead.posts": "Você não pode ver as postagens deste canal.",
        "lead.guidelines": " As diretrizes estão abaixo.",
        "last.message": "Última mensagem: {date}",
        "last.post": "Última postagem: {date}",
        "last.pin": "Última fixação: {date}",
        "slowmode": "Modo lento: {duration}",
        "slowmode.thread": "Modo lento padrão dos tópicos: {duration}",
        "bitrate": "Taxa de bits: {kbps} kbps",
        "region": "Região: {region}",
        "automatic": "Automática",
        "video.quality": "Qualidade de vídeo: {quality}",
        "archive.threads": "Os tópicos são arquivados após {duration} de inatividade",
        "archive.posts": "As postagens são arquivadas após {duration} de inatividade",
        "layout": "Layout padrão: {layout}",
        "layout.0": "Não definido",
        "layout.1": "Visualização em lista",
        "layout.2": "Visualização em galeria",
        "sort": "Ordem padrão: {order}",
        "sort.0": "Atividade mais recente",
        "sort.1": "Data de criação",
        "reaction": "Reação padrão:",
        "tag.required": "As postagens deste fórum precisam de uma tag.",
        "tags": "Tags disponíveis",
        "allowed": "Usuários e cargos com acesso",
        "allowed.hide": "Ocultar usuários e cargos com acesso",
        "allowed.show": "Mostrar usuários e cargos com acesso",
        "nsfw": "NSFW",
        "emoji": "emoji",
        "hidden.channel": "Canal oculto",
        "crashed": "Não foi possível mostrar este canal oculto.",
        "duration.day": { one: "{count} dia", other: "{count} dias" },
        "duration.hour": { one: "{count} hora", other: "{count} horas" },
        "duration.minute": { one: "{count} minuto", other: "{count} minutos" },
        "duration.second": { one: "{count} segundo", other: "{count} segundos" },
        "settings.showMode": "Aparência dos canais ocultos",
        "settings.showMode.description": "Nos canais de voz, só vale depois de recarregar.",
        "settings.showMode.lock": "Um cadeado no lugar do ícone do canal",
        "settings.showMode.muted": "Silenciado, com um olho riscado após o nome",
        "settings.hideUnreads": "Ocultar não lidas",
        "settings.hideUnreads.description": "Canais ocultos nunca aparecem como não lidos.",
        "settings.showAllowed": "Mostrar quem pode ver",
        "settings.showAllowed.description": "Abre por padrão a lista de usuários e cargos com acesso na página de um canal oculto.",
    },
    ru: {
        "title.hidden.text": "Это скрытый текстовый канал",
        "title.locked.text": "Это закрытый текстовый канал",
        "title.hidden.voice": "Это скрытый голосовой канал",
        "title.locked.voice": "Это закрытый голосовой канал",
        "title.hidden.announcement": "Это скрытый канал объявлений",
        "title.locked.announcement": "Это закрытый канал объявлений",
        "title.hidden.stage": "Это скрытая трибуна",
        "title.locked.stage": "Это закрытая трибуна",
        "title.hidden.forum": "Это скрытый форум",
        "title.locked.forum": "Это закрытый форум",
        "title.hidden.media": "Это скрытый медиаканал",
        "title.locked.media": "Это закрытый медиаканал",
        "title.hidden.other": "Это скрытый канал",
        "title.locked.other": "Это закрытый канал",
        "lead.messages": "Вы не можете видеть сообщения в этом канале.",
        "lead.posts": "Вы не можете видеть публикации в этом канале.",
        "lead.guidelines": " Правила канала приведены ниже.",
        "last.message": "Последнее сообщение: {date}",
        "last.post": "Последняя публикация: {date}",
        "last.pin": "Последнее закрепление: {date}",
        "slowmode": "Медленный режим: {duration}",
        "slowmode.thread": "Медленный режим по умолчанию для веток: {duration}",
        "bitrate": "Битрейт: {kbps} кбит/с",
        "region": "Регион: {region}",
        "automatic": "Автоматически",
        "video.quality": "Качество видео: {quality}",
        "archive.threads": "Ветки архивируются после {duration} неактивности",
        "archive.posts": "Публикации архивируются после {duration} неактивности",
        "layout": "Вид по умолчанию: {layout}",
        "layout.0": "Не задан",
        "layout.1": "Список",
        "layout.2": "Галерея",
        "sort": "Сортировка по умолчанию: {order}",
        "sort.0": "Последняя активность",
        "sort.1": "Дата создания",
        "reaction": "Реакция по умолчанию:",
        "tag.required": "Публикациям в этом форуме нужен тег.",
        "tags": "Доступные теги",
        "allowed": "Пользователи и роли с доступом",
        "allowed.hide": "Скрыть пользователей и роли с доступом",
        "allowed.show": "Показать пользователей и роли с доступом",
        "nsfw": "NSFW",
        "emoji": "эмодзи",
        "hidden.channel": "Скрытый канал",
        "crashed": "Не удалось показать этот скрытый канал.",
        "duration.day": { one: "{count} день", few: "{count} дня", many: "{count} дней", other: "{count} дня" },
        "duration.hour": { one: "{count} час", few: "{count} часа", many: "{count} часов", other: "{count} часа" },
        "duration.minute": { one: "{count} минута", few: "{count} минуты", many: "{count} минут", other: "{count} минуты" },
        "duration.second": { one: "{count} секунда", few: "{count} секунды", many: "{count} секунд", other: "{count} секунды" },
        "settings.showMode": "Как выглядят скрытые каналы",
        "settings.showMode.description": "Для голосовых каналов вступает в силу после перезагрузки.",
        "settings.showMode.lock": "Замок вместо значка канала",
        "settings.showMode.muted": "Как с отключёнными уведомлениями, с перечёркнутым глазом после названия",
        "settings.hideUnreads": "Скрыть непрочитанное",
        "settings.hideUnreads.description": "Скрытые каналы никогда не отображаются как непрочитанные.",
        "settings.showAllowed": "Показывать, кто может его видеть",
        "settings.showAllowed.description": "По умолчанию раскрывать список пользователей и ролей с доступом на странице скрытого канала.",
    },
    tr: {
        "title.hidden.text": "Bu, gizli bir metin kanalı",
        "title.locked.text": "Bu, kilitli bir metin kanalı",
        "title.hidden.voice": "Bu, gizli bir ses kanalı",
        "title.locked.voice": "Bu, kilitli bir ses kanalı",
        "title.hidden.announcement": "Bu, gizli bir duyuru kanalı",
        "title.locked.announcement": "Bu, kilitli bir duyuru kanalı",
        "title.hidden.stage": "Bu, gizli bir sahne kanalı",
        "title.locked.stage": "Bu, kilitli bir sahne kanalı",
        "title.hidden.forum": "Bu, gizli bir forum kanalı",
        "title.locked.forum": "Bu, kilitli bir forum kanalı",
        "title.hidden.media": "Bu, gizli bir medya kanalı",
        "title.locked.media": "Bu, kilitli bir medya kanalı",
        "title.hidden.other": "Bu, gizli bir kanal",
        "title.locked.other": "Bu, kilitli bir kanal",
        "lead.messages": "Bu kanaldaki mesajları göremezsin.",
        "lead.posts": "Bu kanaldaki gönderileri göremezsin.",
        "lead.guidelines": " Yönergeleri aşağıda.",
        "last.message": "Son mesaj: {date}",
        "last.post": "Son gönderi: {date}",
        "last.pin": "Son sabitleme: {date}",
        "slowmode": "Yavaş mod: {duration}",
        "slowmode.thread": "Varsayılan alt kanal yavaş modu: {duration}",
        "bitrate": "Bit hızı: {kbps} kbps",
        "region": "Bölge: {region}",
        "automatic": "Otomatik",
        "video.quality": "Video kalitesi: {quality}",
        "archive.threads": "Alt kanallar {duration} etkinlik olmazsa arşivlenir",
        "archive.posts": "Gönderiler {duration} etkinlik olmazsa arşivlenir",
        "layout": "Varsayılan düzen: {layout}",
        "layout.0": "Ayarlanmadı",
        "layout.1": "Liste görünümü",
        "layout.2": "Galeri görünümü",
        "sort": "Varsayılan sıralama: {order}",
        "sort.0": "En son etkinlik",
        "sort.1": "Oluşturulma tarihi",
        "reaction": "Varsayılan tepki:",
        "tag.required": "Bu forumdaki gönderiler için etiket gerekir.",
        "tags": "Kullanılabilir etiketler",
        "allowed": "İzin verilen kullanıcılar ve roller",
        "allowed.hide": "İzin verilen kullanıcıları ve rolleri gizle",
        "allowed.show": "İzin verilen kullanıcıları ve rolleri göster",
        "nsfw": "NSFW",
        "emoji": "emoji",
        "hidden.channel": "Gizli kanal",
        "crashed": "Bu gizli kanal gösterilemedi.",
        "duration.day": "{count} gün",
        "duration.hour": "{count} saat",
        "duration.minute": "{count} dakika",
        "duration.second": "{count} saniye",
        "settings.showMode": "Gizli kanalların görünümü",
        "settings.showMode.description": "Ses kanallarında yeniden yüklemeden sonra geçerli olur.",
        "settings.showMode.lock": "Kanal simgesi yerine kilit",
        "settings.showMode.muted": "Sessize alınmış görünüm, adın sonunda üstü çizili göz",
        "settings.hideUnreads": "Okunmamışları gizle",
        "settings.hideUnreads.description": "Gizli kanallar hiçbir zaman okunmamış olarak görünmez.",
        "settings.showAllowed": "Kimlerin görebildiğini göster",
        "settings.showAllowed.description": "Gizli kanalın sayfasında izin verilen kullanıcılar ve roller listesini varsayılan olarak açar.",
    },
});
