import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.watchAllFriends": "Watch all friends",
        "settings.watchAllFriends.description": "Alert for every friend, not only the people you pick.",
        "settings.showToast": "In-app toast",
        "settings.showToast.description": "A toast at the top of Discord.",
        "settings.showDesktop": "Desktop notification",
        "settings.showDesktop.description": "A Windows notification, like Discord's own. Clicking it opens the DM.",
        "settings.sound": "Sound",
        "settings.sound.description": "One of Discord's sounds.",
        "sound.none": "No sound",
        "sound.message1": "Message",
        "sound.message2": "Soft ping",
        "sound.message3": "Chime",
        "sound.mention1": "Mention",
        "sound.user_join": "User joined",
        "sound.stream_started": "Stream started",
        "sound.success": "Success",
        "settings.volume": "Sound volume",
        "settings.volume.description": "Percent.",
        "settings.alertInDnd": "Alert even in Do Not Disturb",
        "settings.alertInDnd.description": "Otherwise nothing shows or plays while your status is Do Not Disturb.",
        "settings.onOffline": "When they go offline",
        "settings.onGame": "When they start playing a game",
        "settings.onStream": "When they start streaming",
        "settings.flapMinutes": "Ignore reconnects (minutes)",
        "settings.flapMinutes.description": "Coming back online this soon after going offline isn't announced. 0 announces every time.",
        "settings.cooldownMinutes": "Cooldown per person (minutes)",
        "settings.cooldownMinutes.description": "At most one alert of each kind per person in this time. 0 turns it off.",
        "menu.alerts": "Online Alerts",
        "menu.alerts.subtext": "On for all friends",
        "toast.on": "Online alerts on for {name}",
        "toast.off": "Online alerts off for {name}",
        "alert.someone": "Someone",
        "alert.online": "is online",
        "alert.online.text": "{name} is online",
        "alert.onlineGame": "is online, playing {game}",
        "alert.onlineGame.text": "{name} is online, playing {game}",
        "alert.offline": "went offline",
        "alert.offline.text": "{name} went offline",
        "alert.game": "started playing {game}",
        "alert.game.text": "{name} started playing {game}",
        "alert.gameUnknown": "started playing a game",
        "alert.gameUnknown.text": "{name} started playing a game",
        "alert.stream": "started streaming",
        "alert.stream.text": "{name} started streaming",
        "alert.streamGame": "started streaming {game}",
        "alert.streamGame.text": "{name} started streaming {game}",
        "panel.watched": "Watched people",
        "panel.count": { one: "{count} person.", other: "{count} people." },
        "panel.countAll": { one: "{count} person, plus all your friends.", other: "{count} people, plus all your friends." },
        "panel.allFriends": "All your friends. Right-click anyone else and pick Online Alerts to add them.",
        "panel.nobody": "Nobody yet. Right-click someone and pick Online Alerts, or add a user ID here.",
        "panel.stop": "Stop watching {name}",
        "panel.remove": "Remove",
        "panel.userIdLabel": "User ID to watch",
        "panel.userIdPlaceholder": "User ID",
        "panel.add": "Add",
        "panel.recent": "Recent",
        "panel.recent.some": "Since Discord started. Kept in memory only.",
        "panel.recent.none": "No alerts yet. Kept in memory only.",
        "panel.clear": "Clear",
    },
    de: {
        "settings.watchAllFriends": "Alle Freunde beobachten",
        "settings.watchAllFriends.description": "Bei jedem Freund benachrichtigen, nicht nur bei den Leuten, die du auswählst.",
        "settings.showToast": "Hinweis in der App",
        "settings.showToast.description": "Ein Hinweis oben in Discord.",
        "settings.showDesktop": "Desktop-Benachrichtigung",
        "settings.showDesktop.description": "Eine Windows-Benachrichtigung wie bei Discord selbst. Ein Klick darauf öffnet die DM.",
        "settings.sound": "Sound",
        "settings.sound.description": "Einer der Discord-Sounds.",
        "sound.none": "Kein Sound",
        "sound.message1": "Nachricht",
        "sound.message2": "Sanfter Ping",
        "sound.message3": "Glockenspiel",
        "sound.mention1": "Erwähnung",
        "sound.user_join": "Nutzer beigetreten",
        "sound.stream_started": "Stream gestartet",
        "sound.success": "Erfolg",
        "settings.volume": "Lautstärke",
        "settings.volume.description": "Prozent.",
        "settings.alertInDnd": "Auch bei „Nicht stören“ benachrichtigen",
        "settings.alertInDnd.description": "Sonst wird nichts angezeigt oder abgespielt, solange dein Status „Nicht stören“ ist.",
        "settings.onOffline": "Wenn sie offline gehen",
        "settings.onGame": "Wenn sie ein Spiel starten",
        "settings.onStream": "Wenn sie einen Stream starten",
        "settings.flapMinutes": "Wiederverbindungen ignorieren (Minuten)",
        "settings.flapMinutes.description": "Wer kurz nach dem Offlinegehen wieder online kommt, wird nicht gemeldet. Bei 0 wird jedes Mal gemeldet.",
        "settings.cooldownMinutes": "Abklingzeit pro Person (Minuten)",
        "settings.cooldownMinutes.description": "Höchstens eine Benachrichtigung jeder Art pro Person in dieser Zeit. 0 schaltet das ab.",
        "menu.alerts": "Online-Benachrichtigungen",
        "menu.alerts.subtext": "Für alle Freunde aktiv",
        "toast.on": "Online-Benachrichtigungen für {name} aktiviert",
        "toast.off": "Online-Benachrichtigungen für {name} deaktiviert",
        "alert.someone": "Jemand",
        "alert.online": "ist online",
        "alert.online.text": "{name} ist online",
        "alert.onlineGame": "ist online und spielt {game}",
        "alert.onlineGame.text": "{name} ist online und spielt {game}",
        "alert.offline": "ist jetzt offline",
        "alert.offline.text": "{name} ist jetzt offline",
        "alert.game": "spielt jetzt {game}",
        "alert.game.text": "{name} spielt jetzt {game}",
        "alert.gameUnknown": "hat ein Spiel gestartet",
        "alert.gameUnknown.text": "{name} hat ein Spiel gestartet",
        "alert.stream": "streamt jetzt",
        "alert.stream.text": "{name} streamt jetzt",
        "alert.streamGame": "streamt jetzt {game}",
        "alert.streamGame.text": "{name} streamt jetzt {game}",
        "panel.watched": "Beobachtete Personen",
        "panel.count": { one: "{count} Person.", other: "{count} Personen." },
        "panel.countAll": { one: "{count} Person, dazu alle deine Freunde.", other: "{count} Personen, dazu alle deine Freunde." },
        "panel.allFriends": "Alle deine Freunde. Klicke andere mit der rechten Maustaste an und wähle „Online-Benachrichtigungen“, um sie hinzuzufügen.",
        "panel.nobody": "Noch niemand. Klicke jemanden mit der rechten Maustaste an und wähle „Online-Benachrichtigungen“ oder füge hier eine Nutzer-ID hinzu.",
        "panel.stop": "{name} nicht mehr beobachten",
        "panel.remove": "Entfernen",
        "panel.userIdLabel": "Zu beobachtende Nutzer-ID",
        "panel.userIdPlaceholder": "Nutzer-ID",
        "panel.add": "Hinzufügen",
        "panel.recent": "Zuletzt",
        "panel.recent.some": "Seit dem Start von Discord. Nur im Arbeitsspeicher gespeichert.",
        "panel.recent.none": "Noch keine Benachrichtigungen. Nur im Arbeitsspeicher gespeichert.",
        "panel.clear": "Leeren",
    },
    es: {
        "settings.watchAllFriends": "Vigilar a todos los amigos",
        "settings.watchAllFriends.description": "Avisar de cada amigo, no solo de las personas que elijas.",
        "settings.showToast": "Aviso en la app",
        "settings.showToast.description": "Un aviso en la parte superior de Discord.",
        "settings.showDesktop": "Notificación de escritorio",
        "settings.showDesktop.description": "Una notificación de Windows, como las de Discord. Al hacer clic se abre el MD.",
        "settings.sound": "Sonido",
        "settings.sound.description": "Uno de los sonidos de Discord.",
        "sound.none": "Sin sonido",
        "sound.message1": "Mensaje",
        "sound.message2": "Ping suave",
        "sound.message3": "Campanilla",
        "sound.mention1": "Mención",
        "sound.user_join": "Usuario se ha unido",
        "sound.stream_started": "Directo iniciado",
        "sound.success": "Éxito",
        "settings.volume": "Volumen del sonido",
        "settings.volume.description": "Porcentaje.",
        "settings.alertInDnd": "Avisar incluso en No molestar",
        "settings.alertInDnd.description": "Si no, no se muestra ni suena nada mientras tu estado sea No molestar.",
        "settings.onOffline": "Cuando se desconecten",
        "settings.onGame": "Cuando empiecen a jugar",
        "settings.onStream": "Cuando empiecen a hacer un directo",
        "settings.flapMinutes": "Ignorar reconexiones (minutos)",
        "settings.flapMinutes.description": "No se avisa si vuelven a conectarse poco después de desconectarse. Con 0 se avisa siempre.",
        "settings.cooldownMinutes": "Tiempo de espera por persona (minutos)",
        "settings.cooldownMinutes.description": "Como máximo un aviso de cada tipo por persona en este tiempo. 0 lo desactiva.",
        "menu.alerts": "Avisos de conexión",
        "menu.alerts.subtext": "Activado para todos los amigos",
        "toast.on": "Avisos de conexión activados para {name}",
        "toast.off": "Avisos de conexión desactivados para {name}",
        "alert.someone": "Alguien",
        "alert.online": "está en línea",
        "alert.online.text": "{name} está en línea",
        "alert.onlineGame": "está en línea, jugando a {game}",
        "alert.onlineGame.text": "{name} está en línea, jugando a {game}",
        "alert.offline": "se ha desconectado",
        "alert.offline.text": "{name} se ha desconectado",
        "alert.game": "ha empezado a jugar a {game}",
        "alert.game.text": "{name} ha empezado a jugar a {game}",
        "alert.gameUnknown": "ha empezado a jugar",
        "alert.gameUnknown.text": "{name} ha empezado a jugar",
        "alert.stream": "ha empezado un directo",
        "alert.stream.text": "{name} ha empezado un directo",
        "alert.streamGame": "ha empezado un directo de {game}",
        "alert.streamGame.text": "{name} ha empezado un directo de {game}",
        "panel.watched": "Personas vigiladas",
        "panel.count": { one: "{count} persona.", other: "{count} personas." },
        "panel.countAll": { one: "{count} persona, más todos tus amigos.", other: "{count} personas, más todos tus amigos." },
        "panel.allFriends": "Todos tus amigos. Haz clic derecho en cualquier otra persona y elige Avisos de conexión para añadirla.",
        "panel.nobody": "Nadie todavía. Haz clic derecho en alguien y elige Avisos de conexión, o añade un ID de usuario aquí.",
        "panel.stop": "Dejar de vigilar a {name}",
        "panel.remove": "Quitar",
        "panel.userIdLabel": "ID de usuario que vigilar",
        "panel.userIdPlaceholder": "ID de usuario",
        "panel.add": "Añadir",
        "panel.recent": "Recientes",
        "panel.recent.some": "Desde que se abrió Discord. Solo se guarda en la memoria.",
        "panel.recent.none": "Aún no hay avisos. Solo se guarda en la memoria.",
        "panel.clear": "Borrar",
    },
    fr: {
        "settings.watchAllFriends": "Surveiller tous les amis",
        "settings.watchAllFriends.description": "Alerter pour chaque ami, pas seulement pour les personnes que tu choisis.",
        "settings.showToast": "Notification dans l'app",
        "settings.showToast.description": "Une notification en haut de Discord.",
        "settings.showDesktop": "Notification de bureau",
        "settings.showDesktop.description": "Une notification Windows, comme celles de Discord. Un clic dessus ouvre le MP.",
        "settings.sound": "Son",
        "settings.sound.description": "Un des sons de Discord.",
        "sound.none": "Aucun son",
        "sound.message1": "Message",
        "sound.message2": "Ping discret",
        "sound.message3": "Carillon",
        "sound.mention1": "Mention",
        "sound.user_join": "Utilisateur arrivé",
        "sound.stream_started": "Stream démarré",
        "sound.success": "Succès",
        "settings.volume": "Volume du son",
        "settings.volume.description": "Pourcentage.",
        "settings.alertInDnd": "Alerter même en mode Ne pas déranger",
        "settings.alertInDnd.description": "Sinon, rien ne s'affiche ni ne retentit tant que ton statut est Ne pas déranger.",
        "settings.onOffline": "Quand ils se déconnectent",
        "settings.onGame": "Quand ils lancent un jeu",
        "settings.onStream": "Quand ils lancent un stream",
        "settings.flapMinutes": "Ignorer les reconnexions (minutes)",
        "settings.flapMinutes.description": "Un retour en ligne peu après une déconnexion n'est pas signalé. Avec 0, c'est signalé à chaque fois.",
        "settings.cooldownMinutes": "Délai par personne (minutes)",
        "settings.cooldownMinutes.description": "Au plus une alerte de chaque type par personne pendant ce délai. 0 désactive cette limite.",
        "menu.alerts": "Alertes de connexion",
        "menu.alerts.subtext": "Activées pour tous les amis",
        "toast.on": "Alertes de connexion activées pour {name}",
        "toast.off": "Alertes de connexion désactivées pour {name}",
        "alert.someone": "Quelqu'un",
        "alert.online": "est en ligne",
        "alert.online.text": "{name} est en ligne",
        "alert.onlineGame": "est en ligne et joue à {game}",
        "alert.onlineGame.text": "{name} est en ligne et joue à {game}",
        "alert.offline": "s'est déconnecté(e)",
        "alert.offline.text": "{name} s'est déconnecté(e)",
        "alert.game": "a commencé à jouer à {game}",
        "alert.game.text": "{name} a commencé à jouer à {game}",
        "alert.gameUnknown": "a commencé à jouer à un jeu",
        "alert.gameUnknown.text": "{name} a commencé à jouer à un jeu",
        "alert.stream": "a lancé un stream",
        "alert.stream.text": "{name} a lancé un stream",
        "alert.streamGame": "a lancé un stream de {game}",
        "alert.streamGame.text": "{name} a lancé un stream de {game}",
        "panel.watched": "Personnes surveillées",
        "panel.count": { one: "{count} personne.", other: "{count} personnes." },
        "panel.countAll": { one: "{count} personne, plus tous tes amis.", other: "{count} personnes, plus tous tes amis." },
        "panel.allFriends": "Tous tes amis. Fais un clic droit sur quelqu'un d'autre et choisis Alertes de connexion pour l'ajouter.",
        "panel.nobody": "Personne pour l'instant. Fais un clic droit sur quelqu'un et choisis Alertes de connexion, ou ajoute un ID d'utilisateur ici.",
        "panel.stop": "Ne plus surveiller {name}",
        "panel.remove": "Retirer",
        "panel.userIdLabel": "ID d'utilisateur à surveiller",
        "panel.userIdPlaceholder": "ID d'utilisateur",
        "panel.add": "Ajouter",
        "panel.recent": "Récentes",
        "panel.recent.some": "Depuis le lancement de Discord. Gardées en mémoire uniquement.",
        "panel.recent.none": "Aucune alerte pour l'instant. Gardées en mémoire uniquement.",
        "panel.clear": "Effacer",
    },
    ja: {
        "settings.watchAllFriends": "すべてのフレンドを対象にする",
        "settings.watchAllFriends.description": "選んだ人だけでなく、すべてのフレンドについて通知します。",
        "settings.showToast": "アプリ内トースト",
        "settings.showToast.description": "Discordの上部にトーストを表示します。",
        "settings.showDesktop": "デスクトップ通知",
        "settings.showDesktop.description": "Discord本体と同じWindows通知です。クリックするとDMが開きます。",
        "settings.sound": "サウンド",
        "settings.sound.description": "Discordのサウンドから選べます。",
        "sound.none": "サウンドなし",
        "sound.message1": "メッセージ",
        "sound.message2": "やさしいピン",
        "sound.message3": "チャイム",
        "sound.mention1": "メンション",
        "sound.user_join": "ユーザーの参加",
        "sound.stream_started": "配信開始",
        "sound.success": "成功",
        "settings.volume": "サウンドの音量",
        "settings.volume.description": "パーセントで指定します。",
        "settings.alertInDnd": "取り込み中でも通知する",
        "settings.alertInDnd.description": "オフの場合、ステータスが取り込み中の間は何も表示も再生もされません。",
        "settings.onOffline": "オフラインになったとき",
        "settings.onGame": "ゲームを始めたとき",
        "settings.onStream": "配信を始めたとき",
        "settings.flapMinutes": "再接続を無視する (分)",
        "settings.flapMinutes.description": "オフラインになってからこの時間内にオンラインに戻っても通知しません。0にすると毎回通知します。",
        "settings.cooldownMinutes": "1人あたりのクールダウン (分)",
        "settings.cooldownMinutes.description": "この時間内は、1人につき種類ごとに最大1回だけ通知します。0でオフになります。",
        "menu.alerts": "オンライン通知",
        "menu.alerts.subtext": "すべてのフレンドでオン",
        "toast.on": "{name}のオンライン通知をオンにしました",
        "toast.off": "{name}のオンライン通知をオフにしました",
        "alert.someone": "誰か",
        "alert.online": "オンラインになりました",
        "alert.online.text": "{name}さんがオンラインになりました",
        "alert.onlineGame": "{game}をプレイ中でオンラインになりました",
        "alert.onlineGame.text": "{name}さんが{game}をプレイ中でオンラインになりました",
        "alert.offline": "オフラインになりました",
        "alert.offline.text": "{name}さんがオフラインになりました",
        "alert.game": "{game}を始めました",
        "alert.game.text": "{name}さんが{game}を始めました",
        "alert.gameUnknown": "ゲームを始めました",
        "alert.gameUnknown.text": "{name}さんがゲームを始めました",
        "alert.stream": "配信を始めました",
        "alert.stream.text": "{name}さんが配信を始めました",
        "alert.streamGame": "{game}の配信を始めました",
        "alert.streamGame.text": "{name}さんが{game}の配信を始めました",
        "panel.watched": "通知の対象",
        "panel.count": { other: "{count}人。" },
        "panel.countAll": { other: "{count}人と、すべてのフレンド。" },
        "panel.allFriends": "すべてのフレンド。ほかの人を追加するには、その人を右クリックして「オンライン通知」を選びます。",
        "panel.nobody": "まだ誰もいません。誰かを右クリックして「オンライン通知」を選ぶか、ここにユーザーIDを追加してください。",
        "panel.stop": "{name}の通知をやめる",
        "panel.remove": "削除",
        "panel.userIdLabel": "通知の対象にするユーザーID",
        "panel.userIdPlaceholder": "ユーザーID",
        "panel.add": "追加",
        "panel.recent": "最近の通知",
        "panel.recent.some": "Discordの起動後のものです。メモリ内にのみ保存されます。",
        "panel.recent.none": "まだ通知はありません。メモリ内にのみ保存されます。",
        "panel.clear": "クリア",
    },
    pl: {
        "settings.watchAllFriends": "Obserwuj wszystkich znajomych",
        "settings.watchAllFriends.description": "Powiadamiaj o każdym znajomym, nie tylko o wybranych osobach.",
        "settings.showToast": "Powiadomienie w aplikacji",
        "settings.showToast.description": "Powiadomienie u góry okna Discorda.",
        "settings.showDesktop": "Powiadomienie na pulpicie",
        "settings.showDesktop.description": "Powiadomienie Windows, takie jak od samego Discorda. Kliknięcie otwiera DM.",
        "settings.sound": "Dźwięk",
        "settings.sound.description": "Jeden z dźwięków Discorda.",
        "sound.none": "Bez dźwięku",
        "sound.message1": "Wiadomość",
        "sound.message2": "Cichy sygnał",
        "sound.message3": "Dzwonek",
        "sound.mention1": "Wzmianka",
        "sound.user_join": "Użytkownik dołączył",
        "sound.stream_started": "Transmisja rozpoczęta",
        "sound.success": "Sukces",
        "settings.volume": "Głośność dźwięku",
        "settings.volume.description": "Procenty.",
        "settings.alertInDnd": "Powiadamiaj nawet w trybie Nie przeszkadzać",
        "settings.alertInDnd.description": "W przeciwnym razie nic się nie wyświetli ani nie zagra, gdy masz status Nie przeszkadzać.",
        "settings.onOffline": "Gdy przejdą w tryb offline",
        "settings.onGame": "Gdy zaczną grać w grę",
        "settings.onStream": "Gdy zaczną transmisję",
        "settings.flapMinutes": "Ignoruj ponowne połączenia (minuty)",
        "settings.flapMinutes.description": "Powrót online krótko po przejściu w tryb offline nie jest zgłaszany. Przy 0 zgłaszany jest za każdym razem.",
        "settings.cooldownMinutes": "Przerwa dla każdej osoby (minuty)",
        "settings.cooldownMinutes.description": "Najwyżej jedno powiadomienie każdego rodzaju na osobę w tym czasie. 0 wyłącza limit.",
        "menu.alerts": "Powiadomienia o dostępności",
        "menu.alerts.subtext": "Włączone dla wszystkich znajomych",
        "toast.on": "Włączono powiadomienia o dostępności dla: {name}",
        "toast.off": "Wyłączono powiadomienia o dostępności dla: {name}",
        "alert.someone": "Ktoś",
        "alert.online": "jest online",
        "alert.online.text": "{name} jest online",
        "alert.onlineGame": "jest online i gra w {game}",
        "alert.onlineGame.text": "{name} jest online i gra w {game}",
        "alert.offline": "przeszedł(-ła) w tryb offline",
        "alert.offline.text": "{name} przeszedł(-ła) w tryb offline",
        "alert.game": "zaczął(-ęła) grać w {game}",
        "alert.game.text": "{name} zaczął(-ęła) grać w {game}",
        "alert.gameUnknown": "zaczął(-ęła) grać w grę",
        "alert.gameUnknown.text": "{name} zaczął(-ęła) grać w grę",
        "alert.stream": "rozpoczął(-ęła) transmisję",
        "alert.stream.text": "{name} rozpoczął(-ęła) transmisję",
        "alert.streamGame": "rozpoczął(-ęła) transmisję z {game}",
        "alert.streamGame.text": "{name} rozpoczął(-ęła) transmisję z {game}",
        "panel.watched": "Obserwowane osoby",
        "panel.count": { one: "{count} osoba.", few: "{count} osoby.", many: "{count} osób.", other: "{count} osoby." },
        "panel.countAll": { one: "{count} osoba oraz wszyscy twoi znajomi.", few: "{count} osoby oraz wszyscy twoi znajomi.", many: "{count} osób oraz wszyscy twoi znajomi.", other: "{count} osoby oraz wszyscy twoi znajomi." },
        "panel.allFriends": "Wszyscy twoi znajomi. Kliknij prawym przyciskiem inną osobę i wybierz Powiadomienia o dostępności, aby ją dodać.",
        "panel.nobody": "Na razie nikogo. Kliknij kogoś prawym przyciskiem i wybierz Powiadomienia o dostępności albo dodaj tutaj ID użytkownika.",
        "panel.stop": "Przestań obserwować: {name}",
        "panel.remove": "Usuń",
        "panel.userIdLabel": "ID użytkownika do obserwowania",
        "panel.userIdPlaceholder": "ID użytkownika",
        "panel.add": "Dodaj",
        "panel.recent": "Ostatnie",
        "panel.recent.some": "Od uruchomienia Discorda. Przechowywane tylko w pamięci.",
        "panel.recent.none": "Na razie brak powiadomień. Przechowywane tylko w pamięci.",
        "panel.clear": "Wyczyść",
    },
    "pt-BR": {
        "settings.watchAllFriends": "Acompanhar todos os amigos",
        "settings.watchAllFriends.description": "Avisar sobre todos os amigos, não só as pessoas que você escolher.",
        "settings.showToast": "Aviso no app",
        "settings.showToast.description": "Um aviso no topo do Discord.",
        "settings.showDesktop": "Notificação da área de trabalho",
        "settings.showDesktop.description": "Uma notificação do Windows, como as do próprio Discord. Clicar nela abre a DM.",
        "settings.sound": "Som",
        "settings.sound.description": "Um dos sons do Discord.",
        "sound.none": "Sem som",
        "sound.message1": "Mensagem",
        "sound.message2": "Ping suave",
        "sound.message3": "Sino",
        "sound.mention1": "Menção",
        "sound.user_join": "Usuário entrou",
        "sound.stream_started": "Transmissão iniciada",
        "sound.success": "Sucesso",
        "settings.volume": "Volume do som",
        "settings.volume.description": "Porcentagem.",
        "settings.alertInDnd": "Avisar mesmo em Não perturbe",
        "settings.alertInDnd.description": "Caso contrário, nada aparece nem toca enquanto seu status for Não perturbe.",
        "settings.onOffline": "Quando ficarem offline",
        "settings.onGame": "Quando começarem a jogar",
        "settings.onStream": "Quando começarem a transmitir",
        "settings.flapMinutes": "Ignorar reconexões (minutos)",
        "settings.flapMinutes.description": "Voltar a ficar online pouco depois de ficar offline não é avisado. Com 0, avisa sempre.",
        "settings.cooldownMinutes": "Intervalo por pessoa (minutos)",
        "settings.cooldownMinutes.description": "No máximo um aviso de cada tipo por pessoa nesse tempo. 0 desativa.",
        "menu.alerts": "Avisos de online",
        "menu.alerts.subtext": "Ativado para todos os amigos",
        "toast.on": "Avisos de online ativados para {name}",
        "toast.off": "Avisos de online desativados para {name}",
        "alert.someone": "Alguém",
        "alert.online": "está online",
        "alert.online.text": "{name} está online",
        "alert.onlineGame": "está online, jogando {game}",
        "alert.onlineGame.text": "{name} está online, jogando {game}",
        "alert.offline": "ficou offline",
        "alert.offline.text": "{name} ficou offline",
        "alert.game": "começou a jogar {game}",
        "alert.game.text": "{name} começou a jogar {game}",
        "alert.gameUnknown": "começou a jogar",
        "alert.gameUnknown.text": "{name} começou a jogar",
        "alert.stream": "começou a transmitir",
        "alert.stream.text": "{name} começou a transmitir",
        "alert.streamGame": "começou a transmitir {game}",
        "alert.streamGame.text": "{name} começou a transmitir {game}",
        "panel.watched": "Pessoas acompanhadas",
        "panel.count": { one: "{count} pessoa.", other: "{count} pessoas." },
        "panel.countAll": { one: "{count} pessoa, mais todos os seus amigos.", other: "{count} pessoas, mais todos os seus amigos." },
        "panel.allFriends": "Todos os seus amigos. Clique com o botão direito em qualquer outra pessoa e escolha Avisos de online para adicioná-la.",
        "panel.nobody": "Ninguém ainda. Clique com o botão direito em alguém e escolha Avisos de online, ou adicione um ID de usuário aqui.",
        "panel.stop": "Parar de acompanhar {name}",
        "panel.remove": "Remover",
        "panel.userIdLabel": "ID de usuário a acompanhar",
        "panel.userIdPlaceholder": "ID de usuário",
        "panel.add": "Adicionar",
        "panel.recent": "Recentes",
        "panel.recent.some": "Desde que o Discord foi iniciado. Guardados apenas na memória.",
        "panel.recent.none": "Nenhum aviso ainda. Guardados apenas na memória.",
        "panel.clear": "Limpar",
    },
    ru: {
        "settings.watchAllFriends": "Следить за всеми друзьями",
        "settings.watchAllFriends.description": "Уведомлять о каждом друге, а не только о выбранных людях.",
        "settings.showToast": "Уведомление в приложении",
        "settings.showToast.description": "Всплывающее уведомление в верхней части Discord.",
        "settings.showDesktop": "Уведомление на рабочем столе",
        "settings.showDesktop.description": "Уведомление Windows, как у самого Discord. По клику открывается ЛС.",
        "settings.sound": "Звук",
        "settings.sound.description": "Один из звуков Discord.",
        "sound.none": "Без звука",
        "sound.message1": "Сообщение",
        "sound.message2": "Тихий сигнал",
        "sound.message3": "Звонок",
        "sound.mention1": "Упоминание",
        "sound.user_join": "Пользователь присоединился",
        "sound.stream_started": "Трансляция началась",
        "sound.success": "Успех",
        "settings.volume": "Громкость звука",
        "settings.volume.description": "В процентах.",
        "settings.alertInDnd": "Уведомлять даже в режиме «Не беспокоить»",
        "settings.alertInDnd.description": "Иначе ничего не показывается и не воспроизводится, пока у вас статус «Не беспокоить».",
        "settings.onOffline": "Когда они выходят из сети",
        "settings.onGame": "Когда они запускают игру",
        "settings.onStream": "Когда они начинают трансляцию",
        "settings.flapMinutes": "Игнорировать переподключения (минуты)",
        "settings.flapMinutes.description": "Если человек снова появился в сети вскоре после выхода, уведомления не будет. При значении 0 уведомляем каждый раз.",
        "settings.cooldownMinutes": "Пауза для каждого человека (минуты)",
        "settings.cooldownMinutes.description": "Не больше одного уведомления каждого вида на человека за это время. 0 отключает ограничение.",
        "menu.alerts": "Уведомления о появлении в сети",
        "menu.alerts.subtext": "Включены для всех друзей",
        "toast.on": "Уведомления о появлении в сети для {name} включены",
        "toast.off": "Уведомления о появлении в сети для {name} выключены",
        "alert.someone": "Кто-то",
        "alert.online": "в сети",
        "alert.online.text": "{name} в сети",
        "alert.onlineGame": "в сети, играет в {game}",
        "alert.onlineGame.text": "{name} в сети, играет в {game}",
        "alert.offline": "вышел(-ла) из сети",
        "alert.offline.text": "{name} вышел(-ла) из сети",
        "alert.game": "начал(а) играть в {game}",
        "alert.game.text": "{name} начал(а) играть в {game}",
        "alert.gameUnknown": "начал(а) играть в игру",
        "alert.gameUnknown.text": "{name} начал(а) играть в игру",
        "alert.stream": "начал(а) трансляцию",
        "alert.stream.text": "{name} начал(а) трансляцию",
        "alert.streamGame": "начал(а) трансляцию {game}",
        "alert.streamGame.text": "{name} начал(а) трансляцию {game}",
        "panel.watched": "Отслеживаемые люди",
        "panel.count": { one: "{count} человек.", few: "{count} человека.", many: "{count} человек.", other: "{count} человека." },
        "panel.countAll": { one: "{count} человек и все ваши друзья.", few: "{count} человека и все ваши друзья.", many: "{count} человек и все ваши друзья.", other: "{count} человека и все ваши друзья." },
        "panel.allFriends": "Все ваши друзья. Чтобы добавить кого-то ещё, нажмите на него правой кнопкой мыши и выберите «Уведомления о появлении в сети».",
        "panel.nobody": "Пока никого. Нажмите на кого-нибудь правой кнопкой мыши и выберите «Уведомления о появлении в сети» или добавьте ID пользователя здесь.",
        "panel.stop": "Перестать следить за {name}",
        "panel.remove": "Убрать",
        "panel.userIdLabel": "ID пользователя для отслеживания",
        "panel.userIdPlaceholder": "ID пользователя",
        "panel.add": "Добавить",
        "panel.recent": "Недавние",
        "panel.recent.some": "С момента запуска Discord. Хранятся только в памяти.",
        "panel.recent.none": "Уведомлений пока нет. Хранятся только в памяти.",
        "panel.clear": "Очистить",
    },
    tr: {
        "settings.watchAllFriends": "Tüm arkadaşları izle",
        "settings.watchAllFriends.description": "Yalnızca seçtiğin kişiler için değil, her arkadaş için bildirim gönder.",
        "settings.showToast": "Uygulama içi bildirim",
        "settings.showToast.description": "Discord'un üst kısmında çıkan bir bildirim.",
        "settings.showDesktop": "Masaüstü bildirimi",
        "settings.showDesktop.description": "Discord'un kendi bildirimleri gibi bir Windows bildirimi. Tıklayınca DM açılır.",
        "settings.sound": "Ses",
        "settings.sound.description": "Discord seslerinden biri.",
        "sound.none": "Ses yok",
        "sound.message1": "Mesaj",
        "sound.message2": "Hafif bip",
        "sound.message3": "Zil",
        "sound.mention1": "Bahsetme",
        "sound.user_join": "Kullanıcı katıldı",
        "sound.stream_started": "Yayın başladı",
        "sound.success": "Başarılı",
        "settings.volume": "Ses düzeyi",
        "settings.volume.description": "Yüzde olarak.",
        "settings.alertInDnd": "Rahatsız Etmeyin modunda da bildir",
        "settings.alertInDnd.description": "Aksi halde durumun Rahatsız Etmeyin iken hiçbir şey gösterilmez veya çalınmaz.",
        "settings.onOffline": "Çevrimdışı olduklarında",
        "settings.onGame": "Bir oyun oynamaya başladıklarında",
        "settings.onStream": "Yayın açtıklarında",
        "settings.flapMinutes": "Yeniden bağlanmaları yoksay (dakika)",
        "settings.flapMinutes.description": "Çevrimdışı olduktan kısa süre sonra tekrar çevrimiçi olmak bildirilmez. 0 olursa her seferinde bildirilir.",
        "settings.cooldownMinutes": "Kişi başına bekleme süresi (dakika)",
        "settings.cooldownMinutes.description": "Bu süre içinde kişi başına her türden en fazla bir bildirim gelir. 0 kapatır.",
        "menu.alerts": "Çevrimiçi Bildirimleri",
        "menu.alerts.subtext": "Tüm arkadaşlar için açık",
        "toast.on": "{name} için çevrimiçi bildirimleri açıldı",
        "toast.off": "{name} için çevrimiçi bildirimleri kapatıldı",
        "alert.someone": "Biri",
        "alert.online": "çevrimiçi oldu",
        "alert.online.text": "{name} çevrimiçi oldu",
        "alert.onlineGame": "çevrimiçi oldu, {game} oynuyor",
        "alert.onlineGame.text": "{name} çevrimiçi oldu, {game} oynuyor",
        "alert.offline": "çevrimdışı oldu",
        "alert.offline.text": "{name} çevrimdışı oldu",
        "alert.game": "{game} oynamaya başladı",
        "alert.game.text": "{name} {game} oynamaya başladı",
        "alert.gameUnknown": "bir oyun oynamaya başladı",
        "alert.gameUnknown.text": "{name} bir oyun oynamaya başladı",
        "alert.stream": "yayın açtı",
        "alert.stream.text": "{name} yayın açtı",
        "alert.streamGame": "{game} yayını açtı",
        "alert.streamGame.text": "{name} {game} yayını açtı",
        "panel.watched": "İzlenen kişiler",
        "panel.count": { other: "{count} kişi." },
        "panel.countAll": { other: "{count} kişi ve tüm arkadaşların." },
        "panel.allFriends": "Tüm arkadaşların. Başkalarını eklemek için onlara sağ tıkla ve Çevrimiçi Bildirimleri'ni seç.",
        "panel.nobody": "Henüz kimse yok. Birine sağ tıklayıp Çevrimiçi Bildirimleri'ni seç ya da buraya bir kullanıcı kimliği ekle.",
        "panel.stop": "{name} kişisini izlemeyi bırak",
        "panel.remove": "Kaldır",
        "panel.userIdLabel": "İzlenecek kullanıcı kimliği",
        "panel.userIdPlaceholder": "Kullanıcı kimliği",
        "panel.add": "Ekle",
        "panel.recent": "Son bildirimler",
        "panel.recent.some": "Discord açıldığından beri. Yalnızca bellekte tutulur.",
        "panel.recent.none": "Henüz bildirim yok. Yalnızca bellekte tutulur.",
        "panel.clear": "Temizle",
    },
});
