import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.showButton": "Chat bar button",
        "settings.showButton.description": "A button in the chat bar that opens your snippets.",
        "settings.commandAction": "/snip does",
        "settings.commandAction.description": "What /snip does with the snippet when you don't pick the send option.",
        "settings.commandAction.send": "Send it right away",
        "settings.commandAction.insert": "Put it in the message box to edit first",
        "toast.noBox": "Couldn't find the message box to put the snippet in",
        "toast.saved": "Saved \"{name}\". Use it with /snip or the snippets button.",
        "command.description": "Send one of your snippets, or put it in the message box",
        "command.name.choices": "The snippet",
        "command.name.free": "The snippet's name",
        "command.send": "On: send it right away. Off: put it in the message box to edit first.",
        "editor.name": "Name",
        "editor.text": "Text",
        "editor.namePlaceholder": "e.g. welcome",
        "editor.textPlaceholder": "Hi {user}, thanks for reaching out!",
        "editor.placeholders": "Placeholders",
        "editor.cancel": "Cancel",
        "editor.save": "Save",
        "editor.add": "Add snippet",
        "row.edit": "Edit",
        "row.delete": "Delete",
        "row.editLabel": "Edit {name}",
        "row.deleteLabel": "Delete {name}",
        "picker.editTitle": "Edit snippet",
        "picker.newTitle": "New snippet",
        "picker.search": "Search snippets",
        "picker.nameFirst": "Name your first snippet",
        "picker.new": "New",
        "picker.list": "Snippets",
        "picker.noMatch": "No snippet matches \"{query}\". Press Enter to create it.",
        "picker.empty": "Save replies you type often, then put them in the message box from here or with /snip.",
        "picker.hintChoose": "choose",
        "picker.hintInsert": "insert",
        "picker.hintClose": "close",
        "dialog.snippet": "Snippet",
        "dialog.saveTitle": "Save as snippet",
        "button.label": "Snippets",
        "panel.title": "Your snippets · {count}",
        "panel.new": "New snippet",
        "panel.empty": "No snippets yet. Add one here, from the chat bar button, or right-click a message and pick Save as Snippet.",
        "panel.placeholders": "Placeholders: {list}.",
        "panel.escape": "Type {code} to keep one as written.",
        "menu.save": "Save as Snippet",
        "ph.user": "The person you're replying to, or the other person in a DM",
        "ph.me": "Your own display name",
        "ph.channel": "The channel's name",
        "ph.server": "The server's name",
        "ph.date": "Today's date",
        "ph.time": "The current time",
        "ph.clipboard": "Whatever text you have copied",
        "err.nameEmpty": "Give it a name.",
        "err.nameLong": "Names can be up to {max} characters.",
        "err.nameTaken": "There's already a snippet called \"{name}\".",
        "err.textEmpty": "Write the text to insert.",
        "err.textLong": "Snippets can be up to {max} characters (this one is {length}).",
        "err.none": "You have no snippets yet. Add one from the snippets button in the chat bar, or right-click a message and pick Save as Snippet.",
        "err.which": "Which snippet? You have: {list}",
        "err.more": ", and {n} more",
        "err.noneCalledClose": "No snippet is called \"{value}\". Did you mean: {list}?",
        "err.noneCalled": "No snippet is called \"{value}\". You have: {list}",
    },
    de: {
        "settings.showButton": "Button in der Chatleiste",
        "settings.showButton.description": "Ein Button in der Chatleiste, der deine Textbausteine öffnet.",
        "settings.commandAction": "/snip macht",
        "settings.commandAction.description": "Was /snip mit dem Textbaustein macht, wenn du nicht die Sende-Option wählst.",
        "settings.commandAction.send": "Sofort senden",
        "settings.commandAction.insert": "Ins Nachrichtenfeld einfügen, um ihn vorher zu bearbeiten",
        "toast.noBox": "Das Nachrichtenfeld für den Textbaustein wurde nicht gefunden",
        "toast.saved": "„{name}“ gespeichert. Nutze ihn mit /snip oder dem Textbaustein-Button.",
        "command.description": "Einen deiner Textbausteine senden oder ins Nachrichtenfeld einfügen",
        "command.name.choices": "Der Textbaustein",
        "command.name.free": "Der Name des Textbausteins",
        "command.send": "An: sofort senden. Aus: ins Nachrichtenfeld einfügen, um ihn vorher zu bearbeiten.",
        "editor.name": "Name",
        "editor.text": "Text",
        "editor.namePlaceholder": "z. B. Begrüßung",
        "editor.textPlaceholder": "Hallo {user}, danke für deine Nachricht!",
        "editor.placeholders": "Platzhalter",
        "editor.cancel": "Abbrechen",
        "editor.save": "Speichern",
        "editor.add": "Textbaustein hinzufügen",
        "row.edit": "Bearbeiten",
        "row.delete": "Löschen",
        "row.editLabel": "{name} bearbeiten",
        "row.deleteLabel": "{name} löschen",
        "picker.editTitle": "Textbaustein bearbeiten",
        "picker.newTitle": "Neuer Textbaustein",
        "picker.search": "Textbausteine durchsuchen",
        "picker.nameFirst": "Gib deinem ersten Textbaustein einen Namen",
        "picker.new": "Neu",
        "picker.list": "Textbausteine",
        "picker.noMatch": "Kein Textbaustein passt zu „{query}“. Drücke die Eingabetaste, um ihn zu erstellen.",
        "picker.empty": "Speichere Antworten, die du oft schreibst, und füge sie von hier oder mit /snip ins Nachrichtenfeld ein.",
        "picker.hintChoose": "auswählen",
        "picker.hintInsert": "einfügen",
        "picker.hintClose": "schließen",
        "dialog.snippet": "Textbaustein",
        "dialog.saveTitle": "Als Textbaustein speichern",
        "button.label": "Textbausteine",
        "panel.title": "Deine Textbausteine · {count}",
        "panel.new": "Neuer Textbaustein",
        "panel.empty": "Noch keine Textbausteine. Füge hier einen hinzu, über den Button in der Chatleiste oder per Rechtsklick auf eine Nachricht und „Als Textbaustein speichern“.",
        "panel.placeholders": "Platzhalter: {list}.",
        "panel.escape": "Schreibe {code}, um einen so stehen zu lassen.",
        "menu.save": "Als Textbaustein speichern",
        "ph.user": "Die Person, der du antwortest, oder die andere Person in einer DM",
        "ph.me": "Dein eigener Anzeigename",
        "ph.channel": "Der Name des Kanals",
        "ph.server": "Der Name des Servers",
        "ph.date": "Das heutige Datum",
        "ph.time": "Die aktuelle Uhrzeit",
        "ph.clipboard": "Der Text, den du kopiert hast",
        "err.nameEmpty": "Gib ihm einen Namen.",
        "err.nameLong": "Namen dürfen bis zu {max} Zeichen lang sein.",
        "err.nameTaken": "Es gibt bereits einen Textbaustein namens „{name}“.",
        "err.textEmpty": "Schreibe den Text, der eingefügt werden soll.",
        "err.textLong": "Textbausteine dürfen bis zu {max} Zeichen lang sein (dieser hat {length}).",
        "err.none": "Du hast noch keine Textbausteine. Füge einen über den Button in der Chatleiste hinzu oder klicke mit rechts auf eine Nachricht und wähle „Als Textbaustein speichern“.",
        "err.which": "Welcher Textbaustein? Du hast: {list}",
        "err.more": " und {n} weitere",
        "err.noneCalledClose": "Es gibt keinen Textbaustein namens „{value}“. Meintest du: {list}?",
        "err.noneCalled": "Es gibt keinen Textbaustein namens „{value}“. Du hast: {list}",
    },
    es: {
        "settings.showButton": "Botón en la barra de chat",
        "settings.showButton.description": "Un botón en la barra de chat que abre tus respuestas rápidas.",
        "settings.commandAction": "Qué hace /snip",
        "settings.commandAction.description": "Lo que hace /snip con la respuesta rápida cuando no eliges la opción de enviar.",
        "settings.commandAction.send": "Enviarla de inmediato",
        "settings.commandAction.insert": "Ponerla en el cuadro de mensaje para editarla antes",
        "toast.noBox": "No se encontró el cuadro de mensaje donde poner la respuesta rápida",
        "toast.saved": "Se guardó «{name}». Úsala con /snip o con el botón de respuestas rápidas.",
        "command.description": "Envía una de tus respuestas rápidas o ponla en el cuadro de mensaje",
        "command.name.choices": "La respuesta rápida",
        "command.name.free": "El nombre de la respuesta rápida",
        "command.send": "Sí: enviarla de inmediato. No: ponerla en el cuadro de mensaje para editarla antes.",
        "editor.name": "Nombre",
        "editor.text": "Texto",
        "editor.namePlaceholder": "p. ej., bienvenida",
        "editor.textPlaceholder": "¡Hola {user}, gracias por escribirnos!",
        "editor.placeholders": "Marcadores",
        "editor.cancel": "Cancelar",
        "editor.save": "Guardar",
        "editor.add": "Añadir respuesta rápida",
        "row.edit": "Editar",
        "row.delete": "Eliminar",
        "row.editLabel": "Editar {name}",
        "row.deleteLabel": "Eliminar {name}",
        "picker.editTitle": "Editar respuesta rápida",
        "picker.newTitle": "Nueva respuesta rápida",
        "picker.search": "Buscar respuestas rápidas",
        "picker.nameFirst": "Ponle nombre a tu primera respuesta rápida",
        "picker.new": "Nueva",
        "picker.list": "Respuestas rápidas",
        "picker.noMatch": "Ninguna respuesta rápida coincide con «{query}». Pulsa Intro para crearla.",
        "picker.empty": "Guarda las respuestas que escribes a menudo y ponlas en el cuadro de mensaje desde aquí o con /snip.",
        "picker.hintChoose": "elegir",
        "picker.hintInsert": "insertar",
        "picker.hintClose": "cerrar",
        "dialog.snippet": "Respuesta rápida",
        "dialog.saveTitle": "Guardar como respuesta rápida",
        "button.label": "Respuestas rápidas",
        "panel.title": "Tus respuestas rápidas · {count}",
        "panel.new": "Nueva respuesta rápida",
        "panel.empty": "Aún no hay respuestas rápidas. Añade una aquí, desde el botón de la barra de chat, o haz clic derecho en un mensaje y elige Guardar como respuesta rápida.",
        "panel.placeholders": "Marcadores: {list}.",
        "panel.escape": "Escribe {code} para dejar uno tal cual.",
        "menu.save": "Guardar como respuesta rápida",
        "ph.user": "La persona a la que respondes, o la otra persona en un MD",
        "ph.me": "Tu propio nombre para mostrar",
        "ph.channel": "El nombre del canal",
        "ph.server": "El nombre del servidor",
        "ph.date": "La fecha de hoy",
        "ph.time": "La hora actual",
        "ph.clipboard": "El texto que tengas copiado",
        "err.nameEmpty": "Ponle un nombre.",
        "err.nameLong": "Los nombres pueden tener hasta {max} caracteres.",
        "err.nameTaken": "Ya hay una respuesta rápida llamada «{name}».",
        "err.textEmpty": "Escribe el texto que se va a insertar.",
        "err.textLong": "Las respuestas rápidas pueden tener hasta {max} caracteres (esta tiene {length}).",
        "err.none": "Todavía no tienes respuestas rápidas. Añade una desde el botón de la barra de chat, o haz clic derecho en un mensaje y elige Guardar como respuesta rápida.",
        "err.which": "¿Qué respuesta rápida? Tienes: {list}",
        "err.more": " y {n} más",
        "err.noneCalledClose": "Ninguna respuesta rápida se llama «{value}». ¿Querías decir: {list}?",
        "err.noneCalled": "Ninguna respuesta rápida se llama «{value}». Tienes: {list}",
    },
    fr: {
        "settings.showButton": "Bouton dans la barre de discussion",
        "settings.showButton.description": "Un bouton dans la barre de discussion qui ouvre tes réponses rapides.",
        "settings.commandAction": "Effet de /snip",
        "settings.commandAction.description": "Ce que /snip fait de la réponse rapide quand tu ne choisis pas l'option d'envoi.",
        "settings.commandAction.send": "L'envoyer tout de suite",
        "settings.commandAction.insert": "La mettre dans la zone de message pour la modifier d'abord",
        "toast.noBox": "Impossible de trouver la zone de message où placer la réponse rapide",
        "toast.saved": "« {name} » enregistrée. Utilise-la avec /snip ou le bouton des réponses rapides.",
        "command.description": "Envoie l'une de tes réponses rapides ou place-la dans la zone de message",
        "command.name.choices": "La réponse rapide",
        "command.name.free": "Le nom de la réponse rapide",
        "command.send": "Activé : l'envoyer tout de suite. Désactivé : la mettre dans la zone de message pour la modifier d'abord.",
        "editor.name": "Nom",
        "editor.text": "Texte",
        "editor.namePlaceholder": "p. ex. bienvenue",
        "editor.textPlaceholder": "Salut {user}, merci de nous avoir écrit !",
        "editor.placeholders": "Variables",
        "editor.cancel": "Annuler",
        "editor.save": "Enregistrer",
        "editor.add": "Ajouter la réponse rapide",
        "row.edit": "Modifier",
        "row.delete": "Supprimer",
        "row.editLabel": "Modifier {name}",
        "row.deleteLabel": "Supprimer {name}",
        "picker.editTitle": "Modifier la réponse rapide",
        "picker.newTitle": "Nouvelle réponse rapide",
        "picker.search": "Rechercher des réponses rapides",
        "picker.nameFirst": "Donne un nom à ta première réponse rapide",
        "picker.new": "Nouvelle",
        "picker.list": "Réponses rapides",
        "picker.noMatch": "Aucune réponse rapide ne correspond à « {query} ». Appuie sur Entrée pour la créer.",
        "picker.empty": "Enregistre les réponses que tu tapes souvent, puis place-les dans la zone de message depuis ici ou avec /snip.",
        "picker.hintChoose": "choisir",
        "picker.hintInsert": "insérer",
        "picker.hintClose": "fermer",
        "dialog.snippet": "Réponse rapide",
        "dialog.saveTitle": "Enregistrer comme réponse rapide",
        "button.label": "Réponses rapides",
        "panel.title": "Tes réponses rapides · {count}",
        "panel.new": "Nouvelle réponse rapide",
        "panel.empty": "Aucune réponse rapide pour l'instant. Ajoutes-en une ici, depuis le bouton de la barre de discussion, ou fais un clic droit sur un message et choisis Enregistrer comme réponse rapide.",
        "panel.placeholders": "Variables : {list}.",
        "panel.escape": "Tape {code} pour en garder une telle quelle.",
        "menu.save": "Enregistrer comme réponse rapide",
        "ph.user": "La personne à qui tu réponds, ou l'autre personne dans un MP",
        "ph.me": "Ton propre nom d'affichage",
        "ph.channel": "Le nom du salon",
        "ph.server": "Le nom du serveur",
        "ph.date": "La date du jour",
        "ph.time": "L'heure actuelle",
        "ph.clipboard": "Le texte que tu as copié",
        "err.nameEmpty": "Donne-lui un nom.",
        "err.nameLong": "Les noms peuvent contenir jusqu'à {max} caractères.",
        "err.nameTaken": "Il existe déjà une réponse rapide nommée « {name} ».",
        "err.textEmpty": "Écris le texte à insérer.",
        "err.textLong": "Les réponses rapides peuvent contenir jusqu'à {max} caractères (celle-ci en fait {length}).",
        "err.none": "Tu n'as pas encore de réponse rapide. Ajoutes-en une depuis le bouton de la barre de discussion, ou fais un clic droit sur un message et choisis Enregistrer comme réponse rapide.",
        "err.which": "Quelle réponse rapide ? Tu as : {list}",
        "err.more": " et {n} de plus",
        "err.noneCalledClose": "Aucune réponse rapide ne s'appelle « {value} ». Voulais-tu dire : {list} ?",
        "err.noneCalled": "Aucune réponse rapide ne s'appelle « {value} ». Tu as : {list}",
    },
    ja: {
        "settings.showButton": "チャットバーのボタン",
        "settings.showButton.description": "スニペットを開くボタンをチャットバーに表示します。",
        "settings.commandAction": "/snipの動作",
        "settings.commandAction.description": "送信オプションを選ばなかったときに、/snipがスニペットをどうするかを指定します。",
        "settings.commandAction.send": "すぐに送信する",
        "settings.commandAction.insert": "メッセージ欄に入れて先に編集する",
        "toast.noBox": "スニペットを入れるメッセージ欄が見つかりませんでした",
        "toast.saved": "「{name}」を保存しました。/snipまたはスニペットボタンから使えます。",
        "command.description": "保存したスニペットを送信するか、メッセージ欄に入れます",
        "command.name.choices": "スニペット",
        "command.name.free": "スニペットの名前",
        "command.send": "オン: すぐに送信します。オフ: メッセージ欄に入れて先に編集します。",
        "editor.name": "名前",
        "editor.text": "テキスト",
        "editor.namePlaceholder": "例: あいさつ",
        "editor.textPlaceholder": "{user}さん、ご連絡ありがとうございます!",
        "editor.placeholders": "プレースホルダー",
        "editor.cancel": "キャンセル",
        "editor.save": "保存",
        "editor.add": "スニペットを追加",
        "row.edit": "編集",
        "row.delete": "削除",
        "row.editLabel": "{name}を編集",
        "row.deleteLabel": "{name}を削除",
        "picker.editTitle": "スニペットを編集",
        "picker.newTitle": "新しいスニペット",
        "picker.search": "スニペットを検索",
        "picker.nameFirst": "最初のスニペットに名前を付けましょう",
        "picker.new": "新規",
        "picker.list": "スニペット",
        "picker.noMatch": "「{query}」に一致するスニペットはありません。Enterキーで作成できます。",
        "picker.empty": "よく入力する返信を保存して、ここから、または/snipでメッセージ欄に入れられます。",
        "picker.hintChoose": "選択",
        "picker.hintInsert": "挿入",
        "picker.hintClose": "閉じる",
        "dialog.snippet": "スニペット",
        "dialog.saveTitle": "スニペットとして保存",
        "button.label": "スニペット",
        "panel.title": "あなたのスニペット · {count}",
        "panel.new": "新しいスニペット",
        "panel.empty": "スニペットはまだありません。ここから、チャットバーのボタンから、またはメッセージを右クリックして「スニペットとして保存」を選んで追加できます。",
        "panel.placeholders": "プレースホルダー: {list}。",
        "panel.escape": "そのまま残したいときは {code} と入力します。",
        "menu.save": "スニペットとして保存",
        "ph.user": "返信先のユーザー、またはDMの相手",
        "ph.me": "あなた自身の表示名",
        "ph.channel": "チャンネル名",
        "ph.server": "サーバー名",
        "ph.date": "今日の日付",
        "ph.time": "現在の時刻",
        "ph.clipboard": "コピーしているテキスト",
        "err.nameEmpty": "名前を付けてください。",
        "err.nameLong": "名前は{max}文字までです。",
        "err.nameTaken": "「{name}」という名前のスニペットはすでにあります。",
        "err.textEmpty": "挿入するテキストを入力してください。",
        "err.textLong": "スニペットは{max}文字までです(このスニペットは{length}文字)。",
        "err.none": "スニペットはまだありません。チャットバーのスニペットボタンから追加するか、メッセージを右クリックして「スニペットとして保存」を選んでください。",
        "err.which": "どのスニペットですか? 保存済み: {list}",
        "err.more": "、ほか{n}件",
        "err.noneCalledClose": "「{value}」という名前のスニペットはありません。もしかして: {list}?",
        "err.noneCalled": "「{value}」という名前のスニペットはありません。保存済み: {list}",
    },
    pl: {
        "settings.showButton": "Przycisk na pasku czatu",
        "settings.showButton.description": "Przycisk na pasku czatu, który otwiera Twoje szybkie odpowiedzi.",
        "settings.commandAction": "Działanie /snip",
        "settings.commandAction.description": "Co /snip robi z szybką odpowiedzią, gdy nie wybierzesz opcji wysyłania.",
        "settings.commandAction.send": "Wyślij od razu",
        "settings.commandAction.insert": "Wstaw do pola wiadomości, aby najpierw ją edytować",
        "toast.noBox": "Nie znaleziono pola wiadomości, do którego można wstawić szybką odpowiedź",
        "toast.saved": "Zapisano „{name}”. Użyj jej poleceniem /snip lub przyciskiem szybkich odpowiedzi.",
        "command.description": "Wyślij jedną ze swoich szybkich odpowiedzi lub wstaw ją do pola wiadomości",
        "command.name.choices": "Szybka odpowiedź",
        "command.name.free": "Nazwa szybkiej odpowiedzi",
        "command.send": "Włączone: wyślij od razu. Wyłączone: wstaw do pola wiadomości, aby najpierw ją edytować.",
        "editor.name": "Nazwa",
        "editor.text": "Tekst",
        "editor.namePlaceholder": "np. powitanie",
        "editor.textPlaceholder": "Cześć {user}, dzięki za wiadomość!",
        "editor.placeholders": "Symbole zastępcze",
        "editor.cancel": "Anuluj",
        "editor.save": "Zapisz",
        "editor.add": "Dodaj szybką odpowiedź",
        "row.edit": "Edytuj",
        "row.delete": "Usuń",
        "row.editLabel": "Edytuj: {name}",
        "row.deleteLabel": "Usuń: {name}",
        "picker.editTitle": "Edytuj szybką odpowiedź",
        "picker.newTitle": "Nowa szybka odpowiedź",
        "picker.search": "Szukaj szybkich odpowiedzi",
        "picker.nameFirst": "Nazwij swoją pierwszą szybką odpowiedź",
        "picker.new": "Nowa",
        "picker.list": "Szybkie odpowiedzi",
        "picker.noMatch": "Żadna szybka odpowiedź nie pasuje do „{query}”. Naciśnij Enter, aby ją utworzyć.",
        "picker.empty": "Zapisz odpowiedzi, które często wpisujesz, a potem wstawiaj je do pola wiadomości stąd lub poleceniem /snip.",
        "picker.hintChoose": "wybierz",
        "picker.hintInsert": "wstaw",
        "picker.hintClose": "zamknij",
        "dialog.snippet": "Szybka odpowiedź",
        "dialog.saveTitle": "Zapisz jako szybką odpowiedź",
        "button.label": "Szybkie odpowiedzi",
        "panel.title": "Twoje szybkie odpowiedzi · {count}",
        "panel.new": "Nowa szybka odpowiedź",
        "panel.empty": "Nie ma jeszcze szybkich odpowiedzi. Dodaj jedną tutaj, przyciskiem na pasku czatu albo kliknij wiadomość prawym przyciskiem myszy i wybierz Zapisz jako szybką odpowiedź.",
        "panel.placeholders": "Symbole zastępcze: {list}.",
        "panel.escape": "Wpisz {code}, aby zostawić jeden w takiej postaci.",
        "menu.save": "Zapisz jako szybką odpowiedź",
        "ph.user": "Osoba, której odpowiadasz, lub druga osoba w wiadomości prywatnej",
        "ph.me": "Twoja własna wyświetlana nazwa",
        "ph.channel": "Nazwa kanału",
        "ph.server": "Nazwa serwera",
        "ph.date": "Dzisiejsza data",
        "ph.time": "Aktualna godzina",
        "ph.clipboard": "Tekst, który masz skopiowany",
        "err.nameEmpty": "Nadaj jej nazwę.",
        "err.nameLong": "Nazwy mogą mieć do {max} znaków.",
        "err.nameTaken": "Szybka odpowiedź o nazwie „{name}” już istnieje.",
        "err.textEmpty": "Wpisz tekst do wstawienia.",
        "err.textLong": "Szybkie odpowiedzi mogą mieć do {max} znaków (ta ma {length}).",
        "err.none": "Nie masz jeszcze szybkich odpowiedzi. Dodaj jedną przyciskiem na pasku czatu albo kliknij wiadomość prawym przyciskiem myszy i wybierz Zapisz jako szybką odpowiedź.",
        "err.which": "Która szybka odpowiedź? Masz: {list}",
        "err.more": " i {n} więcej",
        "err.noneCalledClose": "Żadna szybka odpowiedź nie nazywa się „{value}”. Chodziło o: {list}?",
        "err.noneCalled": "Żadna szybka odpowiedź nie nazywa się „{value}”. Masz: {list}",
    },
    "pt-BR": {
        "settings.showButton": "Botão na barra de chat",
        "settings.showButton.description": "Um botão na barra de chat que abre suas respostas rápidas.",
        "settings.commandAction": "O que o /snip faz",
        "settings.commandAction.description": "O que o /snip faz com a resposta rápida quando você não escolhe a opção de enviar.",
        "settings.commandAction.send": "Enviar na hora",
        "settings.commandAction.insert": "Colocar na caixa de mensagem para editar antes",
        "toast.noBox": "Não foi possível encontrar a caixa de mensagem para colocar a resposta rápida",
        "toast.saved": "\"{name}\" salva. Use com /snip ou com o botão de respostas rápidas.",
        "command.description": "Envie uma das suas respostas rápidas ou coloque-a na caixa de mensagem",
        "command.name.choices": "A resposta rápida",
        "command.name.free": "O nome da resposta rápida",
        "command.send": "Ligado: enviar na hora. Desligado: colocar na caixa de mensagem para editar antes.",
        "editor.name": "Nome",
        "editor.text": "Texto",
        "editor.namePlaceholder": "ex.: boas-vindas",
        "editor.textPlaceholder": "Oi {user}, obrigado por entrar em contato!",
        "editor.placeholders": "Marcadores",
        "editor.cancel": "Cancelar",
        "editor.save": "Salvar",
        "editor.add": "Adicionar resposta rápida",
        "row.edit": "Editar",
        "row.delete": "Excluir",
        "row.editLabel": "Editar {name}",
        "row.deleteLabel": "Excluir {name}",
        "picker.editTitle": "Editar resposta rápida",
        "picker.newTitle": "Nova resposta rápida",
        "picker.search": "Buscar respostas rápidas",
        "picker.nameFirst": "Dê um nome à sua primeira resposta rápida",
        "picker.new": "Nova",
        "picker.list": "Respostas rápidas",
        "picker.noMatch": "Nenhuma resposta rápida corresponde a \"{query}\". Pressione Enter para criá-la.",
        "picker.empty": "Salve as respostas que você digita com frequência e coloque-as na caixa de mensagem daqui ou com /snip.",
        "picker.hintChoose": "escolher",
        "picker.hintInsert": "inserir",
        "picker.hintClose": "fechar",
        "dialog.snippet": "Resposta rápida",
        "dialog.saveTitle": "Salvar como resposta rápida",
        "button.label": "Respostas rápidas",
        "panel.title": "Suas respostas rápidas · {count}",
        "panel.new": "Nova resposta rápida",
        "panel.empty": "Ainda não há respostas rápidas. Adicione uma aqui, pelo botão da barra de chat, ou clique com o botão direito em uma mensagem e escolha Salvar como resposta rápida.",
        "panel.placeholders": "Marcadores: {list}.",
        "panel.escape": "Digite {code} para manter um como está escrito.",
        "menu.save": "Salvar como resposta rápida",
        "ph.user": "A pessoa a quem você está respondendo, ou a outra pessoa em uma DM",
        "ph.me": "Seu próprio nome de exibição",
        "ph.channel": "O nome do canal",
        "ph.server": "O nome do servidor",
        "ph.date": "A data de hoje",
        "ph.time": "A hora atual",
        "ph.clipboard": "O texto que você copiou",
        "err.nameEmpty": "Dê um nome a ela.",
        "err.nameLong": "Os nomes podem ter até {max} caracteres.",
        "err.nameTaken": "Já existe uma resposta rápida chamada \"{name}\".",
        "err.textEmpty": "Escreva o texto a ser inserido.",
        "err.textLong": "As respostas rápidas podem ter até {max} caracteres (esta tem {length}).",
        "err.none": "Você ainda não tem respostas rápidas. Adicione uma pelo botão da barra de chat, ou clique com o botão direito em uma mensagem e escolha Salvar como resposta rápida.",
        "err.which": "Qual resposta rápida? Você tem: {list}",
        "err.more": " e mais {n}",
        "err.noneCalledClose": "Nenhuma resposta rápida se chama \"{value}\". Você quis dizer: {list}?",
        "err.noneCalled": "Nenhuma resposta rápida se chama \"{value}\". Você tem: {list}",
    },
    ru: {
        "settings.showButton": "Кнопка в панели чата",
        "settings.showButton.description": "Кнопка в панели чата, которая открывает ваши шаблоны.",
        "settings.commandAction": "Что делает /snip",
        "settings.commandAction.description": "Что /snip делает с шаблоном, если вы не выбрали вариант отправки.",
        "settings.commandAction.send": "Сразу отправить",
        "settings.commandAction.insert": "Вставить в поле сообщения, чтобы сначала отредактировать",
        "toast.noBox": "Не удалось найти поле сообщения, чтобы вставить шаблон",
        "toast.saved": "Шаблон «{name}» сохранён. Используйте его командой /snip или кнопкой шаблонов.",
        "command.description": "Отправить один из ваших шаблонов или вставить его в поле сообщения",
        "command.name.choices": "Шаблон",
        "command.name.free": "Название шаблона",
        "command.send": "Вкл.: сразу отправить. Выкл.: вставить в поле сообщения, чтобы сначала отредактировать.",
        "editor.name": "Название",
        "editor.text": "Текст",
        "editor.namePlaceholder": "например, приветствие",
        "editor.textPlaceholder": "Привет, {user}! Спасибо, что написал(а)!",
        "editor.placeholders": "Подстановки",
        "editor.cancel": "Отмена",
        "editor.save": "Сохранить",
        "editor.add": "Добавить шаблон",
        "row.edit": "Изменить",
        "row.delete": "Удалить",
        "row.editLabel": "Изменить: {name}",
        "row.deleteLabel": "Удалить: {name}",
        "picker.editTitle": "Изменить шаблон",
        "picker.newTitle": "Новый шаблон",
        "picker.search": "Поиск шаблонов",
        "picker.nameFirst": "Назовите свой первый шаблон",
        "picker.new": "Новый",
        "picker.list": "Шаблоны",
        "picker.noMatch": "Нет шаблонов, подходящих под «{query}». Нажмите Enter, чтобы создать его.",
        "picker.empty": "Сохраняйте ответы, которые часто набираете, и вставляйте их в поле сообщения отсюда или командой /snip.",
        "picker.hintChoose": "выбрать",
        "picker.hintInsert": "вставить",
        "picker.hintClose": "закрыть",
        "dialog.snippet": "Шаблон",
        "dialog.saveTitle": "Сохранить как шаблон",
        "button.label": "Шаблоны",
        "panel.title": "Ваши шаблоны · {count}",
        "panel.new": "Новый шаблон",
        "panel.empty": "Шаблонов пока нет. Добавьте его здесь, кнопкой в панели чата или нажмите на сообщение правой кнопкой мыши и выберите «Сохранить как шаблон».",
        "panel.placeholders": "Подстановки: {list}.",
        "panel.escape": "Введите {code}, чтобы оставить подстановку как есть.",
        "menu.save": "Сохранить как шаблон",
        "ph.user": "Человек, которому вы отвечаете, или собеседник в личных сообщениях",
        "ph.me": "Ваше отображаемое имя",
        "ph.channel": "Название канала",
        "ph.server": "Название сервера",
        "ph.date": "Сегодняшняя дата",
        "ph.time": "Текущее время",
        "ph.clipboard": "Скопированный вами текст",
        "err.nameEmpty": "Дайте ему название.",
        "err.nameLong": "Название может содержать до {max} символов.",
        "err.nameTaken": "Шаблон с названием «{name}» уже есть.",
        "err.textEmpty": "Введите текст для вставки.",
        "err.textLong": "Шаблон может содержать до {max} символов (в этом {length}).",
        "err.none": "У вас пока нет шаблонов. Добавьте его кнопкой в панели чата или нажмите на сообщение правой кнопкой мыши и выберите «Сохранить как шаблон».",
        "err.which": "Какой шаблон? Доступны: {list}",
        "err.more": " и ещё {n}",
        "err.noneCalledClose": "Шаблона с названием «{value}» нет. Возможно, вы имели в виду: {list}?",
        "err.noneCalled": "Шаблона с названием «{value}» нет. Доступны: {list}",
    },
    tr: {
        "settings.showButton": "Sohbet çubuğu düğmesi",
        "settings.showButton.description": "Sohbet çubuğunda hazır yanıtlarını açan bir düğme.",
        "settings.commandAction": "/snip ne yapar",
        "settings.commandAction.description": "Gönderme seçeneğini seçmediğinde /snip'in hazır yanıtla ne yapacağı.",
        "settings.commandAction.send": "Hemen gönder",
        "settings.commandAction.insert": "Önce düzenlemek için mesaj kutusuna koy",
        "toast.noBox": "Hazır yanıtı koyacak mesaj kutusu bulunamadı",
        "toast.saved": "\"{name}\" kaydedildi. /snip ile veya hazır yanıtlar düğmesiyle kullan.",
        "command.description": "Hazır yanıtlarından birini gönder ya da mesaj kutusuna koy",
        "command.name.choices": "Hazır yanıt",
        "command.name.free": "Hazır yanıtın adı",
        "command.send": "Açık: hemen gönder. Kapalı: önce düzenlemek için mesaj kutusuna koy.",
        "editor.name": "Ad",
        "editor.text": "Metin",
        "editor.namePlaceholder": "örn. hoş geldin",
        "editor.textPlaceholder": "Merhaba {user}, yazdığın için teşekkürler!",
        "editor.placeholders": "Yer tutucular",
        "editor.cancel": "İptal",
        "editor.save": "Kaydet",
        "editor.add": "Hazır yanıt ekle",
        "row.edit": "Düzenle",
        "row.delete": "Sil",
        "row.editLabel": "{name} adlı yanıtı düzenle",
        "row.deleteLabel": "{name} adlı yanıtı sil",
        "picker.editTitle": "Hazır yanıtı düzenle",
        "picker.newTitle": "Yeni hazır yanıt",
        "picker.search": "Hazır yanıtlarda ara",
        "picker.nameFirst": "İlk hazır yanıtına bir ad ver",
        "picker.new": "Yeni",
        "picker.list": "Hazır yanıtlar",
        "picker.noMatch": "\"{query}\" ile eşleşen hazır yanıt yok. Oluşturmak için Enter'a bas.",
        "picker.empty": "Sık yazdığın yanıtları kaydet, sonra buradan veya /snip ile mesaj kutusuna koy.",
        "picker.hintChoose": "seç",
        "picker.hintInsert": "ekle",
        "picker.hintClose": "kapat",
        "dialog.snippet": "Hazır yanıt",
        "dialog.saveTitle": "Hazır yanıt olarak kaydet",
        "button.label": "Hazır yanıtlar",
        "panel.title": "Hazır yanıtların · {count}",
        "panel.new": "Yeni hazır yanıt",
        "panel.empty": "Henüz hazır yanıt yok. Buradan, sohbet çubuğu düğmesinden ekleyebilir ya da bir mesaja sağ tıklayıp Hazır yanıt olarak kaydet'i seçebilirsin.",
        "panel.placeholders": "Yer tutucular: {list}.",
        "panel.escape": "Birini yazıldığı gibi bırakmak için {code} yaz.",
        "menu.save": "Hazır yanıt olarak kaydet",
        "ph.user": "Yanıt verdiğin kişi ya da bir DM'deki diğer kişi",
        "ph.me": "Kendi görünen adın",
        "ph.channel": "Kanalın adı",
        "ph.server": "Sunucunun adı",
        "ph.date": "Bugünün tarihi",
        "ph.time": "Şu anki saat",
        "ph.clipboard": "Kopyaladığın metin",
        "err.nameEmpty": "Ona bir ad ver.",
        "err.nameLong": "Adlar en fazla {max} karakter olabilir.",
        "err.nameTaken": "\"{name}\" adında bir hazır yanıt zaten var.",
        "err.textEmpty": "Eklenecek metni yaz.",
        "err.textLong": "Hazır yanıtlar en fazla {max} karakter olabilir (bu {length} karakter).",
        "err.none": "Henüz hazır yanıtın yok. Sohbet çubuğundaki düğmeden ekle ya da bir mesaja sağ tıklayıp Hazır yanıt olarak kaydet'i seç.",
        "err.which": "Hangi hazır yanıt? Şunlar var: {list}",
        "err.more": " ve {n} tane daha",
        "err.noneCalledClose": "\"{value}\" adında hazır yanıt yok. Şunu mu demek istedin: {list}?",
        "err.noneCalled": "\"{value}\" adında hazır yanıt yok. Şunlar var: {list}",
    },
});
