import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.includeDms": "Include DMs",
        "settings.includeDms.description": "Also mark direct messages and group DMs as read.",
        "settings.showButton": "Server list button",
        "settings.showButton.description": "A button above your servers, shown while anything is unread.",
        "settings.contextMenu": "Server menu item",
        "settings.contextMenu.description": "\"Mark All Servers as Read\" when you right-click a server.",
        "error.stores": "Couldn't find Discord's read state stores",
        "error.failed": "Couldn't mark everything as read",
        "summary.none": "Nothing to mark: everything is already read",
        "summary.channels": { one: "{count} channel", other: "{count} channels" },
        "summary.servers": { one: "{count} server", other: "{count} servers" },
        "summary.done": "Marked {channels} as read",
        "summary.doneInServers": "Marked {channels} in {servers} as read",
        "button.label": { one: "Mark {count} channel as read", other: "Mark {count} channels as read" },
        "command.description": "Mark every server as read",
        "menu.markAll": "Mark All Servers as Read",
    },
    de: {
        "settings.includeDms": "Direktnachrichten einbeziehen",
        "settings.includeDms.description": "Markiert auch Direktnachrichten und Gruppenchats als gelesen.",
        "settings.showButton": "Button in der Serverliste",
        "settings.showButton.description": "Ein Button über deinen Servern, der erscheint, solange etwas ungelesen ist.",
        "settings.contextMenu": "Eintrag im Servermenü",
        "settings.contextMenu.description": "„Alle Server als gelesen markieren“, wenn du einen Server mit der rechten Maustaste anklickst.",
        "error.stores": "Discords Lesestatus-Speicher wurden nicht gefunden",
        "error.failed": "Es konnte nicht alles als gelesen markiert werden",
        "summary.none": "Nichts zu markieren: Alles ist bereits gelesen",
        "summary.channels": { one: "{count} Kanal", other: "{count} Kanäle" },
        "summary.servers": { one: "{count} Server", other: "{count} Servern" },
        "summary.done": "{channels} als gelesen markiert",
        "summary.doneInServers": "{channels} auf {servers} als gelesen markiert",
        "button.label": { one: "{count} Kanal als gelesen markieren", other: "{count} Kanäle als gelesen markieren" },
        "command.description": "Alle Server als gelesen markieren",
        "menu.markAll": "Alle Server als gelesen markieren",
    },
    es: {
        "settings.includeDms": "Incluir MD",
        "settings.includeDms.description": "También marca como leídos los mensajes directos y los grupos de MD.",
        "settings.showButton": "Botón en la lista de servidores",
        "settings.showButton.description": "Un botón sobre tus servidores, visible mientras haya algo sin leer.",
        "settings.contextMenu": "Opción en el menú del servidor",
        "settings.contextMenu.description": "«Marcar todos los servidores como leídos» al hacer clic derecho en un servidor.",
        "error.stores": "No se encontraron los almacenes de estado de lectura de Discord",
        "error.failed": "No se pudo marcar todo como leído",
        "summary.none": "Nada que marcar: todo ya está leído",
        "summary.channels": { one: "{count} canal", other: "{count} canales" },
        "summary.servers": { one: "{count} servidor", other: "{count} servidores" },
        "summary.done": "Se marcaron como leídos {channels}",
        "summary.doneInServers": "Se marcaron como leídos {channels} en {servers}",
        "button.label": { one: "Marcar {count} canal como leído", other: "Marcar {count} canales como leídos" },
        "command.description": "Marcar todos los servidores como leídos",
        "menu.markAll": "Marcar todos los servidores como leídos",
    },
    fr: {
        "settings.includeDms": "Inclure les MP",
        "settings.includeDms.description": "Marque aussi comme lus les messages privés et les groupes privés.",
        "settings.showButton": "Bouton dans la liste des serveurs",
        "settings.showButton.description": "Un bouton au-dessus de tes serveurs, affiché tant qu'il reste des messages non lus.",
        "settings.contextMenu": "Option du menu du serveur",
        "settings.contextMenu.description": "« Marquer tous les serveurs comme lus » quand tu fais un clic droit sur un serveur.",
        "error.stores": "Impossible de trouver les stores d'état de lecture de Discord",
        "error.failed": "Impossible de tout marquer comme lu",
        "summary.none": "Rien à marquer : tout est déjà lu",
        "summary.channels": { one: "{count} salon", other: "{count} salons" },
        "summary.servers": { one: "{count} serveur", other: "{count} serveurs" },
        "summary.done": "Marquage terminé : {channels}",
        "summary.doneInServers": "Marquage terminé : {channels} sur {servers}",
        "button.label": { one: "Marquer {count} salon comme lu", other: "Marquer {count} salons comme lus" },
        "command.description": "Marquer tous les serveurs comme lus",
        "menu.markAll": "Marquer tous les serveurs comme lus",
    },
    ja: {
        "settings.includeDms": "DM も含める",
        "settings.includeDms.description": "ダイレクトメッセージとグループ DM も既読にします。",
        "settings.showButton": "サーバーリストのボタン",
        "settings.showButton.description": "未読があるあいだ、サーバーの上にボタンを表示します。",
        "settings.contextMenu": "サーバーメニューの項目",
        "settings.contextMenu.description": "サーバーを右クリックしたときに「すべてのサーバーを既読にする」を表示します。",
        "error.stores": "Discord の既読状態ストアが見つかりませんでした",
        "error.failed": "すべてを既読にできませんでした",
        "summary.none": "既読にするものはありません。すべて既読です",
        "summary.channels": { other: "{count} 件のチャンネル" },
        "summary.servers": { other: "{count} 個のサーバー" },
        "summary.done": "{channels}を既読にしました",
        "summary.doneInServers": "{servers}の{channels}を既読にしました",
        "button.label": { other: "{count} 件のチャンネルを既読にする" },
        "command.description": "すべてのサーバーを既読にする",
        "menu.markAll": "すべてのサーバーを既読にする",
    },
    pl: {
        "settings.includeDms": "Uwzględnij wiadomości prywatne",
        "settings.includeDms.description": "Oznacza jako przeczytane także wiadomości prywatne i grupy prywatne.",
        "settings.showButton": "Przycisk na liście serwerów",
        "settings.showButton.description": "Przycisk nad serwerami, widoczny, dopóki coś jest nieprzeczytane.",
        "settings.contextMenu": "Pozycja w menu serwera",
        "settings.contextMenu.description": "„Oznacz wszystkie serwery jako przeczytane” po kliknięciu serwera prawym przyciskiem myszy.",
        "error.stores": "Nie znaleziono magazynów stanu odczytu Discorda",
        "error.failed": "Nie udało się oznaczyć wszystkiego jako przeczytane",
        "summary.none": "Nie ma czego oznaczać: wszystko jest już przeczytane",
        "summary.channels": { one: "{count} kanał", few: "{count} kanały", many: "{count} kanałów", other: "{count} kanału" },
        "summary.servers": { one: "{count} serwer", few: "{count} serwery", many: "{count} serwerów", other: "{count} serwera" },
        "summary.done": "Oznaczono jako przeczytane: {channels}",
        "summary.doneInServers": "Oznaczono jako przeczytane: {channels} ({servers})",
        "button.label": { one: "Oznacz {count} kanał jako przeczytany", few: "Oznacz {count} kanały jako przeczytane", many: "Oznacz {count} kanałów jako przeczytane", other: "Oznacz {count} kanału jako przeczytane" },
        "command.description": "Oznacz wszystkie serwery jako przeczytane",
        "menu.markAll": "Oznacz wszystkie serwery jako przeczytane",
    },
    "pt-BR": {
        "settings.includeDms": "Incluir DMs",
        "settings.includeDms.description": "Também marca como lidas as mensagens diretas e os grupos de DM.",
        "settings.showButton": "Botão na lista de servidores",
        "settings.showButton.description": "Um botão acima dos seus servidores, exibido enquanto houver algo não lido.",
        "settings.contextMenu": "Item no menu do servidor",
        "settings.contextMenu.description": "“Marcar todos os servidores como lidos” ao clicar com o botão direito em um servidor.",
        "error.stores": "Não foi possível encontrar os armazenamentos de leitura do Discord",
        "error.failed": "Não foi possível marcar tudo como lido",
        "summary.none": "Nada para marcar: tudo já foi lido",
        "summary.channels": { one: "{count} canal", other: "{count} canais" },
        "summary.servers": { one: "{count} servidor", other: "{count} servidores" },
        "summary.done": "Marcados como lidos: {channels}",
        "summary.doneInServers": "Marcados como lidos: {channels} em {servers}",
        "button.label": { one: "Marcar {count} canal como lido", other: "Marcar {count} canais como lidos" },
        "command.description": "Marcar todos os servidores como lidos",
        "menu.markAll": "Marcar todos os servidores como lidos",
    },
    ru: {
        "settings.includeDms": "Включить личные сообщения",
        "settings.includeDms.description": "Также отмечать прочитанными личные сообщения и групповые чаты.",
        "settings.showButton": "Кнопка в списке серверов",
        "settings.showButton.description": "Кнопка над серверами, которая появляется, пока есть непрочитанное.",
        "settings.contextMenu": "Пункт в меню сервера",
        "settings.contextMenu.description": "«Отметить все серверы прочитанными» при щелчке правой кнопкой мыши по серверу.",
        "error.stores": "Не удалось найти хранилища состояния прочтения Discord",
        "error.failed": "Не удалось отметить всё прочитанным",
        "summary.none": "Отмечать нечего: всё уже прочитано",
        "summary.channels": { one: "{count} канал", few: "{count} канала", many: "{count} каналов", other: "{count} канала" },
        "summary.servers": { one: "{count} сервер", few: "{count} сервера", many: "{count} серверов", other: "{count} сервера" },
        "summary.done": "Отмечено прочитанным: {channels}",
        "summary.doneInServers": "Отмечено прочитанным: {channels} ({servers})",
        "button.label": { one: "Отметить {count} канал прочитанным", few: "Отметить {count} канала прочитанными", many: "Отметить {count} каналов прочитанными", other: "Отметить {count} канала прочитанными" },
        "command.description": "Отметить все серверы прочитанными",
        "menu.markAll": "Отметить все серверы прочитанными",
    },
    tr: {
        "settings.includeDms": "DM'leri de dahil et",
        "settings.includeDms.description": "Direkt mesajları ve grup DM'lerini de okundu olarak işaretler.",
        "settings.showButton": "Sunucu listesi düğmesi",
        "settings.showButton.description": "Okunmamış bir şey olduğu sürece sunucularının üstünde görünen bir düğme.",
        "settings.contextMenu": "Sunucu menüsü öğesi",
        "settings.contextMenu.description": "Bir sunucuya sağ tıkladığında \"Tüm Sunucuları Okundu Olarak İşaretle\".",
        "error.stores": "Discord'un okuma durumu depoları bulunamadı",
        "error.failed": "Her şey okundu olarak işaretlenemedi",
        "summary.none": "İşaretlenecek bir şey yok: her şey zaten okundu",
        "summary.channels": { one: "{count} kanal", other: "{count} kanal" },
        "summary.servers": { one: "{count} sunucu", other: "{count} sunucu" },
        "summary.done": "{channels} okundu olarak işaretlendi",
        "summary.doneInServers": "{servers} içindeki {channels} okundu olarak işaretlendi",
        "button.label": { one: "{count} kanalı okundu olarak işaretle", other: "{count} kanalı okundu olarak işaretle" },
        "command.description": "Tüm sunucuları okundu olarak işaretle",
        "menu.markAll": "Tüm Sunucuları Okundu Olarak İşaretle",
    },
});
