import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "spoiler.show": "Show spoiler",
        "spoiler": "Spoiler",
        "versions": "Previous versions",
        "edited.from": "Edited from",
        "deleted": "Deleted",
        "summary.title": "Logged right now",
        "summary.text": "{deleted} deleted, {edited} edited. Kept in memory only.",
        "clear": "Clear logged messages",
        "clear.menu": "Clear Logged Messages",
        "count.deleted": "{count} deleted",
        "count.edited": "{count} edited",
        "count.sep": ", ",
        "cleared": "Cleared {counts}",
        "settings.keepDeleted": "Keep deleted messages",
        "settings.keepDeleted.description": "Deleted messages stay in the chat, tinted red and marked Deleted.",
        "settings.logEdits": "Keep edit history",
        "settings.logEdits.description": "Edited messages show what they said before, under the message.",
        "settings.ignoreOwnDeletes": "Ignore my own deletes",
        "settings.ignoreOwnDeletes.description": "Messages you delete yourself disappear as usual.",
        "settings.ignoreSelf": "Ignore my own messages",
        "settings.ignoreSelf.description": "Never log your messages, whoever deletes or edits them.",
        "settings.ignoreBots": "Ignore bots",
        "settings.ignoreBots.description": "Don't log messages from bots and apps.",
        "settings.saveMedia": "Keep deleted pictures, videos and files",
        "settings.saveMedia.description": "Saves the attachments in the channel you're looking at as they load (up to 25 MB each, in memory), so a deleted message still shows them.",
        "settings.limit": "Messages logged per channel",
        "settings.limit.description": "Past this, the oldest are forgotten, and deleted ones among them disappear for real.",
    },
    de: {
        "spoiler.show": "Spoiler anzeigen",
        "spoiler": "Spoiler",
        "versions": "Frühere Versionen",
        "edited.from": "Bearbeitet von",
        "deleted": "Gelöscht",
        "summary.title": "Aktuell protokolliert",
        "summary.text": "{deleted} gelöscht, {edited} bearbeitet. Nur im Arbeitsspeicher gehalten.",
        "clear": "Protokollierte Nachrichten löschen",
        "clear.menu": "Protokollierte Nachrichten löschen",
        "count.deleted": "{count} gelöscht",
        "count.edited": "{count} bearbeitet",
        "count.sep": ", ",
        "cleared": "Gelöscht: {counts}",
        "settings.keepDeleted": "Gelöschte Nachrichten behalten",
        "settings.keepDeleted.description": "Gelöschte Nachrichten bleiben im Chat, rot eingefärbt und als gelöscht markiert.",
        "settings.logEdits": "Bearbeitungsverlauf behalten",
        "settings.logEdits.description": "Bearbeitete Nachrichten zeigen unter der Nachricht, was vorher dort stand.",
        "settings.ignoreOwnDeletes": "Eigene Löschungen ignorieren",
        "settings.ignoreOwnDeletes.description": "Nachrichten, die du selbst löschst, verschwinden wie gewohnt.",
        "settings.ignoreSelf": "Eigene Nachrichten ignorieren",
        "settings.ignoreSelf.description": "Deine Nachrichten werden nie protokolliert, egal wer sie löscht oder bearbeitet.",
        "settings.ignoreBots": "Bots ignorieren",
        "settings.ignoreBots.description": "Nachrichten von Bots und Apps nicht protokollieren.",
        "settings.saveMedia": "Gelöschte Bilder, Videos und Dateien behalten",
        "settings.saveMedia.description": "Speichert die Anhänge im Kanal, den du gerade ansiehst, beim Laden (bis zu 25 MB pro Datei, im Arbeitsspeicher), damit eine gelöschte Nachricht sie weiterhin zeigt.",
        "settings.limit": "Protokollierte Nachrichten pro Kanal",
        "settings.limit.description": "Darüber hinaus werden die ältesten vergessen, und gelöschte darunter verschwinden endgültig.",
    },
    es: {
        "spoiler.show": "Mostrar spoiler",
        "spoiler": "Spoiler",
        "versions": "Versiones anteriores",
        "edited.from": "Editado desde",
        "deleted": "Eliminado",
        "summary.title": "Registrado ahora mismo",
        "summary.text": "{deleted} eliminados, {edited} editados. Solo se guardan en la memoria.",
        "clear": "Borrar mensajes registrados",
        "clear.menu": "Borrar mensajes registrados",
        "count.deleted": "{count} eliminados",
        "count.edited": "{count} editados",
        "count.sep": ", ",
        "cleared": "Borrados: {counts}",
        "settings.keepDeleted": "Conservar mensajes eliminados",
        "settings.keepDeleted.description": "Los mensajes eliminados se quedan en el chat, teñidos de rojo y marcados como eliminados.",
        "settings.logEdits": "Conservar historial de ediciones",
        "settings.logEdits.description": "Los mensajes editados muestran debajo lo que decían antes.",
        "settings.ignoreOwnDeletes": "Ignorar mis propios borrados",
        "settings.ignoreOwnDeletes.description": "Los mensajes que eliminas tú desaparecen como siempre.",
        "settings.ignoreSelf": "Ignorar mis propios mensajes",
        "settings.ignoreSelf.description": "Nunca registra tus mensajes, sin importar quién los elimine o edite.",
        "settings.ignoreBots": "Ignorar bots",
        "settings.ignoreBots.description": "No registra mensajes de bots ni de aplicaciones.",
        "settings.saveMedia": "Conservar imágenes, vídeos y archivos eliminados",
        "settings.saveMedia.description": "Guarda los archivos adjuntos del canal que estás viendo a medida que cargan (hasta 25 MB cada uno, en memoria), para que un mensaje eliminado los siga mostrando.",
        "settings.limit": "Mensajes registrados por canal",
        "settings.limit.description": "Pasado este número, se olvidan los más antiguos, y los eliminados entre ellos desaparecen de verdad.",
    },
    fr: {
        "spoiler.show": "Afficher le spoiler",
        "spoiler": "Spoiler",
        "versions": "Versions précédentes",
        "edited.from": "Modifié depuis",
        "deleted": "Supprimé",
        "summary.title": "Actuellement enregistré",
        "summary.text": "{deleted} supprimés, {edited} modifiés. Conservés en mémoire uniquement.",
        "clear": "Effacer les messages enregistrés",
        "clear.menu": "Effacer les messages enregistrés",
        "count.deleted": "{count} supprimés",
        "count.edited": "{count} modifiés",
        "count.sep": ", ",
        "cleared": "Effacés : {counts}",
        "settings.keepDeleted": "Garder les messages supprimés",
        "settings.keepDeleted.description": "Les messages supprimés restent dans la discussion, teintés de rouge et marqués comme supprimés.",
        "settings.logEdits": "Garder l'historique des modifications",
        "settings.logEdits.description": "Les messages modifiés affichent sous le message ce qu'ils disaient avant.",
        "settings.ignoreOwnDeletes": "Ignorer mes propres suppressions",
        "settings.ignoreOwnDeletes.description": "Les messages que tu supprimes toi-même disparaissent comme d'habitude.",
        "settings.ignoreSelf": "Ignorer mes propres messages",
        "settings.ignoreSelf.description": "N'enregistre jamais tes messages, peu importe qui les supprime ou les modifie.",
        "settings.ignoreBots": "Ignorer les bots",
        "settings.ignoreBots.description": "N'enregistre pas les messages des bots et des applications.",
        "settings.saveMedia": "Garder les images, vidéos et fichiers supprimés",
        "settings.saveMedia.description": "Enregistre les pièces jointes du salon que tu regardes au fur et à mesure de leur chargement (jusqu'à 25 Mo chacune, en mémoire), pour qu'un message supprimé les affiche toujours.",
        "settings.limit": "Messages enregistrés par salon",
        "settings.limit.description": "Au-delà, les plus anciens sont oubliés, et ceux qui ont été supprimés disparaissent pour de bon.",
    },
    ja: {
        "spoiler.show": "ネタバレを表示",
        "spoiler": "ネタバレ",
        "versions": "以前のバージョン",
        "edited.from": "編集前",
        "deleted": "削除済み",
        "summary.title": "現在の記録",
        "summary.text": "削除 {deleted} 件、編集 {edited} 件。メモリ上にのみ保持されます。",
        "clear": "記録したメッセージを消去",
        "clear.menu": "記録したメッセージを消去",
        "count.deleted": "削除 {count} 件",
        "count.edited": "編集 {count} 件",
        "count.sep": "、",
        "cleared": "消去しました: {counts}",
        "settings.keepDeleted": "削除されたメッセージを残す",
        "settings.keepDeleted.description": "削除されたメッセージはチャットに残り、赤く表示されて「削除済み」と表示されます。",
        "settings.logEdits": "編集履歴を残す",
        "settings.logEdits.description": "編集されたメッセージの下に、編集前の内容を表示します。",
        "settings.ignoreOwnDeletes": "自分で削除したものは無視",
        "settings.ignoreOwnDeletes.description": "自分で削除したメッセージは通常どおり消えます。",
        "settings.ignoreSelf": "自分のメッセージは無視",
        "settings.ignoreSelf.description": "誰が削除や編集をしても、自分のメッセージは記録しません。",
        "settings.ignoreBots": "ボットを無視",
        "settings.ignoreBots.description": "ボットやアプリのメッセージを記録しません。",
        "settings.saveMedia": "削除された画像、動画、ファイルを残す",
        "settings.saveMedia.description": "表示中のチャンネルの添付ファイルを読み込み時に保存し (1 件あたり最大 25 MB、メモリ上)、削除されたメッセージでも表示できるようにします。",
        "settings.limit": "チャンネルごとの記録メッセージ数",
        "settings.limit.description": "この数を超えると古いものから忘れられ、その中の削除済みメッセージは完全に消えます。",
    },
    pl: {
        "spoiler.show": "Pokaż spoiler",
        "spoiler": "Spoiler",
        "versions": "Poprzednie wersje",
        "edited.from": "Edytowano z",
        "deleted": "Usunięto",
        "summary.title": "Aktualnie zapisane",
        "summary.text": "Usunięte: {deleted}, edytowane: {edited}. Trzymane tylko w pamięci.",
        "clear": "Wyczyść zapisane wiadomości",
        "clear.menu": "Wyczyść zapisane wiadomości",
        "count.deleted": "usunięte: {count}",
        "count.edited": "edytowane: {count}",
        "count.sep": ", ",
        "cleared": "Wyczyszczono ({counts})",
        "settings.keepDeleted": "Zachowuj usunięte wiadomości",
        "settings.keepDeleted.description": "Usunięte wiadomości zostają na czacie, zabarwione na czerwono i oznaczone jako usunięte.",
        "settings.logEdits": "Zachowuj historię edycji",
        "settings.logEdits.description": "Edytowane wiadomości pokazują pod spodem, co było w nich wcześniej.",
        "settings.ignoreOwnDeletes": "Ignoruj moje usunięcia",
        "settings.ignoreOwnDeletes.description": "Wiadomości, które sam usuwasz, znikają jak zwykle.",
        "settings.ignoreSelf": "Ignoruj moje wiadomości",
        "settings.ignoreSelf.description": "Nigdy nie zapisuje Twoich wiadomości, niezależnie od tego, kto je usuwa lub edytuje.",
        "settings.ignoreBots": "Ignoruj boty",
        "settings.ignoreBots.description": "Nie zapisuj wiadomości od botów i aplikacji.",
        "settings.saveMedia": "Zachowuj usunięte zdjęcia, filmy i pliki",
        "settings.saveMedia.description": "Zapisuje załączniki z oglądanego kanału w trakcie ich ładowania (do 25 MB każdy, w pamięci), dzięki czemu usunięta wiadomość nadal je pokazuje.",
        "settings.limit": "Zapisane wiadomości na kanał",
        "settings.limit.description": "Po przekroczeniu tej liczby najstarsze są zapominane, a usunięte wśród nich znikają naprawdę.",
    },
    "pt-BR": {
        "spoiler.show": "Mostrar spoiler",
        "spoiler": "Spoiler",
        "versions": "Versões anteriores",
        "edited.from": "Editada de",
        "deleted": "Excluída",
        "summary.title": "Registrado agora",
        "summary.text": "{deleted} excluídas, {edited} editadas. Mantidas apenas na memória.",
        "clear": "Limpar mensagens registradas",
        "clear.menu": "Limpar mensagens registradas",
        "count.deleted": "{count} excluídas",
        "count.edited": "{count} editadas",
        "count.sep": ", ",
        "cleared": "Limpo: {counts}",
        "settings.keepDeleted": "Manter mensagens excluídas",
        "settings.keepDeleted.description": "As mensagens excluídas continuam no chat, em tom avermelhado e marcadas como excluídas.",
        "settings.logEdits": "Manter histórico de edições",
        "settings.logEdits.description": "As mensagens editadas mostram, abaixo delas, o que diziam antes.",
        "settings.ignoreOwnDeletes": "Ignorar minhas próprias exclusões",
        "settings.ignoreOwnDeletes.description": "As mensagens que você mesmo exclui somem normalmente.",
        "settings.ignoreSelf": "Ignorar minhas próprias mensagens",
        "settings.ignoreSelf.description": "Nunca registra suas mensagens, não importa quem as exclua ou edite.",
        "settings.ignoreBots": "Ignorar bots",
        "settings.ignoreBots.description": "Não registra mensagens de bots e apps.",
        "settings.saveMedia": "Manter imagens, vídeos e arquivos excluídos",
        "settings.saveMedia.description": "Salva os anexos do canal que você está vendo conforme carregam (até 25 MB cada, na memória), para que uma mensagem excluída ainda os mostre.",
        "settings.limit": "Mensagens registradas por canal",
        "settings.limit.description": "Depois disso, as mais antigas são esquecidas, e as excluídas entre elas somem de verdade.",
    },
    ru: {
        "spoiler.show": "Показать спойлер",
        "spoiler": "Спойлер",
        "versions": "Предыдущие версии",
        "edited.from": "Изменено с",
        "deleted": "Удалено",
        "summary.title": "Сейчас записано",
        "summary.text": "Удалено: {deleted}, изменено: {edited}. Хранится только в памяти.",
        "clear": "Очистить записанные сообщения",
        "clear.menu": "Очистить записанные сообщения",
        "count.deleted": "удалено: {count}",
        "count.edited": "изменено: {count}",
        "count.sep": ", ",
        "cleared": "Очищено ({counts})",
        "settings.keepDeleted": "Сохранять удалённые сообщения",
        "settings.keepDeleted.description": "Удалённые сообщения остаются в чате, подсвечены красным и помечены как удалённые.",
        "settings.logEdits": "Сохранять историю изменений",
        "settings.logEdits.description": "Под изменёнными сообщениями показано, что в них было раньше.",
        "settings.ignoreOwnDeletes": "Игнорировать мои удаления",
        "settings.ignoreOwnDeletes.description": "Сообщения, которые вы удаляете сами, исчезают как обычно.",
        "settings.ignoreSelf": "Игнорировать мои сообщения",
        "settings.ignoreSelf.description": "Ваши сообщения не записываются, кто бы их ни удалял и ни изменял.",
        "settings.ignoreBots": "Игнорировать ботов",
        "settings.ignoreBots.description": "Не записывать сообщения от ботов и приложений.",
        "settings.saveMedia": "Сохранять удалённые картинки, видео и файлы",
        "settings.saveMedia.description": "Сохраняет вложения в открытом канале по мере загрузки (до 25 МБ каждое, в памяти), чтобы удалённое сообщение по-прежнему их показывало.",
        "settings.limit": "Записанных сообщений на канал",
        "settings.limit.description": "Сверх этого самые старые забываются, а удалённые среди них исчезают по-настоящему.",
    },
    tr: {
        "spoiler.show": "Spoiler'ı göster",
        "spoiler": "Spoiler",
        "versions": "Önceki sürümler",
        "edited.from": "Şundan düzenlendi",
        "deleted": "Silindi",
        "summary.title": "Şu an kaydedilenler",
        "summary.text": "{deleted} silindi, {edited} düzenlendi. Yalnızca bellekte tutulur.",
        "clear": "Kaydedilen mesajları temizle",
        "clear.menu": "Kaydedilen Mesajları Temizle",
        "count.deleted": "{count} silindi",
        "count.edited": "{count} düzenlendi",
        "count.sep": ", ",
        "cleared": "Temizlendi: {counts}",
        "settings.keepDeleted": "Silinen mesajları koru",
        "settings.keepDeleted.description": "Silinen mesajlar sohbette kalır, kırmızıya boyanır ve silindi olarak işaretlenir.",
        "settings.logEdits": "Düzenleme geçmişini koru",
        "settings.logEdits.description": "Düzenlenen mesajlar, altında önceden ne yazdığını gösterir.",
        "settings.ignoreOwnDeletes": "Kendi sildiklerimi yok say",
        "settings.ignoreOwnDeletes.description": "Kendi sildiğin mesajlar her zamanki gibi kaybolur.",
        "settings.ignoreSelf": "Kendi mesajlarımı yok say",
        "settings.ignoreSelf.description": "Kim silerse ya da düzenlerse düzenlesin, mesajların hiç kaydedilmez.",
        "settings.ignoreBots": "Botları yok say",
        "settings.ignoreBots.description": "Botların ve uygulamaların mesajlarını kaydetme.",
        "settings.saveMedia": "Silinen resim, video ve dosyaları koru",
        "settings.saveMedia.description": "Baktığın kanaldaki ekleri yüklenirken kaydeder (her biri en fazla 25 MB, bellekte), böylece silinen bir mesaj bunları göstermeye devam eder.",
        "settings.limit": "Kanal başına kaydedilen mesaj",
        "settings.limit.description": "Bu sayıdan sonra en eskiler unutulur, aralarındaki silinenler de gerçekten kaybolur.",
    },
});
