import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "menu.root": "Voice Chat Utilities",
        "menu.disconnect": "Disconnect everyone",
        "menu.move": "Move everyone to",
        "menu.mute": "Server mute everyone",
        "menu.unmute": "Server unmute everyone",
        "menu.deafen": "Server deafen everyone",
        "menu.undeafen": "Server undeafen everyone",
        "confirm.disconnect.title": "Disconnect everyone?",
        "confirm.disconnect.body": "Everyone in {channel} ({count}) will be disconnected, you included if you're in it.",
        "confirm.disconnect.button": "Disconnect",
        "confirm.move.title": "Move everyone?",
        "confirm.move.body": "Everyone in {channel} ({count}) will be moved to {target}.",
        "confirm.move.button": "Move",
        "confirm.cancel": "Cancel",
        "toast.disconnect": "Disconnected {done} of {total}",
        "toast.move": "Moved {done} of {total} to {target}",
        "toast.mute": "Server muted {done} of {total}",
        "toast.unmute": "Unmuted {done} of {total}",
        "toast.deafen": "Server deafened {done} of {total}",
        "toast.undeafen": "Undeafened {done} of {total}",
        "toast.failedHint": "The rest didn't work: they may have left, or have a higher role than you.",
        "toast.busy": "Still working on the last one",
    },
    de: {
        "menu.root": "Sprachchat-Werkzeuge",
        "menu.disconnect": "Alle trennen",
        "menu.move": "Alle verschieben nach",
        "menu.mute": "Alle serverweit stummschalten",
        "menu.unmute": "Serverweite Stummschaltung für alle aufheben",
        "menu.deafen": "Ton für alle serverweit ausschalten",
        "menu.undeafen": "Ton für alle serverweit einschalten",
        "confirm.disconnect.title": "Alle trennen?",
        "confirm.disconnect.body": "Alle in {channel} ({count}) werden getrennt, auch du, wenn du drin bist.",
        "confirm.disconnect.button": "Trennen",
        "confirm.move.title": "Alle verschieben?",
        "confirm.move.body": "Alle in {channel} ({count}) werden nach {target} verschoben.",
        "confirm.move.button": "Verschieben",
        "confirm.cancel": "Abbrechen",
        "toast.disconnect": "{done} von {total} getrennt",
        "toast.move": "{done} von {total} nach {target} verschoben",
        "toast.mute": "{done} von {total} serverweit stummgeschaltet",
        "toast.unmute": "Stummschaltung bei {done} von {total} aufgehoben",
        "toast.deafen": "Ton bei {done} von {total} serverweit ausgeschaltet",
        "toast.undeafen": "Ton bei {done} von {total} wieder eingeschaltet",
        "toast.failedHint": "Beim Rest hat es nicht geklappt: Sie sind vielleicht gegangen oder haben eine höhere Rolle als du.",
        "toast.busy": "Die letzte Aktion läuft noch",
    },
    es: {
        "menu.root": "Utilidades de chat de voz",
        "menu.disconnect": "Desconectar a todos",
        "menu.move": "Mover a todos a",
        "menu.mute": "Silenciar a todos en el servidor",
        "menu.unmute": "Quitar el silencio a todos",
        "menu.deafen": "Ensordecer a todos en el servidor",
        "menu.undeafen": "Quitar el ensordecido a todos",
        "confirm.disconnect.title": "¿Desconectar a todos?",
        "confirm.disconnect.body": "Todos en {channel} ({count}) serán desconectados, tú incluido si estás dentro.",
        "confirm.disconnect.button": "Desconectar",
        "confirm.move.title": "¿Mover a todos?",
        "confirm.move.body": "Todos en {channel} ({count}) serán movidos a {target}.",
        "confirm.move.button": "Mover",
        "confirm.cancel": "Cancelar",
        "toast.disconnect": "Desconectados {done} de {total}",
        "toast.move": "Movidos {done} de {total} a {target}",
        "toast.mute": "Silenciados {done} de {total}",
        "toast.unmute": "Sin silencio {done} de {total}",
        "toast.deafen": "Ensordecidos {done} de {total}",
        "toast.undeafen": "Sin ensordecer {done} de {total}",
        "toast.failedHint": "Con el resto no funcionó: puede que se hayan ido o tengan un rol más alto que el tuyo.",
        "toast.busy": "Todavía se está haciendo lo anterior",
    },
    fr: {
        "menu.root": "Outils de salon vocal",
        "menu.disconnect": "Déconnecter tout le monde",
        "menu.move": "Déplacer tout le monde vers",
        "menu.mute": "Rendre tout le monde muet sur le serveur",
        "menu.unmute": "Rétablir le micro de tout le monde",
        "menu.deafen": "Mettre tout le monde en sourdine sur le serveur",
        "menu.undeafen": "Retirer la sourdine de tout le monde",
        "confirm.disconnect.title": "Déconnecter tout le monde ?",
        "confirm.disconnect.body": "Tout le monde dans {channel} ({count}) sera déconnecté, toi compris si tu y es.",
        "confirm.disconnect.button": "Déconnecter",
        "confirm.move.title": "Déplacer tout le monde ?",
        "confirm.move.body": "Tout le monde dans {channel} ({count}) sera déplacé vers {target}.",
        "confirm.move.button": "Déplacer",
        "confirm.cancel": "Annuler",
        "toast.disconnect": "{done} sur {total} déconnectés",
        "toast.move": "{done} sur {total} déplacés vers {target}",
        "toast.mute": "{done} sur {total} rendus muets",
        "toast.unmute": "Micro rétabli pour {done} sur {total}",
        "toast.deafen": "{done} sur {total} mis en sourdine",
        "toast.undeafen": "Sourdine retirée pour {done} sur {total}",
        "toast.failedHint": "Pour les autres, ça n'a pas marché : ils sont peut-être partis ou ont un rôle plus haut que le tien.",
        "toast.busy": "La dernière action est encore en cours",
    },
    ja: {
        "menu.root": "ボイスチャットツール",
        "menu.disconnect": "全員を切断",
        "menu.move": "全員を移動",
        "menu.mute": "全員をサーバーミュート",
        "menu.unmute": "全員のサーバーミュートを解除",
        "menu.deafen": "全員をサーバースピーカーミュート",
        "menu.undeafen": "全員のサーバースピーカーミュートを解除",
        "confirm.disconnect.title": "全員を切断しますか？",
        "confirm.disconnect.body": "{channel} にいる全員（{count}人）を切断します。あなたがいる場合はあなたも切断されます。",
        "confirm.disconnect.button": "切断",
        "confirm.move.title": "全員を移動しますか？",
        "confirm.move.body": "{channel} にいる全員（{count}人）を {target} に移動します。",
        "confirm.move.button": "移動",
        "confirm.cancel": "キャンセル",
        "toast.disconnect": "{total}人中{done}人を切断しました",
        "toast.move": "{total}人中{done}人を {target} に移動しました",
        "toast.mute": "{total}人中{done}人をサーバーミュートしました",
        "toast.unmute": "{total}人中{done}人のミュートを解除しました",
        "toast.deafen": "{total}人中{done}人をサーバースピーカーミュートしました",
        "toast.undeafen": "{total}人中{done}人のスピーカーミュートを解除しました",
        "toast.failedHint": "残りはできませんでした。退出したか、あなたより上のロールを持っている可能性があります。",
        "toast.busy": "前の操作がまだ実行中です",
    },
    pl: {
        "menu.root": "Narzędzia czatu głosowego",
        "menu.disconnect": "Rozłącz wszystkich",
        "menu.move": "Przenieś wszystkich do",
        "menu.mute": "Wycisz wszystkich na serwerze",
        "menu.unmute": "Cofnij wyciszenie wszystkich",
        "menu.deafen": "Wyłącz dźwięk wszystkim na serwerze",
        "menu.undeafen": "Włącz dźwięk wszystkim",
        "confirm.disconnect.title": "Rozłączyć wszystkich?",
        "confirm.disconnect.body": "Wszyscy na {channel} ({count}) zostaną rozłączeni, ty też, jeśli tam jesteś.",
        "confirm.disconnect.button": "Rozłącz",
        "confirm.move.title": "Przenieść wszystkich?",
        "confirm.move.body": "Wszyscy na {channel} ({count}) zostaną przeniesieni do {target}.",
        "confirm.move.button": "Przenieś",
        "confirm.cancel": "Anuluj",
        "toast.disconnect": "Rozłączono {done} z {total}",
        "toast.move": "Przeniesiono {done} z {total} do {target}",
        "toast.mute": "Wyciszono {done} z {total}",
        "toast.unmute": "Cofnięto wyciszenie {done} z {total}",
        "toast.deafen": "Wyłączono dźwięk {done} z {total}",
        "toast.undeafen": "Włączono dźwięk {done} z {total}",
        "toast.failedHint": "U reszty się nie udało: mogli wyjść albo mają wyższą rolę niż ty.",
        "toast.busy": "Poprzednia akcja jeszcze trwa",
    },
    "pt-BR": {
        "menu.root": "Utilitários de chat de voz",
        "menu.disconnect": "Desconectar todos",
        "menu.move": "Mover todos para",
        "menu.mute": "Silenciar todos no servidor",
        "menu.unmute": "Tirar o silêncio de todos",
        "menu.deafen": "Ensurdecer todos no servidor",
        "menu.undeafen": "Tirar o ensurdecer de todos",
        "confirm.disconnect.title": "Desconectar todos?",
        "confirm.disconnect.body": "Todos em {channel} ({count}) serão desconectados, inclusive você se estiver lá.",
        "confirm.disconnect.button": "Desconectar",
        "confirm.move.title": "Mover todos?",
        "confirm.move.body": "Todos em {channel} ({count}) serão movidos para {target}.",
        "confirm.move.button": "Mover",
        "confirm.cancel": "Cancelar",
        "toast.disconnect": "{done} de {total} desconectados",
        "toast.move": "{done} de {total} movidos para {target}",
        "toast.mute": "{done} de {total} silenciados",
        "toast.unmute": "Silêncio tirado de {done} de {total}",
        "toast.deafen": "{done} de {total} ensurdecidos",
        "toast.undeafen": "Ensurdecer tirado de {done} de {total}",
        "toast.failedHint": "Com o resto não deu: talvez tenham saído ou tenham um cargo mais alto que o seu.",
        "toast.busy": "A última ação ainda está em andamento",
    },
    ru: {
        "menu.root": "Инструменты голосового чата",
        "menu.disconnect": "Отключить всех",
        "menu.move": "Переместить всех в",
        "menu.mute": "Заглушить всех на сервере",
        "menu.unmute": "Снять заглушение со всех",
        "menu.deafen": "Отключить звук всем на сервере",
        "menu.undeafen": "Вернуть звук всем",
        "confirm.disconnect.title": "Отключить всех?",
        "confirm.disconnect.body": "Все в {channel} ({count}) будут отключены, включая вас, если вы там.",
        "confirm.disconnect.button": "Отключить",
        "confirm.move.title": "Переместить всех?",
        "confirm.move.body": "Все в {channel} ({count}) будут перемещены в {target}.",
        "confirm.move.button": "Переместить",
        "confirm.cancel": "Отмена",
        "toast.disconnect": "Отключено: {done} из {total}",
        "toast.move": "Перемещено в {target}: {done} из {total}",
        "toast.mute": "Заглушено: {done} из {total}",
        "toast.unmute": "Заглушение снято: {done} из {total}",
        "toast.deafen": "Звук отключён: {done} из {total}",
        "toast.undeafen": "Звук возвращён: {done} из {total}",
        "toast.failedHint": "С остальными не получилось: возможно, они вышли или их роль выше вашей.",
        "toast.busy": "Предыдущее действие ещё выполняется",
    },
    tr: {
        "menu.root": "Sesli Sohbet Araçları",
        "menu.disconnect": "Herkesin bağlantısını kes",
        "menu.move": "Herkesi şuraya taşı",
        "menu.mute": "Herkesi sunucuda sustur",
        "menu.unmute": "Herkesin susturmasını kaldır",
        "menu.deafen": "Herkesin sesini sunucuda kapat",
        "menu.undeafen": "Herkesin sesini aç",
        "confirm.disconnect.title": "Herkesin bağlantısı kesilsin mi?",
        "confirm.disconnect.body": "{channel} kanalındaki herkesin ({count}) bağlantısı kesilecek, oradaysan seninki de.",
        "confirm.disconnect.button": "Bağlantıyı kes",
        "confirm.move.title": "Herkes taşınsın mı?",
        "confirm.move.body": "{channel} kanalındaki herkes ({count}) {target} kanalına taşınacak.",
        "confirm.move.button": "Taşı",
        "confirm.cancel": "İptal",
        "toast.disconnect": "{total} kişiden {done} kişinin bağlantısı kesildi",
        "toast.move": "{total} kişiden {done} kişi {target} kanalına taşındı",
        "toast.mute": "{total} kişiden {done} kişi susturuldu",
        "toast.unmute": "{total} kişiden {done} kişinin susturması kaldırıldı",
        "toast.deafen": "{total} kişiden {done} kişinin sesi kapatıldı",
        "toast.undeafen": "{total} kişiden {done} kişinin sesi açıldı",
        "toast.failedHint": "Kalanlarda olmadı: ayrılmış olabilirler ya da rolleri seninkinden yüksek olabilir.",
        "toast.busy": "Son işlem hâlâ sürüyor",
    },
});
