import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.currency": "Your currency",
        "settings.currency.description": "Prices show in this currency. Rates come from the European Central Bank (through Frankfurter) and ExchangeRate-API, refreshed every 12 hours.",
        "settings.currency.auto": "Auto ({currency})",
        "settings.units": "Your units",
        "settings.units.description": "Auto follows your region: miles and pounds in the US, metres and kilograms elsewhere.",
        "settings.units.auto": "Auto",
        "settings.units.metric": "Metric (km, kg, °C)",
        "settings.units.imperial": "Imperial (mi, lb, °F)",
        "settings.money": "Prices",
        "settings.money.description": "Underline amounts in other currencies, like $20 or 50 TL.",
        "settings.measures": "Measurements",
        "settings.measures.description": "Underline lengths, weights, temperatures, speeds and volumes in the other system.",
        "settings.times": "Times",
        "settings.times.description": "Underline times with a zone, like 3pm EST, and show them in your time zone.",
        "time.yours": "{time} your time",
        "time.yoursDay": "{time} {day}, your time",
    },
    de: {
        "settings.currency": "Deine Währung",
        "settings.currency.description": "Preise erscheinen in dieser Währung. Die Kurse kommen von der Europäischen Zentralbank (über Frankfurter) und von ExchangeRate-API und werden alle 12 Stunden aktualisiert.",
        "settings.currency.auto": "Automatisch ({currency})",
        "settings.units": "Deine Einheiten",
        "settings.units.description": "Automatisch folgt deiner Region: Meilen und Pfund in den USA, Meter und Kilogramm überall sonst.",
        "settings.units.auto": "Automatisch",
        "settings.units.metric": "Metrisch (km, kg, °C)",
        "settings.units.imperial": "Imperial (mi, lb, °F)",
        "settings.money": "Preise",
        "settings.money.description": "Beträge in anderen Währungen unterstreichen, etwa $20 oder 50 TL.",
        "settings.measures": "Maße",
        "settings.measures.description": "Längen, Gewichte, Temperaturen, Geschwindigkeiten und Volumen im anderen System unterstreichen.",
        "settings.times": "Uhrzeiten",
        "settings.times.description": "Uhrzeiten mit Zeitzone wie 3pm EST unterstreichen und in deiner Zeitzone zeigen.",
        "time.yours": "{time} bei dir",
        "time.yoursDay": "{time} {day}, bei dir",
    },
    es: {
        "settings.currency": "Tu moneda",
        "settings.currency.description": "Los precios se muestran en esta moneda. Los tipos de cambio vienen del Banco Central Europeo (a través de Frankfurter) y de ExchangeRate-API, y se actualizan cada 12 horas.",
        "settings.currency.auto": "Automática ({currency})",
        "settings.units": "Tus unidades",
        "settings.units.description": "Automático sigue tu región: millas y libras en EE. UU., metros y kilos en el resto.",
        "settings.units.auto": "Automático",
        "settings.units.metric": "Métrico (km, kg, °C)",
        "settings.units.imperial": "Imperial (mi, lb, °F)",
        "settings.money": "Precios",
        "settings.money.description": "Subraya importes en otras monedas, como $20 o 50 TL.",
        "settings.measures": "Medidas",
        "settings.measures.description": "Subraya longitudes, pesos, temperaturas, velocidades y volúmenes del otro sistema.",
        "settings.times": "Horas",
        "settings.times.description": "Subraya horas con zona horaria, como 3pm EST, y las muestra en tu zona.",
        "time.yours": "{time} en tu hora",
        "time.yoursDay": "{time} {day}, en tu hora",
    },
    fr: {
        "settings.currency": "Ta devise",
        "settings.currency.description": "Les prix s'affichent dans cette devise. Les taux viennent de la Banque centrale européenne (via Frankfurter) et d'ExchangeRate-API, mis à jour toutes les 12 heures.",
        "settings.currency.auto": "Automatique ({currency})",
        "settings.units": "Tes unités",
        "settings.units.description": "Automatique suit ta région : miles et livres aux États-Unis, mètres et kilos ailleurs.",
        "settings.units.auto": "Automatique",
        "settings.units.metric": "Métrique (km, kg, °C)",
        "settings.units.imperial": "Impérial (mi, lb, °F)",
        "settings.money": "Prix",
        "settings.money.description": "Souligne les montants dans d'autres devises, comme $20 ou 50 TL.",
        "settings.measures": "Mesures",
        "settings.measures.description": "Souligne les longueurs, poids, températures, vitesses et volumes de l'autre système.",
        "settings.times": "Heures",
        "settings.times.description": "Souligne les heures avec un fuseau, comme 3pm EST, et les montre dans ton fuseau.",
        "time.yours": "{time} chez toi",
        "time.yoursDay": "{time} {day}, chez toi",
    },
    ja: {
        "settings.currency": "あなたの通貨",
        "settings.currency.description": "価格をこの通貨で表示します。レートは欧州中央銀行(Frankfurter経由)とExchangeRate-APIから取得し、12時間ごとに更新します。",
        "settings.currency.auto": "自動({currency})",
        "settings.units": "あなたの単位",
        "settings.units.description": "自動では地域に合わせます。アメリカではマイルとポンド、それ以外ではメートルとキログラムです。",
        "settings.units.auto": "自動",
        "settings.units.metric": "メートル法(km、kg、°C)",
        "settings.units.imperial": "ヤード・ポンド法(mi、lb、°F)",
        "settings.money": "価格",
        "settings.money.description": "$20や50 TLのような、ほかの通貨の金額に下線を引きます。",
        "settings.measures": "単位",
        "settings.measures.description": "もう一方の単位系の長さ、重さ、温度、速度、容量に下線を引きます。",
        "settings.times": "時刻",
        "settings.times.description": "3pm ESTのようなタイムゾーン付きの時刻に下線を引き、あなたのタイムゾーンで表示します。",
        "time.yours": "あなたの時刻で{time}",
        "time.yoursDay": "あなたの時刻で{day} {time}",
    },
    pl: {
        "settings.currency": "Twoja waluta",
        "settings.currency.description": "Ceny pokazują się w tej walucie. Kursy pochodzą z Europejskiego Banku Centralnego (przez Frankfurter) i z ExchangeRate-API, odświeżane co 12 godzin.",
        "settings.currency.auto": "Automatycznie ({currency})",
        "settings.units": "Twoje jednostki",
        "settings.units.description": "Automatycznie według regionu: mile i funty w USA, metry i kilogramy gdzie indziej.",
        "settings.units.auto": "Automatycznie",
        "settings.units.metric": "Metryczne (km, kg, °C)",
        "settings.units.imperial": "Imperialne (mi, lb, °F)",
        "settings.money": "Ceny",
        "settings.money.description": "Podkreśla kwoty w innych walutach, np. $20 albo 50 TL.",
        "settings.measures": "Miary",
        "settings.measures.description": "Podkreśla długości, wagi, temperatury, prędkości i objętości w drugim systemie.",
        "settings.times": "Godziny",
        "settings.times.description": "Podkreśla godziny ze strefą czasową, np. 3pm EST, i pokazuje je w twojej strefie.",
        "time.yours": "{time} u ciebie",
        "time.yoursDay": "{time} {day}, u ciebie",
    },
    "pt-BR": {
        "settings.currency": "Sua moeda",
        "settings.currency.description": "Os preços aparecem nesta moeda. As cotações vêm do Banco Central Europeu (pelo Frankfurter) e da ExchangeRate-API, atualizadas a cada 12 horas.",
        "settings.currency.auto": "Automática ({currency})",
        "settings.units": "Suas unidades",
        "settings.units.description": "Automático segue sua região: milhas e libras nos EUA, metros e quilos no resto.",
        "settings.units.auto": "Automático",
        "settings.units.metric": "Métrico (km, kg, °C)",
        "settings.units.imperial": "Imperial (mi, lb, °F)",
        "settings.money": "Preços",
        "settings.money.description": "Sublinha valores em outras moedas, como $20 ou 50 TL.",
        "settings.measures": "Medidas",
        "settings.measures.description": "Sublinha comprimentos, pesos, temperaturas, velocidades e volumes do outro sistema.",
        "settings.times": "Horários",
        "settings.times.description": "Sublinha horários com fuso, como 3pm EST, e mostra no seu fuso horário.",
        "time.yours": "{time} no seu horário",
        "time.yoursDay": "{time} {day}, no seu horário",
    },
    ru: {
        "settings.currency": "Ваша валюта",
        "settings.currency.description": "Цены показываются в этой валюте. Курсы берутся у Европейского центрального банка (через Frankfurter) и у ExchangeRate-API и обновляются каждые 12 часов.",
        "settings.currency.auto": "Автоматически ({currency})",
        "settings.units": "Ваши единицы",
        "settings.units.description": "Автоматически по региону: мили и фунты в США, метры и килограммы в остальных странах.",
        "settings.units.auto": "Автоматически",
        "settings.units.metric": "Метрические (км, кг, °C)",
        "settings.units.imperial": "Имперские (mi, lb, °F)",
        "settings.money": "Цены",
        "settings.money.description": "Подчёркивать суммы в других валютах, например $20 или 50 TL.",
        "settings.measures": "Меры",
        "settings.measures.description": "Подчёркивать длину, вес, температуру, скорость и объём в другой системе.",
        "settings.times": "Время",
        "settings.times.description": "Подчёркивать время с часовым поясом, например 3pm EST, и показывать его в вашем поясе.",
        "time.yours": "{time} по вашему времени",
        "time.yoursDay": "{time} {day}, по вашему времени",
    },
    tr: {
        "settings.currency": "Para biriminiz",
        "settings.currency.description": "Fiyatlar bu para biriminde gösterilir. Kurlar Avrupa Merkez Bankası'ndan (Frankfurter aracılığıyla) ve ExchangeRate-API'den alınır, 12 saatte bir yenilenir.",
        "settings.currency.auto": "Otomatik ({currency})",
        "settings.units": "Birimleriniz",
        "settings.units.description": "Otomatik, bölgenize uyar: ABD'de mil ve pound, diğer yerlerde metre ve kilogram.",
        "settings.units.auto": "Otomatik",
        "settings.units.metric": "Metrik (km, kg, °C)",
        "settings.units.imperial": "İngiliz (mi, lb, °F)",
        "settings.money": "Fiyatlar",
        "settings.money.description": "$20 veya 50 TL gibi başka para birimlerindeki tutarların altını çizer.",
        "settings.measures": "Ölçüler",
        "settings.measures.description": "Diğer sistemdeki uzunluk, ağırlık, sıcaklık, hız ve hacimlerin altını çizer.",
        "settings.times": "Saatler",
        "settings.times.description": "3pm EST gibi saat dilimli saatlerin altını çizer ve sizin saat diliminizde gösterir.",
        "time.yours": "Sizin saatinizle {time}",
        "time.yoursDay": "Sizin saatinizle {day} {time}",
    },
});
