import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.showButton": "User panel button",
        "settings.showButton.description": "A gamepad button next to mute and deafen. /gameactivity works either way.",
        "settings.shortcut": "Shortcut",
        "settings.shortcut.description": "Shows or hides your game activity from anywhere in Discord.",
        "button.hide": "Hide game activity",
        "button.show": "Show game activity",
        "toast.shown": "Game activity is visible: others can see what you're playing.",
        "toast.hidden": "Game activity is hidden: others won't see what you're playing.",
        "toast.failed": "Couldn't change your game activity setting",
        "command.description": "Show or hide the game you're playing",
    },
    de: {
        "settings.showButton": "Button in der Benutzerleiste",
        "settings.showButton.description": "Ein Controller-Button neben Stummschalten und Ton aus. /gameactivity funktioniert in beiden Fällen.",
        "settings.shortcut": "Tastenkürzel",
        "settings.shortcut.description": "Zeigt oder verbirgt deine Spielaktivität von überall in Discord aus.",
        "button.hide": "Spielaktivität ausblenden",
        "button.show": "Spielaktivität anzeigen",
        "toast.shown": "Spielaktivität ist sichtbar: Andere sehen, was du spielst.",
        "toast.hidden": "Spielaktivität ist ausgeblendet: Andere sehen nicht, was du spielst.",
        "toast.failed": "Deine Einstellung für die Spielaktivität konnte nicht geändert werden",
        "command.description": "Das Spiel, das du gerade spielst, anzeigen oder ausblenden",
    },
    es: {
        "settings.showButton": "Botón del panel de usuario",
        "settings.showButton.description": "Un botón de mando junto a silenciar y ensordecer. /gameactivity funciona con o sin él.",
        "settings.shortcut": "Atajo",
        "settings.shortcut.description": "Muestra u oculta tu actividad de juego desde cualquier parte de Discord.",
        "button.hide": "Ocultar actividad de juego",
        "button.show": "Mostrar actividad de juego",
        "toast.shown": "La actividad de juego es visible: los demás pueden ver a qué juegas.",
        "toast.hidden": "La actividad de juego está oculta: los demás no verán a qué juegas.",
        "toast.failed": "No se pudo cambiar el ajuste de actividad de juego",
        "command.description": "Muestra u oculta el juego al que estás jugando",
    },
    fr: {
        "settings.showButton": "Bouton du panneau utilisateur",
        "settings.showButton.description": "Un bouton manette à côté de muet et sourdine. /gameactivity fonctionne dans les deux cas.",
        "settings.shortcut": "Raccourci",
        "settings.shortcut.description": "Affiche ou masque ton activité de jeu depuis n'importe où dans Discord.",
        "button.hide": "Masquer l'activité de jeu",
        "button.show": "Afficher l'activité de jeu",
        "toast.shown": "L'activité de jeu est visible : les autres voient à quoi tu joues.",
        "toast.hidden": "L'activité de jeu est masquée : les autres ne voient pas à quoi tu joues.",
        "toast.failed": "Impossible de modifier le paramètre d'activité de jeu",
        "command.description": "Affiche ou masque le jeu auquel tu joues",
    },
    ja: {
        "settings.showButton": "ユーザーパネルのボタン",
        "settings.showButton.description": "ミュートとスピーカーミュートの横にゲームパッドのボタンを表示します。ボタンがなくても /gameactivity は使えます。",
        "settings.shortcut": "ショートカット",
        "settings.shortcut.description": "Discordのどこからでもゲームアクティビティの表示と非表示を切り替えます。",
        "button.hide": "ゲームアクティビティを非表示にする",
        "button.show": "ゲームアクティビティを表示する",
        "toast.shown": "ゲームアクティビティを表示中: 遊んでいるゲームが他の人に見えます。",
        "toast.hidden": "ゲームアクティビティを非表示にしました: 遊んでいるゲームは他の人に見えません。",
        "toast.failed": "ゲームアクティビティの設定を変更できませんでした",
        "command.description": "プレイ中のゲームの表示と非表示を切り替えます",
    },
    pl: {
        "settings.showButton": "Przycisk w panelu użytkownika",
        "settings.showButton.description": "Przycisk pada obok wyciszenia mikrofonu i dźwięku. /gameactivity działa tak czy inaczej.",
        "settings.shortcut": "Skrót",
        "settings.shortcut.description": "Pokazuje lub ukrywa twoją aktywność w grze z dowolnego miejsca w Discordzie.",
        "button.hide": "Ukryj aktywność w grze",
        "button.show": "Pokaż aktywność w grze",
        "toast.shown": "Aktywność w grze jest widoczna: inni widzą, w co grasz.",
        "toast.hidden": "Aktywność w grze jest ukryta: inni nie widzą, w co grasz.",
        "toast.failed": "Nie udało się zmienić ustawienia aktywności w grze",
        "command.description": "Pokaż lub ukryj grę, w którą grasz",
    },
    "pt-BR": {
        "settings.showButton": "Botão no painel do usuário",
        "settings.showButton.description": "Um botão de controle ao lado de silenciar e ensurdecer. O /gameactivity funciona de qualquer jeito.",
        "settings.shortcut": "Atalho",
        "settings.shortcut.description": "Mostra ou oculta sua atividade de jogo de qualquer lugar no Discord.",
        "button.hide": "Ocultar atividade de jogo",
        "button.show": "Mostrar atividade de jogo",
        "toast.shown": "A atividade de jogo está visível: os outros podem ver o que você está jogando.",
        "toast.hidden": "A atividade de jogo está oculta: os outros não vão ver o que você está jogando.",
        "toast.failed": "Não foi possível alterar a configuração de atividade de jogo",
        "command.description": "Mostra ou oculta o jogo que você está jogando",
    },
    ru: {
        "settings.showButton": "Кнопка в панели пользователя",
        "settings.showButton.description": "Кнопка с геймпадом рядом с кнопками отключения микрофона и звука. Команда /gameactivity работает и без неё.",
        "settings.shortcut": "Сочетание клавиш",
        "settings.shortcut.description": "Показывает или скрывает вашу игровую активность из любого места в Discord.",
        "button.hide": "Скрыть игровую активность",
        "button.show": "Показать игровую активность",
        "toast.shown": "Игровая активность видна: другие видят, во что вы играете.",
        "toast.hidden": "Игровая активность скрыта: другие не видят, во что вы играете.",
        "toast.failed": "Не удалось изменить настройку игровой активности",
        "command.description": "Показать или скрыть игру, в которую вы играете",
    },
    tr: {
        "settings.showButton": "Kullanıcı paneli düğmesi",
        "settings.showButton.description": "Mikrofonu ve sesi kapatma düğmelerinin yanında bir oyun kolu düğmesi. /gameactivity her durumda çalışır.",
        "settings.shortcut": "Kısayol",
        "settings.shortcut.description": "Discord'un herhangi bir yerinden oyun etkinliğini gösterir veya gizler.",
        "button.hide": "Oyun etkinliğini gizle",
        "button.show": "Oyun etkinliğini göster",
        "toast.shown": "Oyun etkinliği görünür: diğerleri ne oynadığını görebilir.",
        "toast.hidden": "Oyun etkinliği gizli: diğerleri ne oynadığını görmez.",
        "toast.failed": "Oyun etkinliği ayarın değiştirilemedi",
        "command.description": "Oynadığın oyunu gösterir veya gizler",
    },
});
