import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "player": "Spotify",
        "play": "Play",
        "pause": "Pause",
        "previous": "Previous",
        "next": "Next",
        "seek": "Position in the song",
        "timeOf": "{position} of {duration}",
        "open": "Open {name} in Spotify",
        "error.premium": "Controlling Spotify from Discord needs Spotify Premium",
        "error.device": "Spotify isn't playing on any device right now",
        "error.failed": "Spotify didn't take that. Try again in a moment",
    },
    de: {
        "player": "Spotify",
        "play": "Abspielen",
        "pause": "Pausieren",
        "previous": "Zurück",
        "next": "Weiter",
        "seek": "Position im Song",
        "timeOf": "{position} von {duration}",
        "open": "{name} in Spotify öffnen",
        "error.premium": "Um Spotify aus Discord zu steuern, brauchst du Spotify Premium",
        "error.device": "Spotify spielt gerade auf keinem Gerät",
        "error.failed": "Spotify hat das nicht angenommen. Versuch es gleich noch mal",
    },
    es: {
        "player": "Spotify",
        "play": "Reproducir",
        "pause": "Pausar",
        "previous": "Anterior",
        "next": "Siguiente",
        "seek": "Posición en la canción",
        "timeOf": "{position} de {duration}",
        "open": "Abrir {name} en Spotify",
        "error.premium": "Para controlar Spotify desde Discord necesitas Spotify Premium",
        "error.device": "Spotify no está sonando en ningún dispositivo ahora mismo",
        "error.failed": "Spotify no lo aceptó. Inténtalo de nuevo en un momento",
    },
    fr: {
        "player": "Spotify",
        "play": "Lecture",
        "pause": "Pause",
        "previous": "Précédent",
        "next": "Suivant",
        "seek": "Position dans le morceau",
        "timeOf": "{position} sur {duration}",
        "open": "Ouvrir {name} dans Spotify",
        "error.premium": "Contrôler Spotify depuis Discord demande Spotify Premium",
        "error.device": "Spotify ne joue sur aucun appareil pour le moment",
        "error.failed": "Spotify n'a pas pris en compte la demande. Réessayez dans un instant",
    },
    ja: {
        "player": "Spotify",
        "play": "再生",
        "pause": "一時停止",
        "previous": "前へ",
        "next": "次へ",
        "seek": "曲の再生位置",
        "timeOf": "{position} / {duration}",
        "open": "{name}をSpotifyで開く",
        "error.premium": "DiscordからSpotifyを操作するにはSpotify Premiumが必要です",
        "error.device": "現在Spotifyはどのデバイスでも再生されていません",
        "error.failed": "Spotifyが操作を受け付けませんでした。少し待ってからもう一度お試しください",
    },
    pl: {
        "player": "Spotify",
        "play": "Odtwórz",
        "pause": "Wstrzymaj",
        "previous": "Poprzedni",
        "next": "Następny",
        "seek": "Pozycja w utworze",
        "timeOf": "{position} z {duration}",
        "open": "Otwórz {name} w Spotify",
        "error.premium": "Sterowanie Spotify z Discorda wymaga Spotify Premium",
        "error.device": "Spotify nie gra teraz na żadnym urządzeniu",
        "error.failed": "Spotify tego nie przyjął. Spróbuj ponownie za chwilę",
    },
    "pt-BR": {
        "player": "Spotify",
        "play": "Tocar",
        "pause": "Pausar",
        "previous": "Anterior",
        "next": "Próxima",
        "seek": "Posição na música",
        "timeOf": "{position} de {duration}",
        "open": "Abrir {name} no Spotify",
        "error.premium": "Para controlar o Spotify pelo Discord é preciso ter o Spotify Premium",
        "error.device": "O Spotify não está tocando em nenhum dispositivo agora",
        "error.failed": "O Spotify não aceitou isso. Tente de novo daqui a pouco",
    },
    ru: {
        "player": "Spotify",
        "play": "Воспроизвести",
        "pause": "Пауза",
        "previous": "Предыдущий",
        "next": "Следующий",
        "seek": "Позиция в треке",
        "timeOf": "{position} из {duration}",
        "open": "Открыть {name} в Spotify",
        "error.premium": "Чтобы управлять Spotify из Discord, нужен Spotify Premium",
        "error.device": "Сейчас Spotify ни на одном устройстве не играет",
        "error.failed": "Spotify не принял команду. Попробуйте чуть позже",
    },
    tr: {
        "player": "Spotify",
        "play": "Oynat",
        "pause": "Duraklat",
        "previous": "Önceki",
        "next": "Sonraki",
        "seek": "Şarkıdaki konum",
        "timeOf": "{position} / {duration}",
        "open": "{name} parçasını Spotify'da aç",
        "error.premium": "Spotify'ı Discord'dan kontrol etmek için Spotify Premium gerekir",
        "error.device": "Spotify şu anda hiçbir cihazda çalmıyor",
        "error.failed": "Spotify bunu kabul etmedi. Birazdan tekrar dene",
    },
});
