import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.scope": "What to highlight",
        "settings.scope.description": "The message you jumped to, or the searched words in every message you can see while the search is open.",
        "settings.scope.jumped": "The message I jumped to",
        "settings.scope.all": "Every message on screen",
        "settings.duration": "How long",
        "settings.duration.description": "Fade the jumped-to message's highlight after a few seconds, or keep it until you close the search.",
        "settings.duration.fade": "Fade after a few seconds",
        "settings.duration.stay": "Until I close the search",
    },
    de: {
        "settings.scope": "Was hervorgehoben wird",
        "settings.scope.description": "Die Nachricht, zu der du gesprungen bist, oder die gesuchten Wörter in jeder sichtbaren Nachricht, solange die Suche offen ist.",
        "settings.scope.jumped": "Die Nachricht, zu der ich gesprungen bin",
        "settings.scope.all": "Jede Nachricht auf dem Bildschirm",
        "settings.duration": "Wie lange",
        "settings.duration.description": "Die Hervorhebung der angesprungenen Nachricht nach ein paar Sekunden ausblenden oder behalten, bis du die Suche schließt.",
        "settings.duration.fade": "Nach ein paar Sekunden ausblenden",
        "settings.duration.stay": "Bis ich die Suche schließe",
    },
    es: {
        "settings.scope": "Qué resaltar",
        "settings.scope.description": "El mensaje al que saltaste, o las palabras buscadas en cada mensaje visible mientras la búsqueda esté abierta.",
        "settings.scope.jumped": "El mensaje al que salté",
        "settings.scope.all": "Todos los mensajes en pantalla",
        "settings.duration": "Cuánto tiempo",
        "settings.duration.description": "Desvanecer el resaltado del mensaje al que saltaste tras unos segundos, o mantenerlo hasta que cierres la búsqueda.",
        "settings.duration.fade": "Desvanecer tras unos segundos",
        "settings.duration.stay": "Hasta que cierre la búsqueda",
    },
    fr: {
        "settings.scope": "Quoi surligner",
        "settings.scope.description": "Le message vers lequel tu as sauté, ou les mots recherchés dans chaque message visible tant que la recherche est ouverte.",
        "settings.scope.jumped": "Le message vers lequel j'ai sauté",
        "settings.scope.all": "Chaque message à l'écran",
        "settings.duration": "Combien de temps",
        "settings.duration.description": "Estomper le surlignage du message atteint après quelques secondes, ou le garder jusqu'à ce que tu fermes la recherche.",
        "settings.duration.fade": "Estomper après quelques secondes",
        "settings.duration.stay": "Jusqu'à ce que je ferme la recherche",
    },
    ja: {
        "settings.scope": "ハイライトする範囲",
        "settings.scope.description": "ジャンプ先のメッセージだけ、または検索を開いている間に見えているすべてのメッセージで検索した言葉をハイライトします。",
        "settings.scope.jumped": "ジャンプ先のメッセージ",
        "settings.scope.all": "画面上のすべてのメッセージ",
        "settings.duration": "表示時間",
        "settings.duration.description": "ジャンプ先のハイライトを数秒後に消すか、検索を閉じるまで残すかを選べます。",
        "settings.duration.fade": "数秒後に消す",
        "settings.duration.stay": "検索を閉じるまで",
    },
    pl: {
        "settings.scope": "Co podświetlać",
        "settings.scope.description": "Wiadomość, do której przeskoczyłeś, albo szukane słowa w każdej widocznej wiadomości, dopóki wyszukiwanie jest otwarte.",
        "settings.scope.jumped": "Wiadomość, do której przeskoczyłem",
        "settings.scope.all": "Każdą wiadomość na ekranie",
        "settings.duration": "Jak długo",
        "settings.duration.description": "Wygaszaj podświetlenie wiadomości po kilku sekundach albo trzymaj je, dopóki nie zamkniesz wyszukiwania.",
        "settings.duration.fade": "Wygaś po kilku sekundach",
        "settings.duration.stay": "Do zamknięcia wyszukiwania",
    },
    "pt-BR": {
        "settings.scope": "O que destacar",
        "settings.scope.description": "A mensagem para a qual você pulou, ou as palavras buscadas em cada mensagem visível enquanto a busca estiver aberta.",
        "settings.scope.jumped": "A mensagem para a qual pulei",
        "settings.scope.all": "Todas as mensagens na tela",
        "settings.duration": "Por quanto tempo",
        "settings.duration.description": "Apagar o destaque da mensagem depois de alguns segundos, ou mantê-lo até você fechar a busca.",
        "settings.duration.fade": "Apagar depois de alguns segundos",
        "settings.duration.stay": "Até eu fechar a busca",
    },
    ru: {
        "settings.scope": "Что подсвечивать",
        "settings.scope.description": "Сообщение, к которому вы перешли, или искомые слова во всех видимых сообщениях, пока поиск открыт.",
        "settings.scope.jumped": "Сообщение, к которому я перешёл",
        "settings.scope.all": "Все сообщения на экране",
        "settings.duration": "Как долго",
        "settings.duration.description": "Убирать подсветку сообщения через несколько секунд или держать её, пока вы не закроете поиск.",
        "settings.duration.fade": "Убрать через несколько секунд",
        "settings.duration.stay": "Пока я не закрою поиск",
    },
    tr: {
        "settings.scope": "Neyi vurgula",
        "settings.scope.description": "Atladığın mesajı ya da arama açıkken ekranda görünen her mesajda aradığın kelimeleri.",
        "settings.scope.jumped": "Atladığım mesajı",
        "settings.scope.all": "Ekrandaki her mesajı",
        "settings.duration": "Ne kadar süre",
        "settings.duration.description": "Atlanan mesajın vurgusunu birkaç saniye sonra soldur ya da aramayı kapatana kadar tut.",
        "settings.duration.fade": "Birkaç saniye sonra soldur",
        "settings.duration.stay": "Aramayı kapatana kadar",
    },
});
