import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "panel.label": "Fake deafen",
        "settings.deafen": "Appear deafened",
        "settings.deafen.description": "Others see you deafened while you still hear them. Deafened also shows as muted, like Discord does.",
        "settings.mute": "Appear muted",
        "settings.mute.description": "Others see you muted. Your microphone isn't touched: mute it too if you don't want to be heard.",
        "settings.showButton": "User panel button",
        "settings.showButton.description": "A ghost button next to deafen. /fakedeafen and the shortcut work either way.",
        "settings.shortcut": "Shortcut",
        "settings.shortcut.description": "Turns fake deafen on or off from anywhere in Discord.",
        "button.on": "Turn on fake deafen",
        "button.off": "Turn off fake deafen",
        "toast.on": "Fake deafen is on: others see you deafened, you still hear them.",
        "toast.onIdle": "Fake deafen is on: it applies when you join a voice channel.",
        "toast.onPending": "Fake deafen is on: it applies the next time you mute, deafen or rejoin.",
        "toast.off": "Fake deafen is off: others see your real mute and deafen.",
        "toast.failed": "Couldn't reach Discord's voice connection",
        "command.description": "Appear deafened while you still hear everyone",
    },
    de: {
        "panel.label": "Fake Deafen",
        "settings.deafen": "Als taub angezeigt werden",
        "settings.deafen.description": "Andere sehen dich mit Ton aus, während du sie weiter hörst. Ton aus zeigt dich auch als stummgeschaltet, wie bei Discord.",
        "settings.mute": "Als stummgeschaltet angezeigt werden",
        "settings.mute.description": "Andere sehen dich stummgeschaltet. Dein Mikrofon bleibt unverändert: Schalte es auch stumm, wenn du nicht gehört werden willst.",
        "settings.showButton": "Button in der Benutzerleiste",
        "settings.showButton.description": "Ein Geist-Button neben Ton aus. /fakedeafen und das Tastenkürzel funktionieren in beiden Fällen.",
        "settings.shortcut": "Tastenkürzel",
        "settings.shortcut.description": "Schaltet Fake Deafen von überall in Discord ein oder aus.",
        "button.on": "Fake Deafen einschalten",
        "button.off": "Fake Deafen ausschalten",
        "toast.on": "Fake Deafen ist an: Andere sehen dich mit Ton aus, du hörst sie weiter.",
        "toast.onIdle": "Fake Deafen ist an: Es greift, sobald du einem Sprachkanal beitrittst.",
        "toast.onPending": "Fake Deafen ist an: Es greift, sobald du das nächste Mal stummschaltest, den Ton ausschaltest oder neu beitrittst.",
        "toast.off": "Fake Deafen ist aus: Andere sehen dein echtes Stummschalten und Ton aus.",
        "toast.failed": "Discords Sprachverbindung war nicht erreichbar",
        "command.description": "Mit Ton aus angezeigt werden und trotzdem alle hören",
    },
    es: {
        "panel.label": "Ensordecido falso",
        "settings.deafen": "Aparecer ensordecido",
        "settings.deafen.description": "Los demás te ven ensordecido mientras tú los sigues oyendo. Ensordecido también aparece como silenciado, como en Discord.",
        "settings.mute": "Aparecer silenciado",
        "settings.mute.description": "Los demás te ven silenciado. Tu micrófono no se toca: siléncialo también si no quieres que te oigan.",
        "settings.showButton": "Botón del panel de usuario",
        "settings.showButton.description": "Un botón de fantasma junto a ensordecer. /fakedeafen y el atajo funcionan con o sin él.",
        "settings.shortcut": "Atajo",
        "settings.shortcut.description": "Activa o desactiva el ensordecido falso desde cualquier parte de Discord.",
        "button.on": "Activar ensordecido falso",
        "button.off": "Desactivar ensordecido falso",
        "toast.on": "Ensordecido falso activado: los demás te ven ensordecido y tú los sigues oyendo.",
        "toast.onIdle": "Ensordecido falso activado: se aplica cuando entres a un canal de voz.",
        "toast.onPending": "Ensordecido falso activado: se aplica la próxima vez que te silencies, te ensordezcas o vuelvas a entrar.",
        "toast.off": "Ensordecido falso desactivado: los demás ven tu silencio y ensordecido reales.",
        "toast.failed": "No se pudo acceder a la conexión de voz de Discord",
        "command.description": "Aparece ensordecido mientras sigues oyendo a todos",
    },
    fr: {
        "panel.label": "Fausse sourdine",
        "settings.deafen": "Apparaître en sourdine",
        "settings.deafen.description": "Les autres te voient en sourdine alors que tu les entends toujours. La sourdine s'affiche aussi comme muet, comme sur Discord.",
        "settings.mute": "Apparaître muet",
        "settings.mute.description": "Les autres te voient muet. Ton micro n'est pas touché : coupe-le aussi si tu ne veux pas être entendu.",
        "settings.showButton": "Bouton du panneau utilisateur",
        "settings.showButton.description": "Un bouton fantôme à côté de sourdine. /fakedeafen et le raccourci fonctionnent dans tous les cas.",
        "settings.shortcut": "Raccourci",
        "settings.shortcut.description": "Active ou désactive la fausse sourdine depuis n'importe où dans Discord.",
        "button.on": "Activer la fausse sourdine",
        "button.off": "Désactiver la fausse sourdine",
        "toast.on": "Fausse sourdine activée : les autres te voient en sourdine, tu les entends toujours.",
        "toast.onIdle": "Fausse sourdine activée : elle s'applique quand tu rejoins un salon vocal.",
        "toast.onPending": "Fausse sourdine activée : elle s'applique la prochaine fois que tu te mets en muet, en sourdine ou que tu rejoins.",
        "toast.off": "Fausse sourdine désactivée : les autres voient ton vrai statut muet et sourdine.",
        "toast.failed": "Impossible d'accéder à la connexion vocale de Discord",
        "command.description": "Apparaître en sourdine tout en entendant tout le monde",
    },
    ja: {
        "panel.label": "フェイクスピーカーミュート",
        "settings.deafen": "スピーカーミュート中に見せる",
        "settings.deafen.description": "相手の声は聞こえたまま、他の人にはスピーカーミュート中に見えます。Discordと同じく、スピーカーミュートはマイクミュートとしても表示されます。",
        "settings.mute": "マイクミュート中に見せる",
        "settings.mute.description": "他の人にはマイクミュート中に見えます。マイク自体はそのままなので、声を聞かれたくない場合はマイクもミュートしてください。",
        "settings.showButton": "ユーザーパネルのボタン",
        "settings.showButton.description": "スピーカーミュートの横におばけボタンを表示します。/fakedeafen とショートカットはボタンがなくても使えます。",
        "settings.shortcut": "ショートカット",
        "settings.shortcut.description": "Discordのどこからでもフェイクスピーカーミュートをオン・オフします。",
        "button.on": "フェイクスピーカーミュートをオン",
        "button.off": "フェイクスピーカーミュートをオフ",
        "toast.on": "フェイクスピーカーミュートがオンです。他の人にはスピーカーミュート中に見えますが、声は聞こえます。",
        "toast.onIdle": "フェイクスピーカーミュートがオンです。ボイスチャンネルに参加すると適用されます。",
        "toast.onPending": "フェイクスピーカーミュートがオンです。次にミュート、スピーカーミュート、または再参加したときに適用されます。",
        "toast.off": "フェイクスピーカーミュートがオフです。他の人には実際のミュート状態が見えます。",
        "toast.failed": "Discordの音声接続にアクセスできませんでした",
        "command.description": "全員の声を聞きながらスピーカーミュート中に見せる",
    },
    pl: {
        "panel.label": "Udawane wyciszenie",
        "settings.deafen": "Wyglądaj na wyciszonego",
        "settings.deafen.description": "Inni widzą, że masz wyciszony dźwięk, a ty nadal ich słyszysz. Wyciszony dźwięk pokazuje też wyciszony mikrofon, jak w Discordzie.",
        "settings.mute": "Wyglądaj na wyciszony mikrofon",
        "settings.mute.description": "Inni widzą wyciszony mikrofon. Twój mikrofon zostaje bez zmian: wycisz go też, jeśli nie chcesz być słyszany.",
        "settings.showButton": "Przycisk w panelu użytkownika",
        "settings.showButton.description": "Przycisk ducha obok wyciszenia dźwięku. /fakedeafen i skrót działają tak czy inaczej.",
        "settings.shortcut": "Skrót",
        "settings.shortcut.description": "Włącza lub wyłącza udawane wyciszenie z dowolnego miejsca w Discordzie.",
        "button.on": "Włącz udawane wyciszenie",
        "button.off": "Wyłącz udawane wyciszenie",
        "toast.on": "Udawane wyciszenie włączone: inni widzą wyciszony dźwięk, a ty nadal ich słyszysz.",
        "toast.onIdle": "Udawane wyciszenie włączone: zadziała, gdy dołączysz do kanału głosowego.",
        "toast.onPending": "Udawane wyciszenie włączone: zadziała przy następnym wyciszeniu mikrofonu, dźwięku lub ponownym dołączeniu.",
        "toast.off": "Udawane wyciszenie wyłączone: inni widzą twoje prawdziwe wyciszenie.",
        "toast.failed": "Nie udało się połączyć z połączeniem głosowym Discorda",
        "command.description": "Wyglądaj na wyciszonego, nadal słysząc wszystkich",
    },
    "pt-BR": {
        "panel.label": "Ensurdecer falso",
        "settings.deafen": "Aparecer ensurdecido",
        "settings.deafen.description": "Os outros te veem ensurdecido enquanto você continua ouvindo. Ensurdecido também aparece como silenciado, como no Discord.",
        "settings.mute": "Aparecer silenciado",
        "settings.mute.description": "Os outros te veem silenciado. Seu microfone não é alterado: silencie ele também se não quiser ser ouvido.",
        "settings.showButton": "Botão do painel de usuário",
        "settings.showButton.description": "Um botão de fantasma ao lado de ensurdecer. /fakedeafen e o atalho funcionam de qualquer jeito.",
        "settings.shortcut": "Atalho",
        "settings.shortcut.description": "Liga ou desliga o ensurdecer falso de qualquer lugar do Discord.",
        "button.on": "Ligar ensurdecer falso",
        "button.off": "Desligar ensurdecer falso",
        "toast.on": "Ensurdecer falso ligado: os outros te veem ensurdecido e você continua ouvindo.",
        "toast.onIdle": "Ensurdecer falso ligado: vale quando você entrar em um canal de voz.",
        "toast.onPending": "Ensurdecer falso ligado: vale na próxima vez que você silenciar, ensurdecer ou entrar de novo.",
        "toast.off": "Ensurdecer falso desligado: os outros veem seu estado real.",
        "toast.failed": "Não foi possível acessar a conexão de voz do Discord",
        "command.description": "Apareça ensurdecido enquanto continua ouvindo todos",
    },
    ru: {
        "panel.label": "Фальшивое отключение звука",
        "settings.deafen": "Казаться без звука",
        "settings.deafen.description": "Другие видят, что у вас выключен звук, а вы продолжаете их слышать. Выключенный звук также показывается как выключенный микрофон, как в Discord.",
        "settings.mute": "Казаться без микрофона",
        "settings.mute.description": "Другие видят выключенный микрофон. Сам микрофон не меняется: выключите его тоже, если не хотите, чтобы вас слышали.",
        "settings.showButton": "Кнопка на панели пользователя",
        "settings.showButton.description": "Кнопка с призраком рядом с выключением звука. /fakedeafen и сочетание клавиш работают в любом случае.",
        "settings.shortcut": "Сочетание клавиш",
        "settings.shortcut.description": "Включает или выключает фальшивое отключение звука из любого места Discord.",
        "button.on": "Включить фальшивое отключение звука",
        "button.off": "Выключить фальшивое отключение звука",
        "toast.on": "Фальшивое отключение звука включено: другие видят, что звук выключен, а вы их слышите.",
        "toast.onIdle": "Фальшивое отключение звука включено: сработает, когда вы зайдёте в голосовой канал.",
        "toast.onPending": "Фальшивое отключение звука включено: сработает, когда вы в следующий раз выключите микрофон, звук или перезайдёте.",
        "toast.off": "Фальшивое отключение звука выключено: другие видят ваше настоящее состояние.",
        "toast.failed": "Не удалось обратиться к голосовому подключению Discord",
        "command.description": "Казаться без звука, продолжая всех слышать",
    },
    tr: {
        "panel.label": "Sahte ses kapatma",
        "settings.deafen": "Sesi kapalı görün",
        "settings.deafen.description": "Sen herkesi duymaya devam ederken diğerleri sesini kapalı görür. Discord'daki gibi, ses kapalıyken mikrofon da kapalı görünür.",
        "settings.mute": "Mikrofonu kapalı görün",
        "settings.mute.description": "Diğerleri mikrofonunu kapalı görür. Mikrofonuna dokunulmaz: duyulmak istemiyorsan onu da kapat.",
        "settings.showButton": "Kullanıcı paneli düğmesi",
        "settings.showButton.description": "Sesi kapatma düğmesinin yanında bir hayalet düğmesi. /fakedeafen ve kısayol her durumda çalışır.",
        "settings.shortcut": "Kısayol",
        "settings.shortcut.description": "Sahte ses kapatmayı Discord'un her yerinden açar veya kapatır.",
        "button.on": "Sahte ses kapatmayı aç",
        "button.off": "Sahte ses kapatmayı kapat",
        "toast.on": "Sahte ses kapatma açık: diğerleri sesini kapalı görür, sen onları duymaya devam edersin.",
        "toast.onIdle": "Sahte ses kapatma açık: bir ses kanalına katıldığında geçerli olur.",
        "toast.onPending": "Sahte ses kapatma açık: bir sonraki mikrofon kapatma, ses kapatma veya yeniden katılmada geçerli olur.",
        "toast.off": "Sahte ses kapatma kapalı: diğerleri gerçek durumunu görür.",
        "toast.failed": "Discord'un ses bağlantısına ulaşılamadı",
        "command.description": "Herkesi duymaya devam ederken sesi kapalı görün",
    },
});
