import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "button": "Mark up",
        "editor.title": "Mark up picture",
        "editor.tools": "Tools",
        "editor.color": "Colour {color}",
        "editor.undo": "Undo (Ctrl+Z)",
        "editor.redo": "Redo (Ctrl+Shift+Z)",
        "editor.cancel": "Cancel",
        "editor.save": "Save",
        "editor.error": "Couldn't open this picture.",
        "tool.crop": "Crop",
        "tool.blur": "Blur",
        "tool.box": "Box",
        "tool.arrow": "Arrow",
        "tool.pen": "Pen",
        "hint.crop": "Drag to choose what to keep.",
        "hint.blur": "Drag over names, faces or anything private.",
        "hint.box": "Drag to draw a box around something.",
        "hint.arrow": "Drag from where the arrow starts to what it points at.",
        "hint.pen": "Draw freely.",
    },
    de: {
        "button": "Markieren",
        "editor.title": "Bild markieren",
        "editor.tools": "Werkzeuge",
        "editor.color": "Farbe {color}",
        "editor.undo": "Rückgängig (Strg+Z)",
        "editor.redo": "Wiederholen (Strg+Umschalt+Z)",
        "editor.cancel": "Abbrechen",
        "editor.save": "Speichern",
        "editor.error": "Dieses Bild konnte nicht geöffnet werden.",
        "tool.crop": "Zuschneiden",
        "tool.blur": "Verpixeln",
        "tool.box": "Rahmen",
        "tool.arrow": "Pfeil",
        "tool.pen": "Stift",
        "hint.crop": "Ziehe, um auszuwählen, was bleiben soll.",
        "hint.blur": "Ziehe über Namen, Gesichter oder alles Private.",
        "hint.box": "Ziehe, um einen Rahmen um etwas zu zeichnen.",
        "hint.arrow": "Ziehe vom Anfang des Pfeils zu dem, worauf er zeigt.",
        "hint.pen": "Zeichne frei.",
    },
    es: {
        "button": "Marcar",
        "editor.title": "Marcar imagen",
        "editor.tools": "Herramientas",
        "editor.color": "Color {color}",
        "editor.undo": "Deshacer (Ctrl+Z)",
        "editor.redo": "Rehacer (Ctrl+Mayús+Z)",
        "editor.cancel": "Cancelar",
        "editor.save": "Guardar",
        "editor.error": "No se pudo abrir esta imagen.",
        "tool.crop": "Recortar",
        "tool.blur": "Difuminar",
        "tool.box": "Recuadro",
        "tool.arrow": "Flecha",
        "tool.pen": "Lápiz",
        "hint.crop": "Arrastra para elegir qué conservar.",
        "hint.blur": "Arrastra sobre nombres, caras o cualquier cosa privada.",
        "hint.box": "Arrastra para dibujar un recuadro alrededor de algo.",
        "hint.arrow": "Arrastra desde donde empieza la flecha hasta lo que señala.",
        "hint.pen": "Dibuja libremente.",
    },
    fr: {
        "button": "Annoter",
        "editor.title": "Annoter l'image",
        "editor.tools": "Outils",
        "editor.color": "Couleur {color}",
        "editor.undo": "Annuler (Ctrl+Z)",
        "editor.redo": "Rétablir (Ctrl+Maj+Z)",
        "editor.cancel": "Annuler",
        "editor.save": "Enregistrer",
        "editor.error": "Impossible d'ouvrir cette image.",
        "tool.crop": "Rogner",
        "tool.blur": "Flouter",
        "tool.box": "Cadre",
        "tool.arrow": "Flèche",
        "tool.pen": "Stylo",
        "hint.crop": "Fais glisser pour choisir ce que tu gardes.",
        "hint.blur": "Fais glisser sur des noms, des visages ou tout ce qui est privé.",
        "hint.box": "Fais glisser pour encadrer quelque chose.",
        "hint.arrow": "Fais glisser du début de la flèche jusqu'à ce qu'elle montre.",
        "hint.pen": "Dessine librement.",
    },
    ja: {
        "button": "書き込み",
        "editor.title": "画像に書き込む",
        "editor.tools": "ツール",
        "editor.color": "色 {color}",
        "editor.undo": "元に戻す (Ctrl+Z)",
        "editor.redo": "やり直す (Ctrl+Shift+Z)",
        "editor.cancel": "キャンセル",
        "editor.save": "保存",
        "editor.error": "この画像を開けませんでした。",
        "tool.crop": "切り抜き",
        "tool.blur": "ぼかし",
        "tool.box": "枠",
        "tool.arrow": "矢印",
        "tool.pen": "ペン",
        "hint.crop": "ドラッグして残す範囲を選びます。",
        "hint.blur": "名前や顔など、見せたくない部分をドラッグします。",
        "hint.box": "ドラッグして枠で囲みます。",
        "hint.arrow": "矢印の始点から指したい場所までドラッグします。",
        "hint.pen": "自由に描けます。",
    },
    pl: {
        "button": "Oznacz",
        "editor.title": "Oznacz obraz",
        "editor.tools": "Narzędzia",
        "editor.color": "Kolor {color}",
        "editor.undo": "Cofnij (Ctrl+Z)",
        "editor.redo": "Ponów (Ctrl+Shift+Z)",
        "editor.cancel": "Anuluj",
        "editor.save": "Zapisz",
        "editor.error": "Nie udało się otworzyć tego obrazu.",
        "tool.crop": "Przytnij",
        "tool.blur": "Rozmyj",
        "tool.box": "Ramka",
        "tool.arrow": "Strzałka",
        "tool.pen": "Pióro",
        "hint.crop": "Przeciągnij, aby wybrać, co zostaje.",
        "hint.blur": "Przeciągnij po imionach, twarzach lub czymkolwiek prywatnym.",
        "hint.box": "Przeciągnij, aby obrysować coś ramką.",
        "hint.arrow": "Przeciągnij od początku strzałki do tego, na co wskazuje.",
        "hint.pen": "Rysuj swobodnie.",
    },
    "pt-BR": {
        "button": "Marcar",
        "editor.title": "Marcar imagem",
        "editor.tools": "Ferramentas",
        "editor.color": "Cor {color}",
        "editor.undo": "Desfazer (Ctrl+Z)",
        "editor.redo": "Refazer (Ctrl+Shift+Z)",
        "editor.cancel": "Cancelar",
        "editor.save": "Salvar",
        "editor.error": "Não foi possível abrir esta imagem.",
        "tool.crop": "Cortar",
        "tool.blur": "Desfocar",
        "tool.box": "Caixa",
        "tool.arrow": "Seta",
        "tool.pen": "Caneta",
        "hint.crop": "Arraste para escolher o que manter.",
        "hint.blur": "Arraste sobre nomes, rostos ou qualquer coisa privada.",
        "hint.box": "Arraste para desenhar uma caixa em volta de algo.",
        "hint.arrow": "Arraste do início da seta até o que ela aponta.",
        "hint.pen": "Desenhe livremente.",
    },
    ru: {
        "button": "Разметить",
        "editor.title": "Разметка картинки",
        "editor.tools": "Инструменты",
        "editor.color": "Цвет {color}",
        "editor.undo": "Отменить (Ctrl+Z)",
        "editor.redo": "Повторить (Ctrl+Shift+Z)",
        "editor.cancel": "Отмена",
        "editor.save": "Сохранить",
        "editor.error": "Не удалось открыть эту картинку.",
        "tool.crop": "Обрезать",
        "tool.blur": "Размыть",
        "tool.box": "Рамка",
        "tool.arrow": "Стрелка",
        "tool.pen": "Перо",
        "hint.crop": "Выделите, что оставить.",
        "hint.blur": "Проведите по именам, лицам и всему личному.",
        "hint.box": "Проведите, чтобы обвести что-то рамкой.",
        "hint.arrow": "Проведите от начала стрелки к тому, на что она указывает.",
        "hint.pen": "Рисуйте свободно.",
    },
    tr: {
        "button": "İşaretle",
        "editor.title": "Resmi işaretle",
        "editor.tools": "Araçlar",
        "editor.color": "Renk {color}",
        "editor.undo": "Geri al (Ctrl+Z)",
        "editor.redo": "Yinele (Ctrl+Shift+Z)",
        "editor.cancel": "İptal",
        "editor.save": "Kaydet",
        "editor.error": "Bu resim açılamadı.",
        "tool.crop": "Kırp",
        "tool.blur": "Bulanıklaştır",
        "tool.box": "Kutu",
        "tool.arrow": "Ok",
        "tool.pen": "Kalem",
        "hint.crop": "Neyin kalacağını seçmek için sürükle.",
        "hint.blur": "İsimlerin, yüzlerin ya da özel olan her şeyin üzerinden sürükle.",
        "hint.box": "Bir şeyin etrafına kutu çizmek için sürükle.",
        "hint.arrow": "Okun başladığı yerden gösterdiği şeye sürükle.",
        "hint.pen": "Serbestçe çiz.",
    },
});
