import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.unsortedTab": "Unsorted tab",
        "settings.unsortedTab.description": "A tab with only the favourites that aren't in a folder. All always shows everything.",
        "settings.oneFolderPerGif": "One folder per GIF",
        "settings.oneFolderPerGif.description": "Adding a GIF to a folder takes it out of its other folders, so it moves instead of being in several.",
        "settings.showCounts": "Show counts",
        "settings.showCounts.description": "How many GIFs each tab holds, next to its name.",
        "tabs.label": "GIF folders",
        "tab.all": "All",
        "tab.all.title": "All your favourites",
        "tab.unsorted": "Unsorted",
        "tab.unsorted.title": "Favourites that aren't in any folder",
        "tab.folder.title": "Right-click to rename or delete",
        "tab.new": "+ New Folder",
        "tab.new.label": "New folder",
        "input.rename": "Folder name",
        "input.new": "New folder",
        "error.empty": "Give the folder a name",
        "error.taken": "A folder with that name already exists",
        "folder.menu": "{name} folder",
        "folder.rename": "Rename Folder",
        "folder.delete": "Delete Folder",
        "folder.delete.subtext": "The GIFs stay in your favourites",
        "folder.default": "Folder {n}",
        "gif.removeFrom": "Remove from {name}",
        "gif.newFolder": "New Folder",
        "gif.move": "Move to Folder",
        "gif.add": "Add to Folder",
        "toast.added": "Added to {name}. Right-click its tab to rename it.",
        "toast.addedNew": "Added to a new folder. Right-click its tab to rename it.",
        "resize.title": "Drag to resize, double-click to reset",
    },
    de: {
        "settings.unsortedTab": "Tab „Unsortiert“",
        "settings.unsortedTab.description": "Ein Tab nur mit den Favoriten, die in keinem Ordner sind. „Alle“ zeigt immer alles.",
        "settings.oneFolderPerGif": "Ein Ordner pro GIF",
        "settings.oneFolderPerGif.description": "Wenn du ein GIF zu einem Ordner hinzufügst, wird es aus seinen anderen Ordnern entfernt und also verschoben, statt in mehreren zu liegen.",
        "settings.showCounts": "Anzahl anzeigen",
        "settings.showCounts.description": "Wie viele GIFs jeder Tab enthält, neben seinem Namen.",
        "tabs.label": "GIF-Ordner",
        "tab.all": "Alle",
        "tab.all.title": "Alle deine Favoriten",
        "tab.unsorted": "Unsortiert",
        "tab.unsorted.title": "Favoriten, die in keinem Ordner sind",
        "tab.folder.title": "Rechtsklick zum Umbenennen oder Löschen",
        "tab.new": "+ Neuer Ordner",
        "tab.new.label": "Neuer Ordner",
        "input.rename": "Ordnername",
        "input.new": "Neuer Ordner",
        "error.empty": "Gib dem Ordner einen Namen",
        "error.taken": "Ein Ordner mit diesem Namen existiert bereits",
        "folder.menu": "Ordner {name}",
        "folder.rename": "Ordner umbenennen",
        "folder.delete": "Ordner löschen",
        "folder.delete.subtext": "Die GIFs bleiben in deinen Favoriten",
        "folder.default": "Ordner {n}",
        "gif.removeFrom": "Aus {name} entfernen",
        "gif.newFolder": "Neuer Ordner",
        "gif.move": "In Ordner verschieben",
        "gif.add": "Zu Ordner hinzufügen",
        "toast.added": "Zu {name} hinzugefügt. Rechtsklicke den Tab, um ihn umzubenennen.",
        "toast.addedNew": "Zu einem neuen Ordner hinzugefügt. Rechtsklicke den Tab, um ihn umzubenennen.",
        "resize.title": "Ziehen zum Ändern der Größe, Doppelklick zum Zurücksetzen",
    },
    es: {
        "settings.unsortedTab": "Pestaña Sin clasificar",
        "settings.unsortedTab.description": "Una pestaña solo con los favoritos que no están en ninguna carpeta. Todos siempre muestra todo.",
        "settings.oneFolderPerGif": "Una carpeta por GIF",
        "settings.oneFolderPerGif.description": "Al añadir un GIF a una carpeta se quita de sus otras carpetas, así que se mueve en lugar de estar en varias.",
        "settings.showCounts": "Mostrar recuentos",
        "settings.showCounts.description": "Cuántos GIF tiene cada pestaña, junto a su nombre.",
        "tabs.label": "Carpetas de GIF",
        "tab.all": "Todos",
        "tab.all.title": "Todos tus favoritos",
        "tab.unsorted": "Sin clasificar",
        "tab.unsorted.title": "Favoritos que no están en ninguna carpeta",
        "tab.folder.title": "Clic derecho para cambiar el nombre o eliminar",
        "tab.new": "+ Nueva carpeta",
        "tab.new.label": "Nueva carpeta",
        "input.rename": "Nombre de la carpeta",
        "input.new": "Nueva carpeta",
        "error.empty": "Ponle un nombre a la carpeta",
        "error.taken": "Ya existe una carpeta con ese nombre",
        "folder.menu": "Carpeta {name}",
        "folder.rename": "Cambiar nombre de la carpeta",
        "folder.delete": "Eliminar carpeta",
        "folder.delete.subtext": "Los GIF se quedan en tus favoritos",
        "folder.default": "Carpeta {n}",
        "gif.removeFrom": "Quitar de {name}",
        "gif.newFolder": "Nueva carpeta",
        "gif.move": "Mover a carpeta",
        "gif.add": "Añadir a carpeta",
        "toast.added": "Añadido a {name}. Haz clic derecho en su pestaña para cambiarle el nombre.",
        "toast.addedNew": "Añadido a una carpeta nueva. Haz clic derecho en su pestaña para cambiarle el nombre.",
        "resize.title": "Arrastra para cambiar el tamaño, doble clic para restablecer",
    },
    fr: {
        "settings.unsortedTab": "Onglet Non classés",
        "settings.unsortedTab.description": "Un onglet avec uniquement les favoris qui ne sont dans aucun dossier. Tous affiche toujours tout.",
        "settings.oneFolderPerGif": "Un dossier par GIF",
        "settings.oneFolderPerGif.description": "Ajouter un GIF à un dossier le retire de ses autres dossiers : il est déplacé au lieu d'être dans plusieurs.",
        "settings.showCounts": "Afficher les totaux",
        "settings.showCounts.description": "Le nombre de GIF de chaque onglet, à côté de son nom.",
        "tabs.label": "Dossiers de GIF",
        "tab.all": "Tous",
        "tab.all.title": "Tous vos favoris",
        "tab.unsorted": "Non classés",
        "tab.unsorted.title": "Favoris qui ne sont dans aucun dossier",
        "tab.folder.title": "Clic droit pour renommer ou supprimer",
        "tab.new": "+ Nouveau dossier",
        "tab.new.label": "Nouveau dossier",
        "input.rename": "Nom du dossier",
        "input.new": "Nouveau dossier",
        "error.empty": "Donnez un nom au dossier",
        "error.taken": "Un dossier portant ce nom existe déjà",
        "folder.menu": "Dossier {name}",
        "folder.rename": "Renommer le dossier",
        "folder.delete": "Supprimer le dossier",
        "folder.delete.subtext": "Les GIF restent dans vos favoris",
        "folder.default": "Dossier {n}",
        "gif.removeFrom": "Retirer de {name}",
        "gif.newFolder": "Nouveau dossier",
        "gif.move": "Déplacer vers un dossier",
        "gif.add": "Ajouter à un dossier",
        "toast.added": "Ajouté à {name}. Faites un clic droit sur son onglet pour le renommer.",
        "toast.addedNew": "Ajouté à un nouveau dossier. Faites un clic droit sur son onglet pour le renommer.",
        "resize.title": "Faites glisser pour redimensionner, double-cliquez pour réinitialiser",
    },
    ja: {
        "settings.unsortedTab": "「未分類」タブ",
        "settings.unsortedTab.description": "どのフォルダにも入っていないお気に入りだけを表示するタブです。「すべて」には常にすべてが表示されます。",
        "settings.oneFolderPerGif": "GIFごとにフォルダは1つ",
        "settings.oneFolderPerGif.description": "GIFをフォルダに追加すると他のフォルダから外れ、複数に入る代わりに移動します。",
        "settings.showCounts": "件数を表示",
        "settings.showCounts.description": "各タブの名前の横に、入っているGIFの数を表示します。",
        "tabs.label": "GIFフォルダ",
        "tab.all": "すべて",
        "tab.all.title": "すべてのお気に入り",
        "tab.unsorted": "未分類",
        "tab.unsorted.title": "どのフォルダにも入っていないお気に入り",
        "tab.folder.title": "右クリックで名前の変更や削除ができます",
        "tab.new": "+ 新しいフォルダ",
        "tab.new.label": "新しいフォルダ",
        "input.rename": "フォルダ名",
        "input.new": "新しいフォルダ",
        "error.empty": "フォルダに名前を付けてください",
        "error.taken": "その名前のフォルダはすでにあります",
        "folder.menu": "{name} フォルダ",
        "folder.rename": "フォルダ名を変更",
        "folder.delete": "フォルダを削除",
        "folder.delete.subtext": "GIFはお気に入りに残ります",
        "folder.default": "フォルダ {n}",
        "gif.removeFrom": "{name} から削除",
        "gif.newFolder": "新しいフォルダ",
        "gif.move": "フォルダに移動",
        "gif.add": "フォルダに追加",
        "toast.added": "{name} に追加しました。タブを右クリックすると名前を変更できます。",
        "toast.addedNew": "新しいフォルダに追加しました。タブを右クリックすると名前を変更できます。",
        "resize.title": "ドラッグでサイズ変更、ダブルクリックでリセット",
    },
    pl: {
        "settings.unsortedTab": "Karta Nieposortowane",
        "settings.unsortedTab.description": "Karta tylko z ulubionymi, których nie ma w żadnym folderze. Karta Wszystkie zawsze pokazuje wszystko.",
        "settings.oneFolderPerGif": "Jeden folder na GIF",
        "settings.oneFolderPerGif.description": "Dodanie GIF-a do folderu usuwa go z pozostałych folderów, więc jest przenoszony zamiast być w kilku naraz.",
        "settings.showCounts": "Pokaż liczniki",
        "settings.showCounts.description": "Liczba GIF-ów w każdej karcie, obok jej nazwy.",
        "tabs.label": "Foldery GIF-ów",
        "tab.all": "Wszystkie",
        "tab.all.title": "Wszystkie twoje ulubione",
        "tab.unsorted": "Nieposortowane",
        "tab.unsorted.title": "Ulubione, których nie ma w żadnym folderze",
        "tab.folder.title": "Kliknij prawym przyciskiem, aby zmienić nazwę lub usunąć",
        "tab.new": "+ Nowy folder",
        "tab.new.label": "Nowy folder",
        "input.rename": "Nazwa folderu",
        "input.new": "Nowy folder",
        "error.empty": "Nadaj folderowi nazwę",
        "error.taken": "Folder o tej nazwie już istnieje",
        "folder.menu": "Folder {name}",
        "folder.rename": "Zmień nazwę folderu",
        "folder.delete": "Usuń folder",
        "folder.delete.subtext": "GIF-y zostają w twoich ulubionych",
        "folder.default": "Folder {n}",
        "gif.removeFrom": "Usuń z {name}",
        "gif.newFolder": "Nowy folder",
        "gif.move": "Przenieś do folderu",
        "gif.add": "Dodaj do folderu",
        "toast.added": "Dodano do {name}. Kliknij prawym przyciskiem jego kartę, aby zmienić nazwę.",
        "toast.addedNew": "Dodano do nowego folderu. Kliknij prawym przyciskiem jego kartę, aby zmienić nazwę.",
        "resize.title": "Przeciągnij, aby zmienić rozmiar, kliknij dwukrotnie, aby zresetować",
    },
    "pt-BR": {
        "settings.unsortedTab": "Aba Sem pasta",
        "settings.unsortedTab.description": "Uma aba só com os favoritos que não estão em nenhuma pasta. Todos sempre mostra tudo.",
        "settings.oneFolderPerGif": "Uma pasta por GIF",
        "settings.oneFolderPerGif.description": "Adicionar um GIF a uma pasta o tira das outras pastas, então ele é movido em vez de ficar em várias.",
        "settings.showCounts": "Mostrar contagens",
        "settings.showCounts.description": "Quantos GIFs cada aba tem, ao lado do nome dela.",
        "tabs.label": "Pastas de GIFs",
        "tab.all": "Todos",
        "tab.all.title": "Todos os seus favoritos",
        "tab.unsorted": "Sem pasta",
        "tab.unsorted.title": "Favoritos que não estão em nenhuma pasta",
        "tab.folder.title": "Clique com o botão direito para renomear ou excluir",
        "tab.new": "+ Nova pasta",
        "tab.new.label": "Nova pasta",
        "input.rename": "Nome da pasta",
        "input.new": "Nova pasta",
        "error.empty": "Dê um nome à pasta",
        "error.taken": "Já existe uma pasta com esse nome",
        "folder.menu": "Pasta {name}",
        "folder.rename": "Renomear pasta",
        "folder.delete": "Excluir pasta",
        "folder.delete.subtext": "Os GIFs continuam nos seus favoritos",
        "folder.default": "Pasta {n}",
        "gif.removeFrom": "Remover de {name}",
        "gif.newFolder": "Nova pasta",
        "gif.move": "Mover para pasta",
        "gif.add": "Adicionar à pasta",
        "toast.added": "Adicionado a {name}. Clique com o botão direito na aba dela para renomear.",
        "toast.addedNew": "Adicionado a uma nova pasta. Clique com o botão direito na aba dela para renomear.",
        "resize.title": "Arraste para redimensionar, clique duas vezes para redefinir",
    },
    ru: {
        "settings.unsortedTab": "Вкладка «Без папки»",
        "settings.unsortedTab.description": "Вкладка только с теми избранными, которые не лежат ни в одной папке. Во вкладке «Все» всегда видно всё.",
        "settings.oneFolderPerGif": "Одна папка на GIF",
        "settings.oneFolderPerGif.description": "При добавлении GIF в папку он убирается из остальных папок, то есть переносится, а не лежит сразу в нескольких.",
        "settings.showCounts": "Показывать количество",
        "settings.showCounts.description": "Сколько GIF в каждой вкладке, рядом с её названием.",
        "tabs.label": "Папки с GIF",
        "tab.all": "Все",
        "tab.all.title": "Всё ваше избранное",
        "tab.unsorted": "Без папки",
        "tab.unsorted.title": "Избранное, которое не лежит ни в одной папке",
        "tab.folder.title": "Нажмите правой кнопкой, чтобы переименовать или удалить",
        "tab.new": "+ Новая папка",
        "tab.new.label": "Новая папка",
        "input.rename": "Название папки",
        "input.new": "Новая папка",
        "error.empty": "Назовите папку",
        "error.taken": "Папка с таким названием уже существует",
        "folder.menu": "Папка «{name}»",
        "folder.rename": "Переименовать папку",
        "folder.delete": "Удалить папку",
        "folder.delete.subtext": "GIF останутся в избранном",
        "folder.default": "Папка {n}",
        "gif.removeFrom": "Убрать из «{name}»",
        "gif.newFolder": "Новая папка",
        "gif.move": "Переместить в папку",
        "gif.add": "Добавить в папку",
        "toast.added": "Добавлено в «{name}». Нажмите правой кнопкой на её вкладку, чтобы переименовать.",
        "toast.addedNew": "Добавлено в новую папку. Нажмите правой кнопкой на её вкладку, чтобы переименовать.",
        "resize.title": "Перетащите, чтобы изменить размер, дважды щёлкните, чтобы сбросить",
    },
    tr: {
        "settings.unsortedTab": "Sınıflandırılmamış sekmesi",
        "settings.unsortedTab.description": "Yalnızca hiçbir klasörde olmayan favorileri gösteren bir sekme. Tümü her zaman her şeyi gösterir.",
        "settings.oneFolderPerGif": "GIF başına tek klasör",
        "settings.oneFolderPerGif.description": "Bir GIF'i klasöre eklemek onu diğer klasörlerinden çıkarır; yani birden fazla klasörde durmak yerine taşınır.",
        "settings.showCounts": "Sayıları göster",
        "settings.showCounts.description": "Her sekmenin adının yanında kaç GIF içerdiği.",
        "tabs.label": "GIF klasörleri",
        "tab.all": "Tümü",
        "tab.all.title": "Tüm favorilerin",
        "tab.unsorted": "Sınıflandırılmamış",
        "tab.unsorted.title": "Hiçbir klasörde olmayan favoriler",
        "tab.folder.title": "Yeniden adlandırmak veya silmek için sağ tıkla",
        "tab.new": "+ Yeni klasör",
        "tab.new.label": "Yeni klasör",
        "input.rename": "Klasör adı",
        "input.new": "Yeni klasör",
        "error.empty": "Klasöre bir ad ver",
        "error.taken": "Bu adda bir klasör zaten var",
        "folder.menu": "{name} klasörü",
        "folder.rename": "Klasörü yeniden adlandır",
        "folder.delete": "Klasörü sil",
        "folder.delete.subtext": "GIF'ler favorilerinde kalır",
        "folder.default": "Klasör {n}",
        "gif.removeFrom": "{name} klasöründen kaldır",
        "gif.newFolder": "Yeni klasör",
        "gif.move": "Klasöre taşı",
        "gif.add": "Klasöre ekle",
        "toast.added": "{name} klasörüne eklendi. Yeniden adlandırmak için sekmesine sağ tıkla.",
        "toast.addedNew": "Yeni bir klasöre eklendi. Yeniden adlandırmak için sekmesine sağ tıkla.",
        "resize.title": "Yeniden boyutlandırmak için sürükle, sıfırlamak için çift tıkla",
    },
});
