import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.mentions": "Mentions",
        "settings.mentions.description": "@mentions of people in messages show in their role colour.",
        "settings.typing": "Typing indicator",
        "settings.typing.description": "Names in \"is typing\" above the chat box show in their role colour.",
        "settings.voice": "Voice channels",
        "settings.voice.description": "People in voice channels in the channel list show in their role colour.",
        "settings.reactions": "Reactions",
        "settings.reactions.description": "People in the list of who reacted show in their role colour.",
        "settings.gradients": "Gradient roles",
        "settings.gradients.description": "Gradient and holographic role colours show as gradients. Off, the role's first colour is used.",
    },
    de: {
        "settings.mentions": "Erwähnungen",
        "settings.mentions.description": "@Erwähnungen von Personen in Nachrichten erscheinen in ihrer Rollenfarbe.",
        "settings.typing": "Tippanzeige",
        "settings.typing.description": "Namen in „schreibt gerade“ über dem Chatfeld erscheinen in ihrer Rollenfarbe.",
        "settings.voice": "Sprachkanäle",
        "settings.voice.description": "Personen in Sprachkanälen in der Kanalliste erscheinen in ihrer Rollenfarbe.",
        "settings.reactions": "Reaktionen",
        "settings.reactions.description": "Personen in der Liste, wer reagiert hat, erscheinen in ihrer Rollenfarbe.",
        "settings.gradients": "Farbverlauf-Rollen",
        "settings.gradients.description": "Farbverlauf- und holografische Rollenfarben erscheinen als Verlauf. Ausgeschaltet wird die erste Farbe der Rolle verwendet.",
    },
    es: {
        "settings.mentions": "Menciones",
        "settings.mentions.description": "Las @menciones a personas en los mensajes se muestran con el color de su rol.",
        "settings.typing": "Indicador de escritura",
        "settings.typing.description": "Los nombres en \"está escribiendo\" sobre el cuadro de chat se muestran con el color de su rol.",
        "settings.voice": "Canales de voz",
        "settings.voice.description": "Las personas en canales de voz de la lista de canales se muestran con el color de su rol.",
        "settings.reactions": "Reacciones",
        "settings.reactions.description": "Las personas en la lista de quién reaccionó se muestran con el color de su rol.",
        "settings.gradients": "Roles con degradado",
        "settings.gradients.description": "Los colores de rol con degradado y holográficos se muestran como degradado. Desactivado, se usa el primer color del rol.",
    },
    fr: {
        "settings.mentions": "Mentions",
        "settings.mentions.description": "Les @mentions de personnes dans les messages s'affichent dans la couleur de leur rôle.",
        "settings.typing": "Indicateur d'écriture",
        "settings.typing.description": "Les noms dans « est en train d'écrire » au-dessus de la zone de saisie s'affichent dans la couleur de leur rôle.",
        "settings.voice": "Salons vocaux",
        "settings.voice.description": "Les personnes dans les salons vocaux de la liste des salons s'affichent dans la couleur de leur rôle.",
        "settings.reactions": "Réactions",
        "settings.reactions.description": "Les personnes dans la liste de qui a réagi s'affichent dans la couleur de leur rôle.",
        "settings.gradients": "Rôles en dégradé",
        "settings.gradients.description": "Les couleurs de rôle en dégradé et holographiques s'affichent en dégradé. Désactivé, la première couleur du rôle est utilisée.",
    },
    ja: {
        "settings.mentions": "メンション",
        "settings.mentions.description": "メッセージ内の人への@メンションをロールの色で表示します。",
        "settings.typing": "入力中の表示",
        "settings.typing.description": "チャット欄の上の「入力中」の名前をロールの色で表示します。",
        "settings.voice": "ボイスチャンネル",
        "settings.voice.description": "チャンネル一覧のボイスチャンネルにいる人をロールの色で表示します。",
        "settings.reactions": "リアクション",
        "settings.reactions.description": "リアクションした人の一覧をロールの色で表示します。",
        "settings.gradients": "グラデーションのロール",
        "settings.gradients.description": "グラデーションやホログラフィックのロールの色をグラデーションで表示します。オフにするとロールの最初の色を使います。",
    },
    pl: {
        "settings.mentions": "Wzmianki",
        "settings.mentions.description": "@wzmianki o osobach w wiadomościach pokazują się w kolorze ich roli.",
        "settings.typing": "Wskaźnik pisania",
        "settings.typing.description": "Imiona w „pisze…” nad polem czatu pokazują się w kolorze ich roli.",
        "settings.voice": "Kanały głosowe",
        "settings.voice.description": "Osoby na kanałach głosowych na liście kanałów pokazują się w kolorze ich roli.",
        "settings.reactions": "Reakcje",
        "settings.reactions.description": "Osoby na liście tych, którzy zareagowali, pokazują się w kolorze ich roli.",
        "settings.gradients": "Role z gradientem",
        "settings.gradients.description": "Gradientowe i holograficzne kolory ról pokazują się jako gradient. Po wyłączeniu używany jest pierwszy kolor roli.",
    },
    "pt-BR": {
        "settings.mentions": "Menções",
        "settings.mentions.description": "As @menções a pessoas nas mensagens aparecem na cor do cargo delas.",
        "settings.typing": "Indicador de digitação",
        "settings.typing.description": "Os nomes em \"está digitando\" acima da caixa de chat aparecem na cor do cargo.",
        "settings.voice": "Canais de voz",
        "settings.voice.description": "As pessoas nos canais de voz da lista de canais aparecem na cor do cargo.",
        "settings.reactions": "Reações",
        "settings.reactions.description": "As pessoas na lista de quem reagiu aparecem na cor do cargo.",
        "settings.gradients": "Cargos com degradê",
        "settings.gradients.description": "Cores de cargo em degradê e holográficas aparecem como degradê. Desativado, usa a primeira cor do cargo.",
    },
    ru: {
        "settings.mentions": "Упоминания",
        "settings.mentions.description": "@упоминания людей в сообщениях показываются цветом их роли.",
        "settings.typing": "Индикатор набора",
        "settings.typing.description": "Имена в «печатает» над полем чата показываются цветом их роли.",
        "settings.voice": "Голосовые каналы",
        "settings.voice.description": "Люди в голосовых каналах в списке каналов показываются цветом их роли.",
        "settings.reactions": "Реакции",
        "settings.reactions.description": "Люди в списке поставивших реакцию показываются цветом их роли.",
        "settings.gradients": "Градиентные роли",
        "settings.gradients.description": "Градиентные и голографические цвета ролей показываются градиентом. Если выключено, используется первый цвет роли.",
    },
    tr: {
        "settings.mentions": "Bahsetmeler",
        "settings.mentions.description": "Mesajlardaki kişilere yapılan @bahsetmeler rol renginde görünür.",
        "settings.typing": "Yazıyor göstergesi",
        "settings.typing.description": "Sohbet kutusunun üstündeki \"yazıyor\" satırındaki isimler rol renginde görünür.",
        "settings.voice": "Ses kanalları",
        "settings.voice.description": "Kanal listesindeki ses kanallarında bulunan kişiler rol renginde görünür.",
        "settings.reactions": "Tepkiler",
        "settings.reactions.description": "Tepki verenler listesindeki kişiler rol renginde görünür.",
        "settings.gradients": "Renk geçişli roller",
        "settings.gradients.description": "Renk geçişli ve holografik rol renkleri geçiş olarak görünür. Kapalıyken rolün ilk rengi kullanılır.",
    },
});
