import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.rememberSpeed": "Remember playback speed",
        "settings.rememberSpeed.description": "Videos start at the speed you last picked, instead of 1x.",
        "settings.showStrip": "Show the control strip",
        "settings.showStrip.description": "Speed, loop, frame step and picture-in-picture buttons at the top right of a video you hover.",
        "settings.shortcuts": "Keyboard shortcuts",
        "settings.shortcuts.description": "While hovering a video: Space/K play, J/L and arrow keys seek, M mute, F fullscreen, [ ] speed, P picture-in-picture, , and . step one frame.",
        "settings.seekSeconds": "Seek step (seconds)",
        "settings.seekSeconds.description": "How far J, L and the arrow keys jump.",
        "flash.muted": "Muted",
        "flash.unmuted": "Unmuted",
        "flash.loopOn": "Loop on",
        "flash.loopOff": "Loop off",
        "flash.pipUnavailable": "Picture-in-picture isn't available",
        "flash.playFirst": "Play the video first",
        "flash.pipFailed": "Couldn't open picture-in-picture",
        "flash.nextFrame": "Next frame · {position}",
        "flash.previousFrame": "Previous frame · {position}",
        "label.controls": "Video controls",
        "label.speed": "Playback speed ([ and ])",
        "label.speedMenu": "Playback speed",
        "label.loop": "Loop",
        "label.loopOn": "Loop: on",
        "label.loopOff": "Loop: off",
        "label.pip": "Picture-in-picture",
        "label.previousFrame": "Previous frame",
        "label.nextFrame": "Next frame",
    },
    de: {
        "settings.rememberSpeed": "Wiedergabegeschwindigkeit merken",
        "settings.rememberSpeed.description": "Videos starten mit der zuletzt gewählten Geschwindigkeit statt mit 1x.",
        "settings.showStrip": "Steuerleiste anzeigen",
        "settings.showStrip.description": "Schaltflächen für Geschwindigkeit, Wiederholen, Einzelbild und Bild-in-Bild oben rechts an einem Video, über dem du schwebst.",
        "settings.shortcuts": "Tastenkürzel",
        "settings.shortcuts.description": "Beim Darüberfahren mit der Maus: Leertaste/K Wiedergabe, J/L und Pfeiltasten Spulen, M Stummschalten, F Vollbild, [ ] Geschwindigkeit, P Bild-in-Bild, , und . ein Einzelbild weiter.",
        "settings.seekSeconds": "Spulschritt (Sekunden)",
        "settings.seekSeconds.description": "Wie weit J, L und die Pfeiltasten springen.",
        "flash.muted": "Stummgeschaltet",
        "flash.unmuted": "Ton an",
        "flash.loopOn": "Wiederholen an",
        "flash.loopOff": "Wiederholen aus",
        "flash.pipUnavailable": "Bild-in-Bild ist nicht verfügbar",
        "flash.playFirst": "Starte zuerst das Video",
        "flash.pipFailed": "Bild-in-Bild konnte nicht geöffnet werden",
        "flash.nextFrame": "Nächstes Bild · {position}",
        "flash.previousFrame": "Vorheriges Bild · {position}",
        "label.controls": "Videosteuerung",
        "label.speed": "Wiedergabegeschwindigkeit ([ und ])",
        "label.speedMenu": "Wiedergabegeschwindigkeit",
        "label.loop": "Wiederholen",
        "label.loopOn": "Wiederholen: an",
        "label.loopOff": "Wiederholen: aus",
        "label.pip": "Bild-in-Bild",
        "label.previousFrame": "Vorheriges Bild",
        "label.nextFrame": "Nächstes Bild",
    },
    es: {
        "settings.rememberSpeed": "Recordar la velocidad de reproducción",
        "settings.rememberSpeed.description": "Los vídeos empiezan a la última velocidad que elegiste, en lugar de a 1x.",
        "settings.showStrip": "Mostrar la barra de controles",
        "settings.showStrip.description": "Botones de velocidad, repetición, avance por fotogramas e imagen en imagen en la esquina superior derecha de un vídeo al pasar el ratón.",
        "settings.shortcuts": "Atajos de teclado",
        "settings.shortcuts.description": "Al pasar el ratón por un vídeo: Espacio/K reproducir, J/L y flechas para avanzar o retroceder, M silenciar, F pantalla completa, [ ] velocidad, P imagen en imagen, , y . avanzar un fotograma.",
        "settings.seekSeconds": "Salto al avanzar o retroceder (segundos)",
        "settings.seekSeconds.description": "Cuánto saltan J, L y las flechas.",
        "flash.muted": "Silenciado",
        "flash.unmuted": "Sonido activado",
        "flash.loopOn": "Repetición activada",
        "flash.loopOff": "Repetición desactivada",
        "flash.pipUnavailable": "La imagen en imagen no está disponible",
        "flash.playFirst": "Reproduce primero el vídeo",
        "flash.pipFailed": "No se pudo abrir la imagen en imagen",
        "flash.nextFrame": "Fotograma siguiente · {position}",
        "flash.previousFrame": "Fotograma anterior · {position}",
        "label.controls": "Controles del vídeo",
        "label.speed": "Velocidad de reproducción ([ y ])",
        "label.speedMenu": "Velocidad de reproducción",
        "label.loop": "Repetir",
        "label.loopOn": "Repetir: activado",
        "label.loopOff": "Repetir: desactivado",
        "label.pip": "Imagen en imagen",
        "label.previousFrame": "Fotograma anterior",
        "label.nextFrame": "Fotograma siguiente",
    },
    fr: {
        "settings.rememberSpeed": "Mémoriser la vitesse de lecture",
        "settings.rememberSpeed.description": "Les vidéos démarrent à la dernière vitesse choisie, au lieu de 1x.",
        "settings.showStrip": "Afficher la barre de contrôle",
        "settings.showStrip.description": "Boutons de vitesse, de lecture en boucle, d'avance image par image et d'image dans l'image en haut à droite d'une vidéo survolée.",
        "settings.shortcuts": "Raccourcis clavier",
        "settings.shortcuts.description": "Au survol d'une vidéo : Espace/K lecture, J/L et flèches pour avancer ou reculer, M muet, F plein écran, [ ] vitesse, P image dans l'image, , et . avancer d'une image.",
        "settings.seekSeconds": "Pas de déplacement (secondes)",
        "settings.seekSeconds.description": "De combien J, L et les flèches font sauter la lecture.",
        "flash.muted": "Son coupé",
        "flash.unmuted": "Son activé",
        "flash.loopOn": "Boucle activée",
        "flash.loopOff": "Boucle désactivée",
        "flash.pipUnavailable": "L'image dans l'image n'est pas disponible",
        "flash.playFirst": "Lancez d'abord la vidéo",
        "flash.pipFailed": "Impossible d'ouvrir l'image dans l'image",
        "flash.nextFrame": "Image suivante · {position}",
        "flash.previousFrame": "Image précédente · {position}",
        "label.controls": "Commandes de la vidéo",
        "label.speed": "Vitesse de lecture ([ et ])",
        "label.speedMenu": "Vitesse de lecture",
        "label.loop": "Boucle",
        "label.loopOn": "Boucle : activée",
        "label.loopOff": "Boucle : désactivée",
        "label.pip": "Image dans l'image",
        "label.previousFrame": "Image précédente",
        "label.nextFrame": "Image suivante",
    },
    ja: {
        "settings.rememberSpeed": "再生速度を記憶",
        "settings.rememberSpeed.description": "動画を1xではなく、前回選んだ速度で再生し始めます。",
        "settings.showStrip": "コントロールバーを表示",
        "settings.showStrip.description": "カーソルを合わせた動画の右上に、速度、ループ、コマ送り、ピクチャーインピクチャーのボタンを表示します。",
        "settings.shortcuts": "キーボードショートカット",
        "settings.shortcuts.description": "動画にカーソルを合わせているとき: Space/K で再生、J/L と矢印キーでシーク、M でミュート、F で全画面、[ ] で速度、P でピクチャーインピクチャー、, と . で1コマ送り。",
        "settings.seekSeconds": "シークの間隔(秒)",
        "settings.seekSeconds.description": "J、L、矢印キーで移動する秒数です。",
        "flash.muted": "ミュート中",
        "flash.unmuted": "ミュート解除",
        "flash.loopOn": "ループ オン",
        "flash.loopOff": "ループ オフ",
        "flash.pipUnavailable": "ピクチャーインピクチャーは利用できません",
        "flash.playFirst": "先に動画を再生してください",
        "flash.pipFailed": "ピクチャーインピクチャーを開けませんでした",
        "flash.nextFrame": "次のコマ · {position}",
        "flash.previousFrame": "前のコマ · {position}",
        "label.controls": "動画コントロール",
        "label.speed": "再生速度([ と ])",
        "label.speedMenu": "再生速度",
        "label.loop": "ループ",
        "label.loopOn": "ループ: オン",
        "label.loopOff": "ループ: オフ",
        "label.pip": "ピクチャーインピクチャー",
        "label.previousFrame": "前のコマ",
        "label.nextFrame": "次のコマ",
    },
    pl: {
        "settings.rememberSpeed": "Zapamiętaj prędkość odtwarzania",
        "settings.rememberSpeed.description": "Filmy zaczynają się z ostatnio wybraną prędkością zamiast 1x.",
        "settings.showStrip": "Pokaż pasek sterowania",
        "settings.showStrip.description": "Przyciski prędkości, zapętlenia, przechodzenia klatka po klatce i obrazu w obrazie w prawym górnym rogu filmu, nad którym jest kursor.",
        "settings.shortcuts": "Skróty klawiszowe",
        "settings.shortcuts.description": "Gdy kursor jest nad filmem: Spacja/K odtwarzanie, J/L i strzałki przewijanie, M wyciszenie, F pełny ekran, [ ] prędkość, P obraz w obrazie, , i . jedna klatka do przodu lub do tyłu.",
        "settings.seekSeconds": "Krok przewijania (sekundy)",
        "settings.seekSeconds.description": "O ile przeskakują J, L i strzałki.",
        "flash.muted": "Wyciszono",
        "flash.unmuted": "Włączono dźwięk",
        "flash.loopOn": "Zapętlenie włączone",
        "flash.loopOff": "Zapętlenie wyłączone",
        "flash.pipUnavailable": "Obraz w obrazie jest niedostępny",
        "flash.playFirst": "Najpierw odtwórz film",
        "flash.pipFailed": "Nie udało się otworzyć obrazu w obrazie",
        "flash.nextFrame": "Następna klatka · {position}",
        "flash.previousFrame": "Poprzednia klatka · {position}",
        "label.controls": "Sterowanie filmem",
        "label.speed": "Prędkość odtwarzania ([ i ])",
        "label.speedMenu": "Prędkość odtwarzania",
        "label.loop": "Zapętlenie",
        "label.loopOn": "Zapętlenie: włączone",
        "label.loopOff": "Zapętlenie: wyłączone",
        "label.pip": "Obraz w obrazie",
        "label.previousFrame": "Poprzednia klatka",
        "label.nextFrame": "Następna klatka",
    },
    "pt-BR": {
        "settings.rememberSpeed": "Lembrar a velocidade de reprodução",
        "settings.rememberSpeed.description": "Os vídeos começam na última velocidade escolhida, em vez de 1x.",
        "settings.showStrip": "Mostrar a barra de controles",
        "settings.showStrip.description": "Botões de velocidade, repetição, avanço quadro a quadro e picture-in-picture no canto superior direito do vídeo sobre o qual você passa o mouse.",
        "settings.shortcuts": "Atalhos de teclado",
        "settings.shortcuts.description": "Com o mouse sobre um vídeo: Espaço/K reproduz, J/L e setas avançam ou voltam, M silencia, F tela cheia, [ ] velocidade, P picture-in-picture, , e . avançam um quadro.",
        "settings.seekSeconds": "Salto ao avançar ou voltar (segundos)",
        "settings.seekSeconds.description": "Quanto J, L e as setas pulam.",
        "flash.muted": "Silenciado",
        "flash.unmuted": "Som ativado",
        "flash.loopOn": "Repetição ligada",
        "flash.loopOff": "Repetição desligada",
        "flash.pipUnavailable": "Picture-in-picture não está disponível",
        "flash.playFirst": "Reproduza o vídeo primeiro",
        "flash.pipFailed": "Não foi possível abrir o picture-in-picture",
        "flash.nextFrame": "Próximo quadro · {position}",
        "flash.previousFrame": "Quadro anterior · {position}",
        "label.controls": "Controles do vídeo",
        "label.speed": "Velocidade de reprodução ([ e ])",
        "label.speedMenu": "Velocidade de reprodução",
        "label.loop": "Repetir",
        "label.loopOn": "Repetir: ligado",
        "label.loopOff": "Repetir: desligado",
        "label.pip": "Picture-in-picture",
        "label.previousFrame": "Quadro anterior",
        "label.nextFrame": "Próximo quadro",
    },
    ru: {
        "settings.rememberSpeed": "Запоминать скорость воспроизведения",
        "settings.rememberSpeed.description": "Видео начинаются с последней выбранной скорости, а не с 1x.",
        "settings.showStrip": "Показывать панель управления",
        "settings.showStrip.description": "Кнопки скорости, повтора, покадрового просмотра и «картинка в картинке» в правом верхнем углу видео, на которое наведён курсор.",
        "settings.shortcuts": "Горячие клавиши",
        "settings.shortcuts.description": "При наведении на видео: пробел/K — воспроизведение, J/L и стрелки — перемотка, M — без звука, F — полный экран, [ ] — скорость, P — «картинка в картинке», , и . — на один кадр.",
        "settings.seekSeconds": "Шаг перемотки (секунды)",
        "settings.seekSeconds.description": "На сколько перематывают J, L и стрелки.",
        "flash.muted": "Звук выключен",
        "flash.unmuted": "Звук включён",
        "flash.loopOn": "Повтор включён",
        "flash.loopOff": "Повтор выключен",
        "flash.pipUnavailable": "«Картинка в картинке» недоступна",
        "flash.playFirst": "Сначала запустите видео",
        "flash.pipFailed": "Не удалось открыть «картинку в картинке»",
        "flash.nextFrame": "Следующий кадр · {position}",
        "flash.previousFrame": "Предыдущий кадр · {position}",
        "label.controls": "Управление видео",
        "label.speed": "Скорость воспроизведения ([ и ])",
        "label.speedMenu": "Скорость воспроизведения",
        "label.loop": "Повтор",
        "label.loopOn": "Повтор: включён",
        "label.loopOff": "Повтор: выключен",
        "label.pip": "Картинка в картинке",
        "label.previousFrame": "Предыдущий кадр",
        "label.nextFrame": "Следующий кадр",
    },
    tr: {
        "settings.rememberSpeed": "Oynatma hızını hatırla",
        "settings.rememberSpeed.description": "Videolar 1x yerine en son seçtiğin hızda başlar.",
        "settings.showStrip": "Denetim çubuğunu göster",
        "settings.showStrip.description": "Üzerine geldiğin videonun sağ üst köşesinde hız, döngü, kare kare ilerleme ve pencere içinde pencere düğmeleri.",
        "settings.shortcuts": "Klavye kısayolları",
        "settings.shortcuts.description": "Bir videonun üzerindeyken: Boşluk/K oynat, J/L ve ok tuşları ileri geri sar, M sessize al, F tam ekran, [ ] hız, P pencere içinde pencere, , ve . bir kare ilerle.",
        "settings.seekSeconds": "Sarma adımı (saniye)",
        "settings.seekSeconds.description": "J, L ve ok tuşlarının ne kadar atlayacağı.",
        "flash.muted": "Sessize alındı",
        "flash.unmuted": "Ses açıldı",
        "flash.loopOn": "Döngü açık",
        "flash.loopOff": "Döngü kapalı",
        "flash.pipUnavailable": "Pencere içinde pencere kullanılamıyor",
        "flash.playFirst": "Önce videoyu oynat",
        "flash.pipFailed": "Pencere içinde pencere açılamadı",
        "flash.nextFrame": "Sonraki kare · {position}",
        "flash.previousFrame": "Önceki kare · {position}",
        "label.controls": "Video denetimleri",
        "label.speed": "Oynatma hızı ([ ve ])",
        "label.speedMenu": "Oynatma hızı",
        "label.loop": "Döngü",
        "label.loopOn": "Döngü: açık",
        "label.loopOff": "Döngü: kapalı",
        "label.pip": "Pencere içinde pencere",
        "label.previousFrame": "Önceki kare",
        "label.nextFrame": "Sonraki kare",
    },
});
