import { defineStrings } from "@evi/api";

export const t = defineStrings({
    en: {
        "settings.showOnProfiles": "On profiles",
        "settings.showOnProfiles.description": "Next to the badges on someone's profile.",
        "settings.showInChat": "In chat",
        "settings.showInChat.description": "After the name on each message.",
        "settings.showInMemberList": "In the member list",
        "settings.showInMemberList.description": "After each name in a server's member list.",
        "settings.showOwn": "Your own devices",
        "settings.showOwn.description": "Show which of your own clients are online too.",
        "status.online": "Online",
        "status.idle": "Idle",
        "status.dnd": "Do Not Disturb",
        "device.desktop": "desktop",
        "device.mobile": "mobile",
        "device.web": "the web",
        "device.embedded": "a console",
        tooltip: "{status} on {device}",
    },
    de: {
        "settings.showOnProfiles": "In Profilen",
        "settings.showOnProfiles.description": "Neben den Abzeichen im Profil einer Person.",
        "settings.showInChat": "Im Chat",
        "settings.showInChat.description": "Hinter dem Namen bei jeder Nachricht.",
        "settings.showInMemberList": "In der Mitgliederliste",
        "settings.showInMemberList.description": "Hinter jedem Namen in der Mitgliederliste eines Servers.",
        "settings.showOwn": "Deine eigenen Geräte",
        "settings.showOwn.description": "Zeigt auch, welche deiner eigenen Clients online sind.",
        "status.online": "Online",
        "status.idle": "Abwesend",
        "status.dnd": "Bitte nicht stören",
        "device.desktop": "auf dem Desktop",
        "device.mobile": "auf dem Handy",
        "device.web": "im Web",
        "device.embedded": "auf einer Konsole",
        tooltip: "{status} {device}",
    },
    es: {
        "settings.showOnProfiles": "En los perfiles",
        "settings.showOnProfiles.description": "Junto a las insignias del perfil de alguien.",
        "settings.showInChat": "En el chat",
        "settings.showInChat.description": "Después del nombre en cada mensaje.",
        "settings.showInMemberList": "En la lista de miembros",
        "settings.showInMemberList.description": "Después de cada nombre en la lista de miembros de un servidor.",
        "settings.showOwn": "Tus propios dispositivos",
        "settings.showOwn.description": "Muestra también cuáles de tus propios clientes están conectados.",
        "status.online": "En línea",
        "status.idle": "Ausente",
        "status.dnd": "No molestar",
        "device.desktop": "el escritorio",
        "device.mobile": "el móvil",
        "device.web": "la web",
        "device.embedded": "una consola",
        tooltip: "{status} en {device}",
    },
    fr: {
        "settings.showOnProfiles": "Sur les profils",
        "settings.showOnProfiles.description": "À côté des badges sur le profil de quelqu'un.",
        "settings.showInChat": "Dans le chat",
        "settings.showInChat.description": "Après le nom sur chaque message.",
        "settings.showInMemberList": "Dans la liste des membres",
        "settings.showInMemberList.description": "Après chaque nom dans la liste des membres d'un serveur.",
        "settings.showOwn": "Tes propres appareils",
        "settings.showOwn.description": "Affiche aussi lesquels de tes propres clients sont en ligne.",
        "status.online": "En ligne",
        "status.idle": "Inactif",
        "status.dnd": "Ne pas déranger",
        "device.desktop": "sur ordinateur",
        "device.mobile": "sur mobile",
        "device.web": "sur le web",
        "device.embedded": "sur console",
        tooltip: "{status} {device}",
    },
    ja: {
        "settings.showOnProfiles": "プロフィール",
        "settings.showOnProfiles.description": "ユーザープロフィールのバッジの横に表示します。",
        "settings.showInChat": "チャット",
        "settings.showInChat.description": "各メッセージの名前の後ろに表示します。",
        "settings.showInMemberList": "メンバーリスト",
        "settings.showInMemberList.description": "サーバーのメンバーリストの各名前の後ろに表示します。",
        "settings.showOwn": "自分のデバイス",
        "settings.showOwn.description": "自分のクライアントのうちオンラインのものも表示します。",
        "status.online": "オンライン",
        "status.idle": "退席中",
        "status.dnd": "取り込み中",
        "device.desktop": "デスクトップ",
        "device.mobile": "モバイル",
        "device.web": "ウェブ",
        "device.embedded": "ゲーム機",
        tooltip: "{device}で{status}",
    },
    pl: {
        "settings.showOnProfiles": "Na profilach",
        "settings.showOnProfiles.description": "Obok odznak na profilu użytkownika.",
        "settings.showInChat": "Na czacie",
        "settings.showInChat.description": "Po nazwie przy każdej wiadomości.",
        "settings.showInMemberList": "Na liście członków",
        "settings.showInMemberList.description": "Po każdej nazwie na liście członków serwera.",
        "settings.showOwn": "Twoje urządzenia",
        "settings.showOwn.description": "Pokazuje też, które z twoich klientów są online.",
        "status.online": "Online",
        "status.idle": "Zaraz wracam",
        "status.dnd": "Nie przeszkadzać",
        "device.desktop": "na komputerze",
        "device.mobile": "na telefonie",
        "device.web": "w przeglądarce",
        "device.embedded": "na konsoli",
        tooltip: "{status} {device}",
    },
    "pt-BR": {
        "settings.showOnProfiles": "Nos perfis",
        "settings.showOnProfiles.description": "Ao lado das insígnias no perfil de alguém.",
        "settings.showInChat": "No chat",
        "settings.showInChat.description": "Depois do nome em cada mensagem.",
        "settings.showInMemberList": "Na lista de membros",
        "settings.showInMemberList.description": "Depois de cada nome na lista de membros de um servidor.",
        "settings.showOwn": "Seus próprios dispositivos",
        "settings.showOwn.description": "Mostra também quais dos seus próprios clientes estão online.",
        "status.online": "Online",
        "status.idle": "Ausente",
        "status.dnd": "Não perturbe",
        "device.desktop": "no computador",
        "device.mobile": "no celular",
        "device.web": "na web",
        "device.embedded": "em um console",
        tooltip: "{status} {device}",
    },
    ru: {
        "settings.showOnProfiles": "В профилях",
        "settings.showOnProfiles.description": "Рядом со значками в профиле пользователя.",
        "settings.showInChat": "В чате",
        "settings.showInChat.description": "После имени в каждом сообщении.",
        "settings.showInMemberList": "В списке участников",
        "settings.showInMemberList.description": "После каждого имени в списке участников сервера.",
        "settings.showOwn": "Ваши устройства",
        "settings.showOwn.description": "Показывать также, какие из ваших клиентов сейчас в сети.",
        "status.online": "В сети",
        "status.idle": "Не активен",
        "status.dnd": "Не беспокоить",
        "device.desktop": "на компьютере",
        "device.mobile": "на телефоне",
        "device.web": "в браузере",
        "device.embedded": "на консоли",
        tooltip: "{status} {device}",
    },
    tr: {
        "settings.showOnProfiles": "Profillerde",
        "settings.showOnProfiles.description": "Birinin profilinde rozetlerin yanında.",
        "settings.showInChat": "Sohbette",
        "settings.showInChat.description": "Her mesajda adın yanında.",
        "settings.showInMemberList": "Üye listesinde",
        "settings.showInMemberList.description": "Bir sunucunun üye listesinde her adın yanında.",
        "settings.showOwn": "Kendi cihazların",
        "settings.showOwn.description": "Kendi istemcilerinden hangilerinin çevrimiçi olduğunu da gösterir.",
        "status.online": "Çevrimiçi",
        "status.idle": "Boşta",
        "status.dnd": "Rahatsız Etmeyin",
        "device.desktop": "Masaüstünde",
        "device.mobile": "Mobilde",
        "device.web": "Web'de",
        "device.embedded": "Konsolda",
        tooltip: "{device} {status}",
    },
});
